import type { Gadget } from "./gadgets"

/** Amazon.co.jp「配信用カメラ」検索結果（カメラ本体のみ。アクセサリー除外）。 */
export const cameraStreamingSearch: Gadget[] = [
  {
    id: "cam-str-001-rq8m",
    category: "camera",
    name: "YoloCam S3",
    brand: "YoloLiv",
    tagline: "YoloLiv YoloCam S3、PC・Mac対応4K配信用ウェブカメラ1/1.3型センサー、DSLR風操作、シネマティック効果、4Xズーム、HDR、無圧縮映像、PDオートフォーカス",
    price: 34000,
    rating: 4.6,
    reviews: 237,
    image: "https://m.media-amazon.com/images/I/715R39FsUiL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FQ5NRQ8M",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "82°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "82°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #1" }]}],
  },
  {
    id: "cam-str-002-c6gb",
    category: "camera",
    name: "YoloCam S7",
    brand: "YoloLiv",
    tagline: "レンズ交換式4K60ウェブカメラToFオートフォーカス、ソフトウェア制御、4Xズーム、HDR、DSLR風操作、シネマティック効果、HDMI・USB出力",
    price: 158300,
    rating: 3.9,
    reviews: 18,
    image: "https://m.media-amazon.com/images/I/713wJG9wORL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DZX7C6GB",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #2" }]}],
  },
  {
    id: "cam-str-003-jq1z",
    category: "camera",
    name: "YoloCam S7、18mmマイクロフォーサーズレンズ搭載",
    brand: "YoloLiv",
    tagline: "YoloLiv YoloCam S7、18mmマイクロフォーサーズレンズ搭載4KウェブカメラDSLR風操作、シネマティック効果、ToFオートフォーカス、4Xズーム、レンズ交換式、プラグ&プレイ、Twitch・YouTube・Zoom対応",
    price: 210900,
    rating: 4.3,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/71XRL7BtO+L._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GHRMJQ1Z",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #3" }]}],
  },
  {
    id: "cam-str-004-zr1v",
    category: "camera",
    name: "TINY 2",
    brand: "OBSBOT",
    tagline: "OBSBOT TINY 2 webカメラ AI自動追跡 ウェブカメラ HDR 4K 5000万画素 全画素AF ジェスチャー 音声制御 ノイキャンマイク 会議 ライブ配信 ビデオ通話",
    price: 44030,
    rating: 4.4,
    reviews: 1058,
    image: "https://m.media-amazon.com/images/I/51XeBqiCrRL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C3B6ZR1V",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "85.5°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "85.5°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #4" }]}],
  },
  {
    id: "cam-str-011-p22d",
    category: "camera",
    name: "Insta360 Link 2",
    brand: "Insta360",
    tagline: "Insta360 Link 2 ブラック Webカメラ 4K ウェブカメラ PTZ 1/2インチセンサー AI追跡 ジンバル搭载 HDR AIノイズキャンセリング マイク付き 配信 ビデオ通話 会議用 Zoom Teams Twitchに対応 PC/Windows/Mac用",
    price: 32373,
    rating: 4.7,
    reviews: 143,
    image: "https://m.media-amazon.com/images/I/51R6zRz7EVL._AC_SL1500_.jpg",
    connection: "USB-C / USB-A",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DM5YP22D",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79.5°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "79.5°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C / USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #11" }]}],
  },
    {
    id: "cam-str-013-j7mx",
    category: "camera",
    name: "ActionRing書画カメラ 4K 1500万画素  プロジェクターに直接投影",
    brand: "—",
    tagline: "4K / 30fps・オートフォーカス",
    price: 9999,
    rating: 3.8,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/51Dd6r8yl6L._AC_SL1500_.jpg",
    connection: "USB-C / USB-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FSRHJ7MX",
    highlights: [
      { label: "解像度", value: "4K / 30fps" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K / 30fps" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C / USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #13" }]}],
  },
  {
    id: "cam-str-014-b2t6",
    category: "camera",
    name: "OBSBOT Meet Flip 4K",
    brand: "OBSBOT",
    tagline: "Webカメラ 折りたたみ式 AI搭載超軽量 1/2インチセンサー AI自動フレーミング PDAF高速AF デュアルマイク ジェスチャー操作 HDR 美顔補正",
    price: 22800,
    rating: 4.5,
    reviews: 101,
    image: "https://m.media-amazon.com/images/I/51PX15gciKL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AIオートフレーミング"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GX94B2T6",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #14" }]}],
  },
  {
    id: "cam-str-019-94fh",
    category: "camera",
    name: "DC400 USB /書画カメラ/スキャナー 3-in-1 1600万画素 4K/30fps A",
    brand: "Ideao",
    tagline: "4K / 60fps・内蔵マイク",
    price: 16500,
    rating: 4,
    reviews: 307,
    image: "https://m.media-amazon.com/images/I/61qD1+qQS6L._AC_SL1500_.jpg",
    connection: "USB-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09M3F94FH",
    highlights: [
      { label: "解像度", value: "4K / 60fps" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K / 60fps" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #19" }]}],
  },
  {
    id: "cam-str-020-81b3",
    category: "camera",
    name: "Link 2C 通常版",
    brand: "Insta360",
    tagline: "Insta360 Link 2C 通常版 アークティックホワイト - PC/Mac 用 4K ウェブカメラ、1/2 インチセンサー、自動フレーミング、HDR、AI ノイズキャンセリング マイク、配信やビデオ通話、ゲーム配信に役立つジェスチャー操作",
    price: 25800,
    rating: 4.6,
    reviews: 1280,
    image: "https://m.media-amazon.com/images/I/51wfI8bPutL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DNK381B3",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79.5°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "79.5°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #20" }]}],
  },
  {
    id: "cam-str-023-sst2",
    category: "camera",
    name: "S800",
    brand: "AOC",
    tagline: "4K ウェブカメラ PCカメラ、800万画素 4K@30FPS&1080P@60FPS 90°広角レンズ 固定フォーカス、AIノイズキャンセリングマイク、自動光補正、プライバシーカバー付き",
    price: 4999,
    rating: 4.8,
    reviews: 1621,
    image: "https://m.media-amazon.com/images/I/61-RpWiDcPL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQZ5SST2",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #23" }]}],
  },
  {
    id: "cam-str-024-6ty5",
    category: "camera",
    name: "S600L",
    brand: "EMEET",
    tagline: "EMEET S600L 4K Webカメラ リングライト一体型 美肌PDAFオートフォーカス 自動露出補正 デュアルマイク付き webカメラ ライト付き ウェブカメラ ダイヤル操作 USB接続 配信・会議対応",
    price: 13980,
    rating: 4.4,
    reviews: 37,
    image: "https://m.media-amazon.com/images/I/615ZetJnGlL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCCV6TY5",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "73°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "73°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #24" }]}],
  },
  {
    id: "cam-str-025-2yqd",
    category: "camera",
    name: "C922n",
    brand: "Logicool",
    tagline: "ジクール Webカメラ C922n フルHD 1080P ストリーミング 撮影用 三脚 スタンド 付き オートフォーカス ステレオ マイク ウェブカメラ ウェブカム PC Mac ノートパソコン Zoom Skype 国内正規品 2年間メーカー保証",
    price: 11400,
    rating: 4.4,
    reviews: 2652,
    image: "https://m.media-amazon.com/images/I/51WmL9UhU6L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07QNJ2YQD",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "78°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "78°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #25" }]}],
  },
  {
    id: "cam-str-027-1hm3",
    category: "camera",
    name: "C960",
    brand: "EMEET",
    tagline: "1080p / 30fps・90°画角・固定フォーカス・内蔵マイク",
    price: 2599,
    rating: 4,
    reviews: 304,
    image: "https://m.media-amazon.com/images/I/61PSCxmrwgL._AC_SL1500_.jpg",
    connection: "USB-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09VSM1HM3",
    highlights: [
      { label: "解像度", value: "1080p / 30fps" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p / 30fps" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #27" }]}],
  },
  {
    id: "cam-str-028-y8fg",
    category: "camera",
    name: "Link 2C",
    brand: "Insta360",
    tagline: "2C Webカメラ 4K ウェブカメラ1/2インチセンサー| 自動フレーミング| HDR| AIノイズキャンセリング マイク付き| Zoom Teams Twitch対応",
    price: 25800,
    rating: 4.6,
    reviews: 1280,
    image: "https://m.media-amazon.com/images/I/51ueipcvQRL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AIオートフレーミング"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DDTGY8FG",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79.5°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "79.5°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #28" }]}],
  },
  {
    id: "cam-str-030-nz4j",
    category: "camera",
    name: "MEET SE 1080P 100FPS FHD",
    brand: "OBSBOT",
    tagline: "OBSBOT MEET SE 1080P 100FPS FHD Webカメラウェブカメラ AI搭載 1/2.8 CMOS HDR 位相差検出AF フィルター加工 ノイズ低減マイク ライブ配信 ビデオ通話",
    price: 14280,
    rating: 4.4,
    reviews: 1780,
    image: "https://m.media-amazon.com/images/I/51A+soaAXmL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DQ8TNZ4J",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "79.7°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "100fps" },
          { label: "画角", value: "79.7°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #30" }]}],
  },
  {
    id: "cam-str-031-26zr",
    category: "camera",
    name: "C660OW",
    brand: "Logicool",
    tagline: "ロジクール ウェブカメラ Brio 100 C660OW オフホワイト フルHD 1080P マイク付き 自動光補正 プライバシーシャッター Logi Options+対応 Zoom Mircosoft Teams Meet Webカメラ PC Windows Mac 会議 国内正規品",
    price: 3900,
    rating: 4.3,
    reviews: 243,
    image: "https://m.media-amazon.com/images/I/51XVwJ+TmgL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLP26ZR",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "58°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "58°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #31" }]}],
  },
  {
    id: "cam-str-033-y78y",
    category: "camera",
    name: "TINY 2 Lite  4K",
    brand: "OBSBOT",
    tagline: "Webカメラ 4K ウェブカメラAI搭載 自動追跡 4800万画素 HDR 位相差検出AF フィルター加工 ノイズ低減",
    price: 29800,
    rating: 4.3,
    reviews: 1965,
    image: "https://m.media-amazon.com/images/I/51WarvcFlCL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CZ6XY78Y",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79.4°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "79.4°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #33" }]}],
  },
  {
    id: "cam-str-035-sdc2",
    category: "camera",
    name: "EMEET S600",
    brand: "EMEET",
    tagline: "800万画素| 1080p 60fps| 73°視野角| PDAFオートフォーカス| 二つノイズキャンセリングマイク内蔵",
    price: 8999,
    rating: 4.6,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/61XeAxq0ZdL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D664SDC2",
    highlights: [
      { label: "解像度", value: "4K / 30fps" },
      { label: "画角", value: "73°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K / 30fps" },
          { label: "フレームレート", value: "60fps (1080p)" },
          { label: "画角", value: "73°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #35" }]}],
  },{
    id: "cam-str-038-3hx8",
    category: "camera",
    name: "Insta360 Link 2",
    brand: "Insta360",
    tagline: "Insta360 Link 2 Webカメラ 4K ウェブカメラ PTZ 1/2インチセンサー AI追跡 ジンバル搭载 HDR AIノイズキャンセリング マイク付き 配信 ビデオ通話 会議用 Zoom",
    price: 30880,
    rating: 4.6,
    reviews: 1458,
    image: "/images/cameras/insta360-link-2.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DDTH3HX8",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79.5°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "79.5°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #38" }]}],
  },
  {
    id: "cam-str-039-6cwm",
    category: "camera",
    name: "AIRHUG 02 Webカメラ",
    brand: "AIRHUG",
    tagline: "AIRHUG 2K USB PC用ウェブカメラ（プライバシーカバー付き・マイクなし）プラグ＆プレイ対応、マイク非搭載、78°広角レンズ、ストリーミング・会議用",
    price: 4280,
    rating: 4.2,
    reviews: 270,
    image: "https://m.media-amazon.com/images/I/71vTZ49ZWnL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09XXT6CWM",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "78°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "78°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #39" }]}],
  },
    {
    id: "cam-str-042-xn7j",
    category: "camera",
    name: "書画カメラ USB 1600万画素 OCR対応 A3サイズ撮影 4K動画録画 360°回転 マイ",
    brand: "—",
    tagline: "書画カメラ USB 1600万画素 OCR対応 A3サイズ撮影 4K動画録画 360°回転 マイク内蔵 手元撮影オンライン授業 Web会議用 教育機関 テレワーカー 配信者向け ドキュメントカメラ",
    price: 15999,
    rating: 4.2,
    reviews: 24,
    image: "https://m.media-amazon.com/images/I/61m1nZyOE4L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: ["書画カメラ"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX43XN7J",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "82°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "82°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #42" }]}],
  },
  {
    id: "cam-str-046-lnzf",
    category: "camera",
    name: "TOALLIN 2K ウェブカメラ",
    brand: "TOALLIN",
    tagline: "2K / 30fps・90°画角・内蔵マイクTOALLIN 2K ウェブカメラ ゲーム用 500万画素 マイク内蔵 三脚付き90°広角WEBカメラ USBコンピューターカメラ ノートパソコン用 ライブストリーミング ビデオ通話",
    price: 2999,
    rating: 3.9,
    reviews: 62,
    image: "https://m.media-amazon.com/images/I/619xm8i-jyL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FN3NLNZF",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #46" }]}],
  },
  {
    id: "cam-str-048-r7hb",
    category: "camera",
    name: "C100",
    brand: "EMEET",
    tagline: "EMEET C100 1080P Webカメラ 66°視野角 金属製クリップ ウェブカメラ内蔵マイク 一体型プライバシーシャッター EMEETLINK利用可能 1/4インチ三脚穴 パソコンカメラ 在宅勤務 オンライン授業 会議 ライブ配信 USB-A接続",
    price: 3999,
    rating: 4.8,
    reviews: 29,
    image: "https://m.media-amazon.com/images/I/71Q0NoLzGGL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTXRR7HB",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "66°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "66°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #48" }]}],
  },
  {
    id: "cam-str-049-lvm9",
    category: "camera",
    name: "Joinylotus 2K Webカメラ（BY-B19）",
    brand: "—",
    tagline: "Webカメラ HD 2K 400万画素 広角レンズ マイク付き ブラック自動光補正| USB接続| 1/4インチ三脚穴| Zoom/Skype/YouTube対応| Windows11/10/8/7 Mac OS X対応",
    price: 25000,
    rating: 4,
    reviews: 271,
    image: "https://m.media-amazon.com/images/I/61SP84J3RkL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G1RCLVM9",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #49" }]}],
  },{
    id: "cam-str-050-sfx4",
    category: "camera",
    name: "C960 Ultra",
    brand: "EMEET",
    tagline: "EMEET C960 Ultra 4K webカメラ 1/1.5インチ大型センサー ウェブカメラメタルボディ 0.2秒高速オートフォーカス DRC補正 ホワイトボードモード デュアルマイク付き 回転式プライバシーシャッター",
    price: 17980,
    rating: 4.8,
    reviews: 28,
    image: "https://m.media-amazon.com/images/I/61KfqqGbg+L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GR59SFX4",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "73°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "73°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #50" }]}],
  },
  {
    id: "cam-str-050-xk6r",
    category: "camera",
    name: "OBSBOT Tiny 3 Lite",
    brand: "OBSBOT",
    tagline: "OBSBOT Tiny 3 Lite Webカメラ 4k 業界初の空間オーディオ ウェブカメラ1/2インチCMOS AI追尾 Youtube Twitch 配信 生放送 Zoom Teams オンラインミーティング対応",
    price: 33800,
    rating: 4.3,
    reviews: 297,
    image: "https://m.media-amazon.com/images/I/51HEvpp8M4L._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G63LXK6R",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79.1°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "120fps" },
          { label: "画角", value: "79.1°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #50" }]}],
  },
  {
    id: "cam-str-051-23tk",
    category: "camera",
    name: "C980pro",
    brand: "EMEET",
    tagline: "EMEET C980pro WEBカメラ ウェブカメラ 1台3役1080P HD 四つ360°集音AIマイク 二つスピーカー内蔵 USB接続簡単 目隠しカバー付き WEB会議用 ビデオ通話 生放送 YOUTUBE Windows/Mac対応",
    price: 7999,
    rating: 3.9,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/61vCh3iYXGL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DRCJ23TK",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #51" }]}],
  },
    {
    id: "cam-str-053-t6m8",
    category: "camera",
    name: "V08AF",
    brand: "NearStream",
    tagline: "NearStream V08AF Webカメラ 4K ウェブカメラ 1080p 60fps PCカメラ USB オートフォーカス 視野角調整可能 マイク付き ノイズキャンセリング ビデオ会議/オンライン授業/ライブ配信用 Windows/Mac/Linux/Chrome Zoom/Teams/Meet/Webex LINE YouTube/TikTok プライバシー保護 ブラック",
    price: 9980,
    rating: 3.9,
    reviews: 25,
    image: "https://m.media-amazon.com/images/I/611aiJbz4+L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GW5WT6M8",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #53" }]}],
  },
  {
    id: "cam-str-053-mqxp",
    category: "camera",
    name: "Sofun Webカメラ",
    brand: "—",
    tagline: "1080p / 60fps・90°画角・内蔵マイク",
    price: 1999,
    rating: 3.5,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/61Vm8z5d4mL._AC_SL1500_.jpg",
    connection: "USB-A / USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FW41MQXP",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A / USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #53" }]}],
  },
  {
    id: "cam-str-054-tv64",
    category: "camera",
    name: "4K  UHD 800万画素 120°広角会議用カメラ1080P@60FPS PC用",
    brand: "Angetube",
    tagline: "Angetube 4K Webカメラ UHD 800万画素 120°広角会議用カメラ1080P@60FPSウェブカメラ PC用PDAFオートフォーカス、ノイズキャンセリングマイク2個、自動光補正、USB-A/C、プライバシーカバー",
    price: 7219,
    rating: 4.2,
    reviews: 21,
    image: "https://m.media-amazon.com/images/I/61f8bcUAXUL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FN3BTV64",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #54" }]}],
  },
  {
    id: "cam-str-054-v167",
    category: "camera",
    name: "Creative Live! Cam Sync V3",
    brand: "Creative",
    tagline: "ワイドアングル 2K QHD 4x デジタルズーム デュアルマイク搭載 プライバシー用レンズカバー付 Webカメラ LC-SYNCV3",
    price: 3718,
    rating: 4.6,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/41KI2RFbefL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B74YV167",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "95°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "95°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #54" }]}],
  },
  {
    id: "cam-str-055-8zzz",
    category: "camera",
    name: "Spedal 931 4K Webカメラ",
    brand: "Spedal",
    tagline: "Spedal 931 4K Webカメラ UHD 800万画素 120°広角 会議用カメラ Sony 1/2.8インチセンサー4倍ズーム リモコン＆三脚付き 内蔵マイク USB プラグ＆プレイ オンライン授業・ウェブ会議・テレワーク対応",
    price: 9990,
    rating: 4,
    reviews: 3456,
    image: "https://m.media-amazon.com/images/I/61Bj5nnKCiL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09N6Y8ZZZ",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #55" }]}],
  },
  {
    id: "cam-str-055-mr75",
    category: "camera",
    name: "UCAM-C750FBBK",
    brand: "ELECOM",
    tagline: "エレコム WEBカメラ UCAM-C750FBBK マイク内蔵 フルHD 1080p 30FPS 500万画素 高精細ガラスレンズ ケーブル長1.5m ブラック",
    price: 4011,
    rating: 3.8,
    reviews: 839,
    image: "https://m.media-amazon.com/images/I/61kwW55RnWL._AC_SL1500_.jpg",
    connection: "USB-A (USB 2.0)",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B078J9MR75",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "66°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "66°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A (USB 2.0)" },
          { label: "Amazon売れ筋", value: "Webカメラ #55" }]}],
  },
  {
    id: "cam-str-056-6hx1",
    category: "camera",
    name: "NOVA 4K  UHD",
    brand: "EMEET",
    tagline: "EMEET NOVA 4K webカメラ UHD ウェブカメラPDAFオートフォーカス デュアルノイズキャンセリングマイク 73° 視野角 pcカメラ 自動光補正 プラグ&プレイ プライバシーカバー付き 遠隔会議＆ライブストリーミングに適用",
    price: 4999,
    rating: 4.4,
    reviews: 92,
    image: "https://m.media-amazon.com/images/I/61bCeQBjUwL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CY1N6HX1",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "73°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "73°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #56" }]}],
  },
  {
    id: "cam-str-059-5b4r",
    category: "camera",
    name: "Nuroum Webカメラ V11",
    brand: "Nuroum",
    tagline: "Nuroum Webカメラ 2K ウェブカメラ フルHD1080P 60FPS 400万画素 90°広角 パソコンカメラ デュアルマイク内蔵 ノイズキャンセリング PCカメラ プライバシーカバー付き 自動調光補正 ストリーミング ウェブカム USBプラグ&プレイ テレワーク/ビデオ会議",
    price: 3680,
    rating: 4.1,
    reviews: 409,
    image: "https://m.media-amazon.com/images/I/51hoQUpYchL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09ZTN5B4R",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #59" }]}],
  },{
    id: "cam-str-061-9kv6",
    category: "camera",
    name: "Hollyland Lyra 4K",
    brand: "Hollyland",
    tagline: "Webカメラ ウェブカメラ、5000万画素、USB Type-C接続、全指向性マイク内蔵、オートフォーカス、プライバシー保護機能",
    price: 24200,
    rating: 4.3,
    reviews: 56,
    image: "https://m.media-amazon.com/images/I/51+bDeh8M5L._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FR8P9KV6",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #61" }]}],
  },
  {
    id: "cam-str-064-fj2c",
    category: "camera",
    name: "NexiGoライト付き N960E",
    brand: "NexiGo",
    tagline: "NexiGo webカメラ 60fps ライト付き N960E ウェブカメラ 1080P 自動光補正 無段階調光 3光色 pcカメラ オートフォーカス プライバシーカバー内蔵 usbカメラ ステレオマイク2台 ソフトウェア付属",
    price: 7999,
    rating: 4.4,
    reviews: 3368,
    image: "https://m.media-amazon.com/images/I/61hoP7YTjDL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0921VFJ2C",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #64" }]}],
  },
  {
    id: "cam-str-065-llxl",
    category: "camera",
    name: "Cyvorsky 2K自動ピント機能",
    brand: "Cyvorsky",
    tagline: "Cyvorsky【400万画素・2K自動ピント機能】 ウェブカメラ Webカメラ軽量小型 （75°画角-余計な背後が映らない・盗撮防止カバー付き・マイク内蔵・自動光補正・30fpsオートフォーカス） 挟角 USBカメラ webcam PCカメラ ドライバ不要 テレワーク/オンライン会議 ユーチューバ",
    price: 2780,
    rating: 3.9,
    reviews: 241,
    image: "https://m.media-amazon.com/images/I/61XmeqnNiCL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0919MLLXL",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "75°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "75°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #65" }]}],
  },{
    id: "cam-str-068-ynfx",
    category: "camera",
    name: "INS-Flip 4",
    brand: "INSWAN",
    tagline: "INSWAN INS-Flip 4 (台湾製) USB 携帯型書画カメラ/Webカメラ - 4K解像度 1300万画素 折りたたみ式ポータブルプラグ＆プレイ対応 オートフォーカス 10cm近接撮影 内蔵マイク およびLED | Win/Mac/Chromebook/iPad/インタラクティブホワイトボード対応",
    price: 14900,
    rating: 4.2,
    reviews: 111,
    image: "https://m.media-amazon.com/images/I/51Qh-UhdPYL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: ["書画カメラ"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CNT5YNFX",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #68" }]}],
  },
  {
    id: "cam-str-069-wdn6",
    category: "camera",
    name: "AISPEECH UVC40 4Kウェブカメラ",
    brand: "—",
    tagline: "ウェブカメラ 4K オートフォーカス 自動光調整 ノイズキャンセリングマイク 内蔵 65°広角 プライバシーカバー付き USB接続 UVC40 オンライン会議・ストリーミング・ビデオチャット対応",
    price: 4999,
    rating: 4,
    reviews: 22,
    image: "https://m.media-amazon.com/images/I/61pG8LevpAL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FNZZWDN6",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "65°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "65°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #69" }]}],
  },
  {
    id: "cam-str-070-v1v9",
    category: "camera",
    name: "ZAIDER webカメラ 2K",
    brand: "ZAIDER",
    tagline: "ZAIDER webカメラ 2K ウェブカメラ PCカメラ 【自動光補正＆オートフォーカス】 プライバシー保護カバー付き 2つのマイク内蔵 三脚対応 広角 角度調整 クリップ式 USB-A接続 外付けカメラ",
    price: 2380,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/614Fyae1MIL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GH61V1V9",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "85°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "85°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #70" }]}],
  },
  {
    id: "cam-str-071-1gmn",
    category: "camera",
    name: "Gawervan USB書画カメラ",
    brand: "—",
    tagline: "USB書画カメラ／折りたたみポータブルWebカメラ：実物投影機能、内蔵マイク＆LEDライト搭載、オートフォーカス、画像反転機能対応、A3サイズ - Mac OS／Windows／Chromebook対応、Web会議、遠隔学習、教室授業、ライブ配信",
    price: 8800,
    rating: 3.6,
    reviews: 17,
    image: "https://m.media-amazon.com/images/I/61t4BmKs0mL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: ["書画カメラ"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FQC11GMN",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "—" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #71" }]}],
  },
  {
    id: "cam-str-072-x3sp",
    category: "camera",
    name: "PC用2Kウェブカメラ",
    brand: "—",
    tagline: "PC用2Kウェブカメラ、マイクと三脚付きウェブカメラ、自動光補正、USBウェブカメラプラグアンドプレイ、90°広視野角、プライバシーカバー",
    price: 3299,
    rating: 3.9,
    reviews: 25,
    image: "https://m.media-amazon.com/images/I/71WlY3EH1GL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F87XX3SP",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #72" }]}],
  },
  {
    id: "cam-str-073-yh1y",
    category: "camera",
    name: "Facecam 4K",
    brand: "Elgato",
    tagline: "Elgato Facecam 4K – 4K60 スタジオウェブカメラ、デジタル一眼レフ コントロール、シネマティックエフェクト、49 mm レンズフィルター、HDR、非圧縮映像、最適化されたフォーカスエリア",
    price: 22500,
    rating: 4.4,
    reviews: 11,
    image: "https://m.media-amazon.com/images/I/615qKAG9IML._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DXF7YH1Y",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #73" }]}],
  },
  {
    id: "cam-str-075-nt1f",
    category: "camera",
    name: "Angetube 4K Webカメラ　913AI",
    brand: "Angetube",
    tagline: "Angetube 4K Webカメラ 会議カメラ 高速オートフレーミング 10倍ズーム1080p 60fpsウェブカメラ配信・オンラインミーティングにプライバシーシャッター付、30°- 100°視野角、AI追跡、HDR、リモートコントロール、自動光補正 ノイズキャンセリング マイク プラグアンドプレイ",
    price: 11999,
    rating: 4.2,
    reviews: 162,
    image: "https://m.media-amazon.com/images/I/71-Qv0c5MyL._AC_SL1500_.jpg",
    connection: "USB-C / USB-A",
    cameraSpreadsheetITags: ["AIオートフレーミング"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BYCPNT1F",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "70°/80°/90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "70°/80°/90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C / USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #75" }]}],
  },
  {
    id: "cam-str-076-6p9g",
    category: "camera",
    name: "Aury webカメラ 2K",
    brand: "Aury",
    tagline: "Aury webカメラ 2K ウェブカメラ 自動HD光補正機能を搭載 100°視野角 ノイズキャンセリングマイク付きpcカメラ&プレイ プライバシーカバー",
    price: 2080,
    rating: 4,
    reviews: 80,
    image: "https://m.media-amazon.com/images/I/71f1fZV-etL._AC_SL1500_.jpg",
    connection: "—",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DRFD6P9G",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "100°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "100°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "—" },
          { label: "Amazon売れ筋", value: "Webカメラ #76" }]}],
  },
  {
    id: "cam-str-077-kjjd",
    category: "camera",
    name: "TreasLin USB 書画カメラ",
    brand: "TreasLin",
    tagline: "USB 書画カメラ1000万画素Webカメラ実物投影機4K@30fps/ 1080P@60fps CMOS オートフォーカス LEDライト搭載 ホワイト Zoom Skype Google Meet対応",
    price: 6999,
    rating: 3.8,
    reviews: 56,
    image: "https://m.media-amazon.com/images/I/616DB+DvlPL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CQCCKJJD",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #77" }]}],
  },
  {
    id: "cam-str-079-yc35",
    category: "camera",
    name: "4K Web会議 PTZカメラ",
    brand: "TONGVEO",
    tagline: "TONGVEO 4K Web会議 PTZカメラ AI自動追尾機能3倍光学ズーム92°広角視野HDMI/USB3.0接続プラグアンドプレイ対応 Zoom/Teams/教会/ライブ配信/教育用 リモコン付 三脚取付可能",
    price: 37300,
    rating: 4.4,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/61Wv4Uvi8rL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GHNTYC35",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "92°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "92°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #79" }]}],
  },
  {
    id: "cam-str-080-ccmp",
    category: "camera",
    name: "WASHODO Webカメラ",
    brand: "—",
    tagline: "Webカメラ マイク内蔵 4K 2K 1080P 超高画素 85°広角 USBカメラ ストリーミング ウェブカメラ プライバシーカバー 光補正 ビデオ会議/オンライン授業/ライブ配信用",
    price: 1283,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/41nZaz25Z+L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H1HBCCMP",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "85°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "—" },
          { label: "画角", value: "85°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #80" }]}],
  },
  {
    id: "cam-str-081-hb16",
    category: "camera",
    name: "j5create 360度 Webカメラ",
    brand: "j5create",
    tagline: "j5create 360度 Webカメラ USB C USB A 両対応 ミーティング 会議室カメラ 1080p 左右反転機能 全指向性マイク 6種類モード パノラマ 2分割 ホスト デュアルホスト シングル ワイドビュー タッチバー搭載 設定不要 プラグ＆プレイ",
    price: 15664,
    rating: 3.6,
    reviews: 61,
    image: "https://m.media-amazon.com/images/I/61grC5pbwBL._AC_SL1500_.jpg",
    connection: "USB-C / USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08NV3HB16",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "360°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "360°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C / USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #81" }]}],
  },
  {
    id: "cam-str-082-1q5z",
    category: "camera",
    name: "C570",
    brand: "Innex",
    tagline: "Innex C570 4K ePTZ AI搭載 120°超広視野角5倍デジタルズーム コンファレンスカメラAIによるオートフレーミング デュアルマイク＆プライバシーシャッター内蔵 リモコン付属 USB電源 自動光補正",
    price: 24800,
    rating: 4.1,
    reviews: 67,
    image: "https://m.media-amazon.com/images/I/61tPQKjmuSL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AIオートフレーミング"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BG9B1Q5Z",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "—" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #82" }]}],
  },
  {
    id: "cam-str-083-7f91",
    category: "camera",
    name: "JOYUSING FlexCam10 4K",
    brand: "—",
    tagline: "FlexCam10 4K Webカメラ アイコンタクト PC用 4モード搭載 マイク内蔵 PDAFオートフォーカス ノイズキャンセリングマイク2基 画角79° 会議",
    price: 10449,
    rating: 4.5,
    reviews: 18,
    image: "https://m.media-amazon.com/images/I/61ya+qxa5IL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS547F91",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "79°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #83" }]}],
  },
  {
    id: "cam-str-085-t6r9",
    category: "camera",
    name: "EMEET PIXY ワイヤレス カメラ",
    brand: "EMEET",
    tagline: "EMEET PIXY ワイヤレス カメラ デュアルカメラ AI 自動追跡 PTZ 4K HDR ストリーミングカメラ 1/2.55 インチセンサー ジェスチャーコントロール ライブ配信 48kHz内蔵マイク 最大8時間バッテリー駆動",
    price: 29999,
    rating: 4,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/513IBfiUXrL._AC_SL1500_.jpg",
    connection: "wi-fi/USB",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXFDT6R9",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "97°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "97°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "wi-fi/USB" },
          { label: "Amazon売れ筋", value: "Webカメラ #85" }]}],
  },
  {
    id: "cam-str-086-jgmn",
    category: "camera",
    name: "MAXHUB WebCam UC-W20",
    brand: "MAXHUB",
    tagline: "MAXHUB WebCam UC-W20 会議用 WEBカメラ マイク内蔵 4K 1300万画素 集音最大4ｍ 上下左右10度の角度調整可能USB接続,1/3.06″SONY センサー,視野角80度,ノイズリダクション搭載,2D & 3D DNR,オートフォーカス,360度水平回転,WEB会議,",
    price: 8800,
    rating: 3.5,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/51LD+fd0jeL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09YY7JGMN",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "—" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #86" }]}],
  },
  {
    id: "cam-str-087-m1j2",
    category: "camera",
    name: "G53-2k",
    brand: "—",
    tagline: "Webカメラ ウェブカメラ デュアルAIノイズキャンセリングマイク付き2K QHD2000万画素ウェブカメラ オートフォーカス,自動光補正 超広角120° プライバシーカバー、2560*1440P@30fps USBプラグ&プレイ",
    price: 6649,
    rating: 3.6,
    reviews: 33,
    image: "https://m.media-amazon.com/images/I/610vJWmUFZL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FB3TM1J2",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #87" }]}],
  },
  {
    id: "cam-str-089-s7c3",
    category: "camera",
    name: "デュアルAIノイズキャンセリングマイク付き4K UHD1200万画素 オートフォーカス,自動光補",
    brand: "—",
    tagline: "Webカメラ ウェブカメラ デュアルAIノイズキャンセリングマイク付き4K UHD1200万画素ウェブカメラ オートフォーカス,自動光補正 超広角120° プライバシーカバー、3840*2160P@25fps USBプラグ&プレイ (G53-4k)",
    price: 5990,
    rating: 3.6,
    reviews: 35,
    image: "https://m.media-amazon.com/images/I/610vJWmUFZL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FB3SS7C3",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #89" }]}],
  },
  {
    id: "cam-str-090-867s",
    category: "camera",
    name: "QIMIAOUS Webカメラ",
    brand: "—",
    tagline: "Webカメラ ウェブカメラ フルHD 1080P 200万画素 ストリーミング 自動光補正 超広角120°360°回転 内蔵マイク 会議用PCカメラ 三脚穴 Windows XP/ 2000/ 2003/ Vista/7/8/10/11 、Mac OS、Zoom、Teams、Youtubeなどに対応可能 ビデオ会議/オンライン授業/ライブ配信用 卓上三脚付属",
    price: 2698,
    rating: 4,
    reviews: 33,
    image: "https://m.media-amazon.com/images/I/71IrIRRD6jL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FR4C867S",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #90" }]}],
  },
  {
    id: "cam-str-091-mc1x",
    category: "camera",
    name: "Remarks Japan ウェブカメラ",
    brand: "—",
    tagline: "ウェブカメラ マイク付き 小型 広角 会議用 4K フルHD 1080P webカメラ usb接続 自動光補正 配信用 日本語説明書付き",
    price: 1349,
    rating: 3.6,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/51C-KLl0X8L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GF7KMC1X",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #91" }]}],
  },
  {
    id: "cam-str-092-bfpl",
    category: "camera",
    name: "ST-W36",
    brand: "—",
    tagline: "PC用4Kウェブカメラ、1080P@60FPS、ノイズ低減マイク、92度視野、8MP USB Web カメラ、360度回転ヘッド、プライバシーカバー自動光補正、プラグアンドプレイ、",
    price: 3999,
    rating: 3.7,
    reviews: 33,
    image: "https://m.media-amazon.com/images/I/512IJS+4AZL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FJXFBFPL",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "92°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "92°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #92" }]}],
  },
    {
    id: "cam-str-098-dzgz",
    category: "camera",
    name: "XinYaa　ウェブカメラ",
    brand: "—",
    tagline: "ウェブカメラ Webカメラ フルHD 1080P 200万画素 ストリーミング 自動光補正 内蔵マイク 超広角120° 会議用PCカメラ 三脚穴 Windows",
    price: 2298,
    rating: 3.8,
    reviews: 36,
    image: "https://m.media-amazon.com/images/I/716-L-jEv9L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FG7RDZGZ",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "95°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "95°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #98" }]}],
  },
  {
    id: "cam-str-099-xkv8",
    category: "camera",
    name: "Tenveo VHD3UPro",
    brand: "Tenveo",
    tagline: "Tenveo PTZカメラWeb会議3倍光学ズーム 超広角 HDMI USB3.0 RS232 1080P 60fpsカメラWebカメラリモコン付 三脚対応 会議室用 室内用 少人数会議",
    price: 29490,
    rating: 4.2,
    reviews: 81,
    image: "https://m.media-amazon.com/images/I/71PBORL8XPL._AC_SL1500_.jpg",
    connection: "USB-A/HDMI/RS485/RS232",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CJM2XKV8",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "114°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "114°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A/HDMI/RS485/RS232" },
          { label: "Amazon売れ筋", value: "Webカメラ #99" }]}],
  },{
    id: "cam-str-111-t8bc",
    category: "camera",
    name: "Ｑ’ｆｏｏ　リングライト付きWebカメラ",
    brand: "—",
    tagline: "webカメラ LEDライト ウェブカメラ 三脚 マイク内蔵 110度広角 オートフォーカス usbカメラ 1080p 200万画素 30FPS PCカメラ 外付け Zoom対応",
    price: 2860,
    rating: 4.3,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/61GZRpZ-Z4L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09QXKT8BC",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "110°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "110°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #111" }]}],
  }]
