import type { Gadget } from "./gadgets"

/** Amazon.co.jp ウェブカメラ売れ筋（10500630051）1–2ページ目 + 既存定番モデル。 */
export const cameraBestsellers: Gadget[] = [
  {
    id: "cam-bs-001",
    category: "camera",
    name: "C960",
    brand: "EMEET",
    tagline: "EMEET C960 Webカメラ HD1080P 200万画素 90°広角",
    price: 2599,
    rating: 4.3,
    reviews: 32396,
    image: "https://m.media-amazon.com/images/I/61F+5bd0PUL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07M6Y7355",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "90 × 45 × 45 mm" },
          { label: "重量", value: "118 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #1" }]}],
  },
  {
    id: "cam-bs-002",
    category: "camera",
    name: "C270nd",
    brand: "Logicool",
    tagline: "【Amazon.co.jp限定】 ロジクール ウェブカメラ HD 720P C270nd 小型 自動光補正 国内正規品",
    price: 2490,
    rating: 4.1,
    reviews: 568,
    image: "https://m.media-amazon.com/images/I/51BdAtSHHkL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D21FZ5KN",
    highlights: [
      { label: "解像度", value: "720p" },
      { label: "画角", value: "60°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "72 × 52 × 19 mm" },
          { label: "重量", value: "75 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "720p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "60°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #2" }]}],
  },
  {
    id: "cam-bs-003",
    category: "camera",
    name: "C920n",
    brand: "Logicool",
    tagline: "フルHD 1080p・78°画角・オートフォーカス・デュアルステレオマイクの定番ウェブカメラ",
    price: 5200,
    rating: 4.4,
    reviews: 4616,
    image: "https://m.media-amazon.com/images/I/61FLOm0OiLL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07QQR6G5N",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "78°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "94 × 71 × 43.3 mm" },
          { label: "重量", value: "162 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "78°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #3" }]}],
  },
  {
    id: "cam-bs-004",
    category: "camera",
    name: "PowerConf C200",
    brand: "Anker",
    tagline: "2K画質・65°/78°/95°画角切替・AIノイズリダクション搭載のコンパクトウェブカメラ",
    price: 6980,
    rating: 4.4,
    reviews: 909,
    image: "https://m.media-amazon.com/images/I/71xjnX1ckgL._AC_SL1500_.jpg",
    connection: "USB-C (本体) / USB-A (PC側)",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09MHPFV4Q",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "65°/78°/95°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "55 × 51 × 41 mm" },
          { label: "重量", value: "83 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "65°/78°/95°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C (本体) / USB-A (PC側)" },
          { label: "Amazon売れ筋", value: "Webカメラ #4" }]}],
  },
  {
    id: "cam-bs-005",
    category: "camera",
    name: "FineCam Lite",
    brand: "UGREEN",
    tagline: "1080p / 30fps・85°画角・固定フォーカス・内蔵マイク",
    price: 1949,
    rating: 4.1,
    reviews: 6704,
    image: "https://m.media-amazon.com/images/I/61OOmC0MH7L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C76ZD7KV",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "85°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "5.8 × 11.4 × 12.2 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "85°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #5" }]}],
  },
  {
    id: "cam-bs-006",
    category: "camera",
    name: "Brio 100",
    brand: "Logicool",
    tagline: "ロジクール ウェブカメラ Brio 100 C660GR グラファイト フルHD 1080P マイク付き 自動光補正 プライバシーシャッター Logi Options+対応 Zoom Mircosoft Teams Meet Webカメラ PC",
    price: 3900,
    rating: 4,
    reviews: 1086,
    image: "https://m.media-amazon.com/images/I/51s64c4REDL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BKTJ9X2H",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "58°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "49 × 49 × 45 mm" },
          { label: "重量", value: "75 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "58°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #6" }]}],
  },
  {
    id: "cam-bs-007",
    category: "camera",
    name: "Brio 100",
    brand: "Logicool",
    tagline: "1080p / 30fps・65°画角・固定フォーカス・モノラルマイク",
    price: 3900,
    rating: 4.3,
    reviews: 243,
    image: "https://m.media-amazon.com/images/I/51qVgy7rFoL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLGQ9PD",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "58°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "58°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #7" }]}],
  },
  {
    id: "cam-bs-008",
    category: "camera",
    name: "UGREEN FineCam Lite 4K",
    brand: "UGREEN",
    tagline: "UGREEN FineCam Lite 4K ウェブカメラ PC用 Ultra HD 1080P 60FPS| マイク付き、プライバシーカバー| 70° FOV、PDAF オートフォーカス| USB A＆USB C アダプター|",
    price: 3734,
    rating: 4.4,
    reviews: 2346,
    image: "https://m.media-amazon.com/images/I/619KR4eEZkL._AC_SL1500_.jpg",
    connection: "USB-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DT9MMZTL",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "70°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "70°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #8" }]}],
  },{
    id: "cam-bs-010",
    category: "camera",
    name: "PHILIPS ウェブカメラSPL6418",
    brand: "PHILIPS",
    tagline: "4K UHD webカメラ 800万画素 1080P@30FPS対応 自動光補正 95°視野角 内蔵マイク プライバシーカバー パソコン用カメラ ビデオ会議/オンライン授業/ライブ配信用SPL6418",
    price: 6980,
    rating: 4.5,
    reviews: 69,
    image: "https://m.media-amazon.com/images/I/61t1XOERA-L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS5Y4FBF",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "95°" },
      { label: "フォーカス", value: "自動光補正" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "9 × 3.2 × 3.3 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "95°" },
          { label: "フォーカス", value: "自動光補正" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #10" }]}],
  },
  {
    id: "cam-bs-011",
    category: "camera",
    name: "4K Webカメラ",
    brand: "AOC",
    tagline: "Logicool Webカメラ Brio 300 フルHD 1080P マイク付き 自動光補正 プライバシーシャッター Zoom Mircosoft Teams Meet 認証 ノイズリダクション C700RO グラファイト ウェブカメラ ウェブカム PC Mac ノートパソコン Web会議 Skype 国内正規品 1年間メーカー保証",
    price: 5900,
    rating: 4.8,
    reviews: 127,
    image: "https://m.media-amazon.com/images/I/61-RpWiDcPL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GSVRGKG7",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "70°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "70°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #11" }]}],
  },
  {
    id: "cam-bs-012",
    category: "camera",
    name: "BSW305MBK",
    brand: "Buffalo",
    tagline: "バッファロー ウェブカメラ WEB 1080P フルHD fps 200 万画素 視野角 約81° Teams メーカー動作確認済 BSW305MBK",
    price: 2780,
    rating: 4,
    reviews: 1947,
    image: "https://m.media-amazon.com/images/I/41xeSX5O0kS._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09241T966",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "81°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "8 × 5.1 × 5 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "81°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #12" }]}],
  },
  {
    id: "cam-bs-013",
    category: "camera",
    name: "エレコム　UCAM-C520FBBK",
    brand: "ELECOM",
    tagline: "エレコム(ELECOM) WEBカメラ UCAM-C520FBBK 200万画素 HD 720p 30FPS マイク内蔵 高精細ガラスレンズ ケーブル長1.5m ブラック",
    price: 3068,
    rating: 3.8,
    reviews: 612,
    image: "https://m.media-amazon.com/images/I/51PbTI1r3ML._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B078JJVC4J",
    highlights: [
      { label: "解像度", value: "720p" },
      { label: "画角", value: "68°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "6 × 3.9 × 5.2 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "720p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "68°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #13" }]}],
  },
  {
    id: "cam-bs-014",
    category: "camera",
    name: "AOC AC310",
    brand: "AOC",
    tagline: "AOC Webカメラ 4K ウェブカメラ マイク付き 800万画素 1080P@30FPS対応 99°視野角 自動光補正 USB即挿即用 usbカメラ webcam プライバシーカバー ノイズキャンセル 会議用Webカメラ Streaming & Zoom 対応 パソコン カメラ Web camera ブラック AC310 【国内正規品】",
    price: 5143,
    rating: 4.7,
    reviews: 3159,
    image: "https://m.media-amazon.com/images/I/61t2DDONFfL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GGJ2ZKC1",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "95°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "95°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #14" }]}],
  },
  {
    id: "cam-bs-015",
    category: "camera",
    name: "LUPPY WEBカメラ Full HD 1080p",
    brand: "—",
    tagline: "WEBカメラ Full HD 1080p 200万画素 広角95° 小型 クリップ/スタンド式 固定フォーカスレンズ HD光補正機能付き ウェブカメラ マイク内蔵 ビデオ会議/授業用 WEBカメラ, Windows 11/10/8/7、Mac OS、AndroidおよびLinux, Teams, Zoom, Skype,Lineなど対応可 (小型・固定フォーカス)",
    price: 1480,
    rating: 4,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/61AX-+9o+9L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GGDYW7TS",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "95°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "95°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #15" }]}],
  },
  {
    id: "cam-bs-016",
    category: "camera",
    name: "S600",
    brand: "EMEET",
    tagline: "4K WEBカメラ 三脚＆ボールジョイント付き UHD ウェブカメラ 800万画素 1080p 60fps 高性能センサー搭載73°視野角 PDAFオートフォーカス 2つのノイズキャンセリングマイク内蔵 自動光補正",
    price: 12999,
    rating: 4.3,
    reviews: 162,
    image: "https://m.media-amazon.com/images/I/61TdMwHZIAL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D2XS2KZC",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "73°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "73°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #16" }]}],
  },
  {
    id: "cam-bs-017",
    category: "camera",
    name: "ロジクール ウェブカメラ C270n",
    brand: "Logicool",
    tagline: "HD 720P 小型 Webカメラ usbカメラ 自動光補正 カメラ ノイズリダクション マイク付 パソコン PC Windows Mac Chrome 国内正規品",
    price: 2707,
    rating: 4.2,
    reviews: 9151,
    image: "https://m.media-amazon.com/images/I/51BdAtSHHkL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07QMKND9M",
    highlights: [
      { label: "解像度", value: "720p" },
      { label: "画角", value: "55°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "72 × 52 × 19 mm" },
          { label: "重量", value: "75 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "720p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "55°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #17" }]}],
  },
  {
    id: "cam-bs-018",
    category: "camera",
    name: "DAMOACAMペン型ボディカメラ",
    brand: "DAMOACAM",
    tagline: "ウェアラブルカメラ 小型 録画 護身 会議録画 講義 現場記録 広角75° 大容量バッテリー USB-C 充電式",
    price: 13100,
    rating: 4.5,
    reviews: 35,
    image: "https://m.media-amazon.com/images/I/61egKonRD3L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYL41NT6",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "75°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "—" },
          { label: "画角", value: "75°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #18" }]}],
  },
  {
    id: "cam-bs-019",
    category: "camera",
    name: "EMEET C960 WEBカメラ",
    brand: "EMEET",
    tagline: "HD1080P 200万画素 90°広角 ワイドサイズ対応 内蔵マイク skype会議用 EMEETLINK利用可能 1/4インチ三脚穴 Windows10/11 Mac OS 10.14及び以上 Youtube/Skype",
    price: 2999,
    rating: 4.2,
    reviews: 7300,
    image: "https://m.media-amazon.com/images/I/715vw91kWYL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07MBQ1PT3",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "12.4 × 5.2 × 6.7 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #19" }]}],
  },
  {
    id: "cam-bs-020",
    category: "camera",
    name: "EMEET C960 三脚付き",
    brand: "EMEET",
    tagline: "90°広角 パソコンカメラ 内蔵マイク USB接続簡単 自動光補正 高さ調節 プライバシーカバー付き",
    price: 4799,
    rating: 4.2,
    reviews: 190,
    image: "https://m.media-amazon.com/images/I/61tozarrf+L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTY7C1G2",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #20" }]}],
  },
  {
    id: "cam-bs-022",
    category: "camera",
    name: "EMEET C950",
    brand: "EMEET",
    tagline: "ウェブカメラ 個人会議最適 HD1080P 200万画素 WEBカメラコンパクトサイズ 目隠しカバー 内蔵マイク skype会議用PCカメラ Windows (10,11)、macOS (10.14及び以上), Youtube, Skype",
    price: 2399,
    rating: 4.1,
    reviews: 874,
    image: "https://m.media-amazon.com/images/I/51-QZpvi9sL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09KC272JC",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "70°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "80 × 40 × 40 mm" },
          { label: "重量", value: "90 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "70°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #22" }]}],
  },
  {
    id: "cam-bs-023",
    category: "camera",
    name: "Diccik HD 1080P  内蔵マイク、90°広角、自動光補正機能、USBプラグアンドプレイPCカメラ、",
    brand: "—",
    tagline: "HD 1080P ウェブカメラ 内蔵マイク、90°広角ウェブカメラ、自動光補正機能、USBプラグアンドプレイPCカメラ、ビデオ会議/オンライン授業/ライブ配信に最適、ドライバー不要、ノートパソコン/デスクトップ/Mac対応 (黒) (ブラック)",
    price: 1760,
    rating: 4.3,
    reviews: 1124,
    image: "https://m.media-amazon.com/images/I/61uyuvoN0qL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GV33PHVC",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "10 × 5 × 5.5 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #23" }]}],
  },
  {
    id: "cam-bs-024",
    category: "camera",
    name: "EMEET C950　4K",
    brand: "EMEET",
    tagline: "4K / 30fps・73°画角・オートフォーカス・AIノイズキャンセリングマイク",
    price: 5499,
    rating: 4.1,
    reviews: 5837,
    image: "https://m.media-amazon.com/images/I/61AYxjaE3FL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D7V9BXPH",
    highlights: [
      { label: "解像度", value: "4K / 30fps" },
      { label: "画角", value: "73°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K / 30fps" },
          { label: "フレームレート", value: "60fps (1080p)" },
          { label: "画角", value: "73°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #24" }]}],
  },
  {
    id: "cam-bs-025",
    category: "camera",
    name: "EMEET PIXY webカメラ 4K",
    brand: "EMEET",
    tagline: "AI自動追跡 PTZカメラ PDAF高速オートフォーカス 美肌1/2.55\"ソニー製センサー 三つのマイク付き プリセット・ジェスチャー操作 配信用 OBS／Twitch／Switch 2 対応",
    price: 16000,
    rating: 4.4,
    reviews: 873,
    image: "https://m.media-amazon.com/images/I/61+Z1GoSwxL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F9N8RBF3",
    highlights: [
      { label: "解像度", value: "4K / 30fps" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K / 30fps" },
          { label: "フレームレート", value: "60fps (1080p)" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #25" }]}],
  },
  {
    id: "cam-bs-026",
    category: "camera",
    name: "MX BRIO 700 C1100GR 4K",
    brand: "Logicool",
    tagline: "Webカメラ usbカメラ 自動光補正 プライバシーシャッター USB Type-C ノイズ軽減ステレオマイク Sony Starvis センサー搭載 パソコン カメラ マイク PC Windows Mac Chrome C1100 グラファイト 国内正規品",
    price: 29291,
    rating: 4.5,
    reviews: 46,
    image: "https://m.media-amazon.com/images/I/61WQr6U3mwL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CVZW78XW",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "65°/78°/90°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "102 × 27 × 36 mm" },
          { label: "重量", value: "71 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "65°/78°/90°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #26" }]}],
  },
  {
    id: "cam-bs-027",
    category: "camera",
    name: "BSW505MBK",
    brand: "Buffalo",
    tagline: "バッファロー ウェブカメラ WEBカメラ 1080P フルHD 30fps 200万画素 広角約120° マイク内蔵 シンプル",
    price: 2980,
    rating: 3.9,
    reviews: 1166,
    image: "https://m.media-amazon.com/images/I/51ddgLEMbyL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07YWDP7PD",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "固定フォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "8 × 5.1 × 5 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "固定フォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #27" }]}],
  },
  {
    id: "cam-bs-028",
    category: "camera",
    name: "BxoteウェブカメラフルHD 1080P 30FPS 広角",
    brand: "—",
    tagline: "ルHD 1080P 30FPS 広角 Webカメラ 内蔵マイク USBカメラ ノイズ対策 オートフォーカス 【在宅勤務必要】 動画配信 家庭 会議 ゲーム実況 授業カメラ ビデオ通話用 Windows XP/7/8/10/ 2000/Mac OS X/Android TV対応",
    price: 1151,
    rating: 3.5,
    reviews: 155,
    image: "https://m.media-amazon.com/images/I/515ch9elvcL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08B4YCV8Y",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "—" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "—" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #28" }]}],
  },
  {
    id: "cam-bs-029",
    category: "camera",
    name: "2K Windows Hello Webカメラ",
    brand: "—",
    tagline: "Windows Hello 顔認識カメラ、ノイズ低減マイク、84°広視野角、スライドプライバシーカバー会議やビデオ通話用コンピューターカメラ、HD 自動光補正、USB ウェブカメラ、Microsoft Teams、Zoom、Google Meet 対応",
    price: 5999,
    rating: 3.8,
    reviews: 111,
    image: "https://m.media-amazon.com/images/I/51Lnf1OrwOL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FSKDTVVG",
    highlights: [
      { label: "解像度", value: "2K" },
      { label: "画角", value: "84°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "2K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "84°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #29" }]}],
  },
  {
    id: "cam-bs-030",
    category: "camera",
    name: "Link 2C Pro",
    brand: "Insta360",
    tagline: "4K ウェブカメラ 1/1.3インチセンサー、低照度、オートフレーミング、HDR、マイク付き 指向性ノイズキャンセリングマイク、ストリームデッキ、会議用 Zoom Teams Twitchに対応、配信・オンラインミーティングに最適 PC/Windows/Mac用",
    price: 34500,
    rating: 4.5,
    reviews: 228,
    image: "https://m.media-amazon.com/images/I/51TZdllIO-L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G3SSQMJQ",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "95°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "95°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #30" }]}],
  },
  {
    id: "cam-bs-051",
    category: "camera",
    name: "V02AF",
    brand: "NearStream",
    tagline: "1080p 60fps ウェブカメラ usb 95°広角/75°中角/60°狭角 pcカメラ フルHD オートフォーカス マイク付き ノイズキャンセリング ビデオ会議/オンライン授業用 Windows/Mac Zoom/Teams/Meet対応 プライバシーカバー付き",
    price: 5499,
    rating: 3.5,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61qw1wOTRNL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GM1JWVGC",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "95°/75°～86°/55°～60°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "95°/75°～86°/55°～60°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #51" }]}],
  },
  {
    id: "cam-bs-052",
    category: "camera",
    name: "V02AF",
    brand: "NearStream",
    tagline: "1080p / 60fps・95°/75°/60°画角・内蔵マイク",
    price: 5499,
    rating: 4.3,
    reviews: 84,
    image: "https://m.media-amazon.com/images/I/51uCaMu5d2L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DMZV9N81",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "95°/75°～86°/55°～60°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "42 × 43 × 61 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "95°/75°～86°/55°～60°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #52" }]}],
  },
  {
    id: "cam-bs-053",
    category: "camera",
    name: "C980GR",
    brand: "Logicool",
    tagline: "ロジクール Webカメラ C980GR フルHD 1080P 60fps ストリーミング AI オートフォーカス 自動露出補正 手ブレ USB Type-C ウェブカメラ ウェブカム PC Windows Mac スマホ YouTube グラファイト 国内正規品",
    price: 23980,
    rating: 4.4,
    reviews: 1778,
    image: "https://m.media-amazon.com/images/I/71sCQlUWp8L._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B086R71LGW",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "78°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "5.8 × 6.6 × 4.8 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "78°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #53" }]}],
  },
  {
    id: "cam-bs-054",
    category: "camera",
    name: "NexiGo N60",
    brand: "NexiGo",
    tagline: "1080Pウェブカメラ、マイク付き、調整可能な視野角、ズーム機能、ソフトウェア制御とプライバシーカバー、USB HDコンピューターウェブカメラ、プラグアンドプレイ、",
    price: 2999,
    rating: 4.3,
    reviews: 46332,
    image: "https://m.media-amazon.com/images/I/516WC9mU3-L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B088TSR6YJ",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "110°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "8 × 5.5 × 6.5 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "110°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #54" }]}],
  },
  {
    id: "cam-bs-055",
    category: "camera",
    name: "4K Webカメラ",
    brand: "DEPSTECH",
    tagline: "4K / 30fps・オートフォーカス・デュアルマイク",
    price: 5900,
    rating: 4.2,
    reviews: 36,
    image: "https://m.media-amazon.com/images/I/5179HTtA9PL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BQYCMGNP",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "70°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "70°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #55" }]}],
  },
  {
    id: "cam-bs-056",
    category: "camera",
    name: "DEPSTECH Webカメラ DW49",
    brand: "DEPSTECH",
    tagline: "4K オートフォーカス 800万画素 ウェブカメラ UHD画質 デュアルマイク内蔵 三脚付属 USB接続 PCカメラ",
    price: 3799,
    rating: 4.2,
    reviews: 1654,
    image: "https://m.media-amazon.com/images/I/716IBU12OUL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08QF47VQB",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "80°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "80°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #56" }]}],
  },
  {
    id: "cam-bs-057",
    category: "camera",
    name: "OBSBOT MEET 2 4K",
    brand: "OBSBOT",
    tagline: "AI搭載 4800万画素 HDR 位相差検出AF フィルター加工 ノイズ低減マイク ライブ配信 ビデオ通話 PC Mac Windows (ホワイト)",
    price: 18530,
    rating: 4.4,
    reviews: 1605,
    image: "https://m.media-amazon.com/images/I/51fJeZhKPaL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AIオートフレーミング"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9W7W7PZ",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "79.4°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "79.4°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #57" }]}],
  },
  {
    id: "cam-bs-058",
    category: "camera",
    name: "Nuroum C40",
    brand: "Nuroum",
    tagline: "4K Webカメラ 120°超広角 マイクスピーカー 一体型ノイズキャンセリングマイク 内蔵 拡張マイク＆USBドングル対応 最大16メートル集音範囲 【5倍ズーム｜自動フレーミング｜全二重通話｜リモコン操作】Web会議/オンライン授業/ハイブリッドワーク向け Zoom/Teams/Skype対応",
    price: 35982,
    rating: 4.3,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/610RqVFdtsL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GK75YRGT",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "120°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "—" },
          { label: "画角", value: "120°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #58" }]}],
  },
  {
    id: "cam-bs-059",
    category: "camera",
    name: "Nuroum C10",
    brand: "Nuroum",
    tagline: "会議用マイクスピーカー 一体型Webカメラ 1080P HDR USBプラグ&プレイ90°広角 1080P@60fps 四つノイズキャンセリングマイク内蔵 半径3メートル集音範囲 タッチパネルでコントロール リモートワーク/ビデオ会議/オンライン授業用 コンパクトSkype/Zoomカメラ",
    price: 14980,
    rating: 4.4,
    reviews: 29,
    image: "https://m.media-amazon.com/images/I/61V6TofrsNL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D2L7GR5L",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #59" }]}],
  },
  {
    id: "cam-bs-061",
    category: "camera",
    name: "Insta360 Link 2 Pro",
    brand: "Insta360",
    tagline: "Webカメラ 4K ウェブカメラ PTZ 1/1.3インチセンサー、低照度、AIトラッキング、HDR、マイク付き 指向性ノイズキャンセリングマイク、ストリームデッキ、会議用 Zoom Teams Twitchに対応、配信・オンラインミーティングに最適",
    price: 38500,
    rating: 3.9,
    reviews: 321,
    image: "https://m.media-amazon.com/images/I/61AlkaJb+gL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX5QMB6K",
    highlights: [
      { label: "解像度", value: "4K / 30fps" },
      { label: "画角", value: "83.9°/71.4°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K / 30fps" },
          { label: "フレームレート", value: "60fps (1080p)" },
          { label: "画角", value: "83.9°/71.4°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #61" }]}],
  },
  {
    id: "cam-bs-062",
    category: "camera",
    name: "Link 2 Pro",
    brand: "Insta360",
    tagline: "4K / 30fps・オートフォーカス・内蔵マイク",
    price: 38500,
    rating: 4.6,
    reviews: 367,
    image: "https://m.media-amazon.com/images/I/61BmGGgAcuL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G3T1QKWL",
    highlights: [
      { label: "解像度", value: "4K / 30fps" },
      { label: "画角", value: "83.9°/71.4°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K / 30fps" },
          { label: "フレームレート", value: "60fps (1080p)" },
          { label: "画角", value: "83.9°/71.4°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #62" }]}],
  },
    {
    id: "cam-bs-064",
    category: "camera",
    name: "ロジクールBrio 500 C940GR",
    brand: "Logicool",
    tagline: "ロジクール Webカメラ フルHD 1080P オートフォーカス 自動光補正 ノイズリダクション マイク 広視野角 90度 プライバシーシャッター Brio 500 C940GR グラファイト ウェブカメラ ウェブカム PC Mac ノートパソコン Zoom Skype 国内正規品 1年間メーカー保証",
    price: 17800,
    rating: 4,
    reviews: 71,
    image: "https://m.media-amazon.com/images/I/51wkJ42I74L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BFW55CRZ",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "65°/78°/90°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "65°/78°/90°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #64" }]}],
  },
  {
    id: "cam-bs-065",
    category: "camera",
    name: "400-CAM086",
    brand: "サンワダイレクト",
    tagline: "サンワダイレクト WEBカメラ マイクなし 画角60度 フルHD 1080P 200万画素 三脚対応 Zoom/Teams",
    price: 4980,
    rating: 3.9,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/51+Fmwygw2L._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08P81K67K",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "60°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "60°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #65" }]}],
  },
  {
    id: "cam-bs-066",
    category: "camera",
    name: "400-CAM086",
    brand: "サンワダイレクト",
    tagline: "1080p / 30fps・60°画角",
    price: 4980,
    rating: 3.9,
    reviews: 105,
    image: "https://m.media-amazon.com/images/I/61Gk2NtxrLL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08TC3NR9L",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "60°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "60°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #66" }]}],
  },
  {
    id: "cam-bs-067",
    category: "camera",
    name: "400-CAM103",
    brand: "サンワダイレクト",
    tagline: "サンワダイレクト WEBカメラ マイクなし 狭角35° フルHD 200万画素 三脚対応 ケーブル長1.8m 400-CAM103",
    price: 4980,
    rating: 4.3,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/51UVj0-EKBL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H7L72NNP",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "35°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "8 × 7 × 6 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "35°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #67" }]}],
  },
  {
    id: "cam-bs-068",
    category: "camera",
    name: "400-CAM103",
    brand: "サンワダイレクト",
    tagline: "1080p / 30fps・35°画角",
    price: 4980,
    rating: 3.6,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/611CpbVdbhL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BMKZK9WR",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "35°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "35°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #68" }]}],
  },
  {
    id: "cam-bs-069",
    category: "camera",
    name: "UCAM-C820ABBK",
    brand: "ELECOM",
    tagline: "エレコム WEBカメラ UCAM-C820ABBK フルHD 1080p 30FPS 200万画素 オートフォーカス マイク内蔵 プライバシーシャッター付 1/4インチ三脚穴 ケーブル長1.5m ブラック",
    price: 4803,
    rating: 4.2,
    reviews: 986,
    image: "https://m.media-amazon.com/images/I/612x96ElTSL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08LN1LZX1",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "76°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "76°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #69" }]}],
  },
  {
    id: "cam-bs-070",
    category: "camera",
    name: "Tiny 3",
    brand: "OBSBOT",
    tagline: "webカメラ 4k 業界初の空間オーディオ ウェブカメラ1/1.28インチCMOS AI追尾 Youtube Twitch 配信 生放送 Zoom Teams オンラインミーティング対応",
    price: 58000,
    rating: 4.6,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/61C0h2hE5AL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJ53RC61",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #70" }]}],
  },
  {
    id: "cam-bs-071",
    category: "camera",
    name: "Tiny 3",
    brand: "OBSBOT",
    tagline: "4K / 30fps・オートフォーカス・空間オーディオマイク",
    price: 58000,
    rating: 4.4,
    reviews: 227,
    image: "https://m.media-amazon.com/images/I/51SyUcsLVCL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G636CXQM",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "90°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "90°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #71" }]}],
  },
  {
    id: "cam-bs-072",
    category: "camera",
    name: "ELP 夜間視力 USBカメラ ELP-USBFHD05MT-KL36IR-JP",
    brand: "ELP",
    tagline: "ELP 夜間視力 USBカメラ 高速 100FPS ウェブカメラ 200万画素 1080P Webかめら 広角 監視 PCカメラ CMOS OV2710 防犯Webカメラ 自動暗視機能防塵屋内 Lightburn Camera Raspberry Pi用 バス停駐車場小型産業用 UVC USB2.0 Webcamera コンピューター用",
    price: 6556,
    rating: 3.6,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/61fAKk+1acL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: ["自動暗視機能"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08FD7Z999",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "75°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "100fps" },
          { label: "画角", value: "75°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #72" }]}],
  },
  {
    id: "cam-bs-073",
    category: "camera",
    name: "CMS-V43BK",
    brand: "サンワサプライ",
    tagline: "サンワサプライ 会議用ワイドレンズWEBカメラ USB接続 150°超広角 マイク内蔵 Skype対応 ブラック",
    price: 6036,
    rating: 4.2,
    reviews: 326,
    image: "https://m.media-amazon.com/images/I/71nmiJqOFFL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07JN3NYC5",
    highlights: [
      { label: "解像度", value: "720p" },
      { label: "画角", value: "150°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "720p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "150°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #73" }]}],
  },
  {
    id: "cam-bs-074",
    category: "camera",
    name: "FoMaKo 4K NDI6/NDI/HX3 PTZカメラ K20UH",
    brand: "FoMaKo",
    tagline: "PTZカメラ AI自動追尾 20倍光学ズーム USB3.0 LAN webカメラptz|K20UH4KPTZ カメラ 4Kカメラ poe 自動追尾",
    price: 73000,
    rating: 4.4,
    reviews: 136,
    image: "https://m.media-amazon.com/images/I/61rVRWP4QpL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: ["AI自動追跡"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DK1BXJWY",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "60°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "60°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #74" }]}],
  },
  {
    id: "cam-bs-075",
    category: "camera",
    name: "ELP ガンカメラ 2.8-12mm可変焦点レンズ",
    brand: "ELP",
    tagline: "USBウェブカメラ 100fps 光学4倍ズーム Webカメラ 200万画素 高速Webかめら 4倍ズームWeb会議用カメラ CMOS OV2710 1080P 30fpsズームカメラ",
    price: 6880,
    rating: 4,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71TgVkKsTrL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B42JGLLC",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "可変" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "100fps" },
          { label: "画角", value: "可変" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "—" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #75" }]}],
  },
  {
    id: "cam-bs-076",
    category: "camera",
    name: "NexiGo N660P",
    brand: "NexiGo",
    tagline: "webカメラ 60fps マイク内蔵 N660P 1080P ウェブカメラ ソフトウェア制御 カバー付属 オートフォーカス HD usbカメラ コンピューター用ウェブカメラ OBS/ゲー",
    price: 4999,
    rating: 4.4,
    reviews: 5642,
    image: "https://m.media-amazon.com/images/I/61H5j2WNHdL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08L7ZLNHB",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "80°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "80°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #76" }]}],
  },
  {
    id: "cam-bs-077",
    category: "camera",
    name: "Innex Cube 会議用360度広角Webカメラ",
    brand: "Innex",
    tagline: "会議用360度広角Webカメラ ギャラリーモードなど多彩なAIモード 電源&ソフトウェア不要の完全プラグ＆プレイリモコンでの手動ePTZ操作にも対応 無指向性マイク内蔵 Zoom Teams WebEx GoogleMeet",
    price: 76780,
    rating: 3.9,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/71+H86cjIFL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B6HR1WN2",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "360°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "360°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #77" }]}],
  },
  {
    id: "cam-bs-078",
    category: "camera",
    name: "TOALLIN 4K Ultra HD ウェブカメラ",
    brand: "TOALLIN",
    tagline: "TOALLIN 4K Ultra HD ウェブカメラ Windows Hello対応 顔認証webカメラ オートフォーカス",
    price: 11999,
    rating: 4,
    reviews: 41,
    image: "https://m.media-amazon.com/images/I/51Hd1b34IwL._AC_SL1500_.jpg",
    connection: "USB-C",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GFVNNWMJ",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "83°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "83°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-C" },
          { label: "Amazon売れ筋", value: "Webカメラ #78" }]}],
  },
  {
    id: "cam-bs-079",
    category: "camera",
    name: "Angetube 4K Webカメラ リングライト一体型",
    brand: "Angetube",
    tagline: "Angetube 4K Webカメラ リングライト一体型800万画素ウェブカメラ超広視野角 1080P@60FPS ストリーミング PC用PDAF 自動光補正オートフォーカス AI ノイズキャンセリング 8 倍ズーム USB-A/Cプライバシー保護機能付き",
    price: 5775,
    rating: 4.4,
    reviews: 453,
    image: "https://m.media-amazon.com/images/I/61ptiasAjUL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DDCJBZWQ",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "78°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "60fps" },
          { label: "画角", value: "78°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "Webカメラ #79" }]}],
  },
  {
    id: "cam-bs-080",
    category: "camera",
    name: "400-CAM102",
    brand: "サンワダイレクト",
    tagline: "サンワダイレクト WEBカメラ 無線 ワイヤレス 200万画素 1080p マイク付き 広角 Type-C/USB-A対応",
    price: 19800,
    rating: 3.7,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71Pniiwo3lL._AC_SL1500_.jpg",
    connection: "2.4GHz",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BP955QKZ",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "102°" },
      { label: "フォーカス", value: "—" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "6.2 × 7.7 × 7.1 cm" },
          { label: "重量", value: "—" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "102°" },
          { label: "フォーカス", value: "—" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "2.4GHz" },
          { label: "Amazon売れ筋", value: "Webカメラ #80" }]}],
  },
  {
    id: "cam-cur-059",
    category: "camera",
    name: "BRIO C1000eR",
    brand: "Logicool",
    tagline: "ogitech Logicool(ロジクール) BRIO (ブリオ) RightLight 3 採用 4K Ultra HDウェブカメラ",
    price: 22800,
    rating: 4.4,
    reviews: 173,
    image: "https://m.media-amazon.com/images/I/517+SfilMqL._AC_SL1500_.jpg",
    connection: "USB-A (USB 3.0)",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B075YC4NHB",
    highlights: [
      { label: "解像度", value: "4K" },
      { label: "画角", value: "65°/78°/90°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "102 × 27 × 36 mm" },
          { label: "重量", value: "63 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "4K" },
          { label: "フレームレート", value: "90fps" },
          { label: "画角", value: "65°/78°/90°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A (USB 3.0)" },
          { label: "Amazon売れ筋", value: "—" }]}],
  },
  {
    id: "cam-cur-060",
    category: "camera",
    name: "C920s Pro HD",
    brand: "Logicool",
    tagline: "920x Pro HD Webcam ロジテック プロ HD ウェブカム Webカメラ フルHD1080p [並行輸入品]30fpsビデオ、クリアなオーディオ",
    price: 13400,
    rating: 4.3,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71YN85pLGcL._AC_SL1500_.jpg",
    connection: "USB-A",
    cameraSpreadsheetITags: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B085TFF7M1",
    highlights: [
      { label: "解像度", value: "1080p" },
      { label: "画角", value: "78°" },
      { label: "フォーカス", value: "オートフォーカス" },
      { label: "マイク", value: "内蔵マイク" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "寸法", value: "94 × 43 × 71 mm" },
          { label: "重量", value: "162 g" }]},
      { title: "映像", rows: [
          { label: "解像度", value: "1080p" },
          { label: "フレームレート", value: "30fps" },
          { label: "画角", value: "78°" },
          { label: "フォーカス", value: "オートフォーカス" },
          { label: "マイク", value: "内蔵マイク" }]},
      { title: "接続", rows: [
          { label: "接続端子", value: "USB-A" },
          { label: "Amazon売れ筋", value: "—" }]}],
  }]
