import type { Gadget } from "./gadgets"

/** Amazon.co.jp PCゲーミングチェア新着（5341900051）。本体・座椅子のみ。 */
export const gamingChairNewReleases: Gadget[] = [
  {
    id: "chair-nr-001",
    category: "gaming-chair",
    gamingChairFilterTags: ["mat-pu"],
    dimensions: "120 × 49 × 62 cm",
    hasOttoman: true,
    maxRecliningAngle: "140°",
    name: "オットマン付き PUレザー 腰枕付き 140°リクライニング 座高60-70CM",
    brand: "—",
    tagline: "PUレザー・リクライニング・オットマン付き",
    price: 9980,
    rating: 3.4,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/51tgLOX3-KL._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H94SDWK5",
    highlights: [
      { label: "素材", value: "PUレザー" },
      { label: "最大リクライニング角度", value: "最大140°" },
      { label: "フレームの種類", value: "—" },
      { label: "形状", value: "バケットシート型（ハイバック）" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "120 × 49 × 62 cm" },
        ]},
            { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大140°" },
          { label: "フレームの種類", value: "—" },
        ]},
      { title: "調節機能", rows: [
          { label: "座面の高さ", value: "対応" },
          { label: "リクライニング", value: "対応" },
          { label: "ヘッドレスト", value: "対応" },
          { label: "アームレスト", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "PUレザー" },
          { label: "形状", value: "バケットシート型（ハイバック）" },
          { label: "オットマン", value: "あり" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#1" },
        ]},
    ],
  },{
    id: "chair-nr-003",
    category: "gaming-chair",
    frameMaterial: "合金鋼",
    dimensions: "50 × 60 × 113 cm",
    seatDepth: "50 cm",
    seatWidth: "52 cm",
    backrestWidth: "52 cm",
    hasOttoman: true,
    maxRecliningAngle: "135°",
    name: "ファブリック オフィスチェア デスクチェア 通気性 人間工学 145度リクライニング オットマン",
    brand: "Humergo",
    tagline: "ファブリック・リクライニング・オットマン付き",
    price: 8783,
    rating: 3.6,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/51rmfuvIj9L._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWPPNHH5",
    highlights: [
      { label: "素材", value: "ファブリック" },
      { label: "最大リクライニング角度", value: "最大135°" },
      { label: "フレームの種類", value: "合金鋼フレーム" },
      { label: "形状", value: "オフィスチェアカスタム型" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "50 × 60 × 113 cm" },
          { label: "座面の奥行", value: "50 cm" },
          { label: "座面の幅", value: "52 cm" },
          { label: "背もたれ幅", value: "52 cm" },
        ]},
            { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大135°" },
          { label: "フレームの種類", value: "合金鋼フレーム" },
        ]},
      { title: "調節機能", rows: [
          { label: "座面の高さ", value: "対応" },
          { label: "リクライニング", value: "対応" },
          { label: "ヘッドレスト", value: "対応" },
          { label: "ランバーサポート", value: "対応" },
          { label: "アームレスト", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "ファブリック" },
          { label: "形状", value: "オフィスチェアカスタム型" },
          { label: "オットマン", value: "あり" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#3" },
        ]},
    ],
  },
  {
    id: "chair-nr-004",
    category: "gaming-chair",
    gamingChairFilterTags: ["mat-fabric"],
    frameMaterial: "合金鋼",
    dimensions: "72 × 72 × 122 cm",
    hasOttoman: true,
    maxRecliningAngle: "145°",
    name: "ファブリック オフィスチェア デスクチェア 通気性 人間工学 145度リクライニング オットマン",
    brand: "Humergo",
    tagline: "ファブリック・リクライニング・オットマン付き",
    price: 21800,
    rating: 5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61BuQzbxOPL._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08FGP283T",
    highlights: [
      { label: "素材", value: "ファブリック" },
      { label: "最大リクライニング角度", value: "最大145°" },
      { label: "フレームの種類", value: "合金鋼フレーム" },
      { label: "形状", value: "オフィスチェアカスタム型" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "72 × 72 × 122 cm" },
        ]},
            { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大145°" },
          { label: "フレームの種類", value: "合金鋼フレーム" },
        ]},
      { title: "調節機能", rows: [
          { label: "座面の高さ", value: "対応" },
          { label: "リクライニング", value: "対応" },
          { label: "ヘッドレスト", value: "対応" },
          { label: "ランバーサポート", value: "対応" },
          { label: "アームレスト", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "ファブリック" },
          { label: "形状", value: "オフィスチェアカスタム型" },
          { label: "オットマン", value: "あり" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#4" },
        ]},
    ],
  },
  {
    id: "chair-nr-005",
    category: "gaming-chair",
    frameMaterial: "合金鋼",
    dimensions: "50 × 50 × 130 cm",
    hasOttoman: true,
    maxRecliningAngle: "145°",
    name: "通気性 疲れない 145°リクライニング オットマン付き デスクチェア オフィスチェア ゲームチ",
    brand: "GTPLAYER",
    tagline: "PUレザー・リクライニング・オットマン付き",
    price: 15485,
    rating: 4.2,
    reviews: 3685,
    image: "https://m.media-amazon.com/images/I/71+TfT3pX8L._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H9YVLHX5",
    highlights: [
      { label: "素材", value: "PUレザー" },
      { label: "最大リクライニング角度", value: "最大145°" },
      { label: "フレームの種類", value: "合金鋼フレーム" },
      { label: "形状", value: "バケットシート型（ハイバック）" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "50 × 50 × 130 cm" },
        ]},
            { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大145°" },
          { label: "フレームの種類", value: "合金鋼フレーム" },
        ]},
      { title: "調節機能", rows: [
          { label: "リクライニング", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "PUレザー" },
          { label: "形状", value: "バケットシート型（ハイバック）" },
          { label: "オットマン", value: "あり" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#5" },
        ]},
    ],
  },
  {
    id: "chair-nr-006",
    category: "gaming-chair",
    frameMaterial: "合金鋼",
    dimensions: "60 × 60 × 90 cm",
    seatDepth: "50 cm",
    seatWidth: "50 cm",
    backrestWidth: "71 cm",
    hasOttoman: false,
    maxRecliningAngle: "135°",
    name: "135度リクライニング 360度回転 ヘッドレスト ランバーサポート ゲーム用 おしゃれ フロア",
    brand: "PUPOFA",
    tagline: "リクライニング",
    price: 88335,
    rating: 3,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/619NeRSc0rL._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2CWTDHT",
    highlights: [
      { label: "素材", value: "—" },
      { label: "最大リクライニング角度", value: "最大135°" },
      { label: "フレームの種類", value: "合金鋼フレーム" },
      { label: "形状", value: "座椅子タイプ（ローデスク用）" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "60 × 60 × 90 cm" },
          { label: "座面の奥行", value: "50 cm" },
          { label: "座面の幅", value: "50 cm" },
          { label: "背もたれ幅", value: "71 cm" },
        ]},
                                                { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大135°" },
          { label: "フレームの種類", value: "合金鋼フレーム" },
        ]},
      { title: "調節機能", rows: [
          { label: "リクライニング", value: "対応" },
          { label: "ヘッドレスト", value: "対応" },
          { label: "ランバーサポート", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "—" },
          { label: "形状", value: "座椅子タイプ（ローデスク用）" },
          { label: "オットマン", value: "なし" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#6" },
        ]},
    ],
  },
  {
    id: "chair-nr-007",
    category: "gaming-chair",
    gamingChairFilterTags: ["mat-pu"],
    frameMaterial: "合金鋼",
    maxRecliningAngle: "155°",
    dimensions: "71.5 × 67 × 125 cm",
    hasOttoman: false,
    name: "Soma Chroma ワイヤレス Chroma RGB ゲーミングチェア HyperSpeed",
    brand: "Razer",
    tagline: "Razer Soma Chroma ワイヤレス Chroma RGB ゲーミングチェア HyperSpeed Wireless Blueto",
    price: 88335,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61uo3m6um2L._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H7RYM4M2",
    highlights: [
      { label: "素材", value: "—" },
      { label: "最大リクライニング角度", value: "最大155°" },
      { label: "フレームの種類", value: "合金鋼フレーム" },
      { label: "形状", value: "バケットシート型（ハイバック）" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "71.5 × 67 × 125 cm" },
        ]},
            { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大155°" },
          { label: "フレームの種類", value: "合金鋼フレーム" },
        ]},
      { title: "調節機能", rows: [
          { label: "ランバーサポート", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "—" },
          { label: "形状", value: "バケットシート型（ハイバック）" },
          { label: "オットマン", value: "なし" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#7" },
        ]},
    ],
  },{
    id: "chair-nr-009",
    category: "gaming-chair",
    frameMaterial: "合金鋼",
    maxRecliningAngle: "135°",
    dimensions: "50 × 40 × 75 cm",
    hasOttoman: true,
    name: "135°フルリクライニング オットマン付き 高級PUレザー 調節可能 ランバーサポート オフィス",
    brand: "GTBoy",
    tagline: "PUレザー・リクライニング・オットマン付き",
    price: 17630,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/610SfonKfML._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXXYDZXH",
    highlights: [
      { label: "素材", value: "PUレザー" },
      { label: "最大リクライニング角度", value: "最大135°" },
      { label: "フレームの種類", value: "合金鋼フレーム" },
      { label: "形状", value: "バケットシート型（ハイバック）" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "50 × 40 × 75 cm" },
        ]},
            { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大135°" },
          { label: "フレームの種類", value: "合金鋼フレーム" },
        ]},
      { title: "調節機能", rows: [
          { label: "リクライニング", value: "対応" },
          { label: "ランバーサポート", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "PUレザー" },
          { label: "形状", value: "バケットシート型（ハイバック）" },
          { label: "オットマン", value: "あり" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#9" },
        ]},
    ],
  },
  {
    id: "chair-nr-010",
    category: "gaming-chair",
    gamingChairFilterTags: ["mat-fabric"],
    frameMaterial: "合金鋼",
    maxRecliningAngle: "140°",
    dimensions: "48 × 50 × 130 cm",
    hasOttoman: true,
    name: "ファブリック ブラック オットマン付き 140° 無段階リクライニング 連動アームレスト 通気性",
    brand: "Nekkoflo",
    tagline: "ファブリック・リクライニング・オットマン付き",
    price: 17630,
    rating: 4.7,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61L0UzCiP1L._AC_SL1500_.jpg",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HC6MR7HL",
    highlights: [
      { label: "素材", value: "ファブリック" },
      { label: "最大リクライニング角度", value: "最大140°" },
      { label: "フレームの種類", value: "合金鋼フレーム" },
      { label: "形状", value: "バケットシート型（ハイバック）" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 寸法", rows: [
          { label: "本体寸法", value: "48 × 50 × 130 cm" },
        ]},
            { title: "リクライニング / フレーム", rows: [
          { label: "最大リクライニング角度", value: "最大140°" },
          { label: "フレームの種類", value: "合金鋼フレーム" },
        ]},
      { title: "調節機能", rows: [
          { label: "リクライニング", value: "対応" },
          { label: "アームレスト", value: "対応" },
        ]},
      { title: "構造 / 素材", rows: [
          { label: "素材", value: "ファブリック" },
          { label: "形状", value: "バケットシート型（ハイバック）" },
          { label: "オットマン", value: "あり" },
        ]},
      { title: "Amazon新着", rows: [
          { label: "新着ランク", value: "#10" },
        ]},
    ],
  },
]
