import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングキーボード売れ筋（2151972051 bestsellers pg1+2）。 */
export const keyboardGamingBestsellers: Gadget[] = [{
    id: "k-gbs-003",
    category: "keyboard",
    name: "Logicool G PRO ゲーミングキーボード G-PKB-002LNd テンキーレス リニア 赤軸 日本語配列",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G PRO ゲーミングキーボード G-PKB-002LNd テンキーレス リニア 赤軸 日本語配列 | 静かなタイピング GXスイッチ 有線 メカニカルキーボード LIGHTSYNC RGB 充電 着脱式ケーブル ブラック…",
    price: 13900,
    rating: 4.4,
    reviews: 1784,
    image: "https://m.media-amazon.com/images/I/61eSkWURkIL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BC135WFD",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt-double"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（赤軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（赤軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "980 グラム" }]}],
  },
    {
    id: "k-gbs-006",
    category: "keyboard",
    name: "Logicool G ロジクール G ゲーミングキーボード 有線 G213r パームレスト 日本語配列 独自のMech-domeスイッチ …",
    brand: "Logicool G",
    tagline: "Logicool G ロジクール G ゲーミングキーボード 有線 G213r パームレスト 日本語配列 独自のMech-domeスイッチ キーボード 静音 LIGHTSYNC RGB 国内正規品 【 ファイナルファンタジーXIV 推奨周辺機器 】",
    price: 6535,
    rating: 4.3,
    reviews: 3120,
    image: "https://m.media-amazon.com/images/I/51Rki8IxjSL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09248N9XK",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1005 グラム" }]}],
  },
  {
    id: "k-gbs-017",
    category: "keyboard",
    name: "Logicool G PRO X TKL RAPID ゲーミングキーボード",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G PRO X TKL RAPID ゲーミングキーボード | ラピッドトリガー アクチュエーションポイント 調整可能 押下圧 35g 日本語配列 有線 テンキーレス 磁気式アナログスイッチ",
    price: 25980,
    rating: 4.4,
    reviews: 277,
    image: "https://m.media-amazon.com/images/I/61+9VKaKYIL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9VVL9DY",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gbs-023",
    category: "keyboard",
    name: "Logicool G316 X 98 ゲーミングキーボード（G316X-98-LNWHd）",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G 8000Hz ホットスワップ G316 X 98 ゲーミングキーボード リニア 静音 ガスケットマウント 日本語配列 G316X-98-LNWHd メカニカル LIGHTSYNC RGB 有線",
    price: 17800,
    rating: 4.5,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71ePRAs-ztL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJ8Q1P4X",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "98％" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "98％" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "ホットスワップ・LIGHTSYNC RGB" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gbs-024",
    category: "keyboard",
    name: "Razer BlackWidow V3 Mini HyperSpeed Phantom Pudding Edition",
    brand: "Razer",
    tagline: "Razer BlackWidow V3 Mini HyperSpeed Phantom Pudding Edition Yellow Switch ゲーミングキーボード ワイヤレス 2.4GHz Bluetooth 65% メカニカル イエロー軸 Chroma RGB",
    price: 12882,
    rating: 3.8,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/71vG7vtgjeL._AC_SL1500_.jpg",
    connection: "Bluetooth / 2.4GHz / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09FY5P1LS",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-pbt-double","kb-power-rechargeable"],
        highlights: [
      { label: "レイアウト", value: "65%" },
      { label: "内部構造", value: "メカニカル（黄軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65%" },
          { label: "内部構造", value: "メカニカル（黄軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 2.4GHz / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gbs-007",
    category: "keyboard",
    name: "iClever ゲーミングキーボード テンキーレス 赤軸 メカニカル キーボード 日本語配列 マクロ対応 G06 ブラック",
    brand: "iClever",
    tagline: "iClever ゲーミングキーボード テンキーレス 赤軸 メカニカル キーボード 日本語配列 マクロ対応 G06 ブラック | 有線 91キー 80%サイズ カスタマイズ 24種類 バックライト ゲーム/オフィス用 パソコンキーボード Windows対応",
    price: 3990,
    rating: 4.2,
    reviews: 271,
    image: "https://m.media-amazon.com/images/I/71vL64Q8hXL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D86XCN4G",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gbs-008",
    category: "keyboard",
    name: "雨音のような打鍵音 メカニカルキーボード 3WAY接続 OS互換性 ホットスワップとVIAの対応 カスタマイズ性 ガスケットデザイン アル…",
    brand: "WOBKEY",
    tagline: "【WOBKEY Rainy 75キーボード】雨音のような打鍵音 メカニカルキーボード 3WAY接続 OS互換性 ホットスワップとVIAの対応 カスタマイズ性 ガスケットデザイン アルミニウム素材使用 RGBバックライト(Pro静音版(黑 日本語配列)）",
    price: 27720,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61wYHSXVG-L._AC_SL1500_.jpg",
    connection: "Bluetooth / 2.4GHz / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GGB26MRZ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 2.4GHz / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "k-gbs-012",
    category: "keyboard",
    name: "e元素 Z-88 ゲーミングキーボード フルサイズ メカニカル 赤軸 USB有線 テンキー付き109キー RGBバックライト",
    brand: "e元素",
    tagline: "e元素 Z-88 ゲーミングキーボード フルサイズ メカニカル 赤軸 USB有線 テンキー付き109キー RGBバックライト",
    price: 6399,
    rating: 4.2,
    reviews: 407,
    image: "https://m.media-amazon.com/images/I/61uJQ44uHzL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BNXD2GMR",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（赤軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（赤軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gbs-013",
    category: "keyboard",
    name: "GravaStar Mercury K1 かわいいホワイト ゲーミングキーボード 無線 テンキーレス RGBライト ワイヤレス Bluet…",
    brand: "—",
    tagline: "GravaStar Mercury K1 かわいいホワイト ゲーミングキーボード 無線 テンキーレス RGBライト ワイヤレス Bluetooth接続",
    price: 22980,
    rating: 4.5,
    reviews: 1719,
    image: "https://m.media-amazon.com/images/I/61NuYBHj+hL._AC_SL1500_.jpg",
    connection: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTY7H2S3",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列/US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "JIS日本語配列/US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列/US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "k-gbs-015",
    category: "keyboard",
    name: "YUNZII QL75 タイプライターキーボード ワイヤレス レトロメカニカルキーボード ホットスワップ対応 パンクスタイルの丸型キーキャ…",
    brand: "YUNZII",
    tagline: "YUNZII QL75 タイプライターキーボード ワイヤレス レトロメカニカルキーボード ホットスワップ対応 パンクスタイルの丸型キーキャップ RGBバックライト QMK/VIAプログラマブル 2.4GHz/Type-C/BT5.0マルチデバイス接続 技適認証取得 (ウッド…",
    price: 14820,
    rating: 4.3,
    reviews: 280,
    image: "https://m.media-amazon.com/images/I/81p7yy-k2HL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FFN19KR9",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "有線給電/充電式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1 グラム" }]}],
  },
  {
    id: "k-gbs-016",
    category: "keyboard",
    name: "Keychron C3 Pro カスタムゲーミングキーボード、コンパクトテンキーレスレイアウト/JISレイアウト/RGBバックライト/有線…",
    brand: "Keychron",
    tagline: "【Amazon.co.jp限定】Keychron C3 Pro カスタムゲーミングキーボード、コンパクトテンキーレスレイアウト/JISレイアウト/RGBバックライト/有線接続メカニカルキーボード/ホットスワップ対応/ガスケットマウント/ダブルショットPBTキーキャップ/Ma…",
    price: 8910,
    rating: 4.3,
    reviews: 179,
    image: "https://m.media-amazon.com/images/I/61HJoqkM3DL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DRK4Z8G6",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt-double"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "コード式" }]}],
  },
    {
    id: "k-gbs-019",
    category: "keyboard",
    name: "EPOMAKER TH87 JIS 日本語配列 TKL ワイヤレスゲーミングキーボード 2.4GHz/BT5.0/有線 テンキーレス",
    brand: "EPOMAKER",
    tagline: "EPOMAKER TH87 JIS 日本語配列 TKL ワイヤレスゲーミングキーボード 2.4GHz/BT5.0/有線 テンキーレス | ホットスワップ対応 10000mAh 無線 メカニカルキーボード 91キーリニアスイッチ RGBバックライト ガスケット構造 PBTキー…",
    price: 12500,
    rating: 4.5,
    reviews: 89,
    image: "https://m.media-amazon.com/images/I/61jLA9T4zzL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G4LTQRRH",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-gbs-020",
    category: "keyboard",
    name: "Logicool G ゲーミングキーボード G413SE 有線 タクタイル 確かな打鍵感 日本語配列 高耐久性 PTB キーキャップ ゲー…",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングキーボード G413SE 有線 タクタイル 確かな打鍵感 日本語配列 高耐久性 PTB キーキャップ ゲーミング キーボード メカニカルキーボード G413 PC window mac Chrome 国内正規品 【 ファイナルファンタジー X…",
    price: 9327,
    rating: 4.2,
    reviews: 154,
    image: "https://m.media-amazon.com/images/I/61AFzNLK3VL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B5ZF1X9G",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "780 グラム" }]}],
  },
  {
    id: "k-gbs-021",
    category: "keyboard",
    name: "Logicool G ゲーミングキーボード G515 LIGHTSPEED TKL 薄型 ワイヤレス テンキーレス キーボード G515-…",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングキーボード G515 LIGHTSPEED TKL 薄型 ワイヤレス テンキーレス キーボード G515-WL-LNWH リニア 赤軸 静かなタイピング 日本語配列 LIGHTSPEED Bluetooth 接続対応 LIGHTSYNC RG…",
    price: 18664,
    rating: 4.5,
    reviews: 203,
    image: "https://m.media-amazon.com/images/I/61ydyb79ovL._AC_SL1500_.jpg",
    connection: "2.4GHz (LIGHTSPEED) / Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D7ZMHHFF",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-low-profile"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（赤軸）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（赤軸）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (LIGHTSPEED) / Bluetooth/有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "880 グラム" }]}],
  },
  {
    id: "k-gbs-022",
    category: "keyboard",
    name: "YUNZII X75 PRO 82キーワイヤレス ホットスワップ対応 英語配列 メカニカルゲーミングキーボード 透明キーキャップ BT5.…",
    brand: "YUNZII",
    tagline: "YUNZII X75 PRO 82キーワイヤレス ホットスワップ対応 英語配列 メカニカルゲーミングキーボード 透明キーキャップ BT5.0/2.4G/USB-C ガスケット装着キーボード Windows/Mac用 技適認証取得(Kailh ジェリーフィッシュ軸、無線ホワイト）",
    price: 10959,
    rating: 4.4,
    reviews: 355,
    image: "https://m.media-amazon.com/images/I/71oARXgVw7L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BLTP2ZB9",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "有線給電/充電式" },
          { label: "主な機能", value: "バッテリー式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1 キログラム" }]}],
  },{
    id: "k-gbs-026",
    category: "keyboard",
    name: "SteelSeries ラピッドトリガー 搭載 ゲーミングキーボード ミニサイズ Apex Pro Mini JP 有線 日本語配列 Om…",
    brand: "—",
    tagline: "SteelSeries ラピッドトリガー 搭載 ゲーミングキーボード ミニサイズ Apex Pro Mini JP 有線 日本語配列 OmniPointスイッチ 2ーinー1アクションキー 搭載 64825 ブラック",
    price: 27027,
    rating: 4.2,
    reviews: 571,
    image: "https://m.media-amazon.com/images/I/71wP1cX5R4L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B5X1PSVP",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "950 グラム" }]}],
  },
  {
    id: "k-gbs-028",
    category: "keyboard",
    name: "0.005mmラピッドトリガー搭載 GravaStar Mercury V60 ゲーミングキーボード 60%レイアウト カスタムUFO磁気…",
    brand: "—",
    tagline: "0.005mmラピッドトリガー搭載 GravaStar Mercury V60 ゲーミングキーボード 60%レイアウト カスタムUFO磁気スイッチ | ポーリングレート8000Hz対応 0.125ms超低遅延 磁気式スイッチ テンキーレス 有線 着脱式ケーブル 透明キーキャ…",
    price: 19980,
    rating: 4.7,
    reviews: 222,
    image: "https://m.media-amazon.com/images/I/71w4+f4DYUL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GDGVPS2G",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "ポリカーボネート（透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "ポリカーボネート（透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gbs-029",
    category: "keyboard",
    name: "YUNZII X71 メカニカルゲーミングキーボード 透明キーキャップ 71キー 68%配列 ワイヤレス ホットスワップ対応 BT5.0/…",
    brand: "YUNZII",
    tagline: "YUNZII X71 メカニカルゲーミングキーボード 透明キーキャップ 71キー 68%配列 ワイヤレス ホットスワップ対応 BT5.0/2.4G/USB-C ガスケット搭載 RGB 無線 Windows/Mac用 技適認証取得（クリスタルアイス軸、ホワイト）",
    price: 13199,
    rating: 4.4,
    reviews: 816,
    image: "https://m.media-amazon.com/images/I/71ziElP851L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CN3GH63C",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "68％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "68％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "有線給電/充電式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1 キログラム" }]}],
  },
  {
    id: "k-gbs-030",
    category: "keyboard",
    name: "Logicool G ゲーミングキーボード G512r-TC 有線 タクタイル 茶軸 確かな打鍵感 GXスイッチ 日本語配列 LIGHTS…",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングキーボード G512r-TC 有線 タクタイル 茶軸 確かな打鍵感 GXスイッチ 日本語配列 LIGHTSYNC RGB USB パススルー ゲーミング キーボード メカニカルキーボード G512 PC window mac Chrome ブ…",
    price: 11955,
    rating: 4.4,
    reviews: 816,
    image: "https://m.media-amazon.com/images/I/51y8-ho0rQL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0842XB51D",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1080 グラム" }]}],
  },
    {
    id: "k-gbs-074",
    category: "keyboard",
    name: "[MH-Device] MH-Zeta ジョイスティック・ホイール付き47キー片手ゲーミングキーボード 片手 キーボード 左手キーボード(…",
    brand: "—",
    tagline: "[MH-Device] MH-Zeta ジョイスティック・ホイール付き47キー片手ゲーミングキーボード 片手 キーボード 左手キーボード(左手用-黒)",
    price: 18800,
    rating: 4.2,
    reviews: 87,
    image: "https://m.media-amazon.com/images/I/61JACOa6mxL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G2BNZVTP",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "片手キーボード" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "—" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "片手キーボード" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "280 グラム" }]}],
  },
    {
    id: "k-gbs-081",
    category: "keyboard",
    name: "Razer Huntsman V3 HE マグネット式 TKL 8KHz ゲーミングキーボード US配列",
    brand: "Razer",
    tagline: "Razer Huntsman V3 HE Magnetic Tenkeyless 8KHz ゲーミングキーボード US配列 ラピッドトリガー | Synapse Web対応 ホールエフェクト磁気スイッチ 8000Hz HyperPolling 調整可能アクチュエーション",
    price: 20980,
    rating: 4.9,
    reviews: 16,
    image: "https://m.media-amazon.com/images/I/71w6uhQOMCL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GX2219JY",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "8000Hz HyperPolling" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gbs-082",
    category: "keyboard",
    name: "Razer BlackWidow V4 X Minecraft Edition",
    brand: "Razer",
    tagline: "Minecraft ゲーミングキーボード Razer BlackWidow V4 X Minecraft Edition カスタマイズ可能な6個の専用マクロキー グリーンメカニカルスイッチ 有線 Chroma RGB 英語配列",
    price: 15800,
    rating: 4.3,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/71YyJgmuqNL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F9NPZRBZ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（Green Switch ）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（Green Switch ）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "マクロキー6個・Chroma RGB" }]}],
  },
  {
    id: "k-gbs-083",
    category: "keyboard",
    name: "Razer Huntsman V2 Clicky Optical Switch ゲーミングキーボード US配列",
    brand: "Razer",
    tagline: "Razer Huntsman V2 Clicky Optical Switch ゲーミングキーボード 英語 US配列 オプティカルスイッチ クリッキー触感 ダブルショット PBT キーキャップ リストレスト Chroma RGB",
    price: 29676,
    rating: 4.4,
    reviews: 17,
    image: "https://m.media-amazon.com/images/I/81K36pthoVL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09FY71FK9",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["kb-keycap-pbt-double"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "オプティカル（クリッキー）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "オプティカル（クリッキー）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "PBT・リストレスト・Chroma RGB" }]}],
  },
  {
    id: "k-gbs-084",
    category: "keyboard",
    name: "Razer BlackWidow V4 X Fortnite Edition",
    brand: "Razer",
    tagline: "FORTNITE ゲーミングキーボード Razer BlackWidow V4 X Fortnite Edition カスタマイズ可能な6個の専用マクロキー イエローメカニカルスイッチ 有線 Chroma RGB 英語配列",
    price: 25051,
    rating: 4.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71R0qMymDCL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9KBTC3X",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（黄軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（黄軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "マクロキー6個・Chroma RGB" }]}],
  },
  {
    id: "k-gbs-085",
    category: "keyboard",
    name: "Razer DeathStalker V2 Pro Tenkeyless JP White Edition",
    brand: "Razer",
    tagline: "Razer DeathStalker V2 Pro Tenkeyless JP White Edition Linear Optical Switch 薄型オプティカルスイッチ ワイヤレス 2.4GHz Bluetooth 日本語配列 Chroma RGB",
    price: 31980,
    rating: 4.4,
    reviews: 41,
    image: "https://m.media-amazon.com/images/I/71E3GAjHDtL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CL4TM167",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-power-rechargeable"],
        highlights: [
      { label: "レイアウト", value: "80%" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80%" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー) / Bluetooth/有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gbs-086",
    category: "keyboard",
    name: "Razer Huntsman Mini 60% ゲーミングキーボード ホワイト",
    brand: "Razer",
    tagline: "Razer Huntsman Mini 60% ゲーミングキーボード リニアオプティカルスイッチ ラピッドトリガーモード PBTキーキャップ Snap Tap Chroma RGB ホワイト",
    price: 12638,
    rating: 4.6,
    reviews: 294,
    image: "https://m.media-amazon.com/images/I/61PwMWg2e1L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FFJDH7GM",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["kb-keycap-pbt-double","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "PBT・Snap Tap・Chroma RGB" }]}],
  },
  {
    id: "k-gbs-087",
    category: "keyboard",
    name: "Razer Huntsman V3 Pro Mini JP",
    brand: "Razer",
    tagline: "Razer ラピッドトリガー 搭載 Huntsman V3 Pro Mini JP アナログオプティカルスイッチ 調整可能なアクチュエーション 60%コンパクト 日本語配列",
    price: 25880,
    rating: 3.9,
    reviews: 145,
    image: "https://m.media-amazon.com/images/I/712r-1xpO9L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CLGVLBMV",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "調整可能AP・Chroma RGB" }]}],
  },
  {
    id: "k-gbs-088",
    category: "keyboard",
    name: "Razer DeathStalker V2 Pro Tenkeyless White Edition",
    brand: "Razer",
    tagline: "Razer DeathStalker V2 Pro Tenkeyless White Edition Linear Optical Switch 薄型オプティカルスイッチ ワイヤレス 2.4GHz Bluetooth Type-C Chroma 英語配列",
    price: 31000,
    rating: 4.3,
    reviews: 34,
    image: "https://m.media-amazon.com/images/I/710j82ZsagL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BY8PR3WC",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-power-rechargeable"],
        highlights: [
      { label: "レイアウト", value: "80%" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80%" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー) / Bluetooth/有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gbs-089",
    category: "keyboard",
    name: "Razer DeathStalker V2 Clicky Optical Switch ゲーミングキーボード US配列",
    brand: "Razer",
    tagline: "Razer DeathStalker V2 Clicky Optical Switch 有線ゲーミングキーボード 薄型オプティカル クリッキー触感 Type-C 多機能ローラー Chroma RGB 英語配列",
    price: 22800,
    rating: 2.7,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71VaOacbdhL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C894Q7YK",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "多機能ローラー・Chroma RGB" }]}],
  },
  {
    id: "k-gbs-090",
    category: "keyboard",
    name: "Razer BlackWidow V4 Pro メカニカル ホワイト",
    brand: "Razer",
    tagline: "Razer BlackWidow V4 Pro メカニカルゲーミングキーボード グリーンスイッチ ホワイト コマンドダイヤル 8つの専用マクロキー Chroma RGB 英語配列",
    price: 38971,
    rating: 4.4,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/81wahZUehFL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCTPBDP3",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（Green Switch ）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（Green Switch ）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "マクロキー8個・Chroma RGB" }]}],
  }]
