import type { Gadget } from "./gadgets"

/** Amazon.co.jp gpro 検索 page=3。キーボード本体のみ。 */
export const keyboardGproPage3: Gadget[] = [
  {
    id: "k-gp3-001",
    category: "keyboard",
    name: "K70 PRO TKL",
    brand: "CORSAIR",
    tagline: "Corsair CH-911921G-JP2 K70 Pro TKL MGX Gaming Keyboard Hyperdrive Magnetic Key Switch w/ Rapid Trigger, Detachable Palm Rest, Black/White…",
    price: 25641,
    rating: 4.4,
    reviews: 135,
    image: "https://m.media-amazon.com/images/I/713jkYNwbhL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D7VW5SMC",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（磁気式  / CORSAIR MGX / ラピッドトリガー）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（磁気式  / CORSAIR MGX / ラピッドトリガー）" },
          { label: "キーキャップ", value: "PBT" },
          { label: "バックライト", value: "RGB対応" },
          { label: "フォームファクター", value: "テンキーレス (TKL)" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "967.14 Grams" },
        ]},
    ],
  },
  {
    id: "k-gp3-002",
    category: "keyboard",
    name: "G PRO K/DA TKL",
    brand: "Logicool G",
    tagline: "Logicool G Logicool G PRO LoL K/DA Tenkeyless Gaming Keyboard, Wired, GX Tactile Mechanical Switch, Japanese Layout, LIGHTSYNC RGB, Leagu…",
    price: 13900,
    rating: 4.6,
    reviews: 639,
    image: "https://m.media-amazon.com/images/I/71rOYMLRMcL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B099Z2N8GD",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
    highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル (GX Tactile)" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル (GX Tactile)" },
          { label: "キーキャップ", value: "ABS" },
          { label: "バックライト", value: "LIGHTSYNC RGB" },
          { label: "フォームファクター", value: "テンキーレス (TKL)" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "980 Grams" },
        ]},
    ],
  },
  {
    id: "k-gp3-003",
    category: "keyboard",
    name: "G PRO X 60",
    brand: "Logicool G",
    tagline: "Logicool G PRO X 60 LIGHTSPEED Wireless Mini Gaming Keyboard G-PKB-60-001LNBK Linear Optical GX Switch Bluetooth Japanese Layout LIGHTSYN…",
    price: 16418,
    rating: 3.2,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/61e1mcAhtoL._AC_SL1500_.jpg",
    connection: "2.4GHz (LIGHTSPEED) / Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D1JZZHXM",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
    highlights: [
      { label: "レイアウト", value: "60％" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60％" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "PBT" },
          { label: "バックライト", value: "LIGHTSYNC RGB" },
          { label: "フォームファクター", value: "60% / コンパクト" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (LIGHTSPEED) / Bluetooth/有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（充電式（内蔵バッテリー））" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "610 Grams" },
        ]},
    ],
  },
  {
    id: "k-gp3-004",
    category: "keyboard",
    name: "AIM1 MATAKI",
    brand: "AIM1",
    tagline: "AIM1 Instant Rapid Trigger 0.01mm Gaming Keyboard 75% Size Polling Rate 8000Hz MATAKI (Black, English Layout)",
    price: 14980,
    rating: 4.6,
    reviews: 547,
    image: "https://m.media-amazon.com/images/I/61FQ2AlzYlL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GPT7BGZ3",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（磁気式  / ラピッドトリガー）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（磁気式  / ラピッドトリガー）" },
          { label: "キーキャップ", value: "PBT" },
          { label: "フォームファクター", value: "75%レイアウト" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.9 Kilograms" },
        ]},
    ],
  },
  {
    id: "k-gp3-005",
    category: "keyboard",
    name: "G PRO G-PKB-002LNd",
    brand: "Logicool G",
    tagline: "Logicool G PRO Gaming Keyboard, G-PKB-002LNd, Numeric Keyless, Linear Red Axis, Quiet Typing, GX Switch, Wired Gaming, Mechanical Keyboar…",
    price: 17179,
    rating: 4.7,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61-pnkkzM+L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F32KWT36",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
    highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（赤軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（赤軸）" },
          { label: "キーキャップ", value: "ABS" },
          { label: "バックライト", value: "LIGHTSYNC RGB" },
          { label: "フォームファクター", value: "テンキーレス (TKL)" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
  {
    id: "k-gp3-006",
    category: "keyboard",
    name: "G515 LIGHTSPEED TKL",
    brand: "Logicool G",
    tagline: "Logicool G Gaming Keyboard G515 LIGHTSPEED TKL Thin Wireless Tenkeyless Keyboard G515-WL-TCWH Tactile Brown Switches Sure Typing Experien…",
    price: 18664,
    rating: 4.2,
    reviews: 78,
    image: "https://m.media-amazon.com/images/I/61ydyb79ovL._AC_SL1500_.jpg",
    connection: "2.4GHz (LIGHTSPEED) / Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D7YT8D5K",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
    highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（ロープロファイル）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（ロープロファイル）" },
          { label: "キーキャップ", value: "PBT" },
          { label: "バックライト", value: "LIGHTSYNC RGB" },
          { label: "フォームファクター", value: "テンキーレス (TKL)" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (LIGHTSPEED) / Bluetooth/有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（充電式（内蔵バッテリー））" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "880 Grams" },
        ]},
    ],
  },
  {
    id: "k-gp3-007",
    category: "keyboard",
    name: "PCMK 2HE TKL",
    brand: "Pulsar",
    tagline: "Pulsar Gaming Gears PCMK 2HE TKL Gaming Keyboard JIS Japanese Layout 91 Keys Magnetic Switch 8K Polling Rate [Domestic Genuine Product]",
    price: 20980,
    rating: 4.4,
    reviews: 217,
    image: "https://m.media-amazon.com/images/I/61x0dxpeFDL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DNSJSF2W",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    highlights: [
      { label: "レイアウト", value: "80%" },
      { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80%" },
          { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
          { label: "キーキャップ", value: "PBT" },
          { label: "フォームファクター", value: "テンキーレス (TKL)" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "970 Grams" },
        ]},
    ],
  },
  {
    id: "k-gp3-008",
    category: "keyboard",
    name: "G512 X 75",
    brand: "Logicool G",
    tagline: "Logicool G 8000Hz Rapid Trigger Hot Swap G512 X 75 Gaming Keyboard Tactile Gasket Mount Japanese G512X-75-TCBK Action Point Adjustable Wi…",
    price: 28145,
    rating: 3.3,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61QlxmNEEaL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWLT37Y6",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
          { label: "キーキャップ", value: "PBT" },
          { label: "バックライト", value: "LIGHTSYNC RGB" },
          { label: "フォームファクター", value: "75%レイアウト" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" },
        ]},
    ],
  },
  {
    id: "k-gp3-009",
    category: "keyboard",
    name: "G512 X 98",
    brand: "Logicool G",
    tagline: "Logicool G 8000Hz Rapid Trigger Hot Swap G512 X 98 Gaming Keyboard Tactile Gasket Mount Japanese G512X-98-TCBK Action Point Adjustable Wi…",
    price: 30982,
    rating: 3.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/61LtoRGNr2L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWLRMPRM",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["kb-structure-gasket","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    highlights: [
      { label: "レイアウト", value: "98％" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "98％" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" },
          { label: "バックライト", value: "LIGHTSYNC RGB" },
          { label: "フォームファクター", value: "98%レイアウト" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" },
        ]},
    ],
  },
  {
    id: "k-gp3-010",
    category: "keyboard",
    name: "eS HE 70",
    brand: "Pulsar",
    tagline: "Pulsar Gaming Gears eS HE 70 Hall Effect Magnetic Gaming Keyboard ANSI English Layout 79 Keys Magnetic Switch 8K Polling Rate [Domestic G…",
    price: 27529,
    rating: 4.3,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/61sAeuVEsEL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FLH4QG56",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    highlights: [
      { label: "レイアウト", value: "70%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "70%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" },
          { label: "フォームファクター", value: "70%レイアウト" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "967 Grams" },
        ]},
    ],
  },
]
