import type { Gadget } from "./gadgets"

/** Amazon.co.jp パソコン用キーボード新着 2ページ目（2151977051 new-releases pg=2）。 */
export const keyboardNewReleasesPage2: Gadget[] = [
  {
    id: "k-nr2-054",
    category: "keyboard",
    name: "Redragon K710 無線 ゲーミングキーボード 青軸 テンキー付き Bluetooth/2.4G/有線 RGB US配列 技適認証取得",
    brand: "—",
    tagline: "Redragon K710 無線 ゲーミングキーボード 青軸 テンキー付き Bluetooth/2.4G/有線 RGB US配列 技適認証取得",
    price: 6600,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61A8xK3bipL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2DRWR7R",
    keyboardFilterTags: ["kb-keycap-abs"],
    keyboardUsage: "gaming",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth" },
          { label: "電源", value: "電池式" },
          { label: "主な機能", value: "バッテリー式" },
        ]},
    ],
  },{
    id: "k-nr2-057",
    category: "keyboard",
    name: "Acogedor 折りたたみ式 Bluetooth キーボード（タッチパッド付き）",
    brand: "Acogedor",
    tagline: "Acogedor 折りたたみ式 Bluetooth キーボード、大型タッチパッドとマルチタッチ ジェスチャーを備えた充電式ワイヤレス キーボード、 IOS ラップトップ タブレット スマートフォン用 (グレー)",
    price: 3621,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71SbsS+8TBL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXSVVQ4S",
    keyboardFilterTags: ["tenkeyless","kb-structure-scissor"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "コンパクト" },
      { label: "内部構造", value: "メカニカル（パンタグラフ）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "コンパクト" },
          { label: "内部構造", value: "メカニカル（パンタグラフ）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "k-nr2-058",
    category: "keyboard",
    name: "Valour Doer ou108 メカニカルキーボード 日本語配列 有線 フルサイズ ゲーミングキーボード 108キー 全キーロールオー…",
    brand: "—",
    tagline: "Valour Doer ou108 メカニカルキーボード 日本語配列 有線 フルサイズ ゲーミングキーボード 108キー 全キーロールオーバー LEDバックライト Win／Mac対応 テンキー付き USB-A ブラック 青軸",
    price: 5999,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71q3LdxbXEL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H242JBXR",
    keyboardFilterTags: ["kb-keycap-abs"],
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },{
    id: "k-nr2-060",
    category: "keyboard",
    name: "EPOMAKER x AULA F108 PRO V2 ワイヤレスメカニカルキーボード フルサイズ ピクセルディスプレイ搭載 潤滑済みスイッチ",
    brand: "EPOMAKER",
    tagline: "EPOMAKER x AULA F108 PRO V2 ワイヤレスメカニカルキーボード フルサイズ ピクセルディスプレイ搭載 潤滑済みスイッチ",
    price: 20700,
    rating: 5,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/61kHSI-B6lL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYRP76Y6",
    keyboardFilterTags: ["kb-keycap-pbt-double"],
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "k-nr2-061",
    category: "keyboard",
    name: "EPOMAKER X Aula F75 MAX ワイヤレスメカニカルキーボードTFTスクリーンとノブ付き 75% US配列のガスケットキーボード",
    brand: "EPOMAKER",
    tagline: "EPOMAKER X Aula F75 MAX ワイヤレスメカニカルキーボードTFTスクリーンとノブ付き 75% US配列のガスケットキーボード",
    price: 14510,
    rating: 4.6,
    reviews: 1856,
    image: "https://m.media-amazon.com/images/I/71CgOoh6LdL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GDFTW3QW",
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "k-nr2-065",
    category: "keyboard",
    name: "ミニキーボード 有線 78キー（白）",
    brand: "—",
    tagline: "ミニキーボード 有線 78キー 薄型 静音 高耐久レーザー刻印 軽量230g プロ仕様 ゼロ遅延 オフィス対応 (白)",
    price: 1100,
    rating: 2.7,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/51m1dM8CzkL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GV2PT85S",
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "コンパクト（78キー）" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "コンパクト（78キー）" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "230 グラム" },
        ]},
    ],
  },
  {
    id: "k-nr2-068",
    category: "keyboard",
    name: "Snsowed 超薄型 USB 有線キーボード（ピンク）",
    brand: "Snsowed",
    tagline: "Snsowed かわいい漫画超薄型 USB 有線キーボードサイレントコンピュータホームオフィスラップトップ用ユニバーサル (ピンク)",
    price: 2409,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61gZc-8VSTL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H1X78F47",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
  {
    id: "k-nr2-069",
    category: "keyboard",
    name: "88キー USB 有線キーボード（トラックボール内蔵）",
    brand: "—",
    tagline: "光学式トラックボールと産業用制御システム用の 3 ボタン設計を内蔵した 88Key 人間工学に基づいた USB 有線キーボード トラックボール付き産業用 USB キーボード",
    price: 6447,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61edwDmc6aL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8TRGL4J",
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: ["トラックボール"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" },
          { label: "特徴", value: "トラックボール" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
  {
    id: "k-nr2-071",
    category: "keyboard",
    name: "EWIN エルゴノミクス ワイヤレスキーボード",
    brand: "EWIN",
    tagline: "EWIN エルゴノミクスワイヤレスキーボード Bluetooth iPad/iPhone/Android/Mac/Windows対応 日本語配列",
    price: 19800,
    rating: 4.4,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61eUJJB9xBL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYQRGXDV",
    keyboardUsage: "productivity",
        highlights: [
      { label: "レイアウト", value: "JIS日本語配列（テンキー付き）" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "—" },
      { label: "電源", value: "充電式（内蔵バッテリー）" },
    ],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "JIS日本語配列（テンキー付き）" },
          { label: "内部構造", value: "メンブレン" },
          { label: "キーキャップ", value: "—" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "充電式（内蔵バッテリー）" },
        ]},
    ],
  }]
