import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングキーボード人気ギフト 2ページ目（2151972051 most-gifted pg=2 #51–#100）。 */
export const keyboardGamingMostGiftedPage2: Gadget[] = [
  {
    id: "k-gmg-p2-051",
    category: "keyboard",
    name: "YUNZII X98 QMK/VIA対応 ワイヤレス メカニカルゲーミングキーボード 透明キーキャップ 3モード接続 BT5.0/2.4G…",
    brand: "YUNZII",
    tagline: "YUNZII X98 QMK/VIA対応 ワイヤレス メカニカルゲーミングキーボード 透明キーキャップ 3モード接続 BT5.0/2.4GHz/USB-C ホットスワップ可能 潤滑済みスイッチ ガスケット構造 RGBバックライト ノブ付き Win/Mac対応 技適認証取得 …",
    price: 15280,
    rating: 4.4,
    reviews: 480,
    image: "https://m.media-amazon.com/images/I/81TaHK5BqML._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FC6CMFXH",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（給電）" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-053",
    category: "keyboard",
    name: "ZIYOULANG T60 ゲーミングキーボード メカニカルキーボード 青軸 二色射出成形技術・キーキャップ 金属航空コネクターケーブル付き",
    brand: "—",
    tagline: "ZIYOULANG T60 ゲーミングキーボード メカニカルキーボード 青軸 二色射出成形技術・キーキャップ 金属航空コネクターケーブル付き",
    price: 4299,
    rating: 4,
    reviews: 33,
    image: "https://m.media-amazon.com/images/I/61rPcHXtu2L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CP3CR1NJ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },{
    id: "k-gmg-p2-055",
    category: "keyboard",
    name: "AK35i メカニカルキーボード 美しい有線ゲーミングキーボード 白いバックライト 空色&ホワイト2色PBTボタン 104キー 4マルチメ…",
    brand: "—",
    tagline: "AK35i メカニカルキーボード 美しい有線ゲーミングキーボード 白いバックライト 空色&ホワイト2色PBTボタン 104キー 4マルチメディアキー ボリュームホイール 英語配列 (青軸)",
    price: 18600,
    rating: 4.4,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/61ApT8ZoWdL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08HX4821S",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-056",
    category: "keyboard",
    name: "Apex Pro Mini",
    brand: "エレコム",
    tagline: "SteelSeries Steelseries ラピッドトリガー 搭載 ゲーミングキーボード ミニサイズ Apex Pro Mini Wireless JP 無線 ワイヤレス 日本語配列 Quantum 2.0ワイヤレス接続 OmniPointスイッチ 2ーinー1アクションキー 搭載 64829 ブラック",
    price: 18600,
    rating: 3.2,
    reviews: 150,
    image: "https://m.media-amazon.com/images/I/71db03mHhBL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B5X5DB33",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "60％" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60％" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },{
    id: "k-gmg-p2-058",
    category: "keyboard",
    name: "MAMBASNAKE K75",
    brand: "MAMBASNAKE",
    tagline: "MAMBASNAKE K75メカニカルキーボードガラス軸ホットスワップメBluetooth /2.4G/USB-C接続3モード GSKET構造スペースバー バックライト付き 防塵性 キーキャップ 完全透明チェリーRGB MX全キーコンフリクトフリー",
    price: 4999,
    rating: 3.8,
    reviews: 35,
    image: "https://m.media-amazon.com/images/I/717zuum44mL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CCXR86L9",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（給電）" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-059",
    category: "keyboard",
    name: "EPOMAKER x AULA F99 ワイヤレス メカニカルキーボード ホットスワップ対応 ガスケット カスタム ゲーミングキーボード …",
    brand: "EPOMAKER",
    tagline: "EPOMAKER x AULA F99 ワイヤレス メカニカルキーボード ホットスワップ対応 ガスケット カスタム ゲーミングキーボード 5層パッド Bluetooth/2.4GHz/USB-C RGB NKRO 8000mAhバッテリー Win/M",
    price: 21800,
    rating: 4.6,
    reviews: 1019,
    image: "https://m.media-amazon.com/images/I/61ad5SFeEUL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CSYR5PK5",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "96％" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96％" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" },
        ]},
    ],
  },{
    id: "k-gmg-p2-061",
    category: "keyboard",
    name: "RK ROYAL KLUDGE RK61 ワイヤレス 60% メカニカルキーボード、ミニポータブルサイズ、US QWERTY レイアウト",
    brand: "—",
    tagline: "RK ROYAL KLUDGE RK61 ワイヤレス 60% メカニカルキーボード、ミニポータブルサイズ、US QWERTY レイアウト",
    price: 5359,
    rating: 4.4,
    reviews: 3108,
    image: "https://m.media-amazon.com/images/I/61u4Q4BY02L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQH2KNLB",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt-double"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-062",
    category: "keyboard",
    name: "MAMBASNAKE+ZiYouLang M87 ゲーミングキーボード ワイヤレス Bluetooth/2.4GHz 80% 87キー メ…",
    brand: "—",
    tagline: "MAMBASNAKE+ZiYouLang M87 ゲーミングキーボード ワイヤレス Bluetooth/2.4GHz 80% 87キー メンブレン式 テンキーレス コンパクトキーボード 快速接続 最大3台マルチペアリング対応 静音 軽量化 無線 小型 iPad Window…",
    price: 4299,
    rating: 3.4,
    reviews: 54,
    image: "https://m.media-amazon.com/images/I/71WnowaWTCL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CJHR4S5Y",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-063",
    category: "keyboard",
    name: "Logicool G G515 RAPID TKL",
    brand: "Logicool G",
    tagline: "Logicool G ラピッドトリガー G515 RAPID ゲーミングキーボード G515-TKL-RTBKd",
    price: 23500,
    rating: 4.5,
    reviews: 234,
    image: "https://m.media-amazon.com/images/I/61wSOwpxaQL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FGCDSH1J",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","kb-keycap-low-profile","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "磁気スイッチ（ロープロファイル）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "磁気スイッチ（ロープロファイル）" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },{
    id: "k-gmg-p2-066",
    category: "keyboard",
    name: "e元素 Z-11 ワイヤレスゲーミングキーボード 63キー 青軸 無線メカニカルキーボード BTと2.4GとUSB有線 60％小型コンパクト設計",
    brand: "e元素",
    tagline: "e元素 Z-11 ワイヤレスゲーミングキーボード 63キー 青軸 無線メカニカルキーボード BTと2.4GとUSB有線 60％小型コンパクト設計",
    price: 5588,
    rating: 3.6,
    reviews: 38,
    image: "https://m.media-amazon.com/images/I/61PNVl5VDrL._AC_SL1500_.jpg",
    connection: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09VGSMV75",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル（青軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル（青軸）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-067",
    category: "keyboard",
    name: "e元素 Z-11 ゲーミングキーボード 赤軸を採用 テンキーレス US英語配列 有線61キー メカニカルキースイッチ 60％小型コンパクト設計",
    brand: "e元素",
    tagline: "e元素 Z-11 ゲーミングキーボード 赤軸を採用 テンキーレス US英語配列 有線61キー メカニカルキースイッチ 60％小型コンパクト設計",
    price: 4388,
    rating: 4.2,
    reviews: 235,
    image: "https://m.media-amazon.com/images/I/61VL-lRGc1L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09LLZ16WC",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル（赤軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル（赤軸）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },{
    id: "k-gmg-p2-069",
    category: "keyboard",
    name: "GravaStar Mercury K1 Lite ゲーミングキーボード 日本語配列 無線 75%レイアウト オーロラ RGBバックライト…",
    brand: "—",
    tagline: "GravaStar Mercury K1 Lite ゲーミングキーボード 日本語配列 無線 75%レイアウト オーロラ RGBバックライト ワイヤレス | 唯一無二のフォルム テンキーレス ホットスワップ対応 ガスケット構造 Bluetooth5.0 有線接続 透明キーキャ…",
    price: 14980,
    rating: 4.4,
    reviews: 1356,
    image: "https://m.media-amazon.com/images/I/61-LI5fB4pL._AC_SL1500_.jpg",
    connection: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GSZDW9Q7",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth 5.0（単3形乾電池×1本）" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-070",
    category: "keyboard",
    name: "EPOMAKER x AULA F65 65%ワイヤレスメカニカルキーボード ホットスワップ対応ガスケットカスタムゲーミングキーボード 5…",
    brand: "EPOMAKER",
    tagline: "EPOMAKER x AULA F65 65%ワイヤレスメカニカルキーボード ホットスワップ対応ガスケットカスタムゲーミングキーボード 5層パッド",
    price: 11020,
    rating: 4.4,
    reviews: 524,
    image: "https://m.media-amazon.com/images/I/717KkSzFXDL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DD3SCWHD",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "65%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-071",
    category: "keyboard",
    name: "YUNZII YZ75",
    brand: "YUNZII",
    tagline: "YUNZII YZ75 75% ホットスワップ対応ワイヤレスゲーミングキーボード RGBバックライト BT5.0/2.4G/USB-C、Dye Sub PBTキーキャップ Linux/Win/Mac用 技適認証取得（Gateron G Pro 赤軸,ホワイト)",
    price: 9045,
    rating: 4.4,
    reviews: 227,
    image: "https://m.media-amazon.com/images/I/61I74tHG-hL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BP7CT8SW",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（給電）" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-072",
    category: "keyboard",
    name: "ROCCAT Vulcan II Max JP",
    brand: "ROCCAT",
    tagline: "ROCCAT ゲーミングキーボード Vulcan II Max JP 日本語配列 有線 ホワイト/白 オプティカル リニア 静音 フルサイズ カスタマイズ可能 RGB 半透明アームレスト ボリュームダイヤル 【日本正規代理店品】",
    price: 24347,
    rating: 4.5,
    reviews: 41,
    image: "https://m.media-amazon.com/images/I/81J+4sJkJLL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B097BXSJV9",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-075",
    category: "keyboard",
    name: "Razer Huntsman V2",
    brand: "Razer",
    tagline: "Razer Huntsman V2 Linear Optical Switch ゲーミングキーボード 英語 US配列 オプティカルスイッチ リニア触感 静音 ダブルショット PBT キーキャップ リストレスト デジタルダイヤル & 4メディアキー Chroma RGB 【日…",
    price: 31980,
    rating: 4.8,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/81K36pthoVL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09FY64KW7",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "オプティカル（リニア）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "オプティカル（リニア）" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-078",
    category: "keyboard",
    name: "RK ROYAL KLUDGE L75",
    brand: "RK ROYAL KLUDGE",
    tagline: "RK ROYAL KLUDGE L75 ワイヤレスガスケットRGBメカニカルゲーミングキーボード ノブ付き、US QWERTY レイアウト",
    price: 9999,
    rating: 4.6,
    reviews: 120,
    image: "https://m.media-amazon.com/images/I/61HnngI77HL._AC_SL1500_.jpg",
    connection: "Bluetooth / 2.4GHz /有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DW3V9L1T",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 2.4GHz /有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz / USB-C（給電）" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-079",
    category: "keyboard",
    name: "AKS068pro",
    brand: "—",
    tagline: "AKS068pro ゲーミングキーボード アリスレイアウト ワイヤレス 2.4Ghz/ Bluetooth 5.0/Type-C有線 68キー Sea salt軸 アンチゴースト ガスケットマウント ホットスワップ可能 PBTキーキャップ 人間工学 南向きのRGBバックライ…",
    price: 8599,
    rating: 2.9,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61-+WwxS9oL._AC_SL1500_.jpg",
    connection: "Bluetooth/有線/2.4GHz (USBレシーバー)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CYQ2CKCC",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "65％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth/有線/2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth 5.0（給電）" },
        ]},
    ],
  },
  {
    id: "k-gmg-p2-080",
    category: "keyboard",
    name: "Razer BlackWidow V3 JP",
    brand: "Razer",
    tagline: "Razer BlackWidow V3 JP Yellow Switch ゲーミングキーボード メカニカル イエロー軸 Chroma RGB 日本語配列 【日本正規代理店保証品】 RZ03-03542300-R3J1",
    price: null,
    rating: 4.5,
    reviews: 368,
    image: "https://m.media-amazon.com/images/I/81GSXNfFTML._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08PZ4R15Z",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（黄軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" },
    ],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" },
        ]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（黄軸）" },
          { label: "キーキャップ", value: "ABS" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
]
