import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングキーボード人気ギフト（2151972051 most-gifted #1–#100）。 */
export const keyboardGamingMostGifted: Gadget[] = [
  {
    id: "k-gmg-001",
    category: "keyboard",
    name: "WOBKEY Rainy75 Pro",
    brand: "WOBKEY",
    tagline: "雨音のような打鍵音 メカニカルキーボード 3WAY接続 OS互換性 ホットスワップとVIAの対応 カスタマイズ性 ガスケットデザイン アルミニウム素材使用 RGBバックライト(Pro(Luna 日本語配列))",
    price: 27720,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71aXg368lML._AC_SL1500_.jpg",
    connection: "Bluetooth / 2.4GHz / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVDPMQW8",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 2.4GHz / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz / 有線 USB（給電）" }]}],
  },
  {
    id: "k-gmg-002",
    category: "keyboard",
    name: "MonsGeek FUN60 Pro SP 英語配列 有線モデル 0.01mm ラピッドトリガー対応 高コスパ ゲーミングキーボード ブラック",
    brand: "MonsGeek",
    tagline: "MonsGeek FUN60 Pro SP 英語配列 有線モデル 0.01mm ラピッドトリガー対応 高コスパ ゲーミングキーボード ブラック | 磁気スイッチ Akko Glare Magnetic Switch HEセンサー テンキーレス サイドプリント 有線8K ホッ…",
    price: 5980,
    rating: 4,
    reviews: 116,
    image: "https://m.media-amazon.com/images/I/31T2h5kSx8L._AC_SL1500_.jpg",
    connection: "有線 USB (着脱式)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09BFWB28Z",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
        highlights: [
      { label: "レイアウト", value: "60%（US配列）" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "電源", value: "有線給電" }],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%（US配列）" },
          { label: "内部構造", value: "磁気スイッチ（Akko Glare Magnetic）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB (着脱式)" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gmg-003",
    category: "keyboard",
    name: "EPOMAKER x Aula F75 ゲーミングキーボード ガスケット メカニカルキーボード 5層パッド＆ノブ付き 75% ワイヤレス",
    brand: "EPOMAKER",
    tagline: "EPOMAKER x Aula F75 ゲーミングキーボード ガスケット メカニカルキーボード 5層パッド＆ノブ付き 75% ワイヤレス",
    price: 13991,
    rating: 4.5,
    reviews: 3976,
    image: "https://m.media-amazon.com/images/I/71P5eKh8sVL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D3F69XSP",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1 キログラム" }]}],
  },
  {
    id: "k-gmg-004",
    category: "keyboard",
    name: "e元素 z-88",
    brand: "e元素",
    tagline: "e元素 z-88 ゲーミングキーボード 赤軸 75%コンパクト 81キー テンキーレス RGBメカニカルキーボード 有線 ホットスワップ対応",
    price: 5299,
    rating: 4.2,
    reviews: 815,
    image: "https://m.media-amazon.com/images/I/6110jxaHoiL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07CM63BBC",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "750 グラム" }]}],
  },
  {
    id: "k-gmg-005",
    category: "keyboard",
    name: "YUNZII B75 PRO 75% ガスケットゲーミングキーボード 無線メカニカルキーボード BT/2.4G/有線 ワイヤレス ホットス…",
    brand: "YUNZII",
    tagline: "YUNZII B75 PRO 75% ガスケットゲーミングキーボード 無線メカニカルキーボード BT/2.4G/有線 ワイヤレス ホットスワップ 搭載 RGB ノブ付きカスタムキーボード Mac/Win用 技適認証取得 (グリーン, ココアクリームV2スイッチ)",
    price: 11199,
    rating: 4.6,
    reviews: 1315,
    image: "https://m.media-amazon.com/images/I/714fu-zqbuL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FF9WN7R1",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },{
    id: "k-gmg-007",
    category: "keyboard",
    name: "V-custom VK310S RGB",
    brand: "エレコム",
    tagline: "エレコム ゲーミングキーボード 有線 V-custom VK310S RGB テンキーレス メカニカル ネオクラッチキーキャップ 銀軸 スピードリニア USBポート搭載 TK-VK310SBK",
    price: 7973,
    rating: 4.2,
    reviews: 192,
    image: "https://m.media-amazon.com/images/I/615HCTPpGvL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BB62QGMV",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（銀軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（銀軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },{
    id: "k-gmg-012",
    category: "keyboard",
    name: "AIM1 瞬 ラピッドトリガー 0.01mm ゲーミングキーボード 75%サイズ ポーリングレート8000Hz MATATAKI",
    brand: "AIM1",
    tagline: "AIM1 瞬 ラピッドトリガー 0.01mm ゲーミングキーボード 75%サイズ ポーリングレート8000Hz MATATAKI",
    price: 14980,
    rating: 4.6,
    reviews: 547,
    image: "https://m.media-amazon.com/images/I/61C2UqZTgKL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GMJ79P2F",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.9 キログラム" }]}],
  },{
    id: "k-gmg-014",
    category: "keyboard",
    name: "HyperX Alloy Origins Core RGB メカニカルゲーミングキーボード 日本語配列 テンキーレス 4P5P3AJ#ABJ",
    brand: "—",
    tagline: "HyperX Alloy Origins Core RGB メカニカルゲーミングキーボード 日本語配列 テンキーレス 4P5P3AJ#ABJ",
    price: 11980,
    rating: 4.5,
    reviews: 1391,
    image: "https://m.media-amazon.com/images/I/71QSt58mwfL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B081VR349C",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "テンキーレス" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "テンキーレス" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gmg-015",
    category: "keyboard",
    name: "YUNZII B87",
    brand: "YUNZII",
    tagline: "YUNZII B87 ワイヤレスメカニカルキーボード ゲーミングキーボード BT5.0/2.4G/USB-C NKRO QMK/VIAソフトウェアカスタム MOAキーキャップ ガスケット RGB リストレスト Win/Mac用 (ブラウン, ハートココアクリームV2スイッチ)",
    price: 12608,
    rating: 4.7,
    reviews: 646,
    image: "https://m.media-amazon.com/images/I/712k+Klh5JL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FNRKG942",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（給電）" }]}],
  },
  {
    id: "k-gmg-016",
    category: "keyboard",
    name: "SmackApe Impact 80 メカニカルキーボード 3WAY接続 無線 ワイヤレス 低遅延 テンキーレス TKL JIS 日本語配…",
    brand: "SmackApe",
    tagline: "SmackApe Impact 80 メカニカルキーボード 3WAY接続 無線 ワイヤレス 低遅延 テンキーレス TKL JIS 日本語配列 US 英字配列 ガスケットマウント ARGB ホットスワップ VIA",
    price: 13900,
    rating: 4.3,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/71R9hq-YzkL._AC_SL1500_.jpg",
    connection: "Bluetooth / 2.4GHz /有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCLQ5MM2",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 2.4GHz /有線" },
          { label: "電源", value: "充電式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1100 グラム" }]}],
  },
  {
    id: "k-gmg-018",
    category: "keyboard",
    name: "ATTACK SHARK X820ULTRA メカニカルキーボード 75% 3モード ガスケット 5層消音 LEDディスプレイ ノブ 40…",
    brand: "—",
    tagline: "ATTACK SHARK X820ULTRA メカニカルキーボード 75% 3モード ガスケット 5層消音 LEDディスプレイ ノブ 4000mAh",
    price: 10999,
    rating: 4.3,
    reviews: 151,
    image: "https://m.media-amazon.com/images/I/61pSpOX0xIL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FHW8J3YR",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-gmg-019",
    category: "keyboard",
    name: "YUNZII X75 有線 ホットスワップメカニカルキーボード 透明なキーキャップ ガスケット装着75キーボード RGBバックライト付き …",
    brand: "YUNZII",
    tagline: "YUNZII X75 有線 ホットスワップメカニカルキーボード 透明なキーキャップ ガスケット装着75キーボード RGBバックライト付き ゲーミングキーボード Windows/Mac対応(クリスタルアイス軸、有線ホワイト）",
    price: 8549,
    rating: 4.5,
    reviews: 117,
    image: "https://m.media-amazon.com/images/I/71oARXgVw7L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BLTMTPZH",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gmg-021",
    category: "keyboard",
    name: "YUNZII AL71 メカニカルキーボード 68% コンパクト フルアルミCNC加工 ガスケット構造 [Bluetooth/2.4G/U…",
    brand: "YUNZII",
    tagline: "YUNZII AL71 メカニカルキーボード 68% コンパクト フルアルミCNC加工 ガスケット構造 [Bluetooth/2.4G/USB-C 三モード接続] ホットスワップ対応 NKRO RGBバックライト Win/Mac両対応 技適認証済み プレゼント対応（シルバー…",
    price: 9240,
    rating: 4.6,
    reviews: 68,
    image: "https://m.media-amazon.com/images/I/71snEUI-bmL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CHJN5FQG",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "68％" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "68％" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]}],
  },
  {
    id: "k-gmg-023",
    category: "keyboard",
    name: "Razer Huntsman Mini 小型 ゲーミングキーボード - Clicky Optical Switch 英語US配列 60%レ…",
    brand: "Razer",
    tagline: "Razer Huntsman Mini 小型 ゲーミングキーボード - Clicky Optical Switch 英語US配列 60%レイアウト 光学スイッチ 超高速1.5mm作動 クリッキー触感 Chroma RGB 【日本正規代理店保証品】 RZ03-03390100…",
    price: 18981,
    rating: 4.3,
    reviews: 230,
    image: "https://m.media-amazon.com/images/I/61tT4KFPSQS._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08CXXRLBZ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gmg-025",
    category: "keyboard",
    name: "MAMBASNAKE×AJAZZ AK680 有線ゲーミングキーボード 茶軸 軽量 メカニカルキーボード ホットスワップ対応 小型68キー…",
    brand: "—",
    tagline: "MAMBASNAKE×AJAZZ AK680 有線ゲーミングキーボード 茶軸 軽量 メカニカルキーボード ホットスワップ対応 小型68キー RGB照明 ボール型キーキャップ EVAサンドイッチ WIN/MAC/ANDROID対応 ―グレー",
    price: 2659,
    rating: 4.3,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/61m+DKaOjXL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CZKQ1HL5",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "65%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gmg-026",
    category: "keyboard",
    name: "Pulsar PCMK 3HE TKL Something Edition",
    brand: "Pulsar",
    tagline: "Pulsar Gaming Gears [Pro Series] PCMK 3HE TKL Something Edition ゲーミング キーボード JIS 日本語配列 91キー 磁気スイッチ 8K Polling Rate【国内正規品】",
    price: 27980,
    rating: 4.7,
    reviews: 53,
    image: "https://m.media-amazon.com/images/I/716PuGtZqpL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HC6LVZPB",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80%" },
      { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80%" },
          { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "963 グラム" }]}],
  },
  {
    id: "k-gmg-027",
    category: "keyboard",
    name: "e元素 Z-68 ワイヤレス メカニカルキーボード 銀軸 BT/2.4GHz無線 / 有線 60% コンパクトキーボード US配列 ホット…",
    brand: "e元素",
    tagline: "e元素 Z-68 ワイヤレス メカニカルキーボード 銀軸 BT/2.4GHz無線 / 有線 60% コンパクトキーボード US配列 ホットスワップ",
    price: 6999,
    rating: 3.7,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61B5H6tONkL._AC_SL1500_.jpg",
    connection: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G48JJPFZ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-gmg-028",
    category: "keyboard",
    name: "YUNZII C75 ワイヤレス メカニカルキーボード 75%レイアウト ホットスワップ対応 クリーミーキーボード NKRO PBT MO…",
    brand: "YUNZII",
    tagline: "YUNZII C75 ワイヤレス メカニカルキーボード 75%レイアウト ホットスワップ対応 クリーミーキーボード NKRO PBT MOA キーキャップ RGBバックライト ガスケットマウント 可愛いケーキデザイン BT5.0/2.4G/USB-C Win/Mac/ゲーミ…",
    price: 10908,
    rating: 4.7,
    reviews: 433,
    image: "https://m.media-amazon.com/images/I/71ctwpZTMkL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FLX6H62D",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "有線給電/充電式" }]}],
  },
  {
    id: "k-gmg-029",
    category: "keyboard",
    name: "有線フローティングゲーミングキーボード ライトアップ USBキーボード メカニカルキーボード 手触りRGBバックライトキーボード ゲームア…",
    brand: "—",
    tagline: "有線フローティングゲーミングキーボード ライトアップ USBキーボード メカニカルキーボード 手触りRGBバックライトキーボード ゲームアクセサリー ポータブルコンピュータキーボード クールなもの 男性女性への誕生日プレゼント(C)",
    price: 2350,
    rating: 4,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/61XmxvoH7YL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CCV6MY93",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
    {
    id: "k-gmg-057",
    category: "keyboard",
    name: "エレコム ゲーミングキーボード V-custom VK200S 有線 テンキーレス 65%サイズ メカニカル ネオクラッチキーキャップ 銀…",
    brand: "ELECOM",
    tagline: "エレコム ゲーミングキーボード V-custom VK200S 有線 テンキーレス 65%サイズ メカニカル ネオクラッチキーキャップ 銀軸 スピードリニア USBポート搭載 TK-VK200SBK",
    price: 5630,
    rating: 4.3,
    reviews: 96,
    image: "https://m.media-amazon.com/images/I/71PcJ-IlTbL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BB6FVBFJ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "65%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  }]
