import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングキーボード新着 1ページ目（2151972051 pg=1）#1–#50。 */
export const keyboardGamingNewReleasesPage1: Gadget[] = [{
    id: "k-gnr-p1-003",
    category: "keyboard",
    name: "GravaStar Mercury K1 Lite",
    brand: "GravaStar",
    tagline: "JIS 75% 無線・オーロラRGB・透明キーキャップ・ガスケット構造",
    price: 23980,
    rating: 4.5,
    reviews: 1719,
    image: "https://m.media-amazon.com/images/I/61B-ibsJX5L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth/ 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H5K5PTDH",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth/ 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth 5.0 / 有線 USB（充電式（内蔵バッテリー））" }]}],
  },
    {
    id: "k-gnr-p1-008",
    category: "keyboard",
    name: "e元素 Z-104",
    brand: "e元素",
    tagline: "銀軸・2.4G/BT/有線・フルサイズUS・ガスケット（別SKU）",
    price: 8980,
    rating: 4.1,
    reviews: 48,
    image: "https://m.media-amazon.com/images/I/71vhF8izSPL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVMSQS7F",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー)（充電式（4000mAh））" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1000 グラム" }]}],
  },
    {
    id: "k-gnr-p1-010",
    category: "keyboard",
    name: "東プレ REALFORCE GX1 Plus サザビー 日本語配列 ゲーミングキーボード X1PCS1 KB0939",
    brand: "REALFORCE",
    tagline: "東プレ REALFORCE GX1 Plus サザビー 日本語配列 ゲーミングキーボード X1PCS1 KB0939",
    price: 44373,
    rating: 4.4,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/51Qo+kQ1Z+L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GL1B1L6Y",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "静電容量無接点方式" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "静電容量無接点方式" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
    {
    id: "k-gnr-p1-012",
    category: "keyboard",
    name: "Womier DK98pro キーボード 98キー ゲーミングキーボード ワイヤレス 静音キー テンキー付き 3モード接続",
    brand: "—",
    tagline: "Womier DK98pro キーボード 98キー ゲーミングキーボード ワイヤレス 静音キー テンキー付き 3モード接続 | BT5.0/2.4GHz/USB-C クリーミーでかわいい RGBバックライト メディアノブ OLEDスクリーン付き MAC・Windows対応",
    price: 5794,
    rating: 4.5,
    reviews: 115,
    image: "https://m.media-amazon.com/images/I/61tU7u63KHL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GV7NMKLS",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gnr-p1-013",
    category: "keyboard",
    name: "NuPhy Air75 V3",
    brand: "NuPhy",
    tagline: "JIS 88キー75%・ロープロファイル・ノブ付き・3モード接続・ホットスワップ",
    price: 28620,
    rating: 4.2,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61dpjcVA+0L._AC_SL1500_.jpg",
    connection: "2.4GHz (LIGHTSPEED) / Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3H5FW7Y",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-low-profile"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ロープロファイル・ガスケット・ホットスワップ）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ロープロファイル・ガスケット・ホットスワップ）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (LIGHTSPEED) / Bluetooth/有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gnr-p1-014",
    category: "keyboard",
    name: "RK ROYAL KLUDGE S98",
    brand: "RK ROYAL KLUDGE",
    tagline: "96%・スマートディスプレイ＆ノブ・3モード接続・US QWERTY",
    price: 10649,
    rating: 4.5,
    reviews: 41,
    image: "https://m.media-amazon.com/images/I/61Gmcp3-ljL._AC_SL1500_.jpg",
    connection: "Bluetooth / 2.4GHz /有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTM2FV9C",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 2.4GHz /有線" },
          { label: "電源", value: "充電式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "3 ポンド" }]}],
  },
  {
    id: "k-gnr-p1-015",
    category: "keyboard",
    name: "Logicool G G512 X 75",
    brand: "Logicool G",
    tagline: "8000Hz RT・ホットスワップ・磁気式アナログ 75%テンキーレス（JIS）",
    price: 1699,
    rating: 3.5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/51tJp1TCZmL._AC_SL1500_.jpg",
    connection: "有線 USB (着脱式, 8000Hz)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H4W9F4Z7",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
        highlights: [
      { label: "レイアウト", value: "75%（JIS日本語配列）" },
      { label: "内部構造", value: "メカニカル（磁気式アナログ / ラピッドトリガー・ホットスワップ）" },
      { label: "キーキャップ", value: "—" },
      { label: "電源", value: "有線給電" }],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%（JIS日本語配列）" },
          { label: "内部構造", value: "磁気式アナログ（ラピッドトリガー・ホットスワップ）" },
          { label: "キーキャップ", value: "—" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB (着脱式, 8000Hz)" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p1-016",
    category: "keyboard",
    name: "Logicool G 8000Hz ラピッドトリガー ホットスワップ G512 X 75 ゲーミングキーボード リニア ガスケットマウント…",
    brand: "Logicool G",
    tagline: "Logicool G 8000Hz ラピッドトリガー ホットスワップ G512 X 75 ゲーミングキーボード リニア ガスケットマウント 日本語配列 G512X-75-LNBK アクチュエーションポイント 調整可能 有線 テンキーレス 磁気式アナログスイッチ メカニカル …",
    price: 28145,
    rating: 4.4,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61QlxmNEEaL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWLTN6M4",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p1-017",
    category: "keyboard",
    name: "RK ROYAL KLUDGE R98 Pro ゲーミングキーボード 日本語配列 フルサイズ メカニカルキーボード 有線 ボリュームノブ・…",
    brand: "—",
    tagline: "【Amazon.co.jp限定】RK ROYAL KLUDGE R98 Pro ゲーミングキーボード 日本語配列 フルサイズ メカニカルキーボード 有線 ボリュームノブ・ガスケットマウント・RGBバックライト・PBTキーキャップ (Cherry Profile) ホットスワ…",
    price: 11900,
    rating: 4.2,
    reviews: 20,
    image: "https://m.media-amazon.com/images/I/711dHaEHvgL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS4YXJBV",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-pbt"],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "1,000 Hz" }]}],
  },{
    id: "k-gnr-p1-019",
    category: "keyboard",
    name: "EPOMAKER TH108 PRO",
    brand: "EPOMAKER",
    tagline: "JISフルサイズ・画面+ノブ・10000mAh（別SKU）",
    price: 17500,
    rating: 4.6,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/61BzH+izVML._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H5CDXQV2",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth 5.0 / 有線 USB（充電式（10000mAh））" }]}],
  },
  {
    id: "k-gnr-p1-020",
    category: "keyboard",
    name: "RK ROYAL KLUDGE RK61JP",
    brand: "RK ROYAL KLUDGE",
    tagline: "60% JIS・61キー・3モード・PBT・ホットスワップ",
    price: 28550,
    rating: 4.3,
    reviews: 236,
    image: "https://m.media-amazon.com/images/I/81MeRy27I0L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYS4RP86",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "719.5 グラム" }]}],
  },
  {
    id: "k-gnr-p1-021",
    category: "keyboard",
    name: "RK ROYAL KLUDGE RK61JP ワイヤレス 60% メカニカルキーボード、ミニポータブルサイズ、日本語QWERTY レイアウト",
    brand: "—",
    tagline: "RK ROYAL KLUDGE RK61JP ワイヤレス 60% メカニカルキーボード、ミニポータブルサイズ、日本語QWERTY レイアウト | 61キー 3モード BT5.0/2.4G/USB-C 対応コンパクトゲーミングキーボード ― PBTキーキャップ、専用ソフトウェ…",
    price: 6749,
    rating: 4.5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61czS1hNnVL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTQPNJ3M",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt"],
        highlights: [
      { label: "レイアウト", value: "60%（JIS日本語配列）" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%（JIS日本語配列）" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式/有線給電" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gnr-p1-023",
    category: "keyboard",
    name: "ATTACK SHARK M36HE",
    brand: "ATTACK SHARK",
    tagline: "36キー片手ゲーミングKB・8000Hz・磁気RT・0.01mm精度",
    price: 6499,
    rating: 4.3,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/71osL8nC1LL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H287JCH8",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "片手キーボード（36キー）" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "片手キーボード（36キー）" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p1-026",
    category: "keyboard",
    name: "EPOMAKER Split70",
    brand: "EPOMAKER",
    tagline: "70%左右分割型（68キー）・QMK/VIA・3モード接続（2.4G/BT5.0/Type-C）・PBT・ノブ付き",
    price: 17500,
    rating: 3,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61eHedt91ML._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth 5.0 / 有線 USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6FSY9ZS",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["kb-keycap-pbt", "kb-structure-gasket", "kb-power-rechargeable"],
        highlights: [
      { label: "レイアウト", value: "70% 左右分割型（約70%相当 / 68キー）" },
      { label: "内部構造", value: "メカニカル（ホットスワップ対応 / ガスケットマウント＆多層吸音フォーム構造）" },
      { label: "キーキャップ", value: "PBT（耐摩耗性・質感に優れた素材）" },
      { label: "電源", value: "充電式（内蔵バッテリー / USB Type-C充電対応）" }],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "70% 左右分割型（約70%相当 / 68キー）" },
          { label: "内部構造", value: "メカニカル（ホットスワップ対応 / ガスケットマウント＆多層吸音フォーム構造）" },
          { label: "キーキャップ", value: "PBT（耐摩耗性・質感に優れた素材）" },
          { label: "US配列", value: "はい（英語配列 / US配列）" },
          { label: "ラピッドトリガー", value: "いいえ（標準的なメカニカルスイッチ構造）" },
          { label: "ゲーミングキーボード", value: "はい（QMK/VIA対応カスタム、RGBバックライト、スマート液晶画面＆ノブ搭載）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "3モード接続（2.4GHzワイヤレス / Bluetooth 5.0 / USB Type-C有線）" },
          { label: "電源", value: "充電式（内蔵バッテリー / USB Type-C充電対応）" },
          { label: "ポーリングレート", value: "未記載（一般的なワイヤレスメカニカルキーボードとして最大1000Hz対応）" }]}],
  },
  {
    id: "k-gnr-p1-027",
    category: "keyboard",
    name: "EPOMAKER Split70 ワイヤレスゲーミングキーボード 分割キーボード QMK/VIA対応 テンキーレス 70% メカニカルキーボード",
    brand: "EPOMAKER",
    tagline: "EPOMAKER Split70 ワイヤレスゲーミングキーボード 分割キーボード QMK/VIA対応 テンキーレス 70% メカニカルキーボード | 無線 ホットスワップ対応 クリーミーリニアスイッチ 2.4Ghz/BT/Type-C ノブ付き RGBバックライト PBTキ…",
    price: 20300,
    rating: 3.8,
    reviews: 11,
    image: "https://m.media-amazon.com/images/I/61s8MvfxtpL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVJTMQTD",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-pbt", "kb-structure-gasket", "kb-power-rechargeable"],
        highlights: [
      { label: "レイアウト", value: "70% 分割（テンキーレス）" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "70% 分割（テンキーレス）" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" },
          { label: "US配列", value: "はい（英語配列 / US配列）" },
          { label: "ラピッドトリガー", value: "いいえ（標準的なメカニカルスイッチ構造）" },
          { label: "ゲーミングキーボード", value: "はい（QMK/VIA対応カスタム、RGBバックライト、スマート液晶画面＆ノブ搭載）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "ポーリングレート", value: "未記載（一般的なワイヤレスメカニカルキーボードとして最大1000Hz対応）" }]}],
  },
  {
    id: "k-gnr-p1-028",
    category: "keyboard",
    name: "3キー マクロキーボード",
    brand: "—",
    tagline: "Bluetooth/USB プログラマブル3キー RGB ミニメカニカルパッド",
    price: 3567,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51k0y4PSs0L._AC_SL1500_.jpg",
    connection: "Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXWRDGSJ",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["kb-keycap-abs"],
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "—" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "—" }],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "—" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth/有線" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-gnr-p1-029",
    category: "keyboard",
    name: "AJAZZ AK820",
    brand: "AJAZZ",
    tagline: "75% 82キー・USB-C有線・ガスケット・ノブ付き・ホットスワップ",
    price: 2724,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51ZkvW+YDOL._AC_SL1500_.jpg",
    connection: "有線 USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2FB49S9",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット・ホットスワップ）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "電源", value: "有線給電" }],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット・ホットスワップ）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB Type-C" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gnr-p1-030",
    category: "keyboard",
    name: "AJAZZ AK820",
    brand: "AJAZZ",
    tagline: "75% 82キー・USB-C有線・ガスケット・ノブ付き（別SKU）",
    price: 6999,
    rating: 4,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61IQfgf8TIL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HB4J7KKT",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット・ホットスワップ）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット・ホットスワップ）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  }]
