import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングキーボード売れ筋 2ページ目（2151972051 pg=2 #51–#100）。 */
export const keyboardGamingBestsellersPage2: Gadget[] = [
  {
    id: "k-gbs-p2-051",
    category: "keyboard",
    name: "MAGIC-REFINER K68 ゲーミングキーボード Bluetooth ワイヤレス 2.4GHz 赤軸 テンキーレス RGB",
    brand: "—",
    tagline: "MAGIC-REFINER K68 ゲーミングキーボード Bluetooth ワイヤレス 2.4GHz 赤軸 テンキーレス RGB",
    price: 3383,
    rating: 3.9,
    reviews: 333,
    image: "https://m.media-amazon.com/images/I/61EWJ+5X-aL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTKZFDJD",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "65%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "単4形乾電池×2本" }]}],
  },
  {
    id: "k-gbs-p2-052",
    category: "keyboard",
    name: "YUNZII B75 PRO",
    brand: "YUNZII",
    tagline: "YUNZII B75 PRO 75% ガスケットゲーミングキーボード 無線メカニカルキーボード BT/2.4G/有線 ワイヤレス ホットスワップ 搭載 RGB ノブ付きカスタムキーボード Mac/Win用 技適認証取得 (ピンク, ココアクリームV2スイッチ)",
    price: 11199,
    rating: 4.6,
    reviews: 1315,
    image: "https://m.media-amazon.com/images/I/71YDv-8eCYL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DP8BGL5Z",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー)（給電）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.9 キログラム" }]}],
  },
  {
    id: "k-gbs-p2-053",
    category: "keyboard",
    name: "Razer Huntsman V3 HE Magnetic Mini",
    brand: "Razer",
    tagline: "Razer Huntsman V3 HE Magnetic Mini 65% 8KHz ゲーミングキーボード US配列 ラピッドトリガー",
    price: 17980,
    rating: 3.6,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/71UzoxZzLHL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GX1TQ3K8",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "510 グラム" }]}],
  },
    {
    id: "k-gbs-p2-057",
    category: "keyboard",
    name: "NuPhy Node75 JIS",
    brand: "NuPhy",
    tagline: "NuPhy Node75 JIS ワイヤレス メカニカルキーボード 75% 82キー ホットスワップ対応 Bluetooth/2.4GHz/USB-C 有線接続 RGBバックライト PBTキーキャップ タッチジェスチャー対応 ゲーミングキーボード 日本語配列 (Gray L…",
    price: 17365,
    rating: 4.5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/41vlSzoMdEL._AC_SL1500_.jpg",
    connection: "2.4GHz (LIGHTSPEED) / Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GPDQY2VJ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt-double"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (LIGHTSPEED) / Bluetooth/有線" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（給電）" }]}],
  },
  {
    id: "k-gbs-p2-059",
    category: "keyboard",
    name: "Keychron K2 Max スペシャルエディション",
    brand: "Keychron",
    tagline: "「国内正規品」Keychron K2 Max スペシャルエディション メカニカルキーボード 2.4G/Bluetooth/有線 日本語配列 茶軸",
    price: 22550,
    rating: 3.8,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/618S-6fx6lL._AC_SL1500_.jpg",
    connection: "Bluetooth / 2.4GHz / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FSKL7D4D",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 2.4GHz / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz / 有線 USB（給電）" }]}],
  },
  {
    id: "k-gbs-p2-060",
    category: "keyboard",
    name: "Redragon K524 無線 ゲーミングキーボード 75% テンキーレス 2.4G/Bluetooth/USB有線 英語配列 ブラック",
    brand: "—",
    tagline: "Redragon K524 無線 ゲーミングキーボード 75% テンキーレス 2.4G/Bluetooth/USB有線 英語配列 ブラック",
    price: 5180,
    rating: 4.3,
    reviews: 139,
    image: "https://m.media-amazon.com/images/I/61tD7F8wLVL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F7H9H1C6",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-gbs-p2-063",
    category: "keyboard",
    name: "ATTACK SHARK X68HE ラピッドトリガー ゲーミングキーボード 8000Hz対応 RT0.01mm （ブラック）",
    brand: "—",
    tagline: "ATTACK SHARK X68HE ラピッドトリガー ゲーミングキーボード 8000Hz対応 RT0.01mm （ブラック） | ポーリングレート8000Hz RGB 磁気スイッチ 0.125msディレイ PBTキーキャップ デッドゾーン調整機能 ホットスワップ可能",
    price: 8999,
    rating: 4,
    reviews: 96,
    image: "https://m.media-amazon.com/images/I/81GNje1v+eL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DR2NR6G5",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt-double","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "65%（68キー）" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65%（68キー）" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gbs-p2-064",
    category: "keyboard",
    name: "RK ROYAL KLUDGE R75 メカニカルキーボード 有線｜日本語配列｜ボリュームノブ搭載｜ゲーミングキーボード 75%カスタム｜…",
    brand: "—",
    tagline: "【Amazon.co.jp限定】RK ROYAL KLUDGE R75 メカニカルキーボード 有線｜日本語配列｜ボリュームノブ搭載｜ゲーミングキーボード 75%カスタム｜ガスケットマウント構造・RGBバックライト・ソフトウェア対応｜Cherry Profileプロファイル・…",
    price: 9999,
    rating: 4.3,
    reviews: 626,
    image: "https://m.media-amazon.com/images/I/612ZD5crVcL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CJ2LXNFN",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gbs-p2-065",
    category: "keyboard",
    name: "e元素Z-99 ワイヤレス ゲーミングキーボード 銀軸 Bluetooth/有線/2.4G 無線メカニカルキーボード テンキー付き ホット…",
    brand: "e元素",
    tagline: "e元素Z-99 ワイヤレス ゲーミングキーボード 銀軸 Bluetooth/有線/2.4G 無線メカニカルキーボード テンキー付き ホットスワップ",
    price: 7999,
    rating: 4.1,
    reviews: 48,
    image: "https://m.media-amazon.com/images/I/71vY4WOflAL._AC_SL1500_.jpg",
    connection: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D3T1NB2S",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-pbt-double"],
        highlights: [
      { label: "レイアウト", value: "96％" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96％" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.85 キログラム" }]}],
  },
  {
    id: "k-gbs-p2-066",
    category: "keyboard",
    name: "SteelSeries ゲーミングキーボード テンキーレス 有線 Apex 3 TKL 日本語配列 静音スイッチ IP32防滴 24キー同…",
    brand: "—",
    tagline: "SteelSeries ゲーミングキーボード テンキーレス 有線 Apex 3 TKL 日本語配列 静音スイッチ IP32防滴 24キー同時押し対応 ブラック",
    price: 8573,
    rating: 4.3,
    reviews: 224,
    image: "https://m.media-amazon.com/images/I/61TycZk26CL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09MH9Q1L6",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1.41 ポンド" }]}],
  },
  {
    id: "k-gbs-p2-067",
    category: "keyboard",
    name: "e元素 Z-11 ワイヤレスゲーミングキーボード 63キー メカニカル 赤軸 Bluetoothと2.4G無線と有線 60％小型 コンパクト設計",
    brand: "e元素",
    tagline: "e元素 Z-11 ワイヤレスゲーミングキーボード 63キー メカニカル 赤軸 Bluetoothと2.4G無線と有線 60％小型 コンパクト設計 | 3つモード接続,充電式, RGB発光LEDバックライト, Windows/Macに対応のゲーム/オフィス用キーボード (グレ…",
    price: 5588,
    rating: 3.9,
    reviews: 127,
    image: "https://m.media-amazon.com/images/I/61i9I8K2NVL._AC_SL1500_.jpg",
    connection: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09VGRDJTP",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル（赤軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル（赤軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]}],
  },
  {
    id: "k-gbs-p2-068",
    category: "keyboard",
    name: "MageGee ミニ 60% ゲーミングキーボード、RGB バックライト 61キー 超コンパクトキーボード、TS91 人間工学的 防水 メ…",
    brand: "—",
    tagline: "MageGee ミニ 60% ゲーミングキーボード、RGB バックライト 61キー 超コンパクトキーボード、TS91 人間工学的 防水 メカニカルフィーリング オフィスコンピューターキーボード PC、MAC、PS4、Xbox ONE ゲーマー用（ブラック）",
    price: 2970,
    rating: 4.3,
    reviews: 2540,
    image: "https://m.media-amazon.com/images/I/714Y4KXLVPL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08F7GZDT2",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "263 グラム" }]}],
  },
  {
    id: "k-gbs-p2-069",
    category: "keyboard",
    name: "Redragon K524 ゲーミングキーボード 有線 75% テンキーレス 静音メンブレン式 メカニカルタッチ RGBバックライト 英語配列",
    brand: "—",
    tagline: "Redragon K524 ゲーミングキーボード 有線 75% テンキーレス 静音メンブレン式 メカニカルタッチ RGBバックライト 英語配列 | マクロ機能 26キー同時押し アンチゴースト対応 オフィス・ゲーム用 コンパクトレイアウト USB Type-C接続 PS5/…",
    price: 3698,
    rating: 3.9,
    reviews: 78,
    image: "https://m.media-amazon.com/images/I/71xnaEzGT1L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F7H8629P",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gbs-p2-070",
    category: "keyboard",
    name: "Keychron C3 Pro カスタムゲーミングキーボード、コンパクトテンキーレスレイアウト/USレイアウト/赤色LEDバックライト/有…",
    brand: "Keychron",
    tagline: "Keychron C3 Pro カスタムゲーミングキーボード、コンパクトテンキーレスレイアウト/USレイアウト/赤色LEDバックライト/有線接続メカニカルキーボード/ガスケットマウント/Mac Windows Linux対応 (Keychron K Pro茶軸)",
    price: 28550,
    rating: 4.3,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/51Tlkrb1M3L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DBHY6SNP",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless","kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "719.5 グラム" }]}],
  },{
    id: "k-gbs-p2-072",
    category: "keyboard",
    name: "Merdia メカニカル式ゲーミングキーボード 全104キーボード USB 有線キーボード LEDバックライト付き (茶軸-ブルーとホワイト)",
    brand: "Merdia",
    tagline: "Merdia メカニカル式ゲーミングキーボード 全104キーボード USB 有線キーボード LEDバックライト付き (茶軸-ブルーとホワイト)",
    price: 4090,
    rating: 4.1,
    reviews: 127,
    image: "https://m.media-amazon.com/images/I/511hZRpQZ3L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BC8N9XHY",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1150 グラム" }]}],
  },
  {
    id: "k-gbs-p2-073",
    category: "keyboard",
    name: "iClever ゲーミングキーボード 75%サイズ 赤軸 メカニカル キーボード 日本語配列 マクロ対応 G05 ブラック",
    brand: "iClever",
    tagline: "iClever ゲーミングキーボード 75%サイズ 赤軸 メカニカル キーボード 日本語配列 マクロ対応 G05 ブラック",
    price: 5420,
    rating: 4.3,
    reviews: 226,
    image: "https://m.media-amazon.com/images/I/71LMR8tBYiL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CPLRF6GP",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "760 グラム" }]}],
  },
  {
    id: "k-gbs-p2-078",
    category: "keyboard",
    name: "DAREU COOL68 ゲーミングキーボード 0.01mm ラピッドトリガー対応 光翼ライトボックス 有線8000hzポーリングレート …",
    brand: "—",
    tagline: "DAREU COOL68 ゲーミングキーボード 0.01mm ラピッドトリガー対応 光翼ライトボックス 有線8000hzポーリングレート 磁気スイッチ SOCD対応 ホットスワップ 65%英語配列 テンキーレス 白/ブルー【1年間メーカー保証】",
    price: 10900,
    rating: 4.3,
    reviews: 99,
    image: "https://m.media-amazon.com/images/I/61U4BzuV51L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G6JZWRD3",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "65%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "730 グラム" }]}],
  },{
    id: "k-gbs-p2-080",
    category: "keyboard",
    name: "HUO JI ゲーミングキーボード 有線 テンキー付き 静音メンブレン メカニカル風打鍵感 RGBバックライト US配列 ホワイト",
    brand: "—",
    tagline: "HUO JI ゲーミングキーボード 有線 テンキー付き 静音メンブレン メカニカル風打鍵感 RGBバックライト US配列 ホワイト | 25キーロールオーバー（アンチゴースト）ゲーム用 オフィス用 人間工学 PC/PS4/PS5/Xbox対応",
    price: 3298,
    rating: 4,
    reviews: 416,
    image: "https://m.media-amazon.com/images/I/61eEZn3d2tL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCRYJPHF",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  }]
