import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングキーボード新着 2ページ目（2151972051 pg=2）#51–#80。 */
export const keyboardGamingNewReleasesPage2: Gadget[] = [
  {
    id: "k-gnr-p2-051",
    category: "keyboard",
    name: "XZILEX X68E",
    brand: "XZILEX",
    tagline: "0.005mmラピッドトリガー・8000Hz・68キー磁気スイッチ有線ゲーミングキーボード",
    price: 12980,
    rating: 4.6,
    reviews: 18,
    image: "https://m.media-amazon.com/images/I/71Pg-++tREL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H7JGLPD2",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "65％" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65％" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-052",
    category: "keyboard",
    name: "RK ROYAL KLUDGE RK84",
    brand: "RK ROYAL KLUDGE",
    tagline: "75%ホットスワップ対応RGB有線メカニカルゲーミングキーボード（US QWERTY）",
    price: 7499,
    rating: 4.1,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/61d-h7dpG4L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTYWXPZ6",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "1,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-053",
    category: "keyboard",
    name: "KizunaAI（キズナアイ） 限定コラボデザイン ゲーミングキーボード 日本語配列 有線接続 FUN60 KizunaAI Specia…",
    brand: "KizunaAI",
    tagline: "KizunaAI（キズナアイ） 限定コラボデザイン ゲーミングキーボード 日本語配列 有線接続 FUN60 KizunaAI Special Edition 描き下ろしデザイン 限定キーキャップ 専用箱 かわいいピンク 最大0.005mm ラピッドトリガー テンキーレス",
    price: 9980,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/71EbpyKkFIL._AC_SL1500_.jpg",
    connection: "有線 USB/Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G39189M1",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB/Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-gnr-p2-054",
    category: "keyboard",
    name: "センチュリー 「RACEN」磁気スイッチ式 日本語配列 テンキーレスゲーミングキーボード 色：ホワイト CRC-GKMGRT01WT2_F…",
    brand: "—",
    tagline: "センチュリー 「RACEN」磁気スイッチ式 日本語配列 テンキーレスゲーミングキーボード 色：ホワイト CRC-GKMGRT01WT2_FP ラピッドトリガー 国内サポート キートップ／スイッチリムーバー付き",
    price: 9900,
    rating: 3.4,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/61LbBZjqdoL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GSRDR1DR",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gnr-p2-055",
    category: "keyboard",
    name: "RK ROYAL KLUDGE RK920",
    brand: "RK ROYAL KLUDGE",
    tagline: "104キーフルサイズホットスワップRGB有線メカニカル（US QWERTY・PBT）",
    price: 11999,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/61ZNdHiRxXL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTV7RS88",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["kb-keycap-pbt"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "1,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-056",
    category: "keyboard",
    name: "片手マクロキーボード 3キー+ノブ",
    brand: "—",
    tagline: "USBミニキーパッド プログラム可能 3キー+押せるノブ 赤軸",
    price: 1423,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61lguqGsROL._AC_SL1500_.jpg",
    connection: "有線 USB",
    keyboardSpreadsheetFeatures: [],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3QRWLLV",
    keyboardUsage: "gaming",
        highlights: [
      { label: "レイアウト", value: "マクロパッド（3キー+ノブ）" },
      { label: "内部構造", value: "メカニカル（赤軸）" },
      { label: "キーキャップ", value: "—" },
      { label: "配列", value: "—" }],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "マクロパッド（3キー+ノブ）" },
          { label: "内部構造", value: "メカニカル（赤軸）" },
          { label: "キーキャップ", value: "—" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gnr-p2-058",
    category: "keyboard",
    name: "プログラマブル2キー ノブ付き",
    brand: "—",
    tagline: "ホットスワップ青軸 2キー+ノブ カスタムマクロ対応",
    price: 1455,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/81acCeJfGJL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3BVSHSB",
    keyboardUsage: "gaming",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gnr-p2-059",
    category: "keyboard",
    name: "GravaStar Mercury V75",
    brand: "GravaStar",
    tagline: "0.005mmラピッドトリガー・8000Hz 75%磁気スイッチ有線（クリアブラック）",
    price: 26980,
    rating: 4.8,
    reviews: 20,
    image: "https://m.media-amazon.com/images/I/71AqpDidLvL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6WGQQV8",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-060",
    category: "keyboard",
    name: "Logicool G G512 X 98",
    brand: "Logicool G",
    tagline: "8000Hzラピッドトリガー・ホットスワップ 98キー磁気式（G512X-98-LNWHd）",
    price: 13970,
    rating: 4.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/81WPnp9thsL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVYPKVHV",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "磁気スイッチ（ウルトラファストライム）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "磁気スイッチ（ウルトラファストライム）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-061",
    category: "keyboard",
    name: "Logicool G 8000Hz ラピッドトリガー ホットスワップ G512 X 98 ゲーミングキーボード リニア ガスケットマウント…",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G 8000Hz ラピッドトリガー ホットスワップ G512 X 98 ゲーミングキーボード リニア ガスケットマウント 日本語配列 G512X-98-LNWHd アクチュエーションポイント 調整可能 有線 磁気式アナログ…",
    price: 32800,
    rating: 3.7,
    reviews: 22,
    image: "https://m.media-amazon.com/images/I/61+EWfuK07L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJ8S81TB",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "98％" },
      { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "98％" },
          { label: "内部構造", value: "磁気スイッチ（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-062",
    category: "keyboard",
    name: "Razer Huntsman V3 Pro JP",
    brand: "Razer",
    tagline: "調整可能アクチュエーション搭載アナログ ラピッドトリガー フルサイズ（JIS）",
    price: 30218,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71k+10lN3ML._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYS8XGGS",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-063",
    category: "keyboard",
    name: "Razer(レイザー) ラピッドトリガー 搭載 Huntsman V3 Pro JP 調整可能なアクチュエーション搭載のアナログ ゲーミン…",
    brand: "Razer",
    tagline: "Razer(レイザー) ラピッドトリガー 搭載 Huntsman V3 Pro JP 調整可能なアクチュエーション搭載のアナログ ゲーミングキーボード オプティカルスイッチ 押下圧 40G リストレスト付属 日本語配列 ハンツマンブイスリープロ ジェイピー【日本正規代理店保証品】",
    price: 36980,
    rating: 4,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/71j9o9powXL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GL71RMDH",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "オプティカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "オプティカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "880 グラム" }]}],
  },
  {
    id: "k-gnr-p2-064",
    category: "keyboard",
    name: "TURTLE BEACH Command Series KB7",
    brand: "Turtle Beach",
    tagline: "Command Series 有線TKLゲーミングキーボード（US英語配列）",
    price: 29800,
    rating: 2.8,
    reviews: 36,
    image: "https://m.media-amazon.com/images/I/71B1-t4xuRL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWD2D7S3",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gnr-p2-065",
    category: "keyboard",
    name: "EPOMAKER TH80 V2 PRO ワイヤレスゲーミングキーボード 画面＆ノブ付き10000mAh 2.4GHz/BT/USB-C RGB",
    brand: "EPOMAKER",
    tagline: "EPOMAKER TH80 V2 PRO ワイヤレスゲーミングキーボード 画面＆ノブ付き10000mAh 2.4GHz/BT/USB-C RGB | ホットスワップ カスタムドライバー NKRO PBTキーキャップ PC/Mac用メカニカルキーボード (Black, Cre…",
    price: 11600,
    rating: 4.6,
    reviews: 78,
    image: "https://m.media-amazon.com/images/I/71Eylvf-QtL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GL8558SZ",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
    {
    id: "k-gnr-p2-067",
    category: "keyboard",
    name: "ASUS ROG Strix Morph 96 Wireless Gaming Keyboard ブラック / 96%レイアウトゲーミング…",
    brand: "—",
    tagline: "【Amazon.co.jp限定】ASUS ROG Strix Morph 96 Wireless Gaming Keyboard ブラック / 96%レイアウトゲーミングキーボード/日本語配列/メカニカルスイッチ/スピードタップモード/ホットスワップ対応/エルゴノミクス/ト…",
    price: 26096,
    rating: 4.6,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/71hwRpbbgqL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H28JZ135",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth / 有線 USB（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gnr-p2-068",
    category: "keyboard",
    name: "KiiBOOM Phantom98 Lite 96% ワイヤレス ゲーミングキーボード VIAプログラマブル対応 クリーミーガスケット構造…",
    brand: "—",
    tagline: "KiiBOOM Phantom98 Lite 96% ワイヤレス ゲーミングキーボード VIAプログラマブル対応 クリーミーガスケット構造 かわいいキーボード 8000mAhバッテリー メカニカルキーボード NKRO ホットスワップ対応 RGBバックライト付き Window…",
    price: 19450,
    rating: 4.8,
    reviews: 90,
    image: "https://m.media-amazon.com/images/I/61r4BTsQJKL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCFHZC7S",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket"],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PC（ポリカーボネート / 半透明）" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth / 有線 USB-C（充電式（内蔵バッテリー））" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1.9 キログラム" }]}],
  },
  {
    id: "k-gnr-p2-069",
    category: "keyboard",
    name: "EPOMAKER HE108 ラピトリ ホール効果ゲーミングキーボード 8Kポーリング＆128Kスキャン SOCD &amp; DKS ホ…",
    brand: "EPOMAKER",
    tagline: "EPOMAKER HE108 ラピトリ ホール効果ゲーミングキーボード 8Kポーリング＆128Kスキャン SOCD &amp; DKS ホットスワップ対応 | 2.4GHz/BT/USB有線 108キーフルサイズ 0.005mmアクチュエーションポイント 調整可能 高速トリ…",
    price: 16800,
    rating: 4.6,
    reviews: 24,
    image: "https://m.media-amazon.com/images/I/61sZX0uUe0L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GLYNHB9L",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ（108キー）" },
      { label: "内部構造", value: "メカニカル（ガスケット" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ（108キー）" },
          { label: "内部構造", value: "メカニカル（ガスケット" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-070",
    category: "keyboard",
    name: "DAREU FLEX75 ゲーミングキーボード 無線 ガスケット メカニカルキーボード 75% テンキーレス 英語配列 2.4Gワイヤレス…",
    brand: "—",
    tagline: "DAREU FLEX75 ゲーミングキーボード 無線 ガスケット メカニカルキーボード 75% テンキーレス 英語配列 2.4Gワイヤレス/Bluetooth/有線USB接続可能 ホットスワップ対応 音量調節ノブ付き 赤兎軸（リニア類赤軸） 白/ホワイト 技適認証取得【1年…",
    price: 8960,
    rating: 4.6,
    reviews: 45,
    image: "https://m.media-amazon.com/images/I/61ja-kbcERL._AC_SL1500_.jpg",
    connection: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYVHJ5R2",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / 2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（充電式（内蔵バッテリー））" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "882 グラム" }]}],
  },
  {
    id: "k-gnr-p2-071",
    category: "keyboard",
    name: "REALFORCE × 猫麦とろろ GX1 Plus Keyboard 45g 日本語配列 ブラック 2色成形 昇華印刷 静電容量無接点方…",
    brand: "REALFORSE",
    tagline: "REALFORCE × 猫麦とろろ GX1 Plus Keyboard 45g 日本語配列 ブラック 2色成形 昇華印刷 静電容量無接点方式 ラピッドトリガー 8000Hz 最速0.1mm作動 PBT リアルフォース 日本製 かな無し アクリルスタンド同梱 X1PCT1",
    price: 47800,
    rating: 4.9,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/61d7SbgWItL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GNMGY3V7",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    hasRapidTrigger: true,
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt"],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "静電容量無接点方式" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "静電容量無接点方式" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-072",
    category: "keyboard",
    name: "CORSAIR GALLEON 100 SD有線メカニカルキーボード日本語配列 – 黒 CH-912A31I-JP",
    brand: "CORSAIR",
    tagline: "CORSAIR GALLEON 100 SD有線メカニカルキーボード日本語配列 – 黒 CH-912A31I-JP | Elgato Stream Deckの統合、潤滑済みホットスワップ可能なMLXパルス・トッキー・キースイッチ、PBTキーキャップ、Flash…",
    price: 47146,
    rating: 4.2,
    reviews: 17,
    image: "https://m.media-amazon.com/images/I/71aydEKxr3L._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G4N4K5W5",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-keycap-pbt"],
    isKeyboardAccessory: false,
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "1,000 Hz" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1610 グラム" }]}],
  },{
    id: "k-gnr-p2-074",
    category: "keyboard",
    name: "YUNZII WOOD84",
    brand: "YUNZII",
    tagline: "NuPhy Node100 ワイヤレス メカニカルキーボード ロープロファイル 日本語配列 (JIS) フルサイズ 114キー Bluetooth/2.4GHz/USB-C トライモード接続 ホットスワップ対応 RGBバックライト PBTキーキャップ タッチジェスチャー ゲーミング (Ink Gray, Blush Nano)",
    price: 24420,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/717CnPEVyRL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3VF5MMT",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー)（充電式（内蔵バッテリー））" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "788 グラム" }]}],
  },
  {
    id: "k-gnr-p2-075",
    category: "keyboard",
    name: "YUNZII WOOD84 ワイヤレスメカニカルキーボード 75%レイアウト 木製 ゲーミングキーボード BT/2.4G/USB-C 3モ…",
    brand: "YUNZII",
    tagline: "YUNZII WOOD84 ワイヤレスメカニカルキーボード 75%レイアウト 木製 ゲーミングキーボード BT/2.4G/USB-C 3モード RGBバックライト トレイマウント構造 ホットスワップ対応 カスタムキーボード PBT昇華印刷キーキャップ Mac/Windows…",
    price: 15553,
    rating: 4.5,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/71gylzY7HKL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTLFFPR5",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["tenkeyless"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "有線給電/充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー)（充電式（内蔵バッテリー））" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.9 キログラム" }]}],
  },
  {
    id: "k-gnr-p2-076",
    category: "keyboard",
    name: "YUNZII C98",
    brand: "YUNZII",
    tagline: "98キー 透明Maoキャップ BT5.0/2.4G/USB-C ホットスワップ",
    price: 16342,
    rating: 4.9,
    reviews: 37,
    image: "https://m.media-amazon.com/images/I/71s09r80FkL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H26J5W2T",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "2.4GHz (USBレシーバー) / Bluetooth（充電式（内蔵バッテリー））" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "1.33 キログラム" }]}],
  },
  {
    id: "k-gnr-p2-077",
    category: "keyboard",
    name: "Womier M98",
    brand: "Womier",
    tagline: "96%ワイヤレス ガスケット 画面+ノブ付き テンキー付き",
    price: 12599,
    rating: 4.1,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/61Tus64Vq8L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZZCKP9J",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
    keyboardFilterTags: ["kb-structure-gasket","kb-keycap-abs"],
        highlights: [
      { label: "レイアウト", value: "96%" },
      { label: "内部構造", value: "メカニカル（ガスケット）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "96%" },
          { label: "内部構造", value: "メカニカル（ガスケット）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth / 有線 USB（充電式（内蔵バッテリー））" }]}],
  },
  {
    id: "k-gnr-p2-078",
    category: "keyboard",
    name: "EverGlide AE68 Pro Black Translucent ラピッドトリガーキーボード",
    brand: "—",
    tagline: "【日本正規代理店】EverGlide AE68 Pro Black Translucent ラピッドトリガーキーボード",
    price: 8909,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71sOilLySiL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS1ZKBJV",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "65％" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "65％" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-gnr-p2-079",
    category: "keyboard",
    name: "XEANIXIE OU108",
    brand: "XEANIXIE",
    tagline: "108キー JIS青軸 フルサイズ 有線 LEDバックライト ホットスワップ",
    price: 6999,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61VNYkMItTL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2LTK7QQ",
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（青軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（青軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "1,000 Hz" }]}],
  },
  {
    id: "k-gnr-p2-080",
    category: "keyboard",
    name: "AJAZZ AK820V2",
    brand: "AJAZZ",
    tagline: "75% Hall Effect 0.001mm RT 8K 磁気スイッチ",
    price: 9380,
    rating: 4.5,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/61GKkOknndL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H1ZNBCR4",
    keyboardUsage: "gaming",
    keyboardFilterTags: ["tenkeyless","rapid-trigger"],
    hasRapidTrigger: true,
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "8000Hz",
    keyboardSpreadsheetRapidTrigger: true,
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "磁気スイッチ" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "8000Hz" },
          { label: "ラピッドトリガー", value: "ラピッドトリガー" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "磁気スイッチ" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "ポーリングレート", value: "8,000 Hz" }]}],
  }]
