import type { Gadget } from "./gadgets"

/** Amazon.co.jp パソコン用キーボード売れ筋 2ページ目（2151977051 pg=2）#51–#100。 */
export const keyboardBestsellersPage2: Gadget[] = [
  {
    id: "k-bs-p2-051",
    category: "keyboard",
    name: "PFU キーボード HHKB Professional HYBRID Type-S 日本語配列／墨",
    brand: "PFU",
    tagline: "PFU キーボード HHKB Professional HYBRID Type-S 日本語配列／墨",
    price: 36850,
    rating: 4.6,
    reviews: 832,
    image: "https://m.media-amazon.com/images/I/51DplchTEKL._AC_SL1500_.jpg",
    connection: "Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B082TSZ27D",
    keyboardFilterTags: ["tenkeyless","kb-keycap-pbt-double"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "静電容量無接点方式（Type-S 静音）" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "静電容量無接点方式（Type-S 静音）" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth / 有線 USB" },
          { label: "電源", value: "単3形乾電池×2本" },
          { label: "主な機能", value: "USB Type-C（有線給電 / 単3形乾電池×2本）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "550 グラム" }]}],
  },
  {
    id: "k-bs-p2-052",
    category: "keyboard",
    name: "エレコム キーボード 有線 メンブレン 1000万回高耐久 ブラック TK-FCM062BK",
    brand: "ELECOM",
    tagline: "エレコム キーボード 有線 メンブレン 1000万回高耐久 ブラック TK-FCM062BK",
    price: 1231,
    rating: 4.2,
    reviews: 1016,
    image: "https://m.media-amazon.com/images/I/61C-lB5diYL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00FIYCYCU",
    keyboardFilterTags: ["kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.6 キログラム" }]}],
  },
  {
    id: "k-bs-p2-053",
    category: "keyboard",
    name: "ロジクール WAVE KEYS K820 疲れにくい エルゴノミックキーボード Bluetooth Logi Bolt 日本語配列 ワイヤ…",
    brand: "Logicool",
    tagline: "ロジクール WAVE KEYS K820 疲れにくい エルゴノミックキーボード Bluetooth Logi Bolt 日本語配列 ワイヤレスキーボード ワイヤレス 無線 テンキー パームレスト Windows Mac Chrome Android グラファイト 国内正規品",
    price: 10300,
    rating: 4.2,
    reviews: 229,
    image: "https://m.media-amazon.com/images/I/71tKrOo4uDL._AC_SL1500_.jpg",
    connection: "2.4GHz (Logi Bolt) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CKDJRHW7",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (Logi Bolt) / Bluetooth" },
          { label: "電源", value: "単4形乾電池×2本" },
          { label: "主な機能", value: "Bluetooth（単3形乾電池×2本）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "750 グラム" }]}],
  },
  {
    id: "k-bs-p2-055",
    category: "keyboard",
    name: "エレコム ワイヤレス キーボード 無線 メンブレン式 コンパクト Caps Lock機能無効化スイッチ搭載 500万回高耐久キー採用 抗菌…",
    brand: "ELECOM",
    tagline: "エレコム ワイヤレス キーボード 無線 メンブレン式 コンパクト Caps Lock機能無効化スイッチ搭載 500万回高耐久キー採用 抗菌 Windows 11/10 対応 ブラック TK-CM10DMKBK",
    price: 2300,
    rating: 4,
    reviews: 51,
    image: "https://m.media-amazon.com/images/I/61fAhPp4SaL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CSD6L32Q",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "単3形乾電池×1本" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.49 キログラム" }]}],
  },
  {
    id: "k-bs-p2-056",
    category: "keyboard",
    name: "バッファロー キーボード 有線 USB接続 ホワイト BSKBU14WH",
    brand: "Buffalo",
    tagline: "バッファロー キーボード 有線 USB接続 ホワイト BSKBU14WH",
    price: 1745,
    rating: 4,
    reviews: 1550,
    image: "https://m.media-amazon.com/images/I/610PPcN-tqL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B010M21V6W",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "テンキーレス（コンパクト）" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "テンキーレス（コンパクト）" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "0.4 キログラム" }]}],
  },
  {
    id: "k-bs-p2-058",
    category: "keyboard",
    name: "Ewin ワイヤレス キーボード bluetooth 折り畳み JIS標準日本語配列 タッチパッド搭載 ipad/iphone キーボード…",
    brand: "Ewin",
    tagline: "Ewin ワイヤレス キーボード bluetooth 折り畳み JIS標準日本語配列 タッチパッド搭載 ipad/iphone キーボード 三台同時切替 iOS/Android/Mac/Windows/Google対応 フルサイズ パソコン タブレット スマホ マルチペリン…",
    price: 6480,
    rating: 4.2,
    reviews: 461,
    image: "https://m.media-amazon.com/images/I/61bZR2jX+nL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C53QFZ98",
    keyboardFilterTags: ["kb-structure-scissor"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth" },
          { label: "電源", value: "充電式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "240 グラム" }]}],
  },
  {
    id: "k-bs-p2-059",
    category: "keyboard",
    name: "Perixx(ペリックス) PERIBOARD-106MJP キーボード 有線 パフォーマンス USB フルキー テンキー付き 最大100…",
    brand: "—",
    tagline: "Perixx(ペリックス) PERIBOARD-106MJP キーボード 有線 パフォーマンス USB フルキー テンキー付き 最大1000万回のキーストローク ヴィンテージカラー【正規保証品】JIS配列準拠 (日本語・ベージュ)",
    price: 4999,
    rating: 4.3,
    reviews: 673,
    image: "https://m.media-amazon.com/images/I/611CwpuixAL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08ZYQHLMT",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-bs-p2-060",
    category: "keyboard",
    name: "iClever ワイヤレスキーボード テンキー付き フルサイズ Bluetooth・2.4GHz JIS配列 Type-C充電 DK03 白",
    brand: "iClever",
    tagline: "iClever ワイヤレスキーボード テンキー付き フルサイズ Bluetooth・2.4GHz JIS配列 Type-C充電 DK03 白 | 薄型・軽量設計 静音 ノートPCのような快適な打鍵感 最大3台マルチペアリング",
    price: 4799,
    rating: 4.1,
    reviews: 107,
    image: "https://m.media-amazon.com/images/I/61X92bQI16L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FPD1ZY3J",
    keyboardFilterTags: ["kb-structure-scissor"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ（JIS日本語配列）" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ（JIS日本語配列）" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "447 グラム" }]}],
  },
  {
    id: "k-bs-p2-061",
    category: "keyboard",
    name: "Arteck 2.4Gワイヤレスキーボード 無線 軽量 コンパクトメディア機能 ホットキー ショートカット コンピューター、デスクトップ、…",
    brand: "—",
    tagline: "Arteck 2.4Gワイヤレスキーボード 無線 軽量 コンパクトメディア機能 ホットキー ショートカット コンピューター、デスクトップ、PC、ラップトップ、Surface、スマートテレビ、Windows11/10/8/7との交換性あり、黒",
    price: 2599,
    rating: 4,
    reviews: 5031,
    image: "https://m.media-amazon.com/images/I/61LOPnUvBkL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09WDJNBT1",
    keyboardFilterTags: ["tenkeyless","kb-structure-scissor"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "単4乾電池" }]}],
  },
  {
    id: "k-bs-p2-062",
    category: "keyboard",
    name: "エレコム ワイヤレスキーボード Bluetooth 子供用 パソコン学習 プログラミング KEY PALETTO キーパレット 大阪電気通…",
    brand: "ELECOM",
    tagline: "エレコム ワイヤレスキーボード Bluetooth 子供用 パソコン学習 プログラミング KEY PALETTO キーパレット 大阪電気通信大学 兼宗進副学長監修 iPadOS iOS用 抗菌 よみがなシール付 ブラック TK-FS10BMKIBK",
    price: 3100,
    rating: 4.2,
    reviews: 106,
    image: "https://m.media-amazon.com/images/I/61vfZid5Y-L._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C3QZ7P2P",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth" },
          { label: "電源", value: "単3形乾電池×1本" }]}],
  },
  {
    id: "k-bs-p2-064",
    category: "keyboard",
    name: "ロジクール KX850CT MX MECHANICAL MINI ミニマリスト ワイヤレス メカニカル パフォーマンス キーボード 茶軸 …",
    brand: "Logicool",
    tagline: "ロジクール KX850CT MX MECHANICAL MINI ミニマリスト ワイヤレス メカニカル パフォーマンス キーボード 茶軸 タクタイル テンキーレス 静かな打鍵感 特に静か Logi Bolt bluetooth Unifying非対応 薄型 無線 メカニカル…",
    price: 13109,
    rating: 4.2,
    reviews: 209,
    image: "https://m.media-amazon.com/images/I/617XT98wzkL._AC_SL1500_.jpg",
    connection: "2.4GHz (Logi Bolt) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B1Q5T5TQ",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "gaming",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (Logi Bolt) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "612 グラム" }]}],
  },
  {
    id: "k-bs-p2-065",
    category: "keyboard",
    name: "REALFORCE R3S キーボード 有線 フル 45g 日本語配列 ブラック R3SA11",
    brand: "REALFORSE",
    tagline: "REALFORCE R3S キーボード 有線 フル 45g 日本語配列 ブラック R3SA11",
    price: 26620,
    rating: 4.6,
    reviews: 140,
    image: "https://m.media-amazon.com/images/I/61cvQkW4FoL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B3QHNY7F",
    keyboardFilterTags: ["kb-keycap-pbt"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "静電容量無接点方式" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "静電容量無接点方式" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-bs-p2-066",
    category: "keyboard",
    name: "Arteck 2.4G ワイヤレスキーボード 日本語配列無線ステンレススチール 軽量 フルサイズキーボード コンピューター、デスクトップ、…",
    brand: "—",
    tagline: "Arteck 2.4G ワイヤレスキーボード 日本語配列無線ステンレススチール 軽量 フルサイズキーボード コンピューター、デスクトップ、PC、ラップトップ、Surface、スマートテレビ、Windows10/8/7、Vista、XPとの交換性あり 充電式電池内蔵",
    price: 2930,
    rating: 4.2,
    reviews: 8635,
    image: "https://m.media-amazon.com/images/I/61sV03P3d3L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B073TSKFRX",
    keyboardFilterTags: ["kb-structure-scissor","kb-keycap-low-profile"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ（JIS日本語配列）" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ（JIS日本語配列）" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "10.75 オンス" }]}],
  },
  {
    id: "k-bs-p2-068",
    category: "keyboard",
    name: "ロジクール KX850MSG MX MECHANICAL MINI for Mac ミニマリスト ワイヤレス メカニカル パフォーマンス …",
    brand: "Logicool",
    tagline: "ロジクール KX850MSG MX MECHANICAL MINI for Mac ミニマリスト ワイヤレス メカニカル パフォーマンス キーボード US配列 茶軸 タクタイル テンキーレス 静かな打鍵感 Logi Bolt bluetooth USB-C-C 充電式 薄型…",
    price: 13109,
    rating: 4.4,
    reviews: 110,
    image: "https://m.media-amazon.com/images/I/611rA+qb69L._AC_SL1500_.jpg",
    connection: "2.4GHz (Logi Bolt) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BG4ZW7VM",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "gaming",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (Logi Bolt) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "612 グラム" }]}],
  },
  {
    id: "k-bs-p2-069",
    category: "keyboard",
    name: "REALFORCE R4 キーボード ハイブリッド フル 45g 日本語配列 ブラック R4HA11",
    brand: "REALFORSE",
    tagline: "REALFORCE R4 キーボード ハイブリッド フル 45g 日本語配列 ブラック R4HA11",
    price: 39820,
    rating: 4.7,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/51pH1uT2xjL._AC_SL1500_.jpg",
    connection: "有線 USB / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FNR6SLDV",
    keyboardFilterTags: ["kb-keycap-pbt"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "静電容量無接点方式" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "静電容量無接点方式" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB / Bluetooth" },
          { label: "電源", value: "単3形乾電池×2本/有線給電" },
          { label: "主な機能", value: "Bluetooth（有線給電 / 単3形乾電池×2本）" }]}],
  },
  {
    id: "k-bs-p2-070",
    category: "keyboard",
    name: "Ewin アンドロイド専用 折りたたみ式 Bluetooth5.1 キーボード 日本語配列 Android/Windows/Macに対応 …",
    brand: "Ewin",
    tagline: "Ewin アンドロイド専用 折りたたみ式 Bluetooth5.1 キーボード 日本語配列 Android/Windows/Macに対応 タブレット/マートフォン/パソコン用 ノートPCに対応 ポータブルキーボード スタンド付",
    price: 3344,
    rating: 3.9,
    reviews: 470,
    image: "https://m.media-amazon.com/images/I/71x4U1-ZMvL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CLD5BMLS",
    keyboardFilterTags: ["kb-structure-scissor"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "折りたたみ" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "折りたたみ" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-bs-p2-071",
    category: "keyboard",
    name: "ロジクール ワイヤレスキーボード タッチ キーボード K400pBK",
    brand: "Logicool",
    tagline: "ロジクール ワイヤレスキーボード タッチ キーボード K400pBK 国内正規品",
    price: 5100,
    rating: 3.9,
    reviews: 681,
    image: "https://m.media-amazon.com/images/I/514iRLEnfzL._AC_SL1500_.jpg",
    connection: "2.4GHz",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00ZQNBTQK",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: ["タッチパッド"],
        highlights: [
      { label: "レイアウト", value: "75％" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" },
          { label: "特徴", value: "タッチパッド" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75％" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz" },
          { label: "電源", value: "単3形乾電池×2本" }]}],
  },
  {
    id: "k-bs-p2-072",
    category: "keyboard",
    name: "ロジクール SIGNATURE K650GR ワイヤレス キーボード パームレスト 薄型 疲れにくい bluetooth Logi Bol…",
    brand: "Logicool",
    tagline: "ロジクール SIGNATURE K650GR ワイヤレス キーボード パームレスト 薄型 疲れにくい bluetooth Logi Bolt Unifying非対応 日本語配列 windows mac chrome Android 無線 ワイヤレスキーボード K650 グラ…",
    price: 5781,
    rating: 3.8,
    reviews: 143,
    image: "https://m.media-amazon.com/images/I/61pFsBDxGrL._AC_SL1500_.jpg",
    connection: "2.4GHz (Logi Bolt) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B86TRNNF",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (Logi Bolt) / Bluetooth" },
          { label: "電源", value: "単3形乾電池×2本" },
          { label: "主な機能", value: "Bluetooth（単3形乾電池×2本）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "700.23 グラム" }]}],
  },
  {
    id: "k-bs-p2-073",
    category: "keyboard",
    name: "Nillkin 【公式直営店】キーボード Bluetooth 折りたたみ式 ワイヤレス ipad キーボード ipad mini 薄型 軽…",
    brand: "—",
    tagline: "【2026年最新型】Nillkin 【公式直営店】キーボード Bluetooth 折りたたみ式 ワイヤレス ipad キーボード ipad mini 薄型 軽量 3台同時接続 テンキー＆ タッチパッド搭載 Type-C充電式 トラックパッド マルチペアリング iOS/And…",
    price: 9499,
    rating: 3.2,
    reviews: 503,
    image: "https://m.media-amazon.com/images/I/71SSV5gUe8L._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FDGGXFZZ",
    keyboardFilterTags: ["kb-structure-scissor","kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "折りたたみ" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "折りたたみ" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-bs-p2-074",
    category: "keyboard",
    name: "Omikamo キーボード bluetooth 折り畳み式 ワイヤレス JIS標準日本語配列 ipad用キーボード スマホ マルチペアリング",
    brand: "Omikamo",
    tagline: "【最新型】Omikamo キーボード bluetooth 折り畳み式 ワイヤレス JIS標準日本語配列 ipad用キーボード スマホ マルチペアリング | ipad mini キーボード タッチパッド付き ipad/iphone キーボードiOS/Windows/Andro…",
    price: 6980,
    rating: 3.4,
    reviews: 115,
    image: "https://m.media-amazon.com/images/I/6192RiwAP4L._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F374DNL4",
    keyboardFilterTags: ["kb-structure-scissor"],
    keyboardUsage: "productivity",
        highlights: [
      { label: "レイアウト", value: "折りたたみ（JIS日本語配列）" },
      { label: "内部構造", value: "メカニカル（パンタグラフ / シザースイッチ）" },
      { label: "キーキャップ", value: "—" },
      { label: "電源", value: "充電式（内蔵バッテリー）" }],
    compat: [],
    specGroups: [
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "折りたたみ（JIS日本語配列）" },
          { label: "内部構造", value: "パンタグラフ（シザースイッチ）" },
          { label: "キーキャップ", value: "—" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "充電式（内蔵バッテリー）" }]}],
  },
    {
    id: "k-bs-p2-078",
    category: "keyboard",
    name: "ロジクール ワイヤレスキーボード K780 Bluetooth Unifying ワイヤレス 無線 キーボード windows mac C…",
    brand: "Logicool",
    tagline: "ロジクール ワイヤレスキーボード K780 Bluetooth Unifying ワイヤレス 無線 キーボード windows mac Chrome iOS Android 国内正規品",
    price: 8273,
    rating: 4.2,
    reviews: 1998,
    image: "https://m.media-amazon.com/images/I/51yeYmaygaL._AC_SL1500_.jpg",
    connection: "2.4GHz",
    purchaseUrl: "https://www.amazon.co.jp/dp/B01H2VY13G",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz" },
          { label: "電源", value: "単4形乾電池×2本" },
          { label: "主な機能", value: "Bluetooth（単3形乾電池×2本）" }]}],
  },
  {
    id: "k-bs-p2-079",
    category: "keyboard",
    name: "HP ワイヤレス キーボード 英字配列 HP 230 ブラック",
    brand: "—",
    tagline: "HP ワイヤレス キーボード 英字配列 HP 230 ブラック | フルサイズ テンキー US配列 静音 薄型 最大16ヶ月のロングバッテリー Windows Mac 無線 2.4GHz USBドングル (3L1E7AA#UUF) 国内正規品",
    price: 2950,
    rating: 3.8,
    reviews: 1057,
    image: "https://m.media-amazon.com/images/I/6115ax4YVVL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09GBC1H4Z",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "単4形乾電池×2本" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "495 グラム" }]}],
  }]
