import type { Gadget } from "./gadgets"

/** Amazon.co.jp パソコン用キーボード新着（2151977051 new-releases）。 */
export const keyboardNewReleases: Gadget[] = [
  {
    id: "k-nr-001",
    category: "keyboard",
    name: "Ewin 折りたたみ Bluetoothキーボード 日本語配列 タッチパッド テンキ付き 3台切替対応 タイプc iPad タブレット i…",
    brand: "Ewin",
    tagline: "Ewin 折りたたみ Bluetoothキーボード 日本語配列 タッチパッド テンキ付き 3台切替対応 タイプc iPad タブレット iOS/Windows/Mac対応 フルサイズ EW-NKB303",
    price: 7280,
    rating: 4.5,
    reviews: 40,
    image: "https://m.media-amazon.com/images/I/61NDUzgcFAL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3NG2P8C",
    keyboardFilterTags: ["kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "折りたたみ" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "折りたたみ" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-nr-002",
    category: "keyboard",
    name: "2.4GHzワイヤレス日本語キーボード 7色バックライト 108キー フルサイズ",
    brand: "—",
    tagline: "2.4GHzワイヤレス日本語キーボード 7色バックライト 108キー フルサイズ",
    price: 3999,
    rating: 4.1,
    reviews: 37,
    image: "https://m.media-amazon.com/images/I/61R4kjgwRDL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTRCXQSZ",
    keyboardFilterTags: ["kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-nr-003",
    category: "keyboard",
    name: "iClever ワイヤレスキーボード Bluetooth テンキー付き JIS日本語配列 2.4GHz 静音 DK20",
    brand: "iClever",
    tagline: "iClever ワイヤレスキーボード Bluetooth テンキー付き JIS日本語配列 2.4GHz 静音 DK20",
    price: 4699,
    rating: 4.4,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/61n9ZtKaUUL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTYMLBPF",
    keyboardFilterTags: ["kb-structure-scissor","kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "95％" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "95％" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]},
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "360 グラム" }]}],
  },
  {
    id: "k-nr-004",
    category: "keyboard",
    name: "iClever キーボード ワイヤレス Bluetooth 2.4GHz JIS日本語配列 デュアルモード マルチペアリング テンキー付き…",
    brand: "iClever",
    tagline: "iClever キーボード ワイヤレス Bluetooth 2.4GHz JIS日本語配列 デュアルモード マルチペアリング テンキー付き コンパクト 3台同時接続 充電式 Type-C 静音 薄型 軽量 無線 パンタグラフ式 PC iPad Windows/Mac/iOS…",
    price: 4599,
    rating: 4.4,
    reviews: 41,
    image: "https://m.media-amazon.com/images/I/616k6pAMwGL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GGHJV5VL",
    keyboardFilterTags: ["kb-structure-scissor","kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "90％" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "90％" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]}],
  },
  {
    id: "k-nr-005",
    category: "keyboard",
    name: "Ewin ERGO キーボード JIS配列 左右分離型 エルゴノミクス パームレスト Bluetooth 2.4G両対応 テンキー付き フ…",
    brand: "Ewin",
    tagline: "Ewin ERGO キーボード JIS配列 左右分離型 エルゴノミクス パームレスト Bluetooth 2.4G両対応 テンキー付き フルサイズ",
    price: 15980,
    rating: 3.9,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/71sgivywt5L._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth 5.0",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQ9JWXS1",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth 5.0" },
          { label: "電源", value: "単3形乾電池×1本" }]}],
  },
  {
    id: "k-nr-006",
    category: "keyboard",
    name: "HKW. タイプライター風キーボード 61キー 青軸 USB-C有線 メカニカルキーボード LEDバックライト 丸型キー Windows/…",
    brand: "—",
    tagline: "HKW. タイプライター風キーボード 61キー 青軸 USB-C有線 メカニカルキーボード LEDバックライト 丸型キー Windows/Mac対応 シルバー",
    price: 5980,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71dH9mORDUL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H545ZXP8",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル（青軸）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル（青軸）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-nr-007",
    category: "keyboard",
    name: "YIVU Sofle ワイヤレス 分割キーボード 左右分離 エルゴノミクス 静音メカニカルキーボード 2.4GHz無線 ホットスワップ Q…",
    brand: "—",
    tagline: "YIVU Sofle ワイヤレス 分割キーボード 左右分離 エルゴノミクス 静音メカニカルキーボード 2.4GHz無線 ホットスワップ QMK/VIAL対応 Mac/Windows対応",
    price: 20570,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61ssYh+wKfL._AC_SL1500_.jpg",
    connection: "2.4GHz / Bluetooth / 有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWQBLKHW",
    keyboardFilterTags: ["tenkeyless","kb-keycap-low-profile"],
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "80％" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "80％" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },{
    id: "k-nr-009",
    category: "keyboard",
    name: "YIVU 左右分離型メカニカルキーボード Borne 有線 エルゴノミクス 60%分割型キーボード ホットスワップ対応 QMK/VIAL対…",
    brand: "—",
    tagline: "YIVU 左右分離型メカニカルキーボード Borne 有線 エルゴノミクス 60%分割型キーボード ホットスワップ対応 QMK/VIAL対応 リニア軸 PBTキーキャップ ロータリーノブ搭載 プログラマブル RGBバックライト ブラック",
    price: 17999,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61w41x6iPTL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6CYWFW9",
    keyboardFilterTags: ["tenkeyless"],
    keyboardUsage: "gaming",
    keyboardSpreadsheetGaming: true,
    keyboardPollingRate: "1000Hz",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "60%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "PBT" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "ゲーミングキーボード", value: "ゲーミングキーボード" },
          { label: "ポーリングレート", value: "1000Hz" },
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "60%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "PBT" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-nr-011",
    category: "keyboard",
    name: "Perixx PERIBOARD-427 US、トラックボール付き有線バックライトUSBキーボード - 白色および赤色バックライト機能 -…",
    brand: "—",
    tagline: "Perixx PERIBOARD-427 US、トラックボール付き有線バックライトUSBキーボード - 白色および赤色バックライト機能 - コンパクトな28.4×18.2×2.8 cm寸法 - 内蔵USBハブ2基 - US英語",
    price: 7999,
    rating: 4.2,
    reviews: 28,
    image: "https://m.media-amazon.com/images/I/61FyjmcPTBL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWJXQKH8",
    keyboardFilterTags: ["tenkeyless","kb-structure-scissor","kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: ["トラックボール"],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" },
          { label: "特徴", value: "トラックボール" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-nr-012",
    category: "keyboard",
    name: "有線 US 配列キーボード レトロタイプライター風 円形キーキャップ バックライト付き 3 段階輝度調整 フルサイズ テンキー搭載 Win…",
    brand: "—",
    tagline: "有線 US 配列キーボード レトロタイプライター風 円形キーキャップ バックライト付き 3 段階輝度調整 フルサイズ テンキー搭載 Windows/ノート PC 対応 静音設計 オフィス/ゲーミング用 (Purple)",
    price: 3799,
    rating: 3.6,
    reviews: 11,
    image: "https://m.media-amazon.com/images/I/619EVRrhkSL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTYFMP45",
    keyboardUsage: "gaming",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "フルサイズ" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "フルサイズ" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "k-nr-013",
    category: "keyboard",
    name: "Acogedor 小型スマホ用キーボード、Bluetooth・有線接続対応、ノートPC・タブレット・スマホ用充電式キーボード、コンパクトサ…",
    brand: "—",
    tagline: "Acogedor 小型スマホ用キーボード、Bluetooth・有線接続対応、ノートPC・タブレット・スマホ用充電式キーボード、コンパクトサイズ、旅行に持ち運びやすい (バックライト付きブラック)",
    price: 2349,
    rating: 3,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61we7xzwpPL._AC_SL1500_.jpg",
    connection: "Bluetooth/有線",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXSLC6FN",
    keyboardFilterTags: ["tenkeyless","kb-keycap-abs"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "US英語配列",
    keyboardSpreadsheetFeatures: ["携帯型キーボード"],
        highlights: [
      { label: "レイアウト", value: "タブレット用" },
      { label: "内部構造", value: "メカニカル（メンブレン）" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "US英語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "US英語配列" },
          { label: "特徴", value: "携帯型キーボード" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "タブレット用" },
          { label: "内部構造", value: "メカニカル（メンブレン）" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "Bluetooth/有線" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "k-nr-014",
    category: "keyboard",
    name: "ワイヤレスキーボード（テンキーレス）",
    brand: "サンワサプライ",
    tagline: "サンワサプライ ワイヤレスキーボード Bluetooth・2.4GHz両対応 テンキーレス コンパクト パンタグラフ 日本語配列 85キー 充電式 3台切替対応 Windows Mac iPad iPhone Android ChromeOS対応 グ",
    price: 7980,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61sl7WmYA1L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H4QT1V6T",
    keyboardFilterTags: ["tenkeyless","kb-structure-scissor"],
    keyboardUsage: "productivity",
    keyboardLayoutArray: "JIS日本語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "パンタグラフ" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "JIS日本語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "JIS日本語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "パンタグラフ" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "主な機能", value: "Bluetooth（給電）" }]}],
  },
    {
    id: "k-nr-016",
    category: "keyboard",
    name: "SENECESLI 韓国語キーボード、78キーUSB有線超スリム軽量こぼれ防止人間工学に基づいたチルトデザイン、色あせ防止PCラップトップ…",
    brand: "—",
    tagline: "SENECESLI 韓国語キーボード、78キーUSB有線超スリム軽量こぼれ防止人間工学に基づいたチルトデザイン、色あせ防止PCラップトップデスクトホームオフィスタイピング用",
    price: 2308,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71wFdpwPUPL._AC_SL1500_.jpg",
    connection: "有線 USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYK62QS1",
    keyboardUsage: "productivity",
    keyboardLayoutArray: "韓国語配列",
    keyboardSpreadsheetFeatures: [],
        highlights: [
      { label: "レイアウト", value: "75%" },
      { label: "内部構造", value: "メカニカル" },
      { label: "キーキャップ", value: "ABS" },
      { label: "配列", value: "韓国語配列" }],
    compat: [],
    specGroups: [
      { title: "仕様 / 機能", rows: [
          { label: "配列", value: "韓国語配列" }]},
      { title: "キー / スイッチ", rows: [
          { label: "レイアウト", value: "75%" },
          { label: "内部構造", value: "メカニカル" },
          { label: "キーキャップ", value: "ABS" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方法", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  }]
