import type { Gadget } from "./gadgets"

/** Amazon.co.jp PC用マイク売れ筋 2ページ目（2152017051 pg=2 #51–#80）。マイク本体・会議用スピーカーフォン含む。 */
export const micBestsellersPage2: Gadget[] = [
  {
    id: "mic-bs2-051",
    category: "mic",
    name: "Luna Plus",
    brand: "EMEET",
    tagline: "ミニクリップマイク コンデンサーマイク 単一指向性 イヤホン端子付き 音声モニタリング可能 PC用マイク ネット通話 ゲーム実況 ライブ配信 録音 在宅勤務 会議用",
    price: 10999,
    rating: 4.4,
    reviews: 106,
    image: "https://m.media-amazon.com/images/I/817PlbYTUyL._AC_SL1500_.jpg",
    connection: "USB Type-A / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BZXZ91HR",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A / Bluetooth" },
      { label: "サンプルレート", value: "48KHｚ" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "48KHｚ" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / Bluetooth" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #51" }],
      }],
  },
    {
    id: "mic-bs2-054",
    category: "mic",
    name: "K053",
    brand: "FIFINE",
    tagline: "ミニクリップマイク コンデンサーマイク 単一指向性 イヤホン端子付き 音声モニタリング可能 PC用マイク ネット通話 ゲーム実況 ライブ配信 録音 在宅勤務 会議用",
    price: 2999,
    rating: 3.7,
    reviews: 643,
    image: "https://m.media-amazon.com/images/I/61vIelHXx1L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B077Y974JF",
    micFilterTags: ["pin","condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "Vlog・動画撮影（屋外）"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48KHｚ" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "48KHｚ" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "イヤホンジャック", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #54" }],
      }],
  },
  {
    id: "mic-bs2-055",
    category: "mic",
    name: "USB-Cミニマイク Mac mini M4/M4 Pro・MacBook対応 Plug&Play…",
    brand: "—",
    tagline: "Mac mini M4/M4 Pro・MacBook対応 Plug&Playコンパクトで持ち運びやすいコンデンサーマイク",
    price: 1769,
    rating: 4.2,
    reviews: 157,
    image: "https://m.media-amazon.com/images/I/51rsfXxK4cL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FP5534M6",
    micFilterTags: ["condenser"],
                                micUseTags: [],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "50Hz-15kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "50Hz-15kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #55" }],
      }],
  },
  {
    id: "mic-bs2-056",
    category: "mic",
    name: "Seiren V3 Mini White",
    brand: "Razer",
    tagline: "コンデンサーマイク ホワイト超コンパクト設計| タップ式ミュートセンサー| ゲーミングマイク| 配信用| 日本正規代理店保証品",
    price: 8381,
    rating: 4.3,
    reviews: 84,
    image: "https://m.media-amazon.com/images/I/61SOA8-WWJL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CWGS19RG",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                    micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "タップ式ミュートセンサー" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #56" }],
      }],
  },
  {
    id: "mic-bs2-057",
    category: "mic",
    name: "Luna",
    brand: "EMEET",
    tagline: "スピーカーフォン Bluetooth会議用マイクスピーカー ブラック 360˚全方向集音マイク付き 特許VoiceIA技術を搭載 ノイズキャンセリング 双方向通話 連結機能 5-8名対応 USB/AUX接続",
    price: 8999,
    rating: 4.3,
    reviews: 1962,
    image: "https://m.media-amazon.com/images/I/71W0UraF8WL._AC_SL1500_.jpg",
    connection: "USB Type-A / Bluetooth / AUX",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08F252YBK",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "-20kHz" },
      { label: "接続方式", value: "USB Type-A / Bluetooth / AUX" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / Bluetooth / AUX" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Bluetooth", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #57" }],
      }],
  },
  {
    id: "mic-bs2-059",
    category: "mic",
    name: "PowerConf S3",
    brand: "Anker",
    tagline: "【全指向性マイク搭載の主要会議ツールに対応したマイクスピーカー】 スピーカーフォン Bluetooth 24時間連続使用 グループモード対応 USB-C接続 オンライン会議 テレワーク 在宅 会議用システム ウェブ",
    price: null,
    rating: 4.4,
    reviews: 1953,
    image: "https://m.media-amazon.com/images/I/81ap1S-nOkL._AC_SL1500_.jpg",
    connection: "USB Type-C / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08B68LM7R",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / Bluetooth" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / Bluetooth" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "Bluetooth", value: "対応" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #59" }],
      }],
  },
  {
    id: "mic-bs2-060",
    category: "mic",
    name: "MM-MCU03BKN",
    brand: "サンワサプライ",
    tagline: "サンワサプライ MM-MCU03BKN USBマイクロホン",
    price: 3181,
    rating: 4.3,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/61MCbQ93-fL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BXSNMYG7",
    micFilterTags: ["condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "70Hz-15kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "70Hz-15kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #60" }],
      }],
  },
  {
    id: "mic-bs2-061",
    category: "mic",
    name: "PC USBマイク コンデンサーマイク 会議用 卓上 360°集音 フレキシブルアーム プラグ&プレイ",
    brand: "—",
    tagline: "会議用 卓上 マイクロホン マイクロフォン 360°集音 パソコン フレキシブルアーム式 全指向性 スポンジ付き PC MSN ZOOM Skype Webチャット ゲーム実況",
    price: 2998,
    rating: 3.9,
    reviews: 36,
    image: "https://m.media-amazon.com/images/I/51q206D8IzL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FRSR2SR8",
    micFilterTags: ["condenser","stand"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #61" }],
      }],
  },
  {
    id: "mic-bs2-062",
    category: "mic",
    name: "デスクトップマイク ピンマイク USB直挿し PCマイク 全指向性 フレキシブルアーム コンパクト",
    brand: "Freell",
    tagline: "デスクトップマイク ピンマイク USB 直差し 直挿し PCマイク 無指向性 フレキシブルアーム 軽量 コンパクト 小型マイク 外付けマイク",
    price: 980,
    rating: 3.9,
    reviews: 24,
    image: "https://m.media-amazon.com/images/I/41AWCSjtzML._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DM2GF8MW",
    micFilterTags: ["condenser","pin"],
                                micUseTags: ["Vlog・動画撮影（屋外）"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #62" }],
      }],
  },
  {
    id: "mic-bs2-063",
    category: "mic",
    name: "ワイヤレスピンマイク (2個セット)",
    brand: "BILIWAL",
    tagline: "2026新型】BILIWAL ピンマイク ワイヤレス iPhone/Android/PC用 自動ペアリング 接続ロック 瞬時接続 音画同期 超軽量 Type-C ノイズ軽減 ペアリングロック機能 リバーブ機能 9時間連続使用 360°集音 超ミニ クリップ式 2個セット Vlogカメラ対応 Vlog撮影/動画配信/生放送",
    price: 3980,
    rating: 4.2,
    reviews: 101,
    image: "https://m.media-amazon.com/images/I/81dkjmm3UkL._AC_SL1500_.jpg",
    connection: "USB Type-C / 2.4GHz ワイヤレス",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DYCR675L",
    micFilterTags: ["pin","wireless","condenser"],
                                micUseTags: ["Vlog・動画撮影（屋外）"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / 2.4GHz ワイヤレス" },
      { label: "サンプルレート", value: "48kHz/24bit" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / 2.4GHz ワイヤレス" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #63" }],
      }],
  },
  {
    id: "mic-bs2-067",
    category: "mic",
    name: "USBピンマイク 小型 全指向性 高感度 防風 録音 会議 カラオケ対応",
    brand: "—",
    tagline: "USB ピンマイク 小型全方向性マイクロフォン 高感度 防風 録音・会議・カラオケ・インタビュー・VLOG",
    price: 559,
    rating: 3,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61dLJAx0ioL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTVG1FBT",
    micFilterTags: ["condenser","pin"],
                                micUseTags: ["Web会議・オンライン授業・通話", "Vlog・動画撮影（屋外）"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #67" }],
      }],
  },
  {
    id: "mic-bs2-068",
    category: "mic",
    name: "HS-SP02M2BK",
    brand: "エレコム",
    tagline: "エレコム スピーカーフォン 会議用 USB接続 ノイズリダクション機能 エコーキャンセラー オートゲインコントロール対応 約350ml缶サイズ 無指向性マイク ブラック",
    price: 7454,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/51Ef-Vb-0qL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GFCJ96VP",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "エコーキャンセリング", value: "対応" },
          { label: "エコーキャンセラー", value: "対応" },
          { label: "ノイズリダクション", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #68" }],
      }],
  },
  {
    id: "mic-bs2-069",
    category: "mic",
    name: "MO-MIC04U-B",
    brand: "e-Better",
    tagline: "e-Better MO-MIC04U-B PCマイク USB ミュート機能 全指向性360° テレワーク",
    price: 1480,
    rating: 3.4,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/51NuGiMnhpL._AC_SL1500_.jpg",
    connection: "USB Type-A / 3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BXWPGFP9",
    micFilterTags: ["condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A / 3.5mm" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / 3.5mm" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #69" }],
      }],
  },
  {
    id: "mic-bs2-070",
    category: "mic",
    name: "USB-C グースネックマイク Type-C 卓上 マイク MacBook/iPhone/iPad対応",
    brand: "Cubilux",
    tagline: "サンワダイレクト 会議マイク 無指向性 USB接続 Zoom/Skype対応 直径5m集音 スピーカー接続可能 ミュート機能 薄型",
    price: 2690,
    rating: 3.1,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/61TWlriSNLL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F637C7JG",
    micFilterTags: ["condenser","stand"],
                                micUseTags: [],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "24bit / 96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "24bit / 96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #70" }],
      }],
  },
    {
    id: "mic-bs2-072",
    category: "mic",
    name: "ラベリアマイク USB-C コンデンサーマイク iPhone 16/15 & Android Ty…",
    brand: "—",
    tagline: "USB-C・USB-A対応 有線ピンマイク スマホ・PC用 2mケーブル 全指向性コンデンサーピンマイク，iPhone 17/16/15、Samsung、Google、OnePlus、PC対応，",
    price: 2499,
    rating: 3.9,
    reviews: 133,
    image: "https://m.media-amazon.com/images/I/61e83g3e0gL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DFGMHM4B",
    micFilterTags: ["condenser","pin"],
                                micUseTags: ["Vlog・動画撮影（屋外）"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "24bit / 96kHz" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "24bit / 96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #72" }],
      }],
  },
    {
    id: "mic-bs2-074",
    category: "mic",
    name: "PC USBマイク コンデンサーマイク 会議用 卓上 360°集音",
    brand: "Veetop",
    tagline: "Veetop PC USBマイク コンピュータ コンデンサーマイク 会議用 卓上 マイクロホン マイクロフォン 360°集音 パソコン フレキシブルアーム式 全指向性 スポンジ/LEDランプ付",
    price: 1680,
    rating: 3.7,
    reviews: 471,
    image: "https://m.media-amazon.com/images/I/51p1ts+pPpS._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08NDQ772P",
    micFilterTags: ["condenser","stand"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "24bit / 96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-16kHz" },
          { label: "サンプルレート", value: "24bit / 96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #74" }],
      }],
  },
    {
    id: "mic-bs2-077",
    category: "mic",
    name: "PC用USBマイク 単一指向性 ラベリアクリップ式ミニピンマイク USB-A 1.2m",
    brand: "Cubilux",
    tagline: "Cubilux PC用USBマイク 単一指向性 ラベリアクリップ式ミニピンマイク USB-A 1.2m",
    price: 1750,
    rating: 3.8,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/61DtRROWinL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F2DSX6BN",
    micFilterTags: ["condenser","pin"],
                                micUseTags: ["Web会議・オンライン授業・通話", "Vlog・動画撮影（屋外）"],
                                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "96kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "24bit / 96kHz" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "96kHz" },
          { label: "サンプルレート", value: "24bit / 96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #77" }],
      }],
  },
    {
    id: "mic-bs2-080",
    category: "mic",
    name: "400-MC011",
    brand: "サンワダイレクト",
    tagline: "サンワダイレクト 会議マイク 無指向性 USB接続 Zoom/Skype対応 直径5m集音 スピーカー接続可能 ミュート機能 薄型",
    price: 4980,
    rating: 3.8,
    reviews: 140,
    image: "https://m.media-amazon.com/images/I/61YHLQkQdFL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07XRHZSJC",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                    micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "ミュートボタン", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 2ページ目 #80" }],
      }],
  }
]
