import type { Gadget } from "./gadgets"

/** Amazon.co.jp PC用マイク検索（computers / 2127209051）。マイク本体・会議用スピーカーフォン含む。 */
export const micComputersSearch: Gadget[] = [{
    id: "mic-srch-0006",
    category: "mic",
    name: "Zyrvox PCマイク K6",
    brand: "エレコム",
    tagline: "Zyrvox PCマイク usb スタンド 高感度 USB 卓上 無・全指向性 パソコンマイク ワンタッチミュート プラグアンドプレイ 360˚全方向集音 小型 有線タイプ ゲーミング・テレワーク",
    price: 2599,
    rating: 4.1,
    reviews: 169,
    image: "https://m.media-amazon.com/images/I/61V3Wpk6rfL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTGLP2G5",
    micFilterTags: ["stand","condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "タッチミュート" },
          { label: "ポップガード", value: "付属" },
          { label: "Amazon検索", value: "PC用マイク #6" }],
      }],
  },
      {
    id: "mic-srch-0009",
    category: "mic",
    name: "DuoCast",
    brand: "HyperX",
    tagline: "USBスタンドアロンマイク テレワーク ストリーマー ゲーマー向け ブラック 日本正規代理店品 4P5E2AA 薄型ショックマウント,タッチ式ミュート,コンテンツクリエーター,PC,Mac,2年保証,PC,PS5,PS4,Mac,対応,ハイレゾ24ビット,カスタマイズ可能なRGBライトリング,",
    price: 12837,
    rating: 4.4,
    reviews: 2544,
    image: "https://m.media-amazon.com/images/I/61CLQENUJlL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B119XZBK",
    micFilterTags: ["stand","condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "24ビット/96kHz" },
      { label: "タイプ", value: "テーブルアレイ" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "テーブルアレイ" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "24ビット/96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #9" }],
      }],
  },
    {
    id: "mic-srch-0018",
    category: "mic",
    name: "QuadCast2",
    brand: "HyperX",
    tagline: "コンデンサーマイク USBマイク ゲーム実況 テレワーク ライブ配信 日本正規代理店品 872V1AA アンバサダー愛用,ストリーマー,コンテンツクリエーター,ゲーマー向け,PC,Mac,2年間のメーカー保証,24bit/96KHzのスタジオレベルの音質,LEDステータスインジケータ",
    price: 22591,
    rating: 4.6,
    reviews: 1292,
    image: "https://m.media-amazon.com/images/I/61qy2NjsyOL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9MCK4R8",
    micFilterTags: ["stand","condenser"],
                        micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "４モード" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "４モード" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "RGBライティング", value: "対応" },
          { label: "ミュート", value: "タップミュートセンサー" },
          { label: "Amazon検索", value: "PC用マイク #18" }],
      }],
  },
  {
    id: "mic-srch-0019",
    category: "mic",
    name: "SoloCast",
    brand: "HyperX",
    tagline: "JEOZBM BM700 USBコンデンサーマイク コンピューター用 Hi‑Fi カーディオイドマイクキット 防風カバーブラケット付き ゲームライブポッドキャスト用",
    price: 27164,
    rating: 4.4,
    reviews: 21446,
    image: "https://m.media-amazon.com/images/I/61giVIAzfjL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08KFL3SFV",
    micFilterTags: ["stand","condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "60Hz-19kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "60Hz-19kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "タップミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #19" }],
      }],
  },
    {
    id: "mic-srch-0021",
    category: "mic",
    name: "AT2020USB-X",
    brand: "オーディオテクニカ",
    tagline: "AT2020USB-X コンデンサーマイク USB-Type-C ミュートボタン付き| 音量調整| イヤホン出力| ドライバー不要",
    price: 18480,
    rating: 4.5,
    reviews: 821,
    image: "https://m.media-amazon.com/images/I/61UtbvnnncL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B823S1NR",
    micFilterTags: ["stand","condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ゲインノブ（音量調節ノブ）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "60Hz-19kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "60Hz-19kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "対応" },
          { label: "音量調整", value: "対応" },
          { label: "イヤホンジャック", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #21" }],
      }],
  },
    {
    id: "mic-srch-0051",
    category: "mic",
    name: "PD200X",
    brand: "MAONO",
    tagline: "ゲーミングマイク USB/XLR ダイナミックマイク 専用ソフトウェア付属 PC用ポッドキャストマイク ミュートボタン ボリュームコントロール イヤホン出力端子 ゲーマー向けRGBライティング付き",
    price: 11699,
    rating: 4.3,
    reviews: 2987,
    image: "https://m.media-amazon.com/images/I/61Maq5KstTL._AC_SL1500_.jpg",
    connection: "USB Type-A / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C6XJ9W5T",
    micFilterTags: ["dynamic","stand"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "40Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A / XLR" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "40Hz-16kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "ミュートボタン", value: "対応" },
          { label: "イヤホンジャック", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #51" }],
      }],
  },
      {
    id: "mic-srch-0054",
    category: "mic",
    name: "Snowball",
    brand: "Logicool G",
    tagline: "iCE BM200BK USB ゲーミングマイク コンデンサーマイク 単一指向性 実況 配信 マイク コンパクト ゲーム ゲーミング ストリーミング PC Mac PS5 PS4 ブラック 国内正規品 2年間無償保証",
    price: null,
    rating: 4.3,
    reviews: 607,
    image: "https://m.media-amazon.com/images/I/51UkJ7SGEVL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0822PSXCN",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "40Hz-18kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "40Hz-18kHz" },
          { label: "サンプルレート", value: "48kHz/16bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #54" }],
      }],
  },
                {
    id: "mic-srch-0062",
    category: "mic",
    name: "QuadCast",
    brand: "HyperX",
    tagline: "スタンドアロンマイク ストリーマー/コンテンツクリエーター/ゲーマー向け/PC,PS4使用可能 2年保証 HX-MICQC-BK",
    price: 17800,
    rating: 4.6,
    reviews: 35422,
    image: "https://m.media-amazon.com/images/I/614IJyh+5OL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07NZZZ746",
    micFilterTags: ["stand","condenser"],
                        micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ゲインノブ（音量調節ノブ）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "60Hz-19kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "60Hz-19kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #62" }],
      }],
  },
              {
    id: "mic-srch-0071",
    category: "mic",
    name: "SteelSeries Alias",
    brand: "SteelSeries",
    tagline: "USB マイク 配信用 ゲーム ストリーマー用 コンテンツクリエーター ソナー オーディオ ソフトウェア AIノイズキャンセリング LEDモニタリング 単一指向性 カーディオイド",
    price: 27703,
    rating: 4.4,
    reviews: 402,
    image: "https://m.media-amazon.com/images/I/71d4aKruIZL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CJ36Q5WF",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "60Hz-19kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "60Hz-19kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #71" }],
      }],
  },
    {
    id: "mic-srch-0074",
    category: "mic",
    name: "Snowball",
    brand: "Blue",
    tagline: "【Amazon.co.jp限定】ロジクール G Blue Snowball iCE BM200W USB ゲーミングマイク コンデンサーマイク 単一指向性 実況 配信 マイク コンパクト ゲーム ゲーミング ストリーミング PC Mac PS5 PS4 ホワイト 国内正規品 2年間無償保証",
    price: null,
    rating: 4.2,
    reviews: 360,
    image: "https://m.media-amazon.com/images/I/51L9Ye-cVFL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0822PPCMG",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "60Hz-19kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "60Hz-19kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #74" }],
      }],
  },
    {
    id: "mic-srch-0076",
    category: "mic",
    name: "Yeti GX",
    brand: "Logicool G",
    tagline: "RGB ゲーミングマイク、LIGHTSYNC搭載ポッドキャスト、Blue VO!CE、G HUBコントロール、スーパーカーディオイド、PC/MacでUSBプラグアンドプレイ - ブラック",
    price: 24890,
    rating: 4.6,
    reviews: 219,
    image: "https://m.media-amazon.com/images/I/61YTNgk4vUL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BZBZK4DS",
    micFilterTags: ["dynamic"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #76" }],
      }],
  },
    {
    id: "mic-srch-0081",
    category: "mic",
    name: "NZXT CAPSULE WHITE Cardioid USB Microphone AP-WUM…",
    brand: "—",
    tagline: "NZXT CAPSULE WHITE カーディオイドUSBマイク AP-WUMIC-W1 SP1007",
    price: null,
    rating: 4.5,
    reviews: 620,
    image: "https://m.media-amazon.com/images/I/61YiLgM7OmL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09DTJBLXN",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "96kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "24bit / 96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "96kHz" },
          { label: "サンプルレート", value: "24bit / 96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #81" }],
      }],
  },
    {
    id: "mic-srch-0083",
    category: "mic",
    name: "Yeti GX",
    brand: "Logicool G",
    tagline: "ダイナミックマイク G-YETI-GX-BK ストリーミング配信 スーパーカーディオイド ノイズ軽減 RGB LIGHTSYNC 対応 USB BLUE",
    price: 27164,
    rating: 3.8,
    reviews: 51,
    image: "https://m.media-amazon.com/images/I/613GAp+Tf1L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CRV4VPQY",
    micFilterTags: ["dynamic"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "60Hz-19kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "60Hz-19kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #83" }],
      }],
  },
    {
    id: "mic-srch-0097",
    category: "mic",
    name: "Professional USB Condenser Microphone PC Micropho…",
    brand: "Marantz",
    tagline: "USBコンデンサーマイク PC マイク 単一指向性 スタンド付属 ゲーミング ボイスチャット DTM DAW録音 配信用 レコーディング Mac、PC対応 マランツプロ",
    price: null,
    rating: 4,
    reviews: 3779,
    image: "https://m.media-amazon.com/images/I/71uZQZrWUqL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07WKM5ZCS",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "歌・楽器の録音（DTM）"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-40kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-40kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #97" }],
      }],
  },
                        {
    id: "mic-srch-0109",
    category: "mic",
    name: "SteelSeries Alias",
    brand: "SteelSeries",
    tagline: "USB マイク 配信用 ゲーム ストリーマー用 コンテンツクリエーター ソナー オーディオ ソフトウェア AIノイズキャンセリング LEDモニタリング 単一指向性 カーディオイド",
    price: 26185,
    rating: 4.4,
    reviews: 402,
    image: "https://m.media-amazon.com/images/I/51PB9N-g-oL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CBNTXNWV",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-40kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-40kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #109" }],
      }],
  },
    {
    id: "mic-srch-0148",
    category: "mic",
    name: "GOWENIC 360 無指向性ピックアップ付き USB PC マイク、ワンタッチミュート、ノイズ…",
    brand: "—",
    tagline: "GOWENIC 360 無指向性ピックアップ付き USB PC マイク、ワンタッチミュート、ノイズリダクション、スマートチップ付きコンピュータマイク、ライブストリーミングゲーム通話用",
    price: 2103,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/510fklCPL0L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FWLK8T6S",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "50Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "50Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #148" }],
      }],
  },
    {
    id: "mic-srch-0227",
    category: "mic",
    name: "USBマイク コンピューターマイク 360°集音 PC ノートパソコン 黒",
    brand: "—",
    tagline: "USBマイク コンピューターマイク 360°集音 PC ノートパソコン 黒",
    price: 5279,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51FHqeQlcWL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DXL9CB3K",
    micFilterTags: ["conference"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-40kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-40kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "Amazon検索", value: "PC用マイク #227" }],
      }],
  },
    {
    id: "mic-srch-0255",
    category: "mic",
    name: "PC用USBコンデンサーマイク RGBゲーミングマイク プラグアンドプレイ カーディオイドピックア…",
    brand: "—",
    tagline: "PC用USBコンデンサーマイク RGBゲーミングマイク プラグアンドプレイ カーディオイドピックアップ リアルタイムモニタリング タップトゥミュート ストリーミング/ポッドキャスト/PC/Macでの録画用ゲインコントロール",
    price: 8640,
    rating: 4.2,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/71OikZZ6XRL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G351CLDJ",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-40kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-40kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #255" }],
      }],
  },
                                        {
    id: "mic-srch-0314",
    category: "mic",
    name: "tegongse ゲーミングUSBマイク 30Hz~16kHz周波数 PC用 ブームアームとLED…",
    brand: "—",
    tagline: "tegongse ゲーミングUSBマイク 30Hz~16kHz周波数 PC用 ブームアームとLEDライト付き 没入型ストリーミング用",
    price: 4190,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/616JZyRB3PL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F8B1NBWF",
    micFilterTags: ["condenser"],
                        micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-40kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-40kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #314" }],
      }],
  },
              {
    id: "mic-srch-0327",
    category: "mic",
    name: "VBESTLIFE USBノイズキャンセリングマイク、2チャンネルゲーミングマイク、360°サウン…",
    brand: "—",
    tagline: "VBESTLIFE USBノイズキャンセリングマイク、2チャンネルゲーミングマイク、360°サウンドピックアップ、Wins、OSX、Androidに対応 (青)",
    price: 3525,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61ICQEU9nPL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FP2XRJLK",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-40kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-40kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #327" }],
      }],
  },
    {
    id: "mic-srch-0350",
    category: "mic",
    name: "JEOZBM BM700 USBコンデンサーマイク コンピューター用 Hi‑Fi カーディオイドマ…",
    brand: "—",
    tagline: "JEOZBM BM700 USBコンデンサーマイク コンピューター用 Hi‑Fi カーディオイドマイクキット 防風カバーブラケット付き ゲームライブポッドキャスト用",
    price: 10810,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51qnmO-dPrL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CJCCBLVV",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "Vlog・動画撮影（屋外）"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "192kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #350" }],
      }],
  },
  {
    id: "mic-srch-0351",
    category: "mic",
    name: "TALOMEN USB Condenser Microphone, RGB Glow, Cardi…",
    brand: "—",
    tagline: "セット買い】Razer レイザー Moray ゲーミングイヤホン ハイブリッドデュアルドライバー カスタムイヤーチップ キャリングケース + Seiren V2 X USB 25mm コンデンサーマイク スーパーカーディオイド集音パターン アナログゲインリミッター",
    price: 10440,
    rating: 4.1,
    reviews: 149,
    image: "https://m.media-amazon.com/images/I/714TCkZDmiL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CHW31WLD",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "60Hz-18kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "60Hz-18kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazon検索", value: "PC用マイク #351" }],
      }],
  },
              {
    id: "mic-srch-0360",
    category: "mic",
    name: "RGYBAO ゲーミングUSBマイク",
    brand: "—",
    tagline: "30Hz~16kHz 周波数 PC用 ブームアームとLED照明付き 臨場感あふれるストリーミング用",
    price: 9343,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61p9-IyvvXL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FQCP4X2N",
    micFilterTags: ["condenser"],
                        micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "30Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "30Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #360" }],
      }],
  },
                                    {
    id: "mic-srch-0381",
    category: "mic",
    name: "Samnuerly USBマイク",
    brand: "—",
    tagline: "マイク 360° 自由に調整 スタジオ スピーチ ミニマイク ゲーム チャット 録音 USBマイク デスクトップ PC ノートパソコン (色 : 赤)",
    price: 14129,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51yvKDTUtUL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BDLC1DVJ",
    micFilterTags: ["condenser","stand"],
                        micUseTags: ["歌・楽器の録音（DTM）"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24-bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz/24-bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #381" }],
      }],
  },
    {
    id: "mic-srch-0426",
    category: "mic",
    name: "USBデスクトップマイク 全指向性PCマイク ストリーミング/ポッドキャスティング ボーカル録音/…",
    brand: "—",
    tagline: "USBデスクトップマイク 全指向性PCマイク ストリーミング/ポッドキャスティング ボーカル録音/ゲーム用 プラグアンドプレイUSBデスクマイク ノートパソコン、Mac、PS4、Windows、Linuxに対応",
    price: 1828,
    rating: 3.6,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/61C6btf+f8L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FJM5F5TX",
    micFilterTags: ["condenser"],
                        micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24-bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz/24-bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #426" }],
      }],
  },
                                        {
    id: "mic-srch-0449",
    category: "mic",
    name: "USBマイク USB会議スピーカー 360°全方向スピーカーフォンマイク オンライン会議 ゲーム …",
    brand: "—",
    tagline: "USBマイク USB会議スピーカー 360°全方向スピーカーフォンマイク オンライン会議 ゲーム チャット用",
    price: 2719,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61wdowu8PtL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CJ5GV73S",
    micFilterTags: ["conference"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24-bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz/24-bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "Amazon検索", value: "PC用マイク #449" }],
      }],
  },
    {
    id: "mic-srch-0636",
    category: "mic",
    name: "NGS MS120 USBカーディオイドUSBマイク ストリーミング/ポッドキャスト/ゲーム用 レ…",
    brand: "—",
    tagline: "NGS MS120 USBカーディオイドUSBマイク ストリーミング/ポッドキャスト/ゲーム用 レイテンシーフリーモニタリング ボリュームコントロール ミュートボタン プラグアンドプレイ PC PS4 PS5用 滑り止めスタンド",
    price: 10026,
    rating: 4.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/715S9wZ8GPL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F9FVDDR5",
    micFilterTags: ["condenser","stand"],
                        micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24-bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz/24-bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #636" }],
      }],
  },
                                                                                                                                                                                                                {
    id: "mic-srch-0796",
    category: "mic",
    name: "USBマイク 全指向性USBマイク ゲーム用 ノートパソコン PCマイク スイッチ付き",
    brand: "—",
    tagline: "USBマイク 全指向性USBマイク ゲーム用 ノートパソコン PCマイク スイッチ付き",
    price: 978,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51TPCNHxS5L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DJ7G81Y8",
    micFilterTags: ["condenser"],
                        micUseTags: [],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24-bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz/24-bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #796" }],
      }],
  },
    {
    id: "mic-srch-0907",
    category: "mic",
    name: "RVB USB Cardioid Microphoneコンピューター電話、光削減ノイズ、トランスミ…",
    brand: "—",
    tagline: "RVB USB Cardioid Microphoneコンピューター電話、光削減ノイズ、トランスミッションゲームの11モードのRGB照明を録音する、ABS",
    price: 8085,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/516UP912UyL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FSYWS8L9",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "80Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24-bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "80Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24-bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #907" }],
      }],
  },
                                              {
    id: "mic-srch-0937",
    category: "mic",
    name: "CANYON Lorgar Voicer 521 プロフェッショナル カーディオイド USB-C …",
    brand: "—",
    tagline: "CANYON Lorgar Voicer 521 プロフェッショナル カーディオイド USB-C ゲーミングマイク ブラック LRG-CMT521",
    price: 14955,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/41lQar2gFwL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09Y1XW9J1",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #937" }],
      }],
  },
                                                                                    {
    id: "mic-srch-0991",
    category: "mic",
    name: "V2 X USB コンデンサーマイク",
    brand: "Razer",
    tagline: "セット買い】Razer レイザー Moray ゲーミングイヤホン ハイブリッドデュアルドライバー カスタムイヤーチップ キャリングケース + Seiren V2 X USB 25mm コンデンサーマイク スーパーカーディオイド集音パターン アナログゲインリミッター",
    price: 33204,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51b1JAGBipL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DQ84BXH2",
    micFilterTags: ["condenser"],
                        micUseTags: ["Web会議・オンライン授業・通話"],
                        micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク #991" }],
      }],
  },
  {
    id: "mic-srch-1015",
    category: "mic",
    name: "“2025 New Arrival・Technological Innovation” Zyrvo…",
    brand: "—",
    tagline: "Zyrvox PCマイク usb スタンド 高感度 USB 卓上 無・全指向性 パソコンマイク ワンタッチミュート プラグアンドプレイ 360˚全方向集音 小型 有線タイプ ゲーミング・テレワーク",
    price: 2599,
    rating: 4.4,
    reviews: 89,
    image: "https://m.media-amazon.com/images/I/61htVLTNmLL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FKBV629V",
    micFilterTags: ["condenser","stand"],
                        micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                        micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク #1015" }],
      }],
  }
]
