import type { Gadget } from "./gadgets"

/** Amazon.co.jp コンデンサーマイク売れ筋（2130076051）。マイク本体のみ。 */
export const micCondenserBestsellers: Gadget[] = [
  {
    id: "mic-cnd-001",
    category: "mic",
    name: "USBコンデンサーマイク",
    brand: "Amazonベーシック",
    tagline: "Amazonベーシック USBコンデンサーマイク PC用 ストリーミング/ゲーミング/ポッドキャスト向け ‎8.6cm x 14.7cm",
    price: 3867,
    rating: 4.4,
    reviews: 1297,
    image: "https://m.media-amazon.com/images/I/61kTEwDIwbL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CL9BTQRF",
    micFilterTags: ["stand","condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "96kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #1" }],
      }],
  },
  {
    id: "microphone-audio-technica-at2020",
    category: "mic",
    name: "オーディオテクニカ AT2020",
    brand: "audio-technica",
    tagline:
      "コンデンサーマイク XLR 単一指向性 配信 ブラック レコーディング 宅録 DTM 動画配信 ポッドキャスト 実況 ゲーミング 【国内正規品】",
    price: 13200,
    rating: 4.6,
    reviews: 15384,
    image: "https://m.media-amazon.com/images/I/61y8x7sK8mL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0006H92QK?th=1",
    micFilterTags: ["condenser"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    micSensitivity: "−37dB",
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "バックエレクトレットコンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "バックエレクトレットコンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "マイク感度", value: "−37dB" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "Amazonランキング", value: "コンデンサーマイク #3" },
        ],
      },
    ],
  },
    {
    id: "mic-cnd-005",
    category: "mic",
    name: "コンデンサーマイク ABS製 24bit/96kHz RGBライト 単一指向性 ノイズ低減 20",
    brand: "UGREEN",
    tagline: "コンデンサーマイク ゲーミングマイク PC/卓上マイク RGBライティング 単一指向性 ノイズ低減| ワンタッチミュート| 7RGBライティングモード| ポップフィルター マイクスタンド付き",
    price: 2959,
    rating: 3.9,
    reviews: 514,
    image: "https://m.media-amazon.com/images/I/61HELDnjyGL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FG7DVV62",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話"],
                                                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #5" }],
      }],
  },
  {
    id: "mic-cnd-006",
    category: "mic",
    name: "QUANTUM STREAM",
    brand: "JBL",
    tagline: "デュアルコンデンサー ブラック スタンドアロン| テレワーク/ゲーマー/コンテンツクリエーター/ストリーマー対応| PC/MAC/PS4/PS5/SWITCH使用可能|",
    price: 7900,
    rating: 4.4,
    reviews: 880,
    image: "https://m.media-amazon.com/images/I/71PrDY1SURL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09VGCZHG4",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "2モード (全/単一指向性)" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "44.1kHz/48kHz/96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "2モード (全/単一指向性)" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "44.1kHz/48kHz/96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #6" }],
      }],
  },
  {
    id: "mic-cnd-007",
    category: "mic",
    name: "HS-MC09UBK",
    brand: "エレコム",
    tagline: "MAONO USBマイク コンデンサーマイク PC マイクセット アームスタンド付き 録音 生放送 YOUTUBE ゲーム実況 在宅勤務 適格請求書発行可 AU-A04",
    price: 1300,
    rating: 3.9,
    reviews: 153,
    image: "https://m.media-amazon.com/images/I/61eVSQk-g3L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09BN9N1P3",
    micFilterTags: ["condenser","pin"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "Amazonランキング", value: "コンデンサーマイク #7" }],
      }],
  },
    {
    id: "mic-cnd-010",
    category: "mic",
    name: "AU-A04",
    brand: "MAONO",
    tagline: "MAONO USBマイク コンデンサーマイク PC マイクセット アームスタンド付き 録音 生放送 YOUTUBE ゲーム実況 在宅勤務 適格請求書発行可 AU-A04",
    price: 7699,
    rating: 4.1,
    reviews: 15971,
    image: "https://m.media-amazon.com/images/I/71u0iKDF0SL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07GLWQS61",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "30Hz-19kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "30Hz-19kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "Amazonランキング", value: "コンデンサーマイク #12" }],
      }],
  },
  {
    id: "mic-cnd-011",
    category: "mic",
    name: "AT4040",
    brand: "オーディオテクニカ",
    tagline: "オーディオテクニカ AT4040 コンデンサーマイク XLR 1インチ大口径ダイアフラム / DCバイアス/単一指向性 / 80Hzローカットフィルタースイッチ / 10dBパッドスイッチ / 専用シ",
    price: 39600,
    rating: 4.8,
    reviews: 790,
    image: "https://m.media-amazon.com/images/I/71d0x7JzXUS._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0002D0BQ8",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["歌・楽器の録音（DTM）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "Amazonランキング", value: "コンデンサーマイク #13" }],
      }],
  },
  {
    id: "mic-cnd-012",
    category: "mic",
    name: "マイク コンデンサーマイク PCマイク 単一指向性 エコー機能付き 会議用 ゲーム 実況 タブレ",
    brand: "ZealSound",
    tagline: "コンデンサーマイク USB マイク ゲーミングマイク PC マイク 卓上 192kHz/24bit アクティブノイズキャンセリング エコモード搭載 RGBライト カーディオイド 静音機能付き 高感度",
    price: 5287,
    rating: 4,
    reviews: 226,
    image: "https://m.media-amazon.com/images/I/61D+CXhHL6L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F9FM4MVH",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: ["ミュート機能"],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz/16bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #14" }],
      }],
  },
    {
    id: "mic-cnd-014",
    category: "mic",
    name: "コンデンサーマイク USB マイク ゲーミングマイク PC マイク 卓上 192kHz/24bi",
    brand: "—",
    tagline: "コンデンサーマイク USB マイク ゲーミングマイク PC マイク 卓上 192kHz/24bit アクティブノイズキャンセリング エコモード搭載 RGBライト カーディオイド 静音機能付き 高感度",
    price: 2299,
    rating: 3.5,
    reviews: 155,
    image: "https://m.media-amazon.com/images/I/61vZElo0LlL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DJR3CHKM",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "192kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #16" }],
      }],
  },
  {
    id: "mic-cnd-015",
    category: "mic",
    name: "ECM-TL3",
    brand: "ソニー",
    tagline: "ソニー(SONY) コンデンサーマイク モノラル/電話録音用 ECM-TL3 黒",
    price: 1727,
    rating: 4.1,
    reviews: 704,
    image: "https://m.media-amazon.com/images/I/41Ia4HPGfjL._AC_SL1500_.jpg",
    connection: "3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B004KVIZFM",
    micFilterTags: ["condenser","pin"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "3.5mm" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "3.5mm" },
          { label: "Amazonランキング", value: "コンデンサーマイク #17" }],
      }],
  },
  {
    id: "mic-cnd-016",
    category: "mic",
    name: "MPM-2000U",
    brand: "Marantz",
    tagline: "Marantz Professional MPM-2000U USB コンデンサーマイク",
    price: 7999,
    rating: 4.4,
    reviews: 970,
    image: "https://m.media-amazon.com/images/I/81tQNfnxgmL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B01GJ9IUNY",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話"],
                                                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-17kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-17kHz" },
          { label: "サンプルレート", value: "48kHz/16bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "Amazonランキング", value: "コンデンサーマイク #18" }],
      }],
  },
  {
    id: "mic-cnd-017",
    category: "mic",
    name: "K670",
    brand: "FIFINE",
    tagline: "FIFINE USBマイクロフォン コンデンサーマイク イヤホン端子付き マイクスタンド高さ調節可能 ABタイプ USBケーブル付き 単一指向性 Skype ライブ配信 ゲーム実況 PC用 Windo",
    price: 3200,
    rating: 4.1,
    reviews: 948,
    image: "https://m.media-amazon.com/images/I/61ZPVbHm3qL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B079HRX2ZP",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["イヤホンジャック（ダイレクトモニタリング）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-15kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-15kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "Amazonランキング", value: "コンデンサーマイク #19" }],
      }],
  },
  {
    id: "mic-cnd-018",
    category: "mic",
    name: "AT2035",
    brand: "オーディオテクニカ",
    tagline: "オーディオテクニカ AT2035 コンデンサーマイク 単一指向/ローカットスイッチ/パッドスイッチ/専用ショックマウント付属/レコーディング/宅録/動画配信/ポッドキャスト/実況/DTM/ブラック 【",
    price: 19800,
    rating: 4.6,
    reviews: 3009,
    image: "https://m.media-amazon.com/images/I/71rCf-z8+aL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B002T45X1G",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                                                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "Amazonランキング", value: "コンデンサーマイク #20" }],
      }],
  },
  {
    id: "mic-cnd-019",
    category: "mic",
    name: "ピンマイク 有線 マイク コンデンサーType-C端子 全指向性 スマホ/PC/タブレット対応",
    brand: "—",
    tagline: "全指向性| スマホ/PC/タブレット対応| iPhone iPad Android カメラ対応| 録音 ゲーム ライブ配信 オンライン授業 会議用| 専用カラーボックス＆収納布袋付き",
    price: 558,
    rating: 3.2,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/619bZMkvizL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FL6R2JSJ",
    micFilterTags: ["condenser","pin"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #22" }],
      }],
  },
  {
    id: "mic-cnd-020",
    category: "mic",
    name: "EasySing Mic Mini Duo",
    brand: "JBL",
    tagline: "JBL EasySing Mic Mini Duo/小型ワイヤレスマイク/AI搭載/ピンマイク/ハンドマイク/ボーカルリムーバル機能/ 最大6時間バッテリー/JBL Oneアプリ対応/ピッチ変更/ブラ",
    price: 27000,
    rating: 4.2,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/710DBhkS6QL._AC_SL1500_.jpg",
    connection: "USB Type-C / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3TD27ZS",
    micFilterTags: ["condenser","pin","wireless"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-15kHz" },
      { label: "接続方式", value: "USB Type-C / Bluetooth" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-15kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / Bluetooth" },
          { label: "Amazonランキング", value: "コンデンサーマイク #23" }],
      }],
  },
  {
    id: "mic-cnd-021",
    category: "mic",
    name: "MV88+",
    brand: "SHURE",
    tagline: "SHURE シュア MV88+ ビデオキット ステレオコンデンサーマイク MV88+DIG-VIDKIT USB接続 USB-C スマホ ステレオ iOS Android 対応 外付け 動画撮影用マイ",
    price: 29750,
    rating: 4.2,
    reviews: 1260,
    image: "https://m.media-amazon.com/images/I/61kemddEXaL._AC_SL1500_.jpg",
    connection: "USB Type-C / Lightning",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08G7T3Q9S",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "４モード" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / Lightning" },
      { label: "サンプルレート", value: "48kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "４モード" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / Lightning" },
          { label: "Amazonランキング", value: "コンデンサーマイク #24" }],
      }],
  },
  {
    id: "mic-cnd-022",
    category: "mic",
    name: "QUANTUM STREAM TALK",
    brand: "JBL",
    tagline: "JBL QUANTUM STREAM TALK シングルコンデンサーマイク 卓上 スタンドマイク ミュート機能付 USBプラグ＆プレイ 3.5mm ゲーミング リモート会議 配信用 JBLSTRMTA",
    price: 6930,
    rating: 4.1,
    reviews: 34,
    image: "https://m.media-amazon.com/images/I/51AcAXJR8sL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CTSX8HFS",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "50Hz-12kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "44.1kHz / 48kHz / 96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "50Hz-12kHz" },
          { label: "サンプルレート", value: "44.1kHz / 48kHz / 96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #25" }],
      }],
  },
  {
    id: "mic-cnd-023",
    category: "mic",
    name: "YETI ORB",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングマイク YETI ORB コンデンサーマイク G-YETI-ORB-BK ストリーミング配信 ノイズ軽減 RGB LIGHTSYNC USB BLUE VO!CE PC",
    price: 7900,
    rating: 4.3,
    reviews: 65,
    image: "https://m.media-amazon.com/images/I/61IiWL9dAIL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CRV2C7HD",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "70Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "70Hz-20kHz" },
          { label: "サンプルレート", value: "48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #27" }],
      }],
  },
  {
    id: "mic-cnd-024",
    category: "mic",
    name: "USBマイク コンデンサーマイク 192kHz/24bit 16mm高感度 カーディオイド DS",
    brand: "—",
    tagline: "ソニー(SONY)【付属品でUSB接続も簡単】ソニー エレクトレットコンデンサーマイクロホン PC/ゲーム用 ECM-PCV80U",
    price: 1804,
    rating: 2.8,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61c20bfW9nL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6MV2KPH",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "80Hz-15kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "80Hz-15kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #28" }],
      }],
  },{
    id: "mic-cnd-026",
    category: "mic",
    name: "ECM-PCV80U",
    brand: "ソニー",
    tagline: "ソニー(SONY)【付属品でUSB接続も簡単】ソニー エレクトレットコンデンサーマイクロホン PC/ゲーム用 ECM-PCV80U",
    price: null,
    rating: 4,
    reviews: 4856,
    image: "https://m.media-amazon.com/images/I/41VP5s2Hz-L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B005M2HDA6",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "80Hz-15kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "80Hz-15kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "Amazonランキング", value: "コンデンサーマイク #30" }],
      }],
  },
  {
    id: "microphone-rode-nt1-5th-gen",
    category: "mic",
    name: "RODE NT1（第5世代）",
    brand: "RODE (ロード)",
    tagline:
      "XLRとUSB-Cのデュアルコネクトに対応した大口径ラージダイアフラム・コンデンサーマイク。超低ノイズかつ32bit float録音にも対応した高品質スタジオモデル。",
    price: 42060,
    rating: 4.6,
    reviews: 1423,
    image: "https://m.media-amazon.com/images/I/51-vfZouwQL._AC_SL1500_.jpg",
    connection: "XLR、USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BQHHZ1QQ",
    micSensitivity: "-32dB",
    micFilterTags: ["condenser"],
    micUseTags: ["歌・楽器の録音（DTM）", "ゲーム実況・配信・ラジオ録音"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性（カーディオイド）" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "XLR、USB-C" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性（カーディオイド）" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz" },
          { label: "マイク感度", value: "-32dB" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [{ label: "接続方式", value: "XLR、USB-C" }],
      },
    ],
  },
]
