import type { Gadget } from "./gadgets"

/** Amazon.co.jp PC用マイク人気ギフト 2ページ目（2152017051 pg=2 #51–#80）。マイク本体・会議用スピーカーフォン含む。 */
export const micMostGiftedPage2: Gadget[] = [
  {
    id: "mic-mg2-051",
    category: "mic",
    name: "ROG Carnyx C501",
    brand: "ASUS",
    tagline: "TONOR USB/XLRダイナミックマイク 単一指向性 PC/PS4/PS5対応 RGB ゲーミング/配信用 黒 TD510 AIR S RGBライティング調整可能、接続簡単、音声モニター/ワンタッチ式ミュート/デュアル音量調節機能搭載、USBケーブル付き、パソコン/XLR機器対応、ゲーミング/配信/会議",
    price: 21500,
    rating: 3.9,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/715y91AhirL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D41PZJNG",
    micFilterTags: ["stand","condenser"],
                            micUseTags: ["Web会議・オンライン授業・通話"],
                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24-bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24-bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #51" }],
      }],
  },
    {
    id: "mic-mg2-053",
    category: "mic",
    name: "PowerConf S330",
    brand: "Anker",
    tagline: "Anker PowerConf S330【全指向性マイク搭載の主要会議ツールに対応したマイクスピーカー】",
    price: 5680,
    rating: 4.2,
    reviews: 101,
    image: "https://m.media-amazon.com/images/I/71tIyN0T7OL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09JNRKQK7",
    micFilterTags: ["conference"],
                            micUseTags: ["Web会議・オンライン授業・通話"],
                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "ハウリング抑制", value: "対応" },
          { label: "ノイズリダクション", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #53" }],
      }],
  },
    {
    id: "mic-mg2-055",
    category: "mic",
    name: "ピンマイク 単一指向性マイク ゲーミングマイク イヤホン PC ゲーム実況 配信 Zoom Sky…",
    brand: "G-MODELL",
    tagline: "G-MODELL ピンマイク 単一指向性マイク ゲーミングマイク イヤホン PC ゲーム実況 配信 Zoom Skype YouTube (イヤホンジャック3.5mm)",
    price: 1199,
    rating: 3,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/61qNVxt56cL._AC_SL1500_.jpg",
    connection: "3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CBWF7V1M",
    micFilterTags: ["condenser","pin"],
                            micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "Vlog・動画撮影（屋外）"],
                            micFeatureTags: ["イヤホンジャック（ダイレクトモニタリング）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "3.5mm" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "3.5mm" },
          { label: "電源", value: "有線給電" },
          { label: "イヤホンジャック", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #55" }],
      }],
  },
    {
    id: "mic-mg2-060",
    category: "mic",
    name: "USBマイク コンデンサーマイク TC310+ RGB 単一指向性 ゲーム実況 配信 Zoom P…",
    brand: "TONOR",
    tagline: "TONOR USB/XLRダイナミックマイク 単一指向性 PC/PS4/PS5対応 RGB ゲーミング/配信用 黒 TD510 AIR S RGBライティング調整可能、接続簡単、音声モニター/ワンタッチ式ミュート/デュアル音量調節機能搭載、USBケーブル付き、パソコン/XLR機器対応、ゲーミング/配信/会議",
    price: 5499,
    rating: 4.3,
    reviews: 563,
    image: "https://m.media-amazon.com/images/I/51M-1jdQ1pL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJP76J2M",
    micFilterTags: ["condenser","stand"],
                            micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #60" }],
      }],
  },
  {
    id: "mic-mg2-061",
    category: "mic",
    name: "TC310+",
    brand: "TONOR",
    tagline: "コンデンサーマイク TC310+ RGB 単一指向性 ゲーム実況 配信 Zoom PS5/PS4対応 ワンタッチミュート ブームアーム付き",
    price: 5499,
    rating: 4.5,
    reviews: 3326,
    image: "https://m.media-amazon.com/images/I/71ucAMitTgL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CCV74CL7",
    micFilterTags: ["stand","condenser"],
                            micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "ミュートボタン", value: "ワンタッチミュート" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #61" }],
      }],
  },
  {
    id: "mic-mg2-062",
    category: "mic",
    name: "M2",
    brand: "EMEET",
    tagline: "EMEET M2 スピーカーフォン 会議用マイクスピーカー ブラック",
    price: 23900,
    rating: 4.3,
    reviews: 1082,
    image: "https://m.media-amazon.com/images/I/71Ti00lT5-L._AC_SL1500_.jpg",
    connection: "USB Type-A / Bluetooth / AUX",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07FMLLMKD",
    micFilterTags: ["conference"],
                            micUseTags: ["Web会議・オンライン授業・通話"],
                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A / Bluetooth / AUX" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "テーブルアレイマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "テーブルアレイマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / Bluetooth / AUX" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "ハウリング抑制", value: "対応" },
          { label: "Bluetooth", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #62" }],
      }],
  },
  {
    id: "mic-mg2-063",
    category: "mic",
    name: "EJoy Uni S",
    brand: "COMICA",
    tagline: "COMICA EJoy Uni S USBコンデンサーマイク AIノイズキャンセリングマイク RGBライティング ノイズ軽減 ワンタッチミュート ゲーム実況 在宅勤務 ポッドキャスト ストリーミング ナレーション録音に最適 PC/PS4/P",
    price: 6382,
    rating: 3.8,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/51e9qWqtDmL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09XDPPKTT",
    micFilterTags: ["stand","condenser"],
                            micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "24bit/48kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "24bit/48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #63" }],
      }],
  },
  {
    id: "mic-mg2-065",
    category: "mic",
    name: "USBスピーカーフォン",
    brand: "Kaysuda",
    tagline: "Kaysuda USBスピーカーフォン スピーカー・マイク一体化 PCマイク マイクスピーカー 双方向通話/全二重通信/ノイズキャンセリング/オートゲインコントロール対応 Zoom/Skype/Teams/Google meet 対応 ウェ",
    price: null,
    rating: 3.9,
    reviews: 992,
    image: "https://m.media-amazon.com/images/I/61aA2CSy8EL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0796VFD73",
    micFilterTags: ["conference"],
                            micUseTags: ["Web会議・オンライン授業・通話"],
                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #65" }],
      }],
  },
  {
    id: "mic-mg2-066",
    category: "mic",
    name: "XS LAV USB-C",
    brand: "Sennheiser",
    tagline: "サンワダイレクト WEB会議マイクスピーカーフォン エコー/ノイズキャンセル機能搭載 最大3m集音 マイク3基搭載 400-MC003",
    price: 1148,
    rating: 4.1,
    reviews: 496,
    image: "https://m.media-amazon.com/images/I/31ed4KzZzkL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08YS2G4FB",
    micFilterTags: ["pin","condenser"],
                            micUseTags: [],
                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-5kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-5kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #66" }],
      }],
  },
    {
    id: "mic-mg2-072",
    category: "mic",
    name: "MM-MC28",
    brand: "サンワサプライ",
    tagline: "サンワサプライ WEB会議小型スピーカーフォン マイク 有線USB接続 Skype・Zoom・Teams対応 MM-MC28",
    price: 23669,
    rating: 4.1,
    reviews: 187,
    image: "https://m.media-amazon.com/images/I/71XD2ErkHkL._AC_SL1500_.jpg",
    connection: "USB Type-A / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00HWOEYG8",
    micFilterTags: ["conference"],
                            micUseTags: ["Web会議・オンライン授業・通話"],
                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-5kHz" },
      { label: "接続方式", value: "USB Type-A / Bluetooth" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-5kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / Bluetooth" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #72" }],
      }],
  },
    {
    id: "mic-mg2-075",
    category: "mic",
    name: "USB卓上マイク",
    brand: "—",
    tagline: "PCマイク usb スタンド 高感度 卓上 無・全指向性 パソコンマイク ワンタッチミュート プラグアンドプレイ 360˚全方向集音 小型 有線タイプ ゲーミング・テレワーク・会議用・配信用 録音・ゲーム実況・ボイズチャッ Windows/",
    price: 1148,
    rating: 4.1,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61gpbD8+RML._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX4NQKGL",
    micFilterTags: ["stand","condenser"],
                            micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                            micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "ワンタッチミュート" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #75" }],
      }],
  },
    {
    id: "mic-mg2-080",
    category: "mic",
    name: "400-MC003",
    brand: "サンワダイレクト",
    tagline: "サンワダイレクト WEB会議マイクスピーカーフォン エコー/ノイズキャンセル機能搭載 最大3m集音 マイク3基搭載 400-MC003",
    price: null,
    rating: 3.4,
    reviews: 16,
    image: "https://m.media-amazon.com/images/I/51d0ztJ5GOL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00CXLFZL8",
    micFilterTags: ["conference"],
                            micUseTags: ["Web会議・オンライン授業・通話"],
                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "テーブルアレイ型" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "テーブルアレイ型" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-16kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "エコーキャンセリング", value: "対応" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "エコーキャンセラー", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #80" }],
      }],
  }
]
