import type { Gadget } from "./gadgets"

/** Amazon.co.jp コンデンサーマイク売れ筋 2ページ目（2130076051 pg=2）。マイク本体のみ。 */
export const micCondenserBestsellersPage2: Gadget[] = [
  {
    id: "mic-cnd2-001",
    category: "mic",
    name: "PRO35",
    brand: "オーディオテクニカ",
    tagline: "金管楽器・サックス向けXLRコンデンサーマイク。楽器用ホルダー付属、高耐入力145dB",
    price: 13155,
    rating: 4.1,
    reviews: 119,
    image: "https://m.media-amazon.com/images/I/71ycCLJLkkL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B001TOYV4M",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["歌・楽器の録音（DTM）"],
                                                            micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-18kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-18kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "Amazonランキング", value: "コンデンサーマイク #51" }],
      }],
  },
  {
    id: "mic-cnd2-002",
    category: "mic",
    name: "コンデンサーマイク USB 卓上 PC マイク 192kHz/24bit 録音 2段階ノイズキャ",
    brand: "—",
    tagline: "コンデンサーマイク USB 卓上 PC マイク 192kHz/24bit 録音 2段階ノイズキャンセリング機能搭載 カーディオイド 8種類RGB 16mmマイクヘッド 静音モード リバーブモード Hi",
    price: 699,
    rating: 2.8,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/71IRirVfJ5L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FKM9BS9H",
    micFilterTags: ["condenser","stand"],
                                                    micUseTags: ["Web会議・オンライン授業・通話"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "192kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #52" }],
      }],
  },
  {
    id: "mic-cnd2-003",
    category: "mic",
    name: "Profile USB",
    brand: "Sennheiser",
    tagline: "ポッドキャスト・ストリーマー・ゲーマー向けUSBコンデンサーマイク（国内正規品）",
    price: 15445,
    rating: 4.5,
    reviews: 1007,
    image: "https://m.media-amazon.com/images/I/51QZ0rHYw6L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTPYCD86",
    micFilterTags: ["stand","condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #53" }],
      }],
  },
  {
    id: "mic-cnd2-004",
    category: "mic",
    name: "GamerWave",
    brand: "MAONO",
    tagline: "MAONO USB コンデンサーマイク ゲーミングマイク ノイズキャンセリング PC マイク ミュートボタン 単一指向性 RGBライティング 音量コントロール プラグ＆プレイ パソコンマイク ゲーム実",
    price: 7700,
    rating: 4.6,
    reviews: 22,
    image: "https://m.media-amazon.com/images/I/61XM3P1cpnL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C32W4ZH7",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ゲインノブ（音量調節ノブ）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #54" }],
      }],
  },
  {
    id: "mic-cnd2-005",
    category: "mic",
    name: "RGBライト PCマイク USB ゲーム マイク Windows MacOS スマホ PS4/P",
    brand: "FerBuee",
    tagline: "FerBuee RGBライト PCマイク USB ゲーム マイク Windows MacOS スマホ PS4/PS5等対応 ゲーム実況 生放送 カラオケ 録音 配信などに適用 ミュートボタン 音量調整",
    price: 2000,
    rating: 4.1,
    reviews: 53,
    image: "https://m.media-amazon.com/images/I/71BCG5RaUBL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWXVJQ9N",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "ゲインノブ（音量調節ノブ）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192khz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "192khz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #55" }],
      }],
  },
  {
    id: "mic-cnd2-006",
    category: "mic",
    name: "Wave:3",
    brand: "Elgato",
    tagline: "Wave FX Processor・Clipguard 2.0搭載のプレミアムUSBコンデンサーマイク",
    price: 28980,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/61ngUaydY-L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQRSQ86L",
    micFilterTags: ["stand","condenser"],
                                                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ゲインノブ（音量調節ノブ）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "70Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "70Hz-20kHz" },
          { label: "サンプルレート", value: "48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #56" }],
      }],
  },
  {
    id: "mic-cnd2-007",
    category: "mic",
    name: "USB ゲーミングマイク *Phoneマイク コンデンサーマイクミュートボタン カーディオイド指",
    brand: "Zealsound",
    tagline: "超単一指向性USBコンデンサーマイク。ウェブ会議・配信・ゲーム実況向け",
    price: 9609,
    rating: 4.6,
    reviews: 241,
    image: "https://m.media-amazon.com/images/I/61TCDCssHmL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CMV914QV",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "-18kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "-18kHz" },
          { label: "サンプルレート", value: "48kHz/16bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #57" }],
      }],
  },{
    id: "mic-cnd2-010",
    category: "mic",
    name: "TM-250U",
    brand: "TASCAM",
    tagline: "超単一指向性USBコンデンサーマイク。ウェブ会議・配信・ゲーム実況向け",
    price: 7480,
    rating: 3.9,
    reviews: 82,
    image: "https://m.media-amazon.com/images/I/71PrMMopxKL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B093LFS9QF",
    micFilterTags: ["stand","condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz/16bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #60" }],
      }],
  },
  {
    id: "mic-cnd2-011",
    category: "mic",
    name: "AT9901",
    brand: "オーディオテクニカ",
    tagline: "ZOOM(ズーム) Am7 Androidスマホマイク USB Type-C ブラック",
    price: 3400,
    rating: 4.1,
    reviews: 223,
    image: "https://m.media-amazon.com/images/I/51ehYNISYbL._AC_SL1500_.jpg",
    connection: "3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0014THK5E",
    micFilterTags: ["pin","condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "3.5mm" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "3.5mm" },
          { label: "Amazonランキング", value: "コンデンサーマイク #61" }],
      }],
  },
    {
    id: "mic-cnd2-014",
    category: "mic",
    name: "Am7",
    brand: "ZOOM",
    tagline: "ZOOM(ズーム) Am7 Androidスマホマイク USB Type-C ブラック",
    price: 11490,
    rating: 3.6,
    reviews: 134,
    image: "https://m.media-amazon.com/images/I/61CXOa1GWLL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08P411XR5",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "Amazonランキング", value: "コンデンサーマイク #65" }],
      }],
  },
  {
    id: "mic-cnd2-015",
    category: "mic",
    name: "ECM-999",
    brand: "Superlux",
    tagline: "Superlux 測定用 無指向性コンデンサーマイクロホン ECM-999 ブラック",
    price: 5535,
    rating: 4.5,
    reviews: 114,
    image: "https://m.media-amazon.com/images/I/510vc4xqiuL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07KT8X3XQ",
    micFilterTags: ["condenser","pin"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "Amazonランキング", value: "コンデンサーマイク #66" }],
      }],
  },
  {
    id: "mic-cnd2-016",
    category: "mic",
    name: "auriq01",
    brand: "asmrlabo",
    tagline: "asmrlabo XLR耳型バイノーラルマイク「auriq01 Pro」（Primo EM272マイクカプセル搭載）（ブラック）asmr 環境音",
    price: 42000,
    rating: 4.6,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/617tf+sTQAL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FGJYCPRT",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["歌・楽器の録音（DTM）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: ["ASMR"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "Amazonランキング", value: "コンデンサーマイク #67" }],
      }],
  },
  {
    id: "mic-cnd2-017",
    category: "mic",
    name: "ワイヤレスピンマイク (3in1)",
    brand: "—",
    tagline: "Type-C/Lightning/3.5mm対応のコードレスピンマイク。360°全指向性・2人同時収音",
    price: 1399,
    rating: 3.5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/617DlkcZwKL._AC_SL1500_.jpg",
    connection: "USB Type-C / 3.5mm / Lightning",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6Q4TK8K",
    micFilterTags: ["pin","wireless","condenser"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / 3.5mm / Lightning" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / 3.5mm / Lightning" },
          { label: "Amazonランキング", value: "コンデンサーマイク #68" }],
      }],
  },
  {
    id: "mic-cnd2-018",
    category: "mic",
    name: "SoloCast (ホワイト)",
    brand: "HyperX",
    tagline: "タップトゥミュート・LEDステータス搭載のUSBコンデンサーマイク（ホワイト）",
    price: null,
    rating: 4.2,
    reviews: 1614,
    image: "https://m.media-amazon.com/images/I/61rbC5XiL5L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09XQVB4XC",
    micFilterTags: ["stand","condenser"],
                                                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                                            micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz/16bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "Amazonランキング", value: "コンデンサーマイク #71" }],
      }],
  },
  {
    id: "mic-cnd2-019",
    category: "mic",
    name: "AT875R",
    brand: "オーディオテクニカ",
    tagline: "オーディオテクニカ AT875R ショットガンマイク XLR コンデンサーマイク ファンタム電源 放送 制作 カメラ 【国内正規品】",
    price: 22222,
    rating: 4.6,
    reviews: 827,
    image: "https://m.media-amazon.com/images/I/61y4gLYXY3L._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000BQ79W0",
    micFilterTags: ["condenser"],
                                                    micUseTags: ["歌・楽器の録音（DTM）", "Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "90Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "90Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "Amazonランキング", value: "コンデンサーマイク #73" }],
      }],
  },
  {
    id: "mic-cnd2-020",
    category: "mic",
    name: "クリップマイク ピンマイク マイクロフォン 長さ120mm ジャック 3.5mm φプラグ iP",
    brand: "Rosebe",
    tagline: "Rosebe クリップマイク ピンマイク マイクロフォン 長さ120mm ジャック 3.5mm φプラグ iPhone/iPad/Android/カメラ 対応[ブラック]",
    price: 990,
    rating: 3.3,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/519DKvY-x6L._AC_SL1500_.jpg",
    connection: "3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07MJZ7XQ5",
    micFilterTags: ["condenser","pin"],
                                                    micUseTags: ["Vlog・動画撮影（屋外）"],
                                                            micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "3.5mm" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "3.5mm" },
          { label: "Amazonランキング", value: "コンデンサーマイク #74" }],
      }],
  }
]
