import type { Gadget } from "./gadgets"

/** Amazon.co.jp ダイナミックマイク売れ筋（2130075051）。マイク本体のみ。 */
export const micDynamicBestsellers: Gadget[] = [
  {
    id: "mic-dyn-001",
    category: "mic",
    name: "K688CT",
    brand: "FIFINE",
    tagline: "USB/XLRマイク PCセット ブラック 単一指向性| 音量調整・ミュートボタン| 音声モニタリング| アーム付き| USB/XLR/PS4/PS5/オーディオインターフェース対応",
    price: 12899,
    rating: 4.2,
    reviews: 164,
    image: "https://m.media-amazon.com/images/I/61R6e4Qm8iL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DNJGTMBK",
    micFilterTags: ["dynamic","stand"],
    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
    micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ゲインノブ（音量調節ノブ）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "48kHz/16bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "音量調整", value: "対応" },
          { label: "ダイレクトモニタリング", value: "対応" },
          { label: "Amazonランキング", value: "ダイナミックマイク #1" }],
      }],
  },
  {
    id: "mic-dyn-002",
    category: "mic",
    name: "AT2040",
    brand: "audio-technica (オーディオテクニカ)",
    tagline: "超単一指向性ダイナミックマイク。内蔵ポップフィルター・XLR出力。ポッドキャスト/配信向け",
    price: 13200,
    rating: 4.3,
    reviews: 1500,
    image: "https://m.media-amazon.com/images/I/61H4BAnC+sL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09BFPNW2J",
    micFilterTags: ["dynamic"],
    micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "80Hz-16kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "80Hz-16kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク #2" }],
      }],
  },
  {
    id: "mic-dyn-003",
    category: "mic",
    name: "MV7+",
    brand: "SHURE",
    tagline:
      "MV7+-K : OBS 認証 ダイナミックマイク カーディオイド 単一指向性 USB-C XLR 有線 ノイズ除去 配信 ストリーミング YouTube 録音 レコーディング 音楽 実況 ゲーミング ボーカル DTM 宅録 iOS Android Mac Windows対応 【国内正規品/メーカー保証2年】",
    price: 47000,
    rating: 4,
    reviews: 79,
    image: "https://m.media-amazon.com/images/I/515LuCugyuL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CYYZ78NJ",
    micFilterTags: ["dynamic"],
    micUseTags: [
      "Web会議・オンライン授業・通話",
      "ゲーム実況・配信・ラジオ録音",
      "歌・楽器の録音（DTM）",
    ],
    micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ゲインノブ（音量調節ノブ）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    micSensitivity: "−55dB",
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "マイク感度", value: "−55dB" },
          { label: "サンプルレート", value: "48kHz/16bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "Amazonランキング", value: "ダイナミックマイク #3" },
        ],
      },
    ],
  },
    {
    id: "mic-dyn-005",
    category: "mic",
    name: "SM7dB",
    brand: "SHURE",
    tagline: "ダイナミックマイク カーディオイド 単一指向性 XLR 有線 ストリーミング 配信 YouTube 音声 音楽 演奏 録音 レコーディング 実況 ゲーミング ポッドキャスト ボーカル DTM 【国内正規品/メーカー保証2年】",
    price: 75800,
    rating: 4.3,
    reviews: 942,
    image: "https://m.media-amazon.com/images/I/51s6YLtJXbL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CCSVYWMH",
    micFilterTags: ["dynamic"],
    micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
    micFeatureTags: ["ゲインノブ（音量調節ノブ）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク #5" }],
      }],
  },
    {
    id: "mic-dyn-007",
    category: "mic",
    name: "PartyBox Wireless Mic 2-Piece Set/2.4GHz Wire…",
    brand: "JBL",
    tagline: "2本セット/2.4GHz 無線方式デジタル/単一指向性ダイナミックマイク/有効距離最大30m/ブラック JBLPBWIRELESSMIC",
    price: 17700,
    rating: 4.6,
    reviews: 296,
    image: "https://m.media-amazon.com/images/I/71ejU0KkH9L._AC_SL1500_.jpg",
    connection: "2.4GHz ワイヤレス",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CXHQHW4R",
    micFilterTags: ["dynamic","wireless","conference"],
    micUseTags: ["Web会議・オンライン授業・通話"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-15kHz" },
      { label: "接続方式", value: "2.4GHz ワイヤレス" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ワイヤレスダイナミックマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ワイヤレスダイナミックマイク" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-15kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "2.4GHz ワイヤレス" },
          { label: "電源", value: "充電式" },
          { label: "Amazonランキング", value: "ダイナミックマイク #7" }],
      }],
  },
    {
    id: "mic-dyn-009",
    category: "mic",
    name: "SHURE SM58SE",
    brand: "SHURE",
    tagline: "ON/OFFスイッチ付き マイクスタンド用ネジ有 単一指向性 カーディオイド XLR 有線 ボーカル 歌 ライブ 収録 録音 レコーディング DTM 宅録 マイクロホン マイクロフォン 【国内正規品/メーカー保証2年】",
    price: 16010,
    rating: 4.4,
    reviews: 1396,
    image: "https://m.media-amazon.com/images/I/61yVNJQNdYL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000GUBOYU",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ON/OFFスイッチ", value: "搭載" },
          { label: "Amazonランキング", value: "ダイナミックマイク #9" }],
      }],
  },
  {
    id: "mic-dyn-010",
    category: "mic",
    name: "MV6",
    brand: "SHURE",
    tagline: "スーパーカーディオイドボーカル向けダイナミックマイク。XLR・国内正規品",
    price: 24749,
    rating: 4.1,
    reviews: 85,
    image: "https://m.media-amazon.com/images/I/41hzn43b2jL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DDP2HT3F",
    micFilterTags: ["dynamic"],
    micUseTags: ["Web会議・オンライン授業・通話"],
    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: ["ミュート機能"],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-15kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "44.1kHz、/48kHz" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-15kHz" },
          { label: "サンプルレート", value: "44.1kHz、/48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク #10" }],
      }],
  },
        {
    id: "mic-dyn-014",
    category: "mic",
    name: "PD200XS",
    brand: "MAONO",
    tagline: "USB XLR接続 ダイナミックマイク 専用ソフトウェア付属 単一指向性PCマイク ミュートボタン ボリューム調整 RGBライティング付き PC PS4 PS5 オーディオミキサー対応 ゲーム実況 ライブ配信 ポッドキャスト ナレーション録音",
    price: 13980,
    rating: 4.3,
    reviews: 2987,
    image: "https://m.media-amazon.com/images/I/612ySy1GLyL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CX8H5XYW",
    micFilterTags: ["dynamic"],
    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "40Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "40Hz-16kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク #14" }],
      }],
  },
      {
    id: "mic-dyn-017",
    category: "mic",
    name: "BETA 58A",
    brand: "SHURE",
    tagline: "ダイナミック ボーカル マイク : スーパーカーディオイド 単一指向性 XLR 有線 プロ仕様 ノイズ低減 高耐久性 歌 ライブ 収録 録音 レコーディング DTM 宅録マイクロホン マイクロフォン 【国内正規品/メーカー保証2年】",
    price: 21700,
    rating: 4.5,
    reviews: 95,
    image: "https://m.media-amazon.com/images/I/51Q-1CQoYGL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B31LVXW9",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク #17" }],
      }],
  },
    {
    id: "mic-dyn-021",
    category: "mic",
    name: "e 945",
    brand: "Sennheiser",
    tagline: "スーパーカーディオイドボーカル向けダイナミックマイク。XLR・国内正規品",
    price: 22500,
    rating: 4.6,
    reviews: 1102,
    image: "https://m.media-amazon.com/images/I/61KzZQdCbrL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000NAXCC0",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "40Hz-18kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "40Hz-18kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク #21" }],
      }],
  },
    {
    id: "mic-dyn-024",
    category: "mic",
    name: "e 935",
    brand: "Sennheiser",
    tagline: "カーディオイドボーカル向けダイナミックマイク。XLR・国内正規品",
    price: 22600,
    rating: 4.6,
    reviews: 930,
    image: "https://m.media-amazon.com/images/I/61GVdaIh13L._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000N94RP2",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "40Hz-18kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "40Hz-18kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク #24" }],
      }],
  }]
