import type { Gadget } from "./gadgets"

/** Amazon.co.jp ダイナミックマイク売れ筋 2ページ目（2130075051）。マイク本体のみ。 */
export const micDynamicBestsellersPage2: Gadget[] = [
    {
    id: "mic-dyn2-053",
    category: "mic",
    name: "PGA48-XLR-J",
    brand: "SHURE",
    tagline: "Razer Seiren V2 Pro 30mm USBダイナミックマイク。ハイパスフィルター・アナログゲインリミッター搭載",
    price: 7900,
    rating: 4.4,
    reviews: 37,
    image: "https://m.media-amazon.com/images/I/61MMVQLmsKL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09N955HJJ",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "70Hz-15kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "70Hz-15kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ON/OFFスイッチ", value: "搭載" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #53" }],
      }],
  },
    {
    id: "mic-dyn2-055",
    category: "mic",
    name: "e 845-S",
    brand: "Sennheiser",
    tagline: "スーパーカーディオイド・サイレントON/OFFスイッチ付きライブボーカル用",
    price: 14864,
    rating: 4.5,
    reviews: 474,
    image: "https://m.media-amazon.com/images/I/51H3-Up4SzL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000N94SJC",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "40Hz-16kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "40Hz-16kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ON/OFFスイッチ", value: "搭載" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #55" }],
      }],
  },
  {
    id: "mic-dyn2-056",
    category: "mic",
    name: "D5S",
    brand: "AKG",
    tagline: "TOA DM-1200ハンド型ダイナミックマイク DM-1200",
    price: 14850,
    rating: 4.5,
    reviews: 285,
    image: "https://m.media-amazon.com/images/I/71xhPcyhfbL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000S5L2YA",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "70Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "70Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ON/OFFスイッチ", value: "搭載" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #56" }],
      }],
  },
    {
    id: "mic-dyn2-059",
    category: "mic",
    name: "PodMic",
    brand: "RODE",
    tagline: "ポッドキャスト向けダイナミックマイク。XLR接続",
    price: 18000,
    rating: 4.7,
    reviews: 7084,
    image: "https://m.media-amazon.com/images/I/61V2IPfjMEL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07MSCRCVK",
    micFilterTags: ["dynamic"],
    micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #59" }],
      }],
  },
    {
    id: "mic-dyn2-061",
    category: "mic",
    name: "TOA DM-1200ハンド型ダイナミックマイク DM-1200",
    brand: "—",
    tagline: "TOA DM-1200ハンド型ダイナミックマイク DM-1200",
    price: 12706,
    rating: 3.6,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/41tDjUIpfnL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQGP99Y7",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-12kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-12kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #61" }],
      }],
  },
  {
    id: "mic-dyn2-074",
    category: "mic",
    name: "PRO41",
    brand: "オーディオテクニカ",
    tagline: "PRO41 ダイナミックマイク XLR/単一指向性マイク/ON/OFFスイッチ搭載/ボーカル/スピーチ/マイククランパー付属/マイクポーチ付属/XLRマイクケーブル付属 【国内正規品】",
    price: 8254,
    rating: 4.3,
    reviews: 106,
    image: "https://m.media-amazon.com/images/I/41Sj3zTLpYL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0051DA4NY",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "90Hz-16kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "90Hz-16kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ON/OFFスイッチ", value: "搭載" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #74" }],
      }],
  },
  {
    id: "mic-dyn2-075",
    category: "mic",
    name: "CM5",
    brand: "CLASSIC PRO",
    tagline: "CLASSIC PRO（クラシックプロ）ダイナミックマイク。単一指向性・XLR接続",
    price: 2950,
    rating: 4.3,
    reviews: 29,
    image: "https://m.media-amazon.com/images/I/41QvtGi5jcL._AC_SL1500_.jpg",
    connection: "AUX",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0056YPORY",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "15kHz" },
      { label: "接続方式", value: "AUX" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "15kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "AUX" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #75" }],
      }],
  },
  {
    id: "mic-dyn2-076",
    category: "mic",
    name: "XM1800S",
    brand: "BEHRINGER",
    tagline: "Razer Seiren V2 Pro 30mm USBダイナミックマイク。ハイパスフィルター・アナログゲインリミッター搭載",
    price: 6889,
    rating: 4.6,
    reviews: 3966,
    image: "https://m.media-amazon.com/images/I/719C3gdCVsL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000NJ2TIE",
    micFilterTags: ["dynamic"],
    micUseTags: ["歌・楽器の録音（DTM）"],
    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-15kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-15kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ON/OFFスイッチ", value: "搭載" },
          { label: "セット内容", value: "マイク3本" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #76" }],
      }],
  },
    {
    id: "mic-dyn2-079",
    category: "mic",
    name: "Seiren V2 Pro",
    brand: "Razer",
    tagline: "Razer Seiren V2 Pro 30mm USBダイナミックマイク。ハイパスフィルター・アナログゲインリミッター搭載",
    price: 18359,
    rating: 4.4,
    reviews: 103,
    image: "https://m.media-amazon.com/images/I/51kLgqx9m6L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09KNNL9CR",
    micFilterTags: ["dynamic"],
    micUseTags: ["Web会議・オンライン授業・通話"],
    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: ["ミュート機能"],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ハイパスフィルター", value: "搭載" },
          { label: "アナログゲインリミッター", value: "搭載" },
          { label: "マイクモニタリング", value: "対応" },
          { label: "Amazonランキング", value: "ダイナミックマイク 2ページ目 #79" }],
      }],
  }
]
