import type { Gadget } from "./gadgets"

/** Amazon.co.jp PC用マイク人気ギフト（2152017051 #1–#30）。マイク本体・会議用スピーカーフォン含む。 */
export const micMostGifted: Gadget[] = [{
    id: "mic-mg-002",
    category: "mic",
    name: "K054",
    brand: "COMICA",
    tagline: "FIFINE USBコンデンサーマイク 単一指向性 全段式グースネック 卓上用/会議用/パソコン用 適格請求書発行可 K054",
    price: 4099,
    rating: 4.4,
    reviews: 393,
    image: "https://m.media-amazon.com/images/I/61M6ZFyoWBL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D4Z8LWXC",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-18kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-18kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "ミュートボタン", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #2" }],
      }],
  },
  {
    id: "mic-mg-003",
    category: "mic",
    name: "A6T",
    brand: "FIFINE",
    tagline: "A6T RGB光り カーディオイド指向性 プラグ&プレイ| ワンタッチミュート| PC/PS4/PS5/Windows/MacOS対応| AmpliGame マイクロホンキット| USBケーブル付き",
    price: 7999,
    rating: 4.3,
    reviews: 796,
    image: "https://m.media-amazon.com/images/I/71M5zSSCxsL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09TN7QJ7Y",
    micFilterTags: ["condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                                micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "60Hz-18kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "60Hz-18kHz" },
          { label: "サンプルレート", value: "192kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #3" }],
      }],
  },
  {
    id: "mic-mg-004",
    category: "mic",
    name: "USBスタンドマイク",
    brand: "—",
    tagline: "PC用マイクUSBマイク 全指向性 360°集音 ミュート機能 スタンドマイク 音量調節可能 LEDランプ付き Skype zoom通話 ライブ配信 ゲーム実況 PC PS4 Windows Mac 対応",
    price: 2710,
    rating: 3.8,
    reviews: 214,
    image: "https://m.media-amazon.com/images/I/41Fo34x+7UL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B086QVF3B9",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）", "ゲインノブ（音量調節ノブ）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #4" }],
      }],
  },
  {
    id: "mic-mg-005",
    category: "mic",
    name: "Sync 20+",
    brand: "Poly",
    tagline: "スピーカーフォン USB-C/Bluetooth対応 Bluetoothドングル付属モデル 会議用 PC/Mac/スマートフォン対応 Teams/Zoom対応 簡易パッケージ",
    price: 24555,
    rating: 4.2,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/81KbsRBVrFL._AC_SL1500_.jpg",
    connection: "USB Type-C / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09BZH9J4Q",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / Bluetooth" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / Bluetooth" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "Bluetooth", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #5" }],
      }],
  },
  {
    id: "mic-mg-006",
    category: "mic",
    name: "SP300",
    brand: "Kaysuda",
    tagline: "SP300 スピーカーフォン Bluetooth対応 マイクスピーカー 会議用スピーカーマイク PCマイク 全指向性マイク 双方向通話 オンライン会議/ウェブ会議/在宅勤務/テレワーク/オンライン教育 Zoom/Skype/Teams/Go",
    price: 6799,
    rating: 3.5,
    reviews: 40,
    image: "https://m.media-amazon.com/images/I/71gN6838AAS._AC_SL1500_.jpg",
    connection: "USB Type-C / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B097TF2TYX",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / Bluetooth" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / Bluetooth" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "Bluetooth", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #6" }],
      }],
  },
  {
    id: "mic-mg-007",
    category: "mic",
    name: "SoloCast 2",
    brand: "HyperX",
    tagline: "内蔵ショックマウント ゲーム実況 USBマイク ブラック 日本正規代理店品 AR0A0AA ポップフィルター,テレワーク,ストリーマー,コンテンツクリエーター,ゲームプレイヤー向け,PC,Mac,PS4,PS5対応,メーカー保証2年間,カーディオイド（単一指向性）,タップでミュート,振動ノイズを抑制",
    price: 8982,
    rating: 4.4,
    reviews: 2544,
    image: "https://m.media-amazon.com/images/I/71jznpAUWgL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FLKJ7FH7",
    micFilterTags: ["condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96KHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96KHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #7" }],
      }],
  },
  {
    id: "mic-mg-008",
    category: "mic",
    name: "HS-MC07UBK",
    brand: "エレコム",
    tagline: "2 TX + 1 スタンダードRX + 充電ケース） iPhone 17/16/15＆Android／カメラ／タブレット／PC用ワイヤレスマイク 48時間駆動 400 m伝送 多色Magカバー",
    price: 1027,
    rating: 3.6,
    reviews: 114,
    image: "https://m.media-amazon.com/images/I/519Xb0yLM5S._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B097PDS4Y4",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "対応" },
          { label: "LED", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #8" }],
      }],
  },
    {
    id: "mic-mg-013",
    category: "mic",
    name: "Mic Mini 2",
    brand: "DJI",
    tagline: "2 TX + 1 スタンダードRX + 充電ケース） iPhone 17/16/15＆Android／カメラ／タブレット／PC用ワイヤレスマイク 48時間駆動 400 m伝送 多色Magカバー",
    price: 14520,
    rating: 4.6,
    reviews: 693,
    image: "https://m.media-amazon.com/images/I/61xDA0eTDQL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G39C97WQ",
    micFilterTags: ["wireless","pin"],
                                micUseTags: ["Vlog・動画撮影（屋外）"],
                                micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "Bluetooth" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #13" }],
      }],
  },
  {
    id: "mic-mg-015",
    category: "mic",
    name: "MO-MIC04L-W",
    brand: "e-Better",
    tagline: "PCマイク USB マイクベース ミュート機能 全指向性360° 3.5mm 白 MO-MIC04L-W リモートワーク テレワーク",
    price: 1480,
    rating: 2.9,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/51iLeNrtIPL._AC_SL1500_.jpg",
    connection: "USB Type-A / 3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BXWKW4N2",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A / 3.5mm" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / 3.5mm" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #15" }],
      }],
  },
  {
    id: "mic-mg-016",
    category: "mic",
    name: "YVC-331",
    brand: "ヤマハ",
    tagline: "ヤマハ(YAMAHA) ユニファイドコミュニケーションマイクスピーカーシステム(有線モデル",
    price: 50607,
    rating: 4.4,
    reviews: 61,
    image: "https://m.media-amazon.com/images/I/61zUlkXeMkL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09QX6FX3Q",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "190Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "190Hz-20kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #16" }],
      }],
  },
  {
    id: "mic-mg-017",
    category: "mic",
    name: "Seiren X",
    brand: "Razer",
    tagline: "ストリーミング 実況 配信 Quartz Pink ピンク 単一指向性 PC Windows10 PS5 PS4【日本正規代理店保証品】",
    price: 2710,
    rating: 4.1,
    reviews: 812,
    image: "https://m.media-amazon.com/images/I/61-vVMItbAL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07VBCGHFT",
    micFilterTags: ["condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "44.1kHz/48kHz/96kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "44.1kHz/48kHz/96kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #17" }],
      }],
  },
  {
    id: "mic-mg-018",
    category: "mic",
    name: "U30K",
    brand: "—",
    tagline: "PC用マイク コンデンサマイク ダイナミックマイク 全指向性 高感度 360°集音 ワンタッチミュート 小型卓上 有線 PC会議実況",
    price: 2710,
    rating: 4.7,
    reviews: 285,
    image: "https://m.media-amazon.com/images/I/71sJ4kr1KQL._AC_SL1500_.jpg",
    connection: "USB Type-C / USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJZ1TCQP",
    micFilterTags: ["dynamic","stand"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "ミュートボタン", value: "ワンタッチミュート" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #18" }],
      }],
  },
  {
    id: "mic-mg-019",
    category: "mic",
    name: "DM30 RGB",
    brand: "MAONO",
    tagline: "MAONO USB コンデンサーマイク ゲーミングマイク PC マイク 専用ソフトウェア RGBライティング ヘッドホン出力端子あり 単一指向性 プラグ＆プレイ YouTube Skype ゲーム実況 ライブ配信 在宅勤務 Windows/",
    price: 8499,
    rating: 4.3,
    reviews: 823,
    image: "https://m.media-amazon.com/images/I/61ZSs0HzAiL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BYZFL8RJ",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "24bit/48kHz" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "24bit/48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "RGBライティング", value: "対応" },
          { label: "イヤホンジャック", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #19" }],
      }],
  },
  {
    id: "mic-mg-021",
    category: "mic",
    name: "SP300U",
    brand: "Kaysuda",
    tagline: "SP300U スピーカーフォン マイクスピーカー 会議用スピーカーマイク PCマイク 全指向性マイク Zoom/Skype/Teams/Google meet などに対応",
    price: 6799,
    rating: 3.8,
    reviews: 34,
    image: "https://m.media-amazon.com/images/I/61xjM3ZcBVL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0932MGBY8",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #21" }],
      }],
  },
  {
    id: "mic-mg-022",
    category: "mic",
    name: "STM30BK",
    brand: "SEIKO",
    tagline: "SEIKO セイコー ピックアップマイク ブラック STM30BK",
    price: 2200,
    rating: 4.3,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/51jE+KJDhpL._AC_SL1500_.jpg",
    connection: "3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DW8VNQHC",
    micFilterTags: ["pin","condenser"],
                                micUseTags: [],
                                micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "3.5mm" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピックアップマイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピックアップマイク" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "3.5mm" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #22" }],
      }],
  },
  {
    id: "mic-mg-025",
    category: "mic",
    name: "Speak 710 MS",
    brand: "Jabra",
    tagline: "Jabra Speak 710 MS マイクロソフト認定スピーカーフォン Web会議 エコーキャンセラー内蔵 Bluetooth接続 USB接続",
    price: 14780,
    rating: 4.4,
    reviews: 443,
    image: "https://m.media-amazon.com/images/I/71YgNUKn-VL._AC_SL1500_.jpg",
    connection: "USB Type-A / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B06XX2N987",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A / Bluetooth" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "会議用スピーカーフォン" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "会議用スピーカーフォン" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / Bluetooth" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "エコーキャンセリング", value: "対応" },
          { label: "Bluetooth", value: "対応" },
          { label: "Microsoft認証", value: "対応" },
          { label: "エコーキャンセラー", value: "内蔵" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #25" }],
      }],
  },
  {
    id: "mic-mg-026",
    category: "mic",
    name: "PD100X",
    brand: "MAONO",
    tagline: "MAONO XLR/USB ゲーミングマイク ノイズキャンセリング PCマイク ポッドキャスト ストリーミング用 ダイナミックマイク ミュートボタン 単一指向性 YouTube 録音 ボイスチャット ライブ配信 ゲーム実況に PD100X",
    price: 6944,
    rating: 4.4,
    reviews: 2311,
    image: "https://m.media-amazon.com/images/I/61VscaoyfML._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DP54XTCG",
    micFilterTags: ["dynamic","stand"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "40Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "48kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "40Hz-16kHz" },
          { label: "サンプルレート", value: "48kHz/24bit" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #26" }],
      }],
  },
  {
    id: "mic-mg-027",
    category: "mic",
    name: "AIRHUG",
    brand: "AIRHUG",
    tagline: "AIRHUG 会議用スピーカーマイク（Bluetooth & USB接続対応） 360°全方位集音、高度なノイズリダクション機能、USB-Cプラグ＆プレイ対応、ZoomおよびMicrosoft Teams対応",
    price: 5999,
    rating: 4,
    reviews: 1974,
    image: "https://m.media-amazon.com/images/I/81QsFFm+-xL._AC_SL1500_.jpg",
    connection: "USB Type-A / Bluetooth",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09Y155R6Z",
    micFilterTags: ["conference"],
                                micUseTags: ["Web会議・オンライン授業・通話"],
                                micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-24kHz" },
      { label: "接続方式", value: "USB Type-A / Bluetooth" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "ハンドヘルド型内蔵マイク" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ハンドヘルド型内蔵マイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-24kHz" },
          { label: "サンプルレート", value: "48kHz" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / Bluetooth" },
          { label: "電源", value: "充電式 (USB給電 / バッテリー)" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Bluetooth", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #27" }],
      }],
  },
  {
    id: "mic-mg-028",
    category: "mic",
    name: "AT9933USB",
    brand: "オーディオテクニカ",
    tagline: "audio-technica USBコンデンサーマイク 在宅勤務/録音/動画配信/ポッドキャスト AT9933USB",
    price: 2700,
    rating: 4.2,
    reviews: 170,
    image: "https://m.media-amazon.com/images/I/51Pi6apbIML._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00T5ANN00",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "40Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "40Hz-16kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #28" }],
      }],
  },
  {
    id: "mic-mg-029",
    category: "mic",
    name: "HS-MC06BK",
    brand: "エレコム",
    tagline: "エレコム コンデンサーマイク 3.5mm接続 パソコンマイク クリップ付 1.6m HS-MC06BK",
    price: 608,
    rating: 4,
    reviews: 389,
    image: "https://m.media-amazon.com/images/I/51YJ2NWCPiL._AC_SL1500_.jpg",
    connection: "3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B01HGGWB7K",
    micFilterTags: ["pin","condenser"],
                                micUseTags: [],
                                micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "3.5mm" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "3.5mm" },
          { label: "電源", value: "有線給電" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #29" }],
      }],
  },
  {
    id: "mic-mg-030",
    category: "mic",
    name: "K054",
    brand: "FIFINE",
    tagline: "FIFINE USBコンデンサーマイク 単一指向性 全段式グースネック 卓上用/会議用/パソコン用 適格請求書発行可 K054",
    price: 4099,
    rating: 4.4,
    reviews: 130,
    image: "https://m.media-amazon.com/images/I/61y1+d8gYZL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B6FTQTS8",
    micFilterTags: ["stand","condenser"],
                                micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                                micFeatureTags: ["ミュートボタン（タッチミュート）", "ゲインノブ（音量調節ノブ）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-18kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" }],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-18kHz" },
          { label: "サンプルレート", value: "—" }],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "対応" },
          { label: "音量調整", value: "対応" },
          { label: "Amazonランキング", value: "PC用マイク 人気ギフト #30" }],
      }],
  }
]
