import type { Gadget } from "./gadgets"

/** Amazon.co.jp PC用マイク ストリーミング検索（computers / 17833755051）。マイク本体・会議用スピーカーフォン含む。 */
export const micComputersSearchStreaming: Gadget[] = [
        {
    id: "mic-strm-0004",
    category: "mic",
    name: "Seiren V3 Mini",
    brand: "Razer",
    tagline: "3x14mmカプセル、4パターン、ゲインとミュート、ヘッドホンボル、レイテンシーなし3.5mm出力、Knox Gearポップフィルター付き",
    price: 6880,
    rating: 4.6,
    reviews: 1026,
    image: "https://m.media-amazon.com/images/I/61YoVaG-ShL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CMTQPWQ8",
    micFilterTags: ["stand","condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "ミュートボタン", value: "タップ式ミュートセンサー" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #4" },
        ],
      },
    ],
  },
              {
    id: "mic-strm-0011",
    category: "mic",
    name: "GRAPHT Compact-Mic XLR Streamer Edition",
    brand: "GRAPHT",
    tagline: "【アームセット】 コンデンサーマイク 超小型 日本メーカー XLR接続 マイクアーム ロープロファイル 白 Vtuber 配信 ゲーム実況 鋭指向性 小型 ケーブル一体型 xlr端子 耐荷重 2kg 360度回転 角度調節可能 マイククリップ付き",
    price: 21940,
    rating: 2.9,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/51rn6tEIkUL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GSQPND7C",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "指向性切替対応 (マルチパターン)" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "指向性切替対応 (マルチパターン)" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #11" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0012",
    category: "mic",
    name: "【2025 New Release・Enhanced Sound Quality】BILIWAL …",
    brand: "BILIWAL",
    tagline: "【2026新型】BILIWAL ピンマイク ワイヤレス iPhone/Android/PC用 自動ペアリング 接続ロック 瞬時接続 音画同期 超軽量 Type-C ノイズ軽減 ペアリングロック機能 リバーブ機能 9時間連続使用 360°集音 超ミニ クリップ式 2個セット Vlogカメラ対応",
    price: 3680,
    rating: 3.7,
    reviews: 17,
    image: "https://m.media-amazon.com/images/I/71C5W10PbdL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FH27MKW5",
    micFilterTags: ["condenser","pin","wireless"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "Vlog・動画撮影（屋外）"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ピンマイク" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ピンマイク" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "クリップ付き", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #12" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0013",
    category: "mic",
    name: "QuadCast2",
    brand: "HyperX",
    tagline: "コンデンサーマイク USBマイク ゲーム実況 テレワーク ライブ配信 フロスト 日本正規代理店品 AN1D9AA アンバサダー愛用,ストリーマー,コンテンツクリエーター,ゲーマー向け,PC,Mac,2年間のメーカー保証,24bit/96KHzのスタジオレベルの音質,LEDステータスインジケーター",
    price: 22800,
    rating: 4.6,
    reviews: 1292,
    image: "https://m.media-amazon.com/images/I/51x+qqX44-L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DXW278KB",
    micFilterTags: ["stand","condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ゲインノブ（音量調節ノブ）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "４モード" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "４モード" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #13" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0014",
    category: "mic",
    name: "AM8T",
    brand: "FIFINE",
    tagline: "FIFINE AM8TW XLR/USB Gaming Microphone Set for Streaming, Podcasting, Dynamic Microphone, PC Microphone, Boom Arm Stand,",
    price: 10799,
    rating: 4.4,
    reviews: 139,
    image: "https://m.media-amazon.com/images/I/71Kpw41yVTL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CF23FR3T",
    micFilterTags: ["dynamic","stand"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "48kHz/16bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #14" },
        ],
      },
    ],
  },
                    {
    id: "mic-strm-0027",
    category: "mic",
    name: "QuadCast2S",
    brand: "HyperX",
    tagline: "コンデンサーマイク USBマイク ゲーム実況 テレワーク ライブ配信 ブラック 日本正規代理店品 9A273AA 指向性の変更可能,単一指向性、全方向性、双指向性、ステレオ,RGBライティング,ストリーマー,コンテンツクリエーター,ゲーマー向け,PC,Mac,メーカー保証2年間,LEDインジケーター,",
    price: 29716,
    rating: 4.6,
    reviews: 750,
    image: "https://m.media-amazon.com/images/I/61be+CZMIkL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DG9X4WHW",
    micFilterTags: ["stand","condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "指向性切替対応 (4パターン)" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz/16bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "指向性切替対応 (4パターン)" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "48kHz/16bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #27" },
        ],
      },
    ],
  },
        {
    id: "mic-strm-0031",
    category: "mic",
    name: "AM8TW XLR/USB Gaming Microphone Set for Streaming…",
    brand: "FIFINE",
    tagline: "FIFINE AM8TW XLR/USB Gaming Microphone Set for Streaming, Podcasting, Dynamic Microphone, PC Microphone, Boom Arm Stand,",
    price: 11199,
    rating: 4.1,
    reviews: 39,
    image: "https://m.media-amazon.com/images/I/71O6DVRaiXL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CF269L4N",
    micFilterTags: ["conference"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #31" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0032",
    category: "mic",
    name: "FlipCast Dynamic Microphone XLR/USB Dual Connecti…",
    brand: "HyperX",
    tagline: "ダイナミックマイク 単一指向性 タップミュート対応 ゲーミング テレワーク ブラック 日本正規代理店品 B2CM1AA ,XLR/USB,デュアルコネクション,カーディオイドマルチファンクションノブ搭載,NGENUITY対応,テレワーク,ストリーマー,コンテンツクリエーター,ゲーマー向け,PC,Mac,PS4,PS5,Nintendo,Switch,保証2年間,",
    price: 31980,
    rating: 4.5,
    reviews: 83,
    image: "https://m.media-amazon.com/images/I/61g9pDg870L._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FKTCPR94",
    micFilterTags: ["dynamic"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "-20kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "-20kHz" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #32" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0033",
    category: "mic",
    name: "Sanwa Supply MM-MCTC02NC Noise Canceling USB Micr…",
    brand: "サンワサプライ",
    tagline: "PC PS5/4使用可能 XLR マイク 配信用 ゲーム ストリーマー用 コンテンツクリエーター ソナー オーディオ ソフトウェア AIノイズキャンセリング 単一指向性 カーディオイド",
    price: 8640,
    rating: 1,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61wVfUAs2eL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJD41V2J",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-20kHz" },
          { label: "サンプルレート", value: "48kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #33" },
        ],
      },
    ],
  },
            {
    id: "mic-strm-0039",
    category: "mic",
    name: "FIFINE USB/XLRダイナミックマイク AM8TP",
    brand: "FIFINE",
    tagline: "USB/XLRダイナミックマイク 単一指向性 PC/PS4/PS5対応 アーム付き ゲーミング/配信用 ピンク AM8TP 音声モニター, ワンタッチ式ミュート, RGBライト, マイクとイヤホン端子音量調節機能搭載, USB-AとType-C給電ケーブル付属, パソコン, XLR機器適用",
    price: 11199,
    rating: 4.3,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/61ga131-QlL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CF24YH9S",
    micFilterTags: ["conference"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電 (USB)" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #39" },
        ],
      },
    ],
  },
      {
    id: "mic-strm-0042",
    category: "mic",
    name: "Seiren V3 Chroma",
    brand: "Razer",
    tagline: "コンデンサーマイク マルチファンクション タップ式ミュートセンサー ゲーミングマイク USB マイク 配信 セイレン ブイスリー クローマ 【日本正規代理店保証品】",
    price: 21980,
    rating: 4.6,
    reviews: 191,
    image: "https://m.media-amazon.com/images/I/71CnqjberCL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CNXKMSJG",
    micFilterTags: ["stand","condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "40Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "40Hz-16kHz" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #42" },
        ],
      },
    ],
  },
          {
    id: "mic-strm-0047",
    category: "mic",
    name: "MAONO PD200X",
    brand: "MAONO",
    tagline: "ゲーミングマイク USB/XLR PCマイク 単一指向性ダイナミックマイク 専用ソフトウェア ミュートボタン RGBライティング",
    price: 12699,
    rating: 4.3,
    reviews: 2987,
    image: "https://m.media-amazon.com/images/I/51kUjSEv6mL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BW87WZSV",
    micFilterTags: ["dynamic"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "40Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "40Hz-16kHz" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #47" },
        ],
      },
    ],
  },
    {
    id: "mic-strm-0050",
    category: "mic",
    name: "SteelSeries Alias Pro",
    brand: "SteelSeries",
    tagline: "PC PS5/4使用可能 XLR マイク 配信用 ゲーム ストリーマー用 コンテンツクリエーター ソナー オーディオ ソフトウェア AIノイズキャンセリング 単一指向性 カーディオイド",
    price: 38495,
    rating: 4.4,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/81PIkCNzI4L._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CK4MM8XB?th=1",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "24bit / 48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-20kHz" },
          { label: "サンプルレート", value: "24bit / 48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #50" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0051",
    category: "mic",
    name: "GRAPHT XLR",
    brand: "GRAPHT",
    tagline: "オーディオテクニカ USBマイク PC マイク コンデンサーマイクロホン ストリーマー コンテンツクリエーター ゲーマー ボイスチャット 実況 Windows MAC 国内正規品",
    price: 14960,
    rating: 4.6,
    reviews: 20,
    image: "https://m.media-amazon.com/images/I/513Yf4PGEqL._AC_SL1500_.jpg",
    connection: "XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS5Q54Z3",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "XLR" },
      { label: "サンプルレート", value: "44.1kHz、/48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "44.1kHz、/48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #51" },
        ],
      },
    ],
  },
        {
    id: "mic-strm-0055",
    category: "mic",
    name: "Snowball BM250W",
    brand: "Logicool G",
    tagline: "BM250W USB ゲーミングマイク コンデンサーマイク 単一指向性 実況 ストリーミング 配信 マイク コンパクト ゲーム ゲーミング PC Mac PS5 PS4 ホワイト 白 国内正規品 2年間メーカー保証",
    price: null,
    rating: 3.9,
    reviews: 46,
    image: "https://m.media-amazon.com/images/I/516FtMy+aUL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C1ZJVFSS",
    micFilterTags: ["stand","condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "44.1kHz、/48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "44.1kHz、/48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #55" },
        ],
      },
    ],
  },
    {
    id: "mic-strm-0057",
    category: "mic",
    name: "Audio-Technica USB Microphone PC Microphone Conde…",
    brand: "—",
    tagline: "オーディオテクニカ USBマイク PC マイク コンデンサーマイクロホン ストリーマー コンテンツクリエーター ゲーマー ボイスチャット 実況 Windows MAC 国内正規品",
    price: 17000,
    rating: 4.5,
    reviews: 1019,
    image: "https://m.media-amazon.com/images/I/81YKCbgqkuL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00Q3K32I8",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "44.1kHz、/48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "44.1kHz、/48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #57" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0061",
    category: "mic",
    name: "Elgato Wave: 3 - Premium USB Capacity - Microphon…",
    brand: "—",
    tagline: "プレミアムUSB容量ーマイク、 「 Call of Duty®: Black Ops 6 」スペシャルエディション 配信、ポッドキャスト、再生、およびホームオフィス適用、無料のミキサーソフトウェア、サウンドエフェクトプラグイン、歪みなし、プラグ&プレイMac/PC対応",
    price: 20565,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61QFjLg4JHL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DHCGFBPN",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "70Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz、96kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "70Hz-20kHz" },
          { label: "サンプルレート", value: "48kHz、96kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #61" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0062",
    category: "mic",
    name: "Elgato Wave:1 - Premium Cardioid USB Condenser Mi…",
    brand: "—",
    tagline: "カーディオイドUSBマイク AP-WUMIC-B1 SP1008",
    price: null,
    rating: 4.7,
    reviews: 2377,
    image: "https://m.media-amazon.com/images/I/61chF9lKLzL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B088P2KKHS",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "70Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "70Hz-20kHz" },
          { label: "サンプルレート", value: "48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #62" },
        ],
      },
    ],
  },{
    id: "mic-strm-0069",
    category: "mic",
    name: "NZXT CAPSULE BLACK",
    brand: "—",
    tagline: "カーディオイドUSBマイク AP-WUMIC-B1 SP1008",
    price: null,
    rating: 4.5,
    reviews: 620,
    image: "https://m.media-amazon.com/images/I/618PQZYODmL._AC_SL1500_.jpg",
    connection: "USB Type-A / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09DTJ3NFS",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "96kHz" },
      { label: "接続方式", value: "USB Type-A / XLR" },
      { label: "サンプルレート", value: "24bit / 96kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "96kHz" },
          { label: "サンプルレート", value: "24bit / 96kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #69" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0070",
    category: "mic",
    name: "Yeti GX",
    brand: "Logicool G",
    tagline: "ダイナミックマイク G-YETI-GX-WH ストリーミング配信 スーパーカーディオイド ノイズ軽減 RGB LIGHTSYNC 対応 USB BLUE VO!CE PC MAC ゲーミング マイク 白 ホワイト",
    price: 28882,
    rating: 3.8,
    reviews: 51,
    image: "https://m.media-amazon.com/images/I/51PRX4x-UEL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D1R585XT",
    micFilterTags: ["dynamic","stand"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "60Hz-19kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "60Hz-19kHz" },
          { label: "サンプルレート", value: "96kHz、ビットレート24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "RGBライティング", value: "対応" },
          { label: "ノイズ軽減", value: "BLUE VO!CE" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #70" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0071",
    category: "mic",
    name: "Audio-Technica ATR2100x-USB USB Microphone for Te…",
    brand: "—",
    tagline: "ショックマウント AT8455 USB-Type-C ドライバー不要 ゲーミングマイク 配信用マイク 宅録 Windows MAC PS4 PS5 国内正規品",
    price: 28200,
    rating: 4.2,
    reviews: 203,
    image: "https://m.media-amazon.com/images/I/71wQAiEPKYL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08KDVW9Z3",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "24bit / 192kHz" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "24bit / 192kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #71" },
        ],
      },
    ],
  },
      {
    id: "mic-strm-0074",
    category: "mic",
    name: "AKG Pro Audio Ara Professional USB-C Condenser Mi…",
    brand: "Blue",
    tagline: "USB-C コンデンサーマイク デュアルパターン オーディオキャプチャモード ポッドキャスティング ビデオブログ ゲーム ストリーミング用 ブルー&シルバー",
    price: 11917,
    rating: 4.6,
    reviews: 272,
    image: "https://m.media-amazon.com/images/I/61b9fd3RPnL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09F2FM43B",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "2モード (単一/全指向性)" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "2モード (単一/全指向性)" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #74" },
        ],
      },
    ],
  },
      {
    id: "mic-strm-0077",
    category: "mic",
    name: "Audio Technica Condenser Microphone AT2020USB-XP …",
    brand: "—",
    tagline: "ショックマウント AT8455 USB-Type-C ドライバー不要 ゲーミングマイク 配信用マイク 宅録 Windows MAC PS4 PS5 国内正規品",
    price: 28200,
    rating: 5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/81TbBAPV+SL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C8LTKWLG",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "24bit / 192kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "24bit / 192kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "内蔵ショックマウント", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #77" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0078",
    category: "mic",
    name: "RODE Microphones Road Microphones Pod Microphone …",
    brand: "—",
    tagline: "コンデンサーマイク 録音 レコーディング 歌 楽器 ギター ドラム 演奏 実況 配信 ゲーム ゲーミング ポッドキャスト MOTIVシリーズ iOS Android Mac Windows対応 MV88+STEREO-USB ブラック USBケーブル付属 【国内正規品/メーカー保証2年】",
    price: 40000,
    rating: 4.2,
    reviews: 136,
    image: "https://m.media-amazon.com/images/I/717WRAhMD9L._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9LXG8LH",
    micFilterTags: ["dynamic"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #78" },
        ],
      },
    ],
  },
      {
    id: "mic-strm-0081",
    category: "mic",
    name: "FEELWORLD VM1 Pink Gaming PC Microphone USB Conde…",
    brand: "—",
    tagline: "FEELWORLD VM1 ピンク USB ゲーミングコンデンサーマイク PC用 ブームアームスタンド ノイズキャンセリング、ミュート、RGBライト、ゲーム機器、ギフト用、",
    price: 11009,
    rating: 4.6,
    reviews: 248,
    image: "https://m.media-amazon.com/images/I/61MyntLGGYL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DM12LT7Q",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "50Hz-16kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "50Hz-16kHz" },
          { label: "サンプルレート", value: "48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #81" },
        ],
      },
    ],
  },
              {
    id: "mic-strm-0088",
    category: "mic",
    name: "SHURE MV88+ ステレオ USB マイクロホン",
    brand: "—",
    tagline: "コンデンサーマイク 録音 レコーディング 歌 楽器 ギター ドラム 演奏 実況 配信 ゲーム ゲーミング ポッドキャスト MOTIVシリーズ iOS Android Mac Windows対応 MV88+STEREO-USB ブラック USBケーブル付属 【国内正規品/メーカー保証2年】",
    price: 23380,
    rating: 4.2,
    reviews: 165,
    image: "https://m.media-amazon.com/images/I/71VAOfpbvcL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09BZXP8Y1",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "４モード" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "４モード" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #88" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0089",
    category: "mic",
    name: "AVerMedia USB Microphone Record with Cardioid Pat…",
    brand: "—",
    tagline: "USB-C 出力 カーディオイド オムニ ステレオ 双方向 192k サンプルレート ボリュームコントロール ゲインコントロール クイックミュート 3.5mm AUX プラグアンドプレイ",
    price: 3575,
    rating: 4.3,
    reviews: 89,
    image: "https://m.media-amazon.com/images/I/51Ypgb4i5CL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B071ZB53KM",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "100Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "100Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #89" },
        ],
      },
    ],
  },
            {
    id: "mic-strm-0095",
    category: "mic",
    name: "Blapsuro USBコンピュータマイク M8",
    brand: "—",
    tagline: "ミュートボタンとRGB照明付き プラグアンドプレイマイク 会議 ゲーム YouTube用 デスクトップPCマイク Mac/Window用 ブラック",
    price: 3575,
    rating: 3.8,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/51TZNdbTIiL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DKP4V5V1",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-16kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-16kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Plug&Play", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #95" },
        ],
      },
    ],
  },
                      {
    id: "mic-strm-0106",
    category: "mic",
    name: "BRIBAT USBコンデンサーマイク",
    brand: "—",
    tagline: "プラグアンドプレイRGBデスクトップマイク ワンタッチミュート カーディオイドノイズキャンセリングコンピューターマイク Twitch、YouTube、PCやノートパソコンでの録音用",
    price: 8039,
    rating: 4.7,
    reviews: 21,
    image: "https://m.media-amazon.com/images/I/71sWJkQ8HmL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTZ865L3",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Plug&Play", value: "対応" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #106" },
        ],
      },
    ],
  },
        {
    id: "mic-strm-0113",
    category: "mic",
    name: "JLab JBuds Talk USB Gaming Streaming Microphone W…",
    brand: "—",
    tagline: "USB-C マイク カーディオイド、オムニ、ステレオ、双方向モード、ゲインとミュートコントロール、3.5mm AUX、ホワイト",
    price: 11255,
    rating: 4.4,
    reviews: 43,
    image: "https://m.media-amazon.com/images/I/81DkwyYLxTL._AC_SL1500_.jpg",
    connection: "USB Type-C / USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BFL1S9FP",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C / USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #113" },
        ],
      },
    ],
  },
                                        {
    id: "mic-strm-0133",
    category: "mic",
    name: "Adesso Xtream M1",
    brand: "—",
    tagline: "有線コンデンサーマイク 6フィート 20Hz~20kHz 680オーム 38dB 全指向性 グースネック デスクトップ USB",
    price: 7654,
    rating: 3.9,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/51Ma0xpkpCL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09MJLF4WX",
    micFilterTags: ["condenser","stand"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #133" },
        ],
      },
    ],
  },
    {
    id: "mic-strm-0135",
    category: "mic",
    name: "AVerMedia USB Microphone Streaming Podcasting Gam…",
    brand: "—",
    tagline: "ポッドキャスティング カーディオイドポーラーパターン付きゲーム用 三脚スタンド ヘッドホン出力 ミュートボタン オールメタル",
    price: 12523,
    rating: 4.3,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/41NuOq1FkrL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DFC4GTVN",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "スタンド付属", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #135" },
        ],
      },
    ],
  },
              {
    id: "mic-strm-0142",
    category: "mic",
    name: "FIFINE K658 USBゲーミングダイナミックマイク",
    brand: "FIFINE",
    tagline: "クイックミュート付き PCストリーミング用ゲインコントロール、ヘッドホンジャック、カーディオイドピックアップ、RGBコントロール、ショックマウント",
    price: 18349,
    rating: 4.7,
    reviews: 1128,
    image: "https://m.media-amazon.com/images/I/61lCdWdqYVL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09BNMJM2C",
    micFilterTags: ["dynamic"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "内蔵ショックマウント", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "イヤホンジャック", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #142" },
        ],
      },
    ],
  },
                                {
    id: "mic-strm-0162",
    category: "mic",
    name: "JLab Epic Talk USB ゲーミングストリーミングマイク",
    brand: "—",
    tagline: "USB-C 出力 カーディオイド オムニ ステレオ 双方向 192k サンプルレート ボリュームコントロール ゲインコントロール クイックミュート 3.5mm AUX プラグアンドプレイ",
    price: 20908,
    rating: 4.6,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/81xSCGi-qqL._AC_SL1500_.jpg",
    connection: "USB Type-A / 3.5mm",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BFJRZHJJ",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "４モード" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A / 3.5mm" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "トライカプセルアレイ" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "トライカプセルアレイ" },
          { label: "指向性", value: "４モード" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A / 3.5mm" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #162" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0163",
    category: "mic",
    name: "WMT USB Microphone, Condenser Gaming Microphone f…",
    brand: "—",
    tagline: "192kHz/32bitダイナミックマイク PC用 USB/XLR ゲーミングマイク95dB SNR、リアルタイムモニタリング、タッチミュート、RGB",
    price: 13168,
    rating: 4.4,
    reviews: 1201,
    image: "https://m.media-amazon.com/images/I/714reGgb8mL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09YCWFKNC",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "192kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "192kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #163" },
        ],
      },
    ],
  },
      {
    id: "mic-strm-0166",
    category: "mic",
    name: "MAILANGSHI 192kHz/32bitダイナミックマイク PC用 USB/XLR ゲーミン…",
    brand: "—",
    tagline: "192kHz/32bitダイナミックマイク PC用 USB/XLR ゲーミングマイク95dB SNR、リアルタイムモニタリング、タッチミュート、RGB",
    price: 23330,
    rating: 4.4,
    reviews: 176,
    image: "https://m.media-amazon.com/images/I/61cUT8B+QQL._AC_SL1500_.jpg",
    connection: "USB Type-C / XLR",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTXG96MZ",
    micFilterTags: ["dynamic"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-C / XLR" },
      { label: "サンプルレート", value: "192kHz/32ビット" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "192kHz/32ビット" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C / XLR" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #166" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0168",
    category: "mic",
    name: "CHERRY UM 3.0 USB Microphone Podcast Streaming Ho…",
    brand: "—",
    tagline: "CHERRY UM 3.0 USBマイク ポッドキャスト ストリーミング ホームオフィス カーディオイド特性 ヘッドホン接続",
    price: 16449,
    rating: 3.8,
    reviews: 48,
    image: "https://m.media-amazon.com/images/I/61KzX4svirL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BVBBVB9R",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96KHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96KHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #168" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0169",
    category: "mic",
    name: "Yeti GX",
    brand: "Logicool G",
    tagline: "スロンマックス MDrill One Pro 96kHz/24bit マルチ指向性 USBマイク",
    price: 33353,
    rating: 4.4,
    reviews: 58,
    image: "https://m.media-amazon.com/images/I/41dZ6leOWVL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07W4DH8KG",
    micFilterTags: ["dynamic"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "超単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-C" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "ダイナミック" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "ダイナミック" },
          { label: "指向性", value: "超単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-C" },
          { label: "電源", value: "有線給電" },
          { label: "Plug&Play", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #169" },
        ],
      },
    ],
  },
      {
    id: "mic-strm-0172",
    category: "mic",
    name: "Thronmax MDrill One Pro 96kHz/24bit Multi-Directi…",
    brand: "—",
    tagline: "スロンマックス MDrill One Pro 96kHz/24bit マルチ指向性 USBマイク",
    price: null,
    rating: 4.4,
    reviews: 2544,
    image: "https://m.media-amazon.com/images/I/31bgDKW8YVL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09DSRLKBT",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #172" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0173",
    category: "mic",
    name: "Mars Gaming MMIC-CX Professional Studio Microphon…",
    brand: "—",
    tagline: "ウェブカメラとコンデンサーマイク - 1080p HD ウェブカメラ プロカーディオイドコンデンサーマイク - HD USBカメラとコンピューターマイク",
    price: 12947,
    rating: 3.8,
    reviews: 47,
    image: "https://m.media-amazon.com/images/I/612F-oq3+4L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DT9JVSRZ",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音", "歌・楽器の録音（DTM）"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48KHｚ" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "48KHｚ" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ノイズキャンセリング", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #173" },
        ],
      },
    ],
  },
            {
    id: "mic-strm-0180",
    category: "mic",
    name: "Movo WebMic-HD",
    brand: "—",
    tagline: "ウェブカメラとコンデンサーマイク - 1080p HD ウェブカメラ プロカーディオイドコンデンサーマイク - HD USBカメラとコンピューターマイク",
    price: 12454,
    rating: 4,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/51j3OnaUG7L._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09JQZH7TP",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "—" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "—" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #180" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0182",
    category: "mic",
    name: "ENHANCE USB Microphone for PC - Omnidirectional C…",
    brand: "—",
    tagline: "USBゲーミングマイク (25mmコンデンサーカプセル、192kHz/24ビット、カーディオイド、ハイパスフィルター、ポップフィルター内蔵、メタルショックマウント、ワンタッチミュート、オーラ同期RGB)",
    price: 12579,
    rating: 3.8,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/71GBfntpyDL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B2YDRPWN",
    micFilterTags: ["condenser","stand"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "16bit/48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "16bit/48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #182" },
        ],
      },
    ],
  },
      {
    id: "mic-strm-0186",
    category: "mic",
    name: "RIG M100 HD Streaming Microphone - USB Microphone…",
    brand: "—",
    tagline: "USBマイク ゲーム/録画/ポッドキャスト/ブロードキャスト用 カーディオイドポーラーパターン USBプラグアンドプレイ",
    price: 22068,
    rating: 4.1,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/61otTFyBKAL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C47C28VP",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "100Hz-10kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "16bit/48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "100Hz-10kHz" },
          { label: "サンプルレート", value: "16bit/48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #186" },
        ],
      },
    ],
  },
                {
    id: "mic-strm-0194",
    category: "mic",
    name: "ENDORFY Solum Voice S",
    brand: "—",
    tagline: "ストリーミング/チャット/ポッドキャスト録画用マイク RGB照明 USBプラグアンドプレイ タップしてミュートボタン GAINコントロール カーディオイドパターン",
    price: 18340,
    rating: 4.6,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/51qor8HipLL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CNKLL2BB",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "80Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "80Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #194" },
        ],
      },
    ],
  },
                {
    id: "mic-strm-0202",
    category: "mic",
    name: "JARO J100-CB",
    brand: "—",
    tagline: "192kHz/24bit カーディオイドコンデンサーマイク ブームアームポップフィルター付き ミュート ノイズリダクション RGB ゲームポッドキャストストリーミング",
    price: 19266,
    rating: 4.2,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/71TswZIL5CL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DXQ8CN91",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "80Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "192kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "80Hz-20kHz" },
          { label: "サンプルレート", value: "192kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Web会議アプリ", value: "Zoom / Teams 等" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #202" },
        ],
      },
    ],
  },
                {
    id: "mic-strm-0210",
    category: "mic",
    name: "ASUS ROG Carnyx",
    brand: "ASUS",
    tagline: "USBゲーミングマイク (25mmコンデンサーカプセル、192kHz/24ビット、カーディオイド、ハイパスフィルター、ポップフィルター内蔵、メタルショックマウント、ワンタッチミュート、オーラ同期RGB)",
    price: null,
    rating: 4.5,
    reviews: 119,
    image: "https://m.media-amazon.com/images/I/71bRXWbs6iL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DF46SQLB",
    micFilterTags: ["condenser"],
                    micUseTags: ["Web会議・オンライン授業・通話", "ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "ノイズキャンセリング機能"],
    micSpreadsheetJTags: ["ノイズキャンセリング"],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "単一指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "24bit / 192kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "単一指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "24bit / 192kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "内蔵ショックマウント", value: "対応" },
          { label: "ミュート", value: "対応" },
          { label: "RGBライティング", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #210" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0211",
    category: "mic",
    name: "Thronmax Mdrill Zero Plus 96kHz/24bit Multi-Direc…",
    brand: "—",
    tagline: "スロンマックス Mdrill Zero Plus 96kHz/24bit マルチ指向性 USBマイク",
    price: 9000,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/31hiVryxYIL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09DS9CQRH",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: [],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "全指向性" },
      { label: "周波数特性", value: "20Hz-20kHz" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "96kHz/24bit" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "全指向性" },
          { label: "周波数特性", value: "20Hz-20kHz" },
          { label: "サンプルレート", value: "96kHz/24bit" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #211" },
        ],
      },
    ],
  },
  {
    id: "mic-strm-0212",
    category: "mic",
    name: "Blue Yeti",
    brand: "Blue",
    tagline: "3x14mmカプセル、4パターン、ゲインとミュート、ヘッドホンボル、レイテンシーなし3.5mm出力、Knox Gearポップフィルター付き",
    price: 34946,
    rating: 4,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/31+XcSLnXHL._AC_SL1500_.jpg",
    connection: "USB Type-A",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B34YRMN8",
    micFilterTags: ["condenser"],
                    micUseTags: ["ゲーム実況・配信・ラジオ録音"],
                    micFeatureTags: ["ミュートボタン（タッチミュート）", "イヤホンジャック（ダイレクトモニタリング）"],
    micSpreadsheetJTags: [],
    micSpreadsheetKTags: [],
    highlights: [
      { label: "指向性", value: "指向性切替対応 (マルチパターン)" },
      { label: "周波数特性", value: "—" },
      { label: "接続方式", value: "USB Type-A" },
      { label: "サンプルレート", value: "48kHz" },
      { label: "タイプ", value: "コンデンサー" },
    ],
    compat: [],
    specGroups: [
      {
        title: "オーディオ",
        rows: [
          { label: "タイプ", value: "コンデンサー" },
          { label: "指向性", value: "指向性切替対応 (マルチパターン)" },
          { label: "周波数特性", value: "—" },
          { label: "サンプルレート", value: "48kHz" },
        ],
      },
      {
        title: "接続 / 機能",
        rows: [
          { label: "接続方式", value: "USB Type-A" },
          { label: "電源", value: "有線給電" },
          { label: "ミュート", value: "対応" },
          { label: "イヤホンジャック", value: "対応" },
          { label: "Amazon検索", value: "PC用マイク ストリーミング検索 #212" },
        ],
      },
    ],
  },
        ]
