import type { Gadget } from "./gadgets"

/** Amazon.co.jp ディスプレイ新着 1ページ目（2151982051 pg=1）#1–#50。 */
export const monitorNewReleases: Gadget[] = [
  {
    id: "mon-nr-001",
    category: "monitor",
    name: "S2425HSM",
    brand: "Dell",
    tagline: "Dell S2425HSM 23.8インチ モニター 無輝点3年保証/FHD/IPS,非光沢/HDMIx2/sRGB 99%/縦横回転,高さ調整/1ms,144Hz/AMD FreeSync/内蔵スピーカー",
    price: 19980,
    rating: 4.4,
    reviews: 395,
    image: "https://m.media-amazon.com/images/I/716GLBIaGjL._AC_SL1500_.jpg",
    connection: "HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GR4RLMKR",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon新着", value: "PCモニター #1" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "53.8 × 45.7 × 19.2 cm" },
          { label: "重量", value: "3.03Kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-002",
    category: "monitor",
    name: "SE2225HM",
    brand: "Dell",
    tagline: "Dell SE2225HM 21.5インチ モニター | 3年保証/FHD/VA,非光沢/HDMI1.4x1,VGAx1/傾き調整",
    price: 10980,
    rating: 4.1,
    reviews: 28,
    image: "https://m.media-amazon.com/images/I/7180Ks-incL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GR4M23MF",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon新着", value: "PCモニター #2" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "49.3 × 39.6 × 21.2 cm" },
          { label: "重量", value: "2.96 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-003",
    category: "monitor",
    name: "IODATA GigaCrysta EX-GD243UDB",
    brand: "IO DATA",
    tagline: "IODATA GigaCrysta ゲーミングモニター 23.8インチ FHD 240Hz リモコン付（HDMI/DP） EX-GD243UDB IPS方式, 0.2ms, 無輝点保証, スピーカー付",
    price: 21800,
    rating: 4.3,
    reviews: 291,
    image: "https://m.media-amazon.com/images/I/71z329Hi0jL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H4L58ZFR",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon新着", value: "PCモニター #3" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 40.9 × 18 cm" },
          { label: "重量", value: "3.6Kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-004",
    category: "monitor",
    name: "LG モニター27U711B-B 27インチ/4K/IPS/約10.7億色表示(8bit+FRC)/DCI-P3 90%/HDR",
    brand: "—",
    tagline: "LG モニター27U711B-B 27インチ/4K/IPS/約10.7億色表示(8bit+FRC)/DCI-P3 90%/HDR",
    price: 37900,
    rating: 4.1,
    reviews: 335,
    image: "https://m.media-amazon.com/images/I/71NDGee5qbL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYPVGG2D",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","vesa-100","panel-ips"],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "—" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27 インチ" },
          { label: "解像度", value: "3840 x 2160 (4K UHD)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "—" },
          { label: "Amazon新着", value: "PCモニター #4" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 46.2 × 22 cm" },
          { label: "重量", value: "5.75 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-005",
    category: "monitor",
    name: "LG ゲーミング 24G414B-B",
    brand: "—",
    tagline: "23.8インチ/フルHD/144Hz/IPS 1ms/HDMI、DP/スピーカー多機能スタンド",
    price: 17163,
    rating: 4.3,
    reviews: 91,
    image: "https://m.media-amazon.com/images/I/71RYLqd8zZL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYPH4QDC",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon新着", value: "PCモニター #5" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 34.7 × 22 cm" },
          { label: "重量", value: "3.7 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-006",
    category: "monitor",
    name: "S3425DW",
    brand: "Dell",
    tagline: "34インチ 曲面 WQHD VA・USB Type-C・1800R",
    price: 64980,
    rating: 4.2,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/710wTX832IL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GR4Q6FL4",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","port-hdmi","port-dp","port-usb-c","refresh-100","res-wqhd","vesa-100","panel-va-matte"],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34 インチ" },
          { label: "解像度", value: "2560 x 1440 (QHD)" },
          { label: "パネル", value: "VA非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon新着", value: "PCモニター #6" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "80.7 × 51.7 × 22.2 cm" },
          { label: "重量", value: "9.38 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-007",
    category: "monitor",
    name: "34U640B-BAJP",
    brand: "LG",
    tagline: "34インチ UWQHD 144Hz・USB-C PD 65W・sRGB 99%",
    price: 63800,
    rating: 4.5,
    reviews: 28,
    image: "https://m.media-amazon.com/images/I/71cznOkqKaL._AC_SL1500_.jpg",
    connection: "USB Type-C対応 / HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3RH1Y2H",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-va"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon新着", value: "PCモニター #7" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C (PD 65W)", value: "映像/給電対応" },
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "80.9 × 38.4 × 22 cm" },
          { label: "重量", value: "5.6Kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-008",
    category: "monitor",
    name: "MAG 274QF",
    brand: "MSI",
    tagline: "MSI ゲーミングモニター MAG 274QF E20 27インチ/WQHD/RAPID IPS/200Hz/0.5ms（GTG、最小値）/DisplayHDR 400/G-SYNC Compatible/HDMI 2.0b/DP 1.4a/VESA100/PIP/PBPメーカー3年保証",
    price: 31800,
    rating: 3.8,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/818Z0DMpUXL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B096Y5RWHD",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon新着", value: "PCモニター #8" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 44 × 25 cm" },
          { label: "重量", value: "4.9 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-009",
    category: "monitor",
    name: "NK-16H",
    brand: "—",
    tagline: "kksmart モバイル・ゲーミングモニター 16インチ 144Hz 2.5K解像度(2560x1600) 100%sRGB広色域 Switch2ドック不要 軽量670g ベゼルレス WQXGA 画像比調整可能 非光沢IPSパネル 収納ケース付 モバイルモニター",
    price: 20999,
    rating: 4.5,
    reviews: 1110,
    image: "https://m.media-amazon.com/images/I/81oL8owrYsL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCDF8QLB",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","refresh-144-plus","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "16\"" },
      { label: "解像度", value: "2.5K(2560 x 1600)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "16\"" },
          { label: "解像度", value: "2.5K(2560 x 1600)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon新着", value: "PCモニター #9" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" },
        ]},
      { title: "その他", rows: [
          { label: "重量", value: "0.7 kg" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "35.4 × 23 × 1.6 cm" },
          { label: "重量", value: "0.7 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-010",
    category: "monitor",
    name: "AW2525HM 24.5インチ Alienware",
    brand: "Dell",
    tagline: "Dell AW2525HM 24.5インチ Alienware ゲーミングモニター 無輝点3年保証/FHD/IPS,非光沢/DP 1.4×1,HDMI×2/sRGB 99%/縦横回転,高さ調整/0.5ms,320Hz(DP),255Hz(HDMI",
    price: 28686,
    rating: 4.6,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/61J1f8jMjwL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / USB-A対応 / USB-B対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GR4RPP31",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "320Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "320Hz" },
          { label: "Amazon新着", value: "PCモニター #10" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "55.6 × 50.1 × 20.6 cm" },
          { label: "重量", value: "3.69Kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-011",
    category: "monitor",
    name: "CRUA 28型 4K+ モニター",
    brand: "CRUA",
    tagline: "CRUA 28インチ 4K+ 60Hz PCモニター 3840×2560 IPS Type-C HDMI2.0 DP1.4 スピーカー内蔵 ブラック | 15:",
    price: 22999,
    rating: 4.3,
    reviews: 3165,
    image: "https://m.media-amazon.com/images/I/71LVWQYxtCL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXFY2N8C",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "28\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "28\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #11" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61 × 50.7 × 19 cm" },
          { label: "重量", value: "5 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-012",
    category: "monitor",
    name: "JN-i27G120U",
    brand: "JAPANNEXT",
    tagline: "【Amazon.co.jp限定】JAPANNEXT 27インチ IPSパネル搭載 120Hz/1ms(MPRT)対応 4K(3840×2160)解像度 ゲーミングモニター JN-iA27G120U2 HDMI2.1 DP sRGB:100% HDR400相当 PS5 4K:120Hz接続 VRR【2年保証】",
    price: 33980,
    rating: 4.5,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/71PiMbVV0AL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H29BM2PR",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-100","port-hdmi","port-dp","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #12" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 46 × 19.5 cm" },
          { label: "重量", value: "4.4 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-013",
    category: "monitor",
    name: "KOORUI モニター 27インチ E2712K",
    brand: "KOORUI",
    tagline: "KOORUI モニター 27インチ pcモニター 144Hz フルhd 液晶ディスプレイ 非光沢 Adaptive Sync/ブルーライト軽減/傾き調整/HDMI＋VGAポート/VESA対応",
    price: 14800,
    rating: 4.3,
    reviews: 1290,
    image: "https://m.media-amazon.com/images/I/81oFHiu3qjL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DTTNSKYH",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon新着", value: "PCモニター #13" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "10.2 × 43.7 × 67.6 cm" },
          { label: "重量", value: "3.25 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-014",
    category: "monitor",
    name: "AW3426DW",
    brand: "Dell",
    tagline: "Dell Alienware AW3426DW 34インチ曲面 有機EL ゲーミングモニター 無輝点3年保証/WQHD/QD-OLED,抗反射,1800R曲面/HDMI2.1x2,DP1.4 x1/DCI-P3 99%/0.03ms,280Hz",
    price: 130980,
    rating: 4.6,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/61oNFN+ncKL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6HL2CL2",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "280Hz" },
      { label: "パネル", value: "有機EL (OLED) MLA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "有機EL (OLED) MLA" },
          { label: "リフレッシュレート", value: "280Hz" },
          { label: "Amazon新着", value: "PCモニター #14" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "81.4 × 55.5 × 23.2 cm" },
          { label: "重量", value: "4.88Kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-015",
    category: "monitor",
    name: "KIMOCA 7インチ モバイルモニター",
    brand: "KIMOCA",
    tagline: "KIMOCA 7インチ モバイルモニター IPS液晶 1024×600 HDMI入力 Type-C給電（5V） 金属ボディ 高耐久 軽量 小型ディスプレイ Raspberry Pi使用可 VESA規格 スピーカー内蔵 サブモニター",
    price: 6251,
    rating: 4.3,
    reviews: 36,
    image: "https://m.media-amazon.com/images/I/71dIukI4NmL._AC_SL1500_.jpg",
    connection: "HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYMYCTXL",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","refresh-60","port-hdmi","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "7\"" },
      { label: "解像度", value: "1024×600" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "7\"" },
          { label: "解像度", value: "1024×600" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "VESA", value: "75 × 75 mm" },
          { label: "Amazon新着", value: "PCモニター #15" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "USB Type-C", value: "5V給電対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "0.23Kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-017",
    category: "monitor",
    name: "H24F7",
    brand: "—",
    tagline: "KEY TO COMBAT 23.8インチ FHD(1920*1080) 240Hz FAST IPSパネル 1ms HDR400 ゲーミングモニター ΔE<2 DC調光 400cd/m² sRGB 111% 色域 FreeSync & G-Sync ブルーライト軽減 HDMI2.0*2 DP1.4*1 USB2.0 チルト可能 VESA 三年保証付き",
    price: 16980,
    rating: 4.1,
    reviews: 48,
    image: "https://m.media-amazon.com/images/I/615leE5bHVL._AC_SL1500_.jpg",
    connection: "HDMI / Displayport対応 / USB-A対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G2VHV18G",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon新着", value: "PCモニター #17" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "54 × 32 × 4.8 cm" },
          { label: "重量", value: "1 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-018",
    category: "monitor",
    name: "24インチ 144Hz ゲーミングE2412K",
    brand: "KOORUI",
    tagline: "KOORUI モニター 24インチ 144Hz ゲーミングモニター フルHD VAパネル (HDMI/VGA/AdaptiveSync/VESA対応/ブルーライト軽減)",
    price: 13980,
    rating: 4.2,
    reviews: 1509,
    image: "https://m.media-amazon.com/images/I/71zsPfEjiaL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQH4SM7B",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon新着", value: "PCモニター #18" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "48.5 × 54.2 × 18.5 cm" },
          { label: "重量", value: "2.75 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-019",
    category: "monitor",
    name: "Acer モバイルモニター PM141Wbmiuux",
    brand: "Acer",
    tagline: "Acer モバイルモニター 14インチ WUXGA 16:10 IPS 非光沢 NTSC 45% 60Hz 7ms(GTG) 600g 超薄型 Adaptive-Sync HDR10 HDMI 1.4 USB-C デュアルスピーカー スタンド内蔵 無段階チルト調整 ブルーライト低減",
    price: 13999,
    rating: 5,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/61zxJuvSVeL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6WSMXBL",
    vesaStandard: "非対応",
    monitorFilterTags: ["size-238","refresh-60","port-hdmi","port-usb-c","vesa-none","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "14\"" },
      { label: "解像度", value: "WUXGA（1920×1200）" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "14\"" },
          { label: "解像度", value: "WUXGA（1920×1200）" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #19" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" },
        ]},
      { title: "その他", rows: [
          { label: "重量", value: "0.6 kg" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "31.2 × 20.5 × 1.6 cm" },
          { label: "重量", value: "0.6 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-021",
    category: "monitor",
    name: "Lenovo ゲーミングモニター LOQ 27Q-10",
    brand: "Lenovo",
    tagline: "【Amazon.co.jp限定】Lenovo ゲーミングモニター LOQ 27Q-10 27インチ/QHD/IPSパネル/180㎐/1ms(GtG)/HDMI2.1x2, DP1.4x1/AMD FreeSync™ Premium/チルト対応/日本国内3年保証",
    price: 19800,
    rating: 3.1,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71zS6MEikGL._AC_SL1500_.jpg",
    connection: "HDMI / Displayport対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H1PWX6SN",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon新着", value: "PCモニター #23" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 45.2 × 21.6 cm" },
          { label: "重量", value: "4.5 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-022",
    category: "monitor",
    name: "Acer Nitro 16型 モバイルモニター",
    brand: "Acer",
    tagline: "Acer Nitro モバイル ゲーミングモニター 16インチ ワイド IPS 非光沢 WUXGA 144Hz 4ms(GTG) NTSC 45% 785g 軽量薄型 AMD FreeSync HDR10 HDMI 1.4 USB-C デュアルスピーカー 縦画面表示 無段階チルト調整 ブルーライト抑制 3年保証(パネルは1年)",
    price: 19999,
    rating: 4.7,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61mucvplACL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6WS2CP1",
    vesaStandard: "非対応",
    monitorFilterTags: ["size-238","refresh-144-plus","port-hdmi","port-usb-c","vesa-none","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "16\"" },
      { label: "解像度", value: "WUXGA（1920×1200）" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "16\"" },
          { label: "解像度", value: "WUXGA（1920×1200）" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon新着", value: "PCモニター #24" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" },
        ]},
      { title: "その他", rows: [
          { label: "重量", value: "0.79 kg" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "35.7 × 24.3 × 1.5 cm" },
          { label: "重量", value: "0.79 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-023",
    category: "monitor",
    name: "InnoView 18.5型 モバイルモニター",
    brand: "InnoView",
    tagline: "InnoView モバイルモニター 18.5インチ モバイルディスプレイ 120%sRGB 120Hz 2560×1440 QHD 大画面 保護ケース付きゲーミングモニター IPS液晶パネル 非光沢ポータブルモニター HDRモード FreeSync ブルーライト機能 Type-C",
    price: 25999,
    rating: 3.9,
    reviews: 1252,
    image: "https://m.media-amazon.com/images/I/71Vl1iWGuuL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYR9BBB9",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-wqhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #25" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "42.4 × 25.9 × 1.4 cm" },
          { label: "重量", value: "1.4 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-024",
    category: "monitor",
    name: "INNOCN 34C1R 34インチ ウルトラワイドモニター",
    brand: "—",
    tagline: "INNOCN 34C1R 34インチ ウルトラワイドモニター UWQHD 3440x1440 180Hz IPSパネル HDR400 HDMI 2.0*2+DP1.4*2 PIP/PBP対応 高さ調整",
    price: 87980,
    rating: 4.7,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61nEpLpouIL._AC_SL1500_.jpg",
    connection: "HDMI 2.1 / DisplayPort 1.4",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZTXD6M3",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "32\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "VESA", value: "100 × 100 mm" },
          { label: "Amazon新着", value: "PCモニター #26" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
          { label: "USB Type-C", value: "65W PD対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 42.3 × 19.5 cm" },
          { label: "重量", value: "9.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-025",
    category: "monitor",
    name: "Upperizon 14型 モバイルモニター",
    brand: "Upperizon",
    tagline: "【Switch2ドック不要】Upperizon モバイルモニター 14インチ 120Hz 2K 軽量530g 100%sRGB 高輝度450nits 光沢IPS 2520×1680 2.5K 3対2 アスペクト比調整対応 極薄 自立型 無段階チルト調整 VESA対応 撥水収納ケース付き",
    price: 16999,
    rating: 4.8,
    reviews: 205,
    image: "https://m.media-amazon.com/images/I/71HQc8AnBCL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYFC8Q78",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "14\"" },
      { label: "解像度", value: "2.5K(2560 x 1600)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "14\"" },
          { label: "解像度", value: "2.5K(2560 x 1600)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #27" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" },
        ]},
      { title: "その他", rows: [
          { label: "重量", value: "0.5 kg" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "31 × 22.2 × 1.6 cm" },
          { label: "重量", value: "0.5 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-026",
    category: "monitor",
    name: "AOC ゲーミング 27インチ, QHD/2560x1440@180Hz, 応答速度0.5ms(",
    brand: "—",
    tagline: "AOC ゲーミングモニター 27インチ, QHD/2560x1440@180Hz, 応答速度0.5ms(MPRT), Fast IPS, HDMI2.0 x 1/ DP1.4x1,ブルーライト低減, フリッカーフリー, G-sync Compatible, HDR10対応, 3年保証",
    price: 18909,
    rating: 4,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/814BDUy9gWL._AC_SL1500_.jpg",
    connection: "HDMI / Displayport対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G26VMQB3",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "Fast IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon新着", value: "PCモニター #28" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 45 × 19.8 cm" },
          { label: "重量", value: "3.53 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-027",
    category: "monitor",
    name: "JAPANNEXT 50インチ",
    brand: "JAPANNEXT",
    tagline: "【2年保証モデル】JAPANNEXT 50インチ VAパネル搭載 4K(3840×2160)解像度 大型液晶モニター JN-V50U2-M HDMI ビデオ/音声入力 コンポーネント入力 オプティカル音声出力 USBメモリ再生対応 リモコン同梱",
    price: 59980,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71+vTnfsGDL._AC_SL1500_.jpg",
    connection: "HDMI / USB-A対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8SBPYP6",
    vesaStandard: "200×200 mm",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","vesa-200-plus","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "50\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "50\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #29" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "111.2 × 70.1 × 25.5 cm" },
          { label: "重量", value: "9.5 kg" },
        ]},

    ],
  },
  {
    id: "mon-nr-028",
    category: "monitor",
    name: "LG ゲーミング モニター 32G620B-B",
    brand: "—",
    tagline: "LG ゲーミング モニター 32G620B-B 31.5インチ/WQHD@200Hz/IPS 1ms/HDR/HDMI、DP/多機能スタンド",
    price: 40200,
    rating: 4.6,
    reviews: 34,
    image: "https://m.media-amazon.com/images/I/71+jinjzoiL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYPLSKWT",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon新着", value: "PCモニター #30" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "71.3 × 48 × 22 cm" },
          { label: "重量", value: "4.7Kg" },
        ]},

    ],
  },
]
