import type { Gadget } from "./gadgets"

/** Amazon.co.jp Lenovo ディスプレイ検索（22.0～25.9インチ / Lenovo）。 */
export const monitorLenovoSearch: Gadget[] = [
  {
    id: "mon-lenovo-001",
    category: "monitor",
    name: "Lenovo L24-41",
    brand: "Lenovo",
    tagline: "Lenovo モニター L24-41 日本国内5年保証/23.8インチ/フルHD/IPSパネル/HDMI1.4x1, VGAx1/傾き調整/VESA対応",
    price: 11880,
    rating: 3.9,
    reviews: 22,
    image: "https://m.media-amazon.com/images/I/610o5mrvwQL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G42QB93M",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #1" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA (D-Sub)", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 40.3 × 18 cm" },
          { label: "重量", value: "3.1Kg" }]}],
  },
    {
    id: "mon-lenovo-005",
    category: "monitor",
    name: "Lenovo ThinkVision C24-40",
    brand: "Lenovo",
    tagline: "(23.8型 フルHD 非光沢 VA HDMI mini D-Sub チルト VESA 3 ブラック",
    price: 15051,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/518Kcj-kndL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GK8H12LS",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #5" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "2.8Kg" }]}],
  },
  {
    id: "mon-lenovo-008",
    category: "monitor",
    name: "Lenovo ゲーミングモニター R25f-30",
    brand: "Lenovo",
    tagline: "24.5インチ VA WLED液晶 FHD 240Hz 0.5ms 非光沢 チルト対応 VESA) ブラック 67B8GACBJP",
    price: 18300,
    rating: 3,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/71TwBRZJtBL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CVN7VL3F",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #8" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 49.9 × 25.9 cm" },
          { label: "重量", value: "3.6Kg" }]}],
  },
  {
    id: "mon-lenovo-010",
    category: "monitor",
    name: "Lenovo G25-20 ゲーミングモニター",
    brand: "Lenovo",
    tagline: "24.5インチ 165Hz 0.8ms TN WLED液晶 FHD 非光沢 高さ調整 角度調整 VESA DisplayPort ケーブル付) 66D6GAC2JP",
    price: 22000,
    rating: 4.7,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/61ms2GNH-mL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BB6Y92GV",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-tn"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "TN 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "TN 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #10" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 49.8 × 23.5 cm" },
          { label: "重量", value: "3.7Kg" }]}],
  },
  {
    id: "mon-lenovo-011",
    category: "monitor",
    name: "Lenovo R25i-30 モニター",
    brand: "Lenovo",
    tagline: "24.5インチ IPS WLED液晶 FHD 165Hz 0.5ms 非光沢 チルト対応 VESA) ブラック 67B7GACBJP",
    price: 25300,
    rating: 3.6,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/71yakSIGiEL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DCNQBYP9",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #11" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 49.9 × 25.9 cm" },
          { label: "重量", value: "3.4Kg" }]}],
  },
  {
    id: "mon-lenovo-012",
    category: "monitor",
    name: "Lenovo L24-4e モニター",
    brand: "Lenovo",
    tagline: "23.8インチフラットIPS FullHDディスプレイ、100Hzリフレッシュ、4ms応答、HDMI 1.4、VGA、チルトスタンド、レイブンブラック",
    price: 21208,
    rating: 4.6,
    reviews: 43,
    image: "https://m.media-amazon.com/images/I/71Z9kXFD6uL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FPRKBD8J",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #12" }]},
      { title: "接続端子", rows: [
          { label: "HDMI 1.4", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 40.3 × 18 cm" },
          { label: "重量", value: "2.99 kg" }]}],
  },
  {
    id: "mon-lenovo-013",
    category: "monitor",
    name: "Lenovo ThinkVision P24QD-40",
    brand: "Lenovo",
    tagline: "23.8型 IPS WQHD 非光沢 48Hz-120Hz HDMI DisplayPort USB Type-C RJ45 チルト スイベル ピボット 高さ調節 3",
    price: 54706,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51tzMVvqSIL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C / RJ45",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GPC1QNKV",
    monitorFilterTags: ["size-238","res-wqhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #13" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" },
          { label: "RJ45", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 50.6 × 19 cm" },
          { label: "重量", value: "3.0 kg" }]}],
  },
  {
    id: "mon-lenovo-015",
    category: "monitor",
    name: "Lenovo Legion Y25g-30",
    brand: "Lenovo",
    tagline: "24.5インチ フルHD WLED ゲーミングLCDモニター - 16:9 - ブラック",
    price: 31800,
    rating: 4,
    reviews: 16,
    image: "https://m.media-amazon.com/images/I/51BqeC5qUnL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BT4ZL24J",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "360Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "360Hz" },
          { label: "Amazon検索", value: "PCモニター #15" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.24 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "62.2 × 51.1 × 51.1 cm" },
          { label: "重量", value: "4.24 kg" }]}],
  },
  {
    id: "mon-lenovo-016",
    category: "monitor",
    name: "Lenovo ThinkVision T23i-30",
    brand: "Lenovo",
    tagline: "レノボジャパン ThinkVision T23i-30",
    price: 23945,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/31gVBlxyi5L._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLH1MD2",
    monitorFilterTags: ["size-238","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #16" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]}],
  },
  {
    id: "mon-lenovo-017",
    category: "monitor",
    name: "Lenovo ThinkVision T24-40",
    brand: "Lenovo",
    tagline: "23.8型 IPS フルHD 非光沢 HDMI VGA DisplayPort チルト スイベル ピボット 高さ調節 3",
    price: 33000,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51ZZ3hdch4L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GK87J5L7",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #17" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 50.6 × 19 cm" },
          { label: "重量", value: "3Kg" }]}],
  },
  {
    id: "mon-lenovo-018",
    category: "monitor",
    name: "ThinkVision T24d-10 61B4MAR1JP",
    brand: "Lenovo",
    tagline: "レノボ・ジャパン 61B4MAR1JP ThinkVision T24d-10",
    price: 27500,
    rating: 2.7,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/71lrLLDgMYL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B072ZCXNFN",
    monitorFilterTags: ["size-24","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "WUXGA（1920×1200）" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "WUXGA（1920×1200）" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #18" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.98 kg" }]}],
  },
  {
    id: "mon-lenovo-019",
    category: "monitor",
    name: "Lenovo ThinkVision T24i-30",
    brand: "—",
    tagline: "23.8 フルHD WLED LCDモニター - 16:9",
    price: 34389,
    rating: 4.4,
    reviews: 24,
    image: "https://m.media-amazon.com/images/I/611+HieXa2L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BZWLJFTD",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #19" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "6.21 kg" }]}],
  },
  {
    id: "mon-lenovo-020",
    category: "monitor",
    name: "Lenovo ThinkVision S24e-20",
    brand: "Lenovo",
    tagline: "Lenovo 23.6インチ LED モニター 62A0KAT1UK 1920 X 1080 1Ms Vga Hdmi Vesa",
    price: 38006,
    rating: 4.6,
    reviews: 215,
    image: "https://m.media-amazon.com/images/I/61apmr+phTL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07LGHWQ1C",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #20" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "63.8 × 40.6 × 12.2 cm" },
          { label: "重量", value: "3.08 kg" }]}],
  },
  {
    id: "mon-lenovo-021",
    category: "monitor",
    name: "D24-20 23.6インチ VA FHD VGA/HDMI 60Hz 1ms LCD",
    brand: "Lenovo",
    tagline: "Lenovo D24-20 23.6インチ VA FHD VGA/HDMI 60Hz 1ms LCDモニター",
    price: 38045,
    rating: 4.2,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/41X+3AWM3qL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08G1RNRWJ",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #21" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "4.46 kg" }]}],
  },
  {
    id: "mon-lenovo-022",
    category: "monitor",
    name: "ThinkVision S24-4e 23.8インチモニター。",
    brand: "—",
    tagline: "ThinkVision S24-4e 23.8インチモニター",
    price: 32912,
    rating: 3.4,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61KM-0bJzCL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FQJPMZLJ",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #22" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 32.5 × 4.3 cm" },
          { label: "重量", value: "2.7 kg" }]}],
  },
  {
    id: "mon-lenovo-023",
    category: "monitor",
    name: "ThinkVision E24-30 24インチ FHD LED",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision E24-30 24インチクラスフルHD LEDモニター - 16:9",
    price: 44292,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71O6aAHxvDL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D3QQ7MR8",
    monitorFilterTags: ["size-24","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #23" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 34.2 × 17.9 cm" },
          { label: "重量", value: "3.4Kg" }]}],
  },
  {
    id: "mon-lenovo-024",
    category: "monitor",
    name: "Lenovo R25i-30 モニター",
    brand: "Lenovo",
    tagline: "LED display 62,2 cm (24.5\") 1920 x 1080 ピクセル フルHD ノワール",
    price: 33409,
    rating: 4.2,
    reviews: 48,
    image: "https://m.media-amazon.com/images/I/81BDwGeBpvL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CLH7R3KY",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #24" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 49.9 × 25.9 cm" },
          { label: "重量", value: "3.4Kg" }]}],
  },
  {
    id: "mon-lenovo-025",
    category: "monitor",
    name: "Lenovo ThinkVision T23i-20",
    brand: "Lenovo",
    tagline: "(61F6MAT2US) ??HD 1920×1080 IPS LED 6ms",
    price: 41327,
    rating: 4.7,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/51RGw-mJOPL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08DP5BNDH",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #25" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.32Kg" }]}],
  },
  {
    id: "mon-lenovo-026",
    category: "monitor",
    name: "Lenovo ThinkVision S24e-20",
    brand: "Lenovo",
    tagline: "23.8\" Full HD WLED LCD Monitor - 16:9 - Raven Black - 24\" Class - Vertical Alignment (VA) - 1920 x 1080-16.7 Million Colors - FreeSync - 250 Nit Typical - 4 ms E",
    price: 41508,
    rating: 4.4,
    reviews: 149,
    image: "https://m.media-amazon.com/images/I/7192b446A+L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B098TSWSD8",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #26" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.02Kg" }]}],
  },
  {
    id: "mon-lenovo-027",
    category: "monitor",
    name: "Lenovo ThinkVision E24-30",
    brand: "Lenovo",
    tagline: "24インチ クラス フルHD LEDモニター - 16:9 - レイヴンブラック - 23.8インチ - インプレーンスイッチング (IPS) テクノロジー - WLEDバックライト - 1920 x 1080-1,670万色 - 250",
    price: 47747,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71GPpkyzG6L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D29WH27Y",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #27" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 49.7 × 17.8 cm" },
          { label: "重量", value: "3.4Kg" }]}],
  },
    {
    id: "mon-lenovo-029",
    category: "monitor",
    name: "Lenovo Legion R24e",
    brand: "Lenovo",
    tagline: "- ゲームモニター - 23.8インチ フラット FHD - 180 Hz - 1ms レスポンス - AMD FreeSync - HDRDecode, HDMI 2.1, DP 1.4, オーディオ - リフト/チルト/ピボット/スイベルスタンド",
    price: 47263,
    rating: 4.4,
    reviews: 45,
    image: "https://m.media-amazon.com/images/I/614+3kY3ZJL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DZQ685Q3",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #29" }]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 52.3 × 25.9 cm" },
          { label: "重量", value: "3.0Kg" }]}],
  },
  {
    id: "mon-lenovo-030",
    category: "monitor",
    name: "Lenovo ThinkVision T24t-20",
    brand: "Lenovo",
    tagline: "レノボジャパン ThinkVision T24t-20 62C5GAR1JP",
    price: 51279,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/513EaZ5g9XL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLKB7D7",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #30" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.73Kg" }]}],
  },
  {
    id: "mon-lenovo-031",
    category: "monitor",
    name: "Lenovo ゲーミング モニター G24e-20",
    brand: "Lenovo",
    tagline: "23.8インチ VA WLED液晶 FHD 1ms MPRT 100Hz 120Hz 非光沢 傾き調整 VESA HDMI ケーブル付) ブラック 66D7GAR1JP",
    price: 19000,
    rating: 4.2,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61oFZy4g1EL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BL6TK685",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #31" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 40.9 × 18.5 cm" },
          { label: "重量", value: "3.3Kg" }]}],
  },
  {
    id: "mon-lenovo-032",
    category: "monitor",
    name: "Lenovo ThinkVision S24e-20",
    brand: "Lenovo",
    tagline: "レノボジャパン ThinkVision S24e-20 62AEKAR2J9",
    price: 32800,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51kbg3shhPL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLGPLPL",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #32" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.02Kg" }]}],
  },
  {
    id: "mon-lenovo-033",
    category: "monitor",
    name: "Lenovo ThinkVision E24q-30",
    brand: "Lenovo",
    tagline: "モニター ビジネ 23.8型 QHD 非光沢 VESA HDMI ブラック 63ECGAR2JP",
    price: 23618,
    rating: 4.2,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/71KDO9HXgCL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQ39Q3KG",
    monitorFilterTags: ["size-238","res-wqhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #33" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 49.7 × 17.9 cm" },
          { label: "重量", value: "3.32Kg" }]}],
  },
  {
    id: "mon-lenovo-034",
    category: "monitor",
    name: "Lenovo Q24h-10 (66A8GCC6US)",
    brand: "Lenovo",
    tagline: "23.8インチ QHD (2560 x 1440) USB-C LCDモニター LEDバックライト AMD FreeSync 75Hz 4ms 99% sRGB スピーカー ローブルーライト",
    price: 59968,
    rating: 4.4,
    reviews: 478,
    image: "https://m.media-amazon.com/images/I/611dshcfT1L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08D6SKVVN",
    monitorFilterTags: ["size-238","res-wqhd","refresh-75","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #34" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "18 × 43.8 × 54.3 cm" },
          { label: "重量", value: "4.68Kg" }]}],
  },
  {
    id: "mon-lenovo-036",
    category: "monitor",
    name: "Lenovo ThinkVision P24q-30",
    brand: "Lenovo",
    tagline: "24インチ クラス WQHD LED モニター - 16:9",
    price: 49705,
    rating: 4.6,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61BzLwfeS6L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTMNBSZ2",
    monitorFilterTags: ["size-238","res-wqhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #36" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.8 × 32.3 × 4.6 cm" },
          { label: "重量", value: "3.8Kg" }]}],
  },
  {
    id: "mon-lenovo-037",
    category: "monitor",
    name: "Lenovo ThinkVision T24i-2L",
    brand: "Lenovo",
    tagline: "23.8インチ 60Hz 液晶モニター レイヴン ブラック - 1920 x 1080 フルHDディスプレイ @ 60Hz - インプレーンスイッチング (IPS) テクノロジー - 250 Nit輝度 - HDMI & DisplayPortコネクタ",
    price: 55520,
    rating: 4.6,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/71hddGPpgWL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09C8CPQ2Y",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #37" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 32.8 × 4.3 cm" },
          { label: "重量", value: "3.3Kg" }]}],
  },
  {
    id: "mon-lenovo-038",
    category: "monitor",
    name: "Lenovo ThinkVision T22i-30",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T22i-30 21.5 フルHD WLED LCDモニター - 16:9",
    price: 49525,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/41570EmeelL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BT7MYZC8",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #38" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.8 × 48.7 × 19.5 cm" },
          { label: "重量", value: "3.0 kg" }]}],
  },
  {
    id: "mon-lenovo-039",
    category: "monitor",
    name: "Lenovo ThinkVision S24e-20",
    brand: "Lenovo",
    tagline: "23.8インチ FHD(1920x1080) WLED モニター レイヴン ブラック-62AEKAT2US - USBハブ付き",
    price: 48353,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71qqQT0oTeL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BDT5RKZD",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #39" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.0 kg" }]}],
  },{
    id: "mon-lenovo-041",
    category: "monitor",
    name: "Lenovo ThinkVision 24インチ (Ergoflexyアームセット",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision 24インチ FHD IPSモニター 応答時間4ms、アンチグレア、ちらつきなし、VESAマウント(100mm)、ディスプレイポート、HDMI&DKZハブ",
    price: 62890,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61nrN9SJrfL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FK2VJ5RQ",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #41" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 40.4 × 18 cm" },
          { label: "重量", value: "3 kg" }]}],
  },
  {
    id: "mon-lenovo-042",
    category: "monitor",
    name: "Lenovo ThinkVision T24i-30",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T24i-30 24インチクラスフルHD LEDモニター - 16:9",
    price: 48234,
    rating: 4.6,
    reviews: 51,
    image: "https://m.media-amazon.com/images/I/61Pk+HFihjL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C3943YVG",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #42" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 32.3 × 4.8 cm" },
          { label: "重量", value: "3.4Kg" }]}],
  },
  {
    id: "mon-lenovo-043",
    category: "monitor",
    name: "Lenovo ThinkVision T23i-30",
    brand: "Lenovo",
    tagline: "23インチ クラス フルHD 液晶モニター - 16:9",
    price: 46501,
    rating: 3.8,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61bPwox0rML._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BXHM5699",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #43" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "52.3 × 31.2 × 4.6 cm" },
          { label: "重量", value: "3.20 kg" }]}],
  },
  {
    id: "mon-lenovo-044",
    category: "monitor",
    name: "Lenovo ThinkVision S24-4e",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T24i-20 23.8インチ FHD WLED LCD",
    price: 54151,
    rating: 4.6,
    reviews: 47,
    image: "https://m.media-amazon.com/images/I/51P+ZwzNzpL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08FBH31TM",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #44" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 42.4 × 20.6 cm" },
          { label: "重量", value: "3.3Kg" }]}],
  },
  {
    id: "mon-lenovo-045",
    category: "monitor",
    name: "ThinkVision P24H-30 23.8インチ IPS 2560×1440 HDMI D",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P24H-30 23.8インチ IPS 2560×1440 HDMI DP USB",
    price: 82671,
    rating: 3.7,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/611esKek25L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C7HGFC37",
    monitorFilterTags: ["size-238","port-hdmi","port-dp","refresh-60","res-wqhd","vesa-100","panel-ips"],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8 インチ" },
          { label: "解像度", value: "2560 x 1440 (QHD)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #45" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "12.7 × 38.1 × 50.8 cm" },
          { label: "重量", value: "5.72 kg" }]}],
  },
  {
    id: "mon-lenovo-046",
    category: "monitor",
    name: "T24-40",
    brand: "Lenovo",
    tagline: "61cm FHD IPS モニター 100Hzリフレッシュレート、VESAマウント。 応答時間4ms、ちらつきなし、アンチグレア、HDMI w/DKZ USBハブ、ブラック(64B5KAT1UZ)、ErgoFlexyシングルマウントアーム",
    price: 69047,
    rating: 5,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/61tg8YrMIzL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FK2W43ZM",
    monitorFilterTags: ["size-24","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #46" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 50.5 × 19.1 cm" },
          { label: "重量", value: "3 kg" }]}],
  }]
