import type { Gadget } from "./gadgets"

/** Amazon.co.jp ディスプレイ検索 2ページ目（18.0～25.9インチ / 144–240Hz）。 */
export const monitorRefresh144SearchPage2: Gadget[] = [
  {
    id: "mon-hfr144-p2-001",
    category: "monitor",
    name: "INNOCN 25G2S ゲーミングモニター",
    brand: "INNOCN",
    tagline: "24 .5インチ 240Hz IPSパネル モニター WQHD ゲームモニター ブラック（HDMI 2.1x2/DisplayPort 1.4x2/傾き調整/VESA対応/非光沢ディスプレイ",
    price: 32800,
    rating: 4.2,
    reviews: 215,
    image: "https://m.media-amazon.com/images/I/71ngArGBd2L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DXDW1CJG",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #1" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1 x 2", value: "対応" },
          { label: "DisplayPort 1.4 x 2", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 42.3 × 19.5 cm" },
          { label: "重量", value: "3.2 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-003",
    category: "monitor",
    name: "KTC 24M1ゲーミングモニター",
    brand: "KTC",
    tagline: "23.8 インチ WQHD ゲーミングモニター 240Hz(260Hz OC) 1ms(MPRT) Fast IPS パネル 3年保証 450cd/㎡ 99%sRGB Adaptive Sync HDMI2.0×2 / DP1.4×2 回転対応 遮光フード付 VESA対応 3年保証",
    price: 26980,
    rating: 4.1,
    reviews: 805,
    image: "https://m.media-amazon.com/images/I/61iz6v1hTyL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H4LY1F1Q",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #3" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.0 x 2", value: "対応" },
          { label: "DisplayPort 1.4 x 2", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "56.4 × 36.7 × 24.3 cm" },
          { label: "重量", value: "5.9Kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-005",
    category: "monitor",
    name: "KEY TO COMBAT 23.8インチゲーミングモニター",
    brand: "KEY TO COMBAT",
    tagline: "フルHD(1920×1080) IPS 144Hz sRGB103% DCI-P3 96% HDR10 1500:1コントラスト比 300cd/㎡ ΔE<2の高色精度 低ブルーライト フリッカーフリー Adative Sync対応 HDMI1.4×1 DP1.2×1 チルト調整可能 3年保証",
    price: 11263,
    rating: 3.9,
    reviews: 83,
    image: "https://m.media-amazon.com/images/I/71pQgAhKaAL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FHB76PQW",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #5" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "45 × 30 × 78 cm" },
          { label: "重量", value: "3.8Kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-006",
    category: "monitor",
    name: "MSI MAG 255F X24",
    brand: "MSI",
    tagline: "24.5インチ/フルHD/RAPID IPSパネル/240Hz/0.5ms（GTG、最小値）/HDR/Adaptive-Sync/HDMI2.0b/DP 1.2a/VESA100/メーカー3年保証",
    price: 21800,
    rating: 4,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/81A5-H-JG8L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJSFGF54",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #6" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.0b", value: "対応" },
          { label: "DisplayPort 1.2a", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 41.9 × 22.1 cm" },
          { label: "重量", value: "3.24 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-010",
    category: "monitor",
    name: "Pixio PX249WAVE ゲーミングモニター",
    brand: "Pixio",
    tagline: "24インチ WQHD 240hz Fast IPS ゲーミング モニター 金 ピクシオディスプレイ サブモニター pcモニター ゲームモニター monitor gaming 23.8インチ",
    price: 29980,
    rating: 4.7,
    reviews: 45,
    image: "https://m.media-amazon.com/images/I/71pG4NV-h1L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GLNJ1X86",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #10" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 42.5 × 18 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-011",
    category: "monitor",
    name: "KTC H24B9S ゲーミングモニター",
    brand: "KTC",
    tagline: "FHD 144Hz IPS HDR10 H24B9S 23.8インチ・FHD・144Hz・IPS・HDR10・sRGB103%・DCI-P3 96%・ΔE<2・300cd/㎡・1500:1・Adaptive Sync・HDMI1.4×1・DP1.2×1・低ブルーライト",
    price: 12980,
    rating: 3.5,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/71eChXrdk+L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GGXHTLCX",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #11" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 40.7 × 19.1 cm" },
          { label: "重量", value: "3.69Kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-012",
    category: "monitor",
    name: "BenQ MOBIUZ EX240N",
    brand: "BenQ",
    tagline: "23.8インチ VA フルHD 165Hz 1ms ゲーミングモニター ノングレア HDRi スピーカー内蔵(treVolo) FreeSync Premium Black eQualizer 輝度自動調整機能（B.I.+）搭載 ブルーライト軽減 フリッカーフリー 3年保証",
    price: 24588,
    rating: 4.3,
    reviews: 235,
    image: "https://m.media-amazon.com/images/I/81PI5MHoGJL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B68VMGFH",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #12" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "60 × 40.5 × 18 cm" },
          { label: "重量", value: "5.6 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-013",
    category: "monitor",
    name: "MSI PRO MP241 E14V",
    brand: "MSI",
    tagline: "23.8インチ/フルHD/VA/144Hz/1ms/AMD FreeSync/HDMI2.0/DP1.2a/VESA100/メーカー3年保証",
    price: 14800,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/616TKKK5OWL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H7121BZ6",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #13" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.0", value: "対応" },
          { label: "DisplayPort 1.2a", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "39.8 × 54.2 × 18.2 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-015",
    category: "monitor",
    name: "iiyama G-MASTER GB2471HSU-B1",
    brand: "iiyama",
    tagline: "23.8インチ Fast IPSパネル搭載 240Hz/0.3ms対応 フルHD(1920×1080)解像度 ゲーミングモニタ ブラック",
    price: 20553,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/71215hXQx4L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FV3JYTS9",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #15" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 37.9 × 17.1 cm" },
          { label: "重量", value: "4.8 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-018",
    category: "monitor",
    name: "KTC 24インチ 曲面ゲーミングモニター H24S17P",
    brand: "KTC",
    tagline: "VA・1ms MPRT・1500R曲面・3000:1・HDR10・sRGB99%・Adaptive Sync・HDMI2.0×2・DP1.4×1・PS5対応・VESA対応・チルト調整",
    price: 16980,
    rating: 4.4,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71Odm6fRtzL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GRVVW7QH",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-75","panel-va"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #18" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.4 × 40.5 × 14.3 cm" },
          { label: "重量", value: "2.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-019",
    category: "monitor",
    name: "LG 24G411B-B 23.8インチ モニター",
    brand: "LG",
    tagline: "23.8インチ/フルHD/IPS/144Hz/sRGB 99%/HDR/1ms/HDMI、DP 省エネモード搭載。目に優しいブルーライト低減モードやフリッカーセーフ、低反射パネルを採用。ビジネスからライトゲームまで幅広くこなせるLGのハイスペックPCモニター。メーカー3年保証",
    price: 15197,
    rating: 4.4,
    reviews: 290,
    image: "https://m.media-amazon.com/images/I/71EnzI0zYcL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYPP63DR",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #19" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.2 × 22 cm" },
          { label: "重量", value: "3.3 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-021",
    category: "monitor",
    name: "INNOCN 24.5インチ 240Hz WQHDモニター 25M2S",
    brand: "INNOCN",
    tagline: "240Hz WQHDモニター QD-MiniLED ゲーミングモニター 1440p 量子ドット ゲーミングディスプレイ HDR1000 IPS非光沢 HDMI 2.1/DisplayPort 1.4/スピーカー 高さ調整可能 光センサー搭載",
    price: 45446,
    rating: 4.1,
    reviews: 351,
    image: "https://m.media-amazon.com/images/I/71Pa5Qs9w5L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F29CKQ6H",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "QD-MiniLED" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "QD-MiniLED" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #21" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 49.8 × 19.6 cm" },
          { label: "重量", value: "5.3 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-024",
    category: "monitor",
    name: "Newsoul 18.5インチ モバイルモニター",
    brand: "Newsoul",
    tagline: "120Hz ポータブルモニター Newsoul ゲーミングモニター 大画面125%sRGB広色域 付属収納ケース付きFHD薄型軽量自立一体型 180度調整スタンド サブモニター 縦横回転 IPS非光沢 HDRサブディスプレイ VESA スピーカー内蔵 TYPE-C/Mini HDMI接続 持ち運びモニター",
    price: 17580,
    rating: 4.5,
    reviews: 176,
    image: "https://m.media-amazon.com/images/I/71idoFDVS2L._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FZR7BRBY",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #24" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "2.44Kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-027",
    category: "monitor",
    name: "Acouto Zen18 モバイルモニター",
    brand: "Acouto Zen18",
    tagline: "18.5インチ 120Hz 自立型スタンド モバイルディスプレイ ゲーム スイッチ用 USB Type-C/HDMI【1920x1080/非光沢/内蔵スピーカー/IPSパネル/VESA対応】",
    price: 18980,
    rating: 4.4,
    reviews: 684,
    image: "https://m.media-amazon.com/images/I/71tPeiFAzuL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C9J4LDFD",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #27" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "42.5 × 25.3 × 0.8 cm" },
          { label: "重量", value: "1.08 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-028",
    category: "monitor",
    name: "AVISTA ゲーミングモニター 24.5インチ",
    brand: "Avista DGF240SDB",
    tagline: "24インチ 240Hz フルHD モニター 1ms (AdaptiveSync/HDMI×2/DisplayPort/VESA対応/ブルーライト軽減/HDR400)",
    price: 12500,
    rating: 4,
    reviews: 65,
    image: "https://m.media-amazon.com/images/I/61HTMBCobrL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FSBYTJ28",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-75","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #28" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.9 × 44.8 × 19 cm" },
          { label: "重量", value: "3.2 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-029",
    category: "monitor",
    name: "KOORUI G2411X",
    brand: "KOORUI",
    tagline: "24インチ 240Hz フルHD モニター 1ms (AdaptiveSync/HDMI×2/DisplayPort/VESA対応/ブルーライト軽減/HDR400)，",
    price: 15890,
    rating: 4.2,
    reviews: 474,
    image: "https://m.media-amazon.com/images/I/716Vx0j2RuL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCD62S2H",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-75","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #29" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "15.2 × 40.9 × 61.2 cm" },
          { label: "重量", value: "3.07 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-030",
    category: "monitor",
    name: "EVICIV タッチパネルモニター 18.5インチ 120Hz",
    brand: "EVICIV",
    tagline: "120Hz タッチパネル 10点マルチタッチ 保護カバー付き モバイルディスプレイ FHD 1920×1080 100% sRGB 広色域 薄型 ポータブルモニター 光沢 IPS",
    price: 24679,
    rating: 4.2,
    reviews: 1957,
    image: "https://m.media-amazon.com/images/I/71-TV6ylHQL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GFD2GCFH",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #30" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "Mini HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "42.5 × 25.5 × 1.4 cm" },
          { label: "重量", value: "2.9Kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-031",
    category: "monitor",
    name: "CUIUIC モバイルモニター 18.5インチ",
    brand: "Mobile",
    tagline: "1920*1080FHD 大画面 120Hz IPSパネル 非光沢 HDRモード レザーケース付き USB C/mini HDMI 内蔵スピーカー スタンド付き",
    price: 15999,
    rating: 4.5,
    reviews: 77,
    image: "https://m.media-amazon.com/images/I/710UPE-pPkL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DP22FN42",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #31" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "1.05 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-032",
    category: "monitor",
    name: "CUNPU 27インチ 4K ゲーミングモニター",
    brand: "CUNPU",
    tagline: "160Hz UHD(3840x2160)解像度 4k モニター 10.7億色表示135%SRGB/100%AdobeRGB IPS非光沢パネル 縦横回転・高さ調整 FPS/PS5 120Hz 対応 VESAサポート ブルーライト軽減 フリッカーフリー デュアル HDR400nit PCモニター HDMI2.1×2/DP1.4×2",
    price: 33980,
    rating: 4.1,
    reviews: 114,
    image: "https://m.media-amazon.com/images/I/715uBZ0t6-L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GY869ZYW",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "160Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "160Hz" },
          { label: "Amazon検索", value: "PCモニター #32" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 42.6 × 18.1 cm" },
          { label: "重量", value: "7.16Kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-035",
    category: "monitor",
    name: "iiyama G-MASTER GB2471HSU-W1",
    brand: "iiyama",
    tagline: "23.8インチ Fast IPSパネル搭載 240Hz/0.3ms対応 フルHD(1920×1080)解像度 ゲーミングモニタ",
    price: 20553,
    rating: 5,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/71e1uVpZReL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FV3G6WR7",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #35" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 37.9 × 17.1 cm" },
          { label: "重量", value: "4.8 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-038",
    category: "monitor",
    name: "ASUS VY279HGR",
    brand: "ASUS",
    tagline: "Eye Care Monitor / 27インチ FHD（1920 x 1080）/ IPS / 120Hz(OC) / SmoothMotion / 1ms（MPRT）/ Adaptive Sync/ブルーライト軽減機能/フリッカーフリー",
    price: 14980,
    rating: 4.2,
    reviews: 206,
    image: "https://m.media-amazon.com/images/I/71O2ThvdW6L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08LGHP4C7",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #38" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 43.5 × 20.2 cm" },
          { label: "重量", value: "4.05 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-040",
    category: "monitor",
    name: "UPERFECT モバイルモニター 18インチ 2.5K",
    brand: "UPERFECT",
    tagline: "144Hz QLED 100%DCI-P3 IPS ゲーミング ポータブルディスプレイ 18インチ大画面2.5K（2560×1600）QLED IPS液晶 100%DCI-P3広色域と144Hz高速表示対応",
    price: 33754,
    rating: 4.2,
    reviews: 3614,
    image: "https://m.media-amazon.com/images/I/71QM24Ra0EL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FF8Y8569",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","refresh-144-plus","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18\"" },
      { label: "解像度", value: "2.5K(2560 x 1600)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18\"" },
          { label: "解像度", value: "2.5K(2560 x 1600)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #40" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "40 × 26 × 1 cm" },
          { label: "重量", value: "0.9 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-042",
    category: "monitor",
    name: "TCL Mini LED モニター 25インチ 25G54",
    brand: "TCL Mini LED",
    tagline: "FHD 広色域 液晶 非光沢 HFSパネル DisplayHDR 450nits/コントラスト比1300:1/ローカルディミング/ブルーライト軽減/目保護 フレームレス/HDMIケーブル付き/VESA対応 ゲーミングモニター/G54シリーズ",
    price: 12000,
    rating: 4.6,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/71DomHGbUAL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F3HQTJL6",
    vesaStandard: "—",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "25\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "25\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #42" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.6 × 43.9 × 18.2 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-043",
    category: "monitor",
    name: "COOLHOOD モバイルモニター 18.5インチ",
    brand: "—",
    tagline: "120Hz 1080P HDRモード・FreeSync・VESA対応 USB-C/HDMIポート ブルーライト低減 非光沢 IPS液晶パネル デュアルスピーカー内蔵 USBType-C mini HDMI",
    price: 15999,
    rating: 4.5,
    reviews: 259,
    image: "https://m.media-amazon.com/images/I/712GR3VgrNL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DP46W461",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #43" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "2.58Kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-044",
    category: "monitor",
    name: "FeuVision ゲーミングモニター 24インチ",
    brand: "FeuVision",
    tagline: "FHD 1080p, 240Hz IPSパネルPCモニター, 3辺超狭額&超薄型, 100% sRGB,広色域 ブルーライトフィルター HDMI&DPポート",
    price: 13980,
    rating: 4.2,
    reviews: 39,
    image: "https://m.media-amazon.com/images/I/81f221YecAL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F2HRQT3X",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #44" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.96Kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-045",
    category: "monitor",
    name: "JAPANNEXT ゲーミングモニター 24.5インチ",
    brand: "JAPANNEXT",
    tagline: "IPSパネル搭載 144Hz/1ms(MPRT)対応 フルHD(1920x1080)解像度 ゲーミングモニター JN-i245G144F HDMI DisplayPort HDR sRGB:99% PS5 フルHD:120Hz接続【2年保証】",
    price: 14380,
    rating: 4,
    reviews: 20,
    image: "https://m.media-amazon.com/images/I/7121fXqp4GL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F4X5M6CV",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #45" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 42.6 × 19.5 cm" },
          { label: "重量", value: "2.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-046",
    category: "monitor",
    name: "JAPANNEXT 23.8インチ IPSパネル搭載 ゲーミングモニター",
    brand: "JAPANNEXT",
    tagline: "165Hz/1ms(MPRT)対応 フルHD(1920×1080)解像度 ゲーミングモニター(ピンク) JN-Ei238G165F-PK HDMI DisplayPort sRGB:100% HDR PS5 フルHD:120Hz接続 HDMIケーブル(ホワイト)同梱【2年保証】",
    price: 13980,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71lA-jsxncL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2XKGV8Z",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #46" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 44.4 × 20 cm" },
          { label: "重量", value: "3.3 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-048",
    category: "monitor",
    name: "Vimonic モバイルモニター 18.5インチ タッチパネル",
    brand: "Mobile",
    tagline: "120Hz Vimonic グレア ゲーミングディスプレイ フルHD 自立スタンド付 18.5インチ大画面×120Hz高速表示 タッチ操作対応",
    price: 23445,
    rating: 4.2,
    reviews: 134,
    image: "https://m.media-amazon.com/images/I/71Y5GojhM7L._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GT95VY87",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #48" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "2.46Kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-049",
    category: "monitor",
    name: "aimuonos 18.5インチ ポータブルモニター",
    brand: "—",
    tagline: "超薄型0.3インチ 1080P IPS 光沢 120Hz ゲームモニター USB-C/HDMI接続 外部ディスプレイ スリム軽量2.4ポンド",
    price: 15999,
    rating: 4.1,
    reviews: 218,
    image: "https://m.media-amazon.com/images/I/71tMxlvKPLL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CB45H7XP",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #49" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "1.09 kg" },
        ]},

    ],
  },{
    id: "mon-hfr144-p2-051",
    category: "monitor",
    name: "HKC 27インチ モニター FHD IPS",
    brand: "—",
    tagline: "144Hz Adaptive-Sync sRGB99% 3年保証 在宅ワーク向け V2718S テレワーク向け・ハードウェア低ブルーライト・フリッカーフリー・HDMI1.4・VGA・Audio出力・VESA100×100mm対応・チルト角度調整",
    price: 15979,
    rating: 4.4,
    reviews: 33,
    image: "https://m.media-amazon.com/images/I/71ALt1cqehL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G26KGR8S",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #51" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 46.1 × 18.5 cm" },
          { label: "重量", value: "3.9 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-052",
    category: "monitor",
    name: "HKC ゲーミングモニター G24H3D",
    brand: "HKC MG24H39FS",
    tagline: "PCモニター240Hz(OC260Hz) FHD FastIPS MPRT1ms 3年保証 1920×1080・Adaptive-Sync・90%DCI-P3・ΔE≤2・DisplayHDR400・ハードウェア低ブルーライト・フリッカーフリー・ノングレア・チルト角度調整・VESA100×100mm・HDMI2.0×2",
    price: 17980,
    rating: 4.8,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/71wxfWgrQ3L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G7JTLDB1",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #52" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 44.2 × 21.5 cm" },
          { label: "重量", value: "3.5 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-053",
    category: "monitor",
    name: "JN-IPS245G144F",
    brand: "JAPANNEXT",
    tagline: "【2年保証】IPSパネル,144Hz/1ms,FHD,1080p1920×1080解像度,HDMI,DisplayPort,VESA対応,ブルーライトカット,視野角178°",
    price: 15980,
    rating: 5,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71ZZPEslGpL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F7XG3551",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #53" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 41.9 × 21.5 cm" },
          { label: "重量", value: "2.7 kg" },
        ]},

    ],
  },
  {
    id: "mon-hfr144-p2-055",
    category: "monitor",
    name: "UPERFECT 18.5インチ120Hz Eye Care モバイルモニター",
    brand: "Mobile",
    tagline: "QLED FHD 非光沢 Eye Care ポータブルディスプレイ NxtLED 【Amazon.co.jp限定】モバイルディスプレイ ブルーライト フリッカーフリー 目に優しい USB-C/HDMI",
    price: 28980,
    rating: 4.2,
    reviews: 3614,
    image: "https://m.media-amazon.com/images/I/81lUEs+ME1L._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTYD4CLY",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #55" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "42.3 × 25 × 0.8 cm" },
          { label: "重量", value: "1.5 kg" },
        ]},

    ],
  },
]
