import type { Gadget } from "./gadgets"

/** Amazon.co.jp Acer ディスプレイ検索（18.0～25.9インチ / Acer）。 */
export const monitorAcerSearch: Gadget[] = [
  {
    id: "mon-acer-001",
    category: "monitor",
    name: "Acer Nitro VG250QW3bmiipx",
    brand: "Acer",
    tagline: "IPS 240Hz フルHD 0.5ms(GTG) 非光沢 sRGB 99% AMD FreeSync Premium HDR10 ブルーライト低減 ブラックブースト HDMI 2.1 DisplayPort v1.4 スピーカー・ヘッドフォン端子 ゼロフレーム ゲーミングモニター 3年保証(パネルは1年)",
    price: 20980,
    rating: 4.6,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/810x87JO2SL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX4V8L8N",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #1" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 43 × 19.9 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-002",
    category: "monitor",
    name: "Acer 24.5インチ フルHD 200Hz ゲーミングモニター",
    brand: "Acer",
    tagline: "フルHD 200Hz 0.5ms(GTG) 広視野角 VA 非光沢 sRGB 99% AMD FreeSync Premium HDR10 ブラックブースト VRB対応 ブルーライト低減 HDMI 2.0 DisplayPort v1.2 Acer Display Widget Nitro ゲーミングモニター 3年保証",
    price: 16980,
    rating: 4.4,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/61FGoBAvUVL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FF9GHPSK",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon検索", value: "PCモニター #2" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 41.4 × 21 cm" },
          { label: "重量", value: "3.4 kg" },
        ]},

    ],
  },{
    id: "mon-acer-004",
    category: "monitor",
    name: "Acer 21.5インチ VA フルHD 120Hz モニター",
    brand: "Acer",
    tagline: "120Hz 1ms(VRB) 非光沢 sRGB 99% Adaptive-Sync ブルーライト低減 ゼロフレーム 薄型 HDMI 1.4 ミニD-Sub 15ピン 6軸カラー スタンダードモニター 3年保証(パネルは1年)",
    price: 10980,
    rating: 4.1,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61gggQQ10xL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX57S1BD",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #4" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.3 × 37.7 × 19.2 cm" },
          { label: "重量", value: "2.5 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-005",
    category: "monitor",
    name: "Acer Nitro ゲーミングモニター 21.5インチ",
    brand: "Acer",
    tagline: "ゲーミングモニター 21.5インチ VA 非光沢 フルHD 100Hz 1ms(VRB) HDMI ミニD-Sub15 VESAマウント対応 スピーカー内蔵 ヘッドホン端子",
    price: 11800,
    rating: 4.2,
    reviews: 569,
    image: "https://m.media-amazon.com/images/I/61OWVzAo81L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C4J5MPL4",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #5" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.2 × 37.9 × 22.1 cm" },
          { label: "重量", value: "2.7 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-006",
    category: "monitor",
    name: "Acer NITRO KG241YP6bip",
    brand: "Acer",
    tagline: "フルHD 144Hz 1ms(VRB) IPS 非光沢 sRGB 99% AMD FreeSync ブラックブースト VRB対応 ブルーライト低減 HDMI 1.4 DisplayPort v1.2 ゲームビューテクノロジー Acer Display Widget 6軸カラー調整 VESAマウント対応 Nitro ゲーミングモニター",
    price: 13980,
    rating: 4.7,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61ZwVfzi0uL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCM37HCT",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #6" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 42.3 × 21 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-007",
    category: "monitor",
    name: "Acer モニター 23.8インチ EK241YP6bmix",
    brand: "Acer",
    tagline: "23.8インチ IPS フルHD 144Hz 1ms(VRB) 非光沢 sRGB 99% AMD FreeSync ブルーライト低減 スピーカー内蔵 ゼロフレーム HDMI 1.4 ミニD-Sub 15ピン 6軸カラー スタンダード 3年保証",
    price: 12980,
    rating: 4.2,
    reviews: 11,
    image: "https://m.media-amazon.com/images/I/61QKJiSgVCL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX4Z1YX1",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #7" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 40.1 × 19.2 cm" },
          { label: "重量", value: "2.9 kg" },
        ]},

    ],
  },{
    id: "mon-acer-009",
    category: "monitor",
    name: "Acer モニター 23.8インチ EK241YP6bi",
    brand: "Acer",
    tagline: "IPS フルHD 144Hz 1ms(VRB) 非光沢 sRGB 99% AMD FreeSync ブルーライト低減 ゼロフレーム HDMI 1.4 ミニD-Sub 15ピン 6軸カラー スタンダード 3年保証",
    price: 11980,
    rating: 4.5,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/61f5D8tkzkL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX58C11Q",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #9" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 40.1 × 19.2 cm" },
          { label: "重量", value: "2.9 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-010",
    category: "monitor",
    name: "Acer NITRO23.8インチ QG241YP6bmipx",
    brand: "Acer",
    tagline: "Acer 23.8\" Full HD 144Hz 1ms (VRB) IPS Anti-Glare sRGB 99% AMD FreeSync HDMI 1.4",
    price: 15990,
    rating: 4.4,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61mCmqMyu+L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCM4WL7F",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #10" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 42.3 × 19.9 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-011",
    category: "monitor",
    name: "Acer Nitro23.8インチ VG240YW3bmiipx",
    brand: "Acer",
    tagline: "IPS 240Hz フルHD 0.5ms(GTG) 非光沢 sRGB 99% AMD FreeSync Premium HDR10 ブルーライト低減 ブラックブースト HDMI 2.0 DisplayPort v1.4 スピーカー・ヘッドフォン端子 ゼロフレーム ゲーミングモニター 3年保証",
    price: 18980,
    rating: 4,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/81MpEDdbxJL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G2MSZ4HZ",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #11" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 41.6 × 19.9 cm" },
          { label: "重量", value: "3.1 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-012",
    category: "monitor",
    name: "Acer AlphaLine E200Qbi",
    brand: "Acer",
    tagline: "19.5インチ HD+ (1600x900) 非光沢 TN 75Hz 6ms (GTG) NTSC 72% HDMI 1.4 ミニD-Sub 15ピン スピーカー・ヘッドフォン端子非搭載",
    price: 9374,
    rating: 1.8,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61+-rLS6KLL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DMF3351F",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","refresh-75","port-hdmi","vesa-100","panel-tn"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "19.5\"" },
      { label: "解像度", value: "HD₊(1600×900)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "TN 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "19.5\"" },
          { label: "解像度", value: "HD₊(1600×900)" },
          { label: "パネル", value: "TN 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #12" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "46.9 × 37.3 × 21.1 cm" },
          { label: "重量", value: "2 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-013",
    category: "monitor",
    name: "Acer Nitro KG241YX3bmipx",
    brand: "Acer",
    tagline: "23.8インチ フルHD 200Hz 0.5ms(GTG) 広視野角 VA 非光沢 sRGB 99% AMD FreeSync Premium HDR10 ブラックブースト VRB対応 ブルーライト低減 HDMI 2.0 DisplayPort v1.4 Acer Display Widget Nitro ゲーミングモニター 3年保証",
    price: 14980,
    rating: 4.6,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/61aLfZ1thBL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FF9DJVYS",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon検索", value: "PCモニター #13" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41 × 21 cm" },
          { label: "重量", value: "3.1 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-014",
    category: "monitor",
    name: "Acer AlphaLine EK221QJ0bmix",
    brand: "Acer",
    tagline: "21.5インチ VA フルHD 120Hz 1ms(VRB) 非光沢 sRGB 99% Adaptive-Sync ブルーライト低減 ゼロフレーム HDMI 1.4 ミニD-Sub 15ピン スピーカー・ヘッドホン端子 6軸カラー スタンダードモニター 3年保証",
    price: 11880,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61uCe11Hw3L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G5HRZTNV",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #14" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.3 × 37.7 × 19.2 cm" },
          { label: "重量", value: "2.5 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-015",
    category: "monitor",
    name: "Acer Nitro VG250QF3bmiipx",
    brand: "Acer",
    tagline: "24.5インチ IPS 320Hz フルHD 0.5ms(GTG) 非光沢 sRGB 99% AMD FreeSync Premium HDR10 ブルーライト低減 ブラックブースト HDMI 2.0 DisplayPort v1.4 スピーカー・ヘッドフォン端子 ゼロフレーム ゲーミングモニター 3年保証",
    price: 24980,
    rating: 4.3,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/618Of7fdPbL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX54Z96J",
    vesaStandard: "—",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "320Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "320Hz" },
          { label: "Amazon検索", value: "PCモニター #15" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 43 × 19.9 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-016",
    category: "monitor",
    name: "Acer AlphaLine KA242YP6bmix",
    brand: "Acer",
    tagline: "23.8インチ IPS フルHD 144Hz 1ms(VRB) 非光沢 sRGB 99% AMD FreeSync ブルーライト低減 スピーカー内蔵 ゼロフレーム HDMI 1.4 ミニD-Sub 15ピン 6軸カラー スタンダード 3年保証",
    price: 12980,
    rating: 3.8,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61CIGz36OtL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX561MSM",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #16" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 42.3 × 18.5 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },{
    id: "mon-acer-019",
    category: "monitor",
    name: "Acer Nitro KG251QZ1bmiipx",
    brand: "Acer",
    tagline: "ゲーミングモニター 24.5インチ VA フルHD 非光沢 280Hz 1ms sRGB99% AMD FreeSync Premium HDR10 HDMI 2.0 DisplayPort 1.4 スピーカー・ヘッドフォン端子搭載",
    price: 23980,
    rating: 4.4,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/61CGetpxzsL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DMF317JS",
    vesaStandard: "—",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "280Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "280Hz" },
          { label: "Amazon検索", value: "PCモニター #19" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.0", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 42.9 × 21 cm" },
          { label: "重量", value: "3.3 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-020",
    category: "monitor",
    name: "Acer Nitro VG240YS6bmix",
    brand: "Acer",
    tagline: "23.8インチ IPS フルHD 180Hz 1ms(VRB) 非光沢 sRGB 99% AMD FreeSync ブルーライト低減 ブラックブースト HDMI 2.1 ミニD-Sub 15ピン スピーカー・ヘッドフォン端子・3.5mmステレオミニジャック 4辺フレームレス ゲーミングモニター 3年保証",
    price: 16679,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61H0BoxMC6L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6WQTYQG",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #20" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 42.3 × 19.9 cm" },
          { label: "重量", value: "3.1 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-021",
    category: "monitor",
    name: "Acer Nitro QG221QJ0bmix",
    brand: "Acer",
    tagline: "21インチ VA 120Hz フルHD 1ms(VRB) 非光沢 sRGB 99% AMD FreeSync ブルーライト低減 ブラックブースト HDMI 1.4 ミニD-Sub 15ピン スピーカー・ヘッドフォン端子 ゼロフレーム ゲーミングモニター 3年保証",
    price: 12880,
    rating: 2.9,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/71g9UXyACJL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GK5S5W6Q",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #21" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.2 × 38.6 × 19.9 cm" },
          { label: "重量", value: "2.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-022",
    category: "monitor",
    name: "Acer Nitro VG240YX1bmiipx",
    brand: "Acer",
    tagline: "ゲーミングモニター 23.8インチ IPS フルHD 非光沢 200Hz 0.5ms sRGB 99% AMD FreeSync Premium HDR10 HDMI 2.0 DisplayPort v1.2 スピーカー・ヘッドフォン端子 搭載 Nitro",
    price: 17680,
    rating: 4.2,
    reviews: 62,
    image: "https://m.media-amazon.com/images/I/61EyjdTJaNL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DM8K72P1",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon検索", value: "PCモニター #22" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 41.6 × 19.9 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-023",
    category: "monitor",
    name: "Acer Nitro VG240YW5bmiipx",
    brand: "Acer",
    tagline: "23.8インチ IPS フルHD 260Hz 0.5ms(GTG) 非光沢 sRGB 99% AMD FreeSync Premium HDR10 ブルーライト低減 ブラックブースト HDMI 2.1 DisplayPort v1.4 スピーカー・ヘッドフォン端子 ゼロフレーム ゲーミングモニター 3年保証",
    price: 19979,
    rating: 1,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61lB6bJ29RL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6WWMF8Y",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "260Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "260Hz" },
          { label: "Amazon検索", value: "PCモニター #23" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 42.1 × 19.9 cm" },
          { label: "重量", value: "3.2 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-024",
    category: "monitor",
    name: "Acer AlphaLine EK251QP6bmix",
    brand: "Acer",
    tagline: "4.5インチ IPS 144Hz 1ms(VRB) 非光沢 sRGB 99% AMD FreeSync ブルーライト低減 ゼロフレームプロ HDMI 1.4 ミニD-Sub 15ピン スピーカー・ヘッドフォン端子 6軸カラー調整 スタンダードモニター 3年保証",
    price: 14680,
    rating: 3.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/613LryqrTbL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FJ2Y8ZKD",
    vesaStandard: "—",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #24" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 40.9 × 19.2 cm" },
          { label: "重量", value: "2.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-025",
    category: "monitor",
    name: "Acer AlphaLine EK251QP6bi",
    brand: "Acer",
    tagline: "24.5インチ IPS フルHD 144Hz 1ms(VRB) 非光沢 sRGB 99% AMD FreeSync ブルーライト低減 チルト調整 4辺フレームレス HDMI 1.4 ミニD-Sub 15ピン 6軸カラー 3年保証",
    price: 13280,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61i+-KjjYUL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQ3CC7LD",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #25" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 40.9 × 19.2 cm" },
          { label: "重量", value: "2.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-026",
    category: "monitor",
    name: "SDGs推進 21.5型",
    brand: "Acer",
    tagline: "21.5\" FHD VA SDGsモデル",
    price: 10965,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/41Kyf5OwYJL._AC_SL1500_.jpg",
    connection: "HDMI / ミニD-Sub",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FN2L4XTZ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #26" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "ミニD-Sub (VGA)", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-acer-028",
    category: "monitor",
    name: "Acer VERO CB242YP6bmiprx",
    brand: "Acer",
    tagline: "23.8インチ フルHD IPS 非光沢 エルゴスタンド 144Hz 1ms(VRB) sRGB 99% ブルーライトシールドプロ HDMI 1.4 DisplayPort v1.2 ミニD-Sub 15ピン スピーカー ヘッドフォン端子 VESAマウント対応 4辺フレームレス モニター 3年保証",
    price: 17980,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61RIJBfwpeL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GNPZWMSS",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #28" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 53.6 × 24.5 cm" },
          { label: "重量", value: "2.6Kg" },
        ]},

    ],
  },
  {
    id: "mon-acer-032",
    category: "monitor",
    name: "Acer PM191Q Ebmiuux",
    brand: "Acer",
    tagline: "ポータブルモニター | 18.5インチ FHD IPS | アダプティブ同期対応 (FreeSync対応) | スリムデザイン | ノートパソコン/Mac用外部モニター | 100Hz | USB 3.1 Type-Cポート×2 & HDMI 1.4",
    price: 25192,
    rating: 4.7,
    reviews: 69,
    image: "https://m.media-amazon.com/images/I/619LNzolY9L._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FJS4YHPL",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #32" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "42.2 × 25.6 × 1.4 cm" },
          { label: "重量", value: "1.13 kg" },
        ]},

    ],
  },
]
