import type { Gadget } from "./gadgets"

/** Amazon.co.jp コンピュータモニターアーム（売れ筋 + カテゴリ検索 + featured検索2ページ目）。 */
export const monitorArmBestsellers: Gadget[] = [
  {
    id: "arm-bs-001",
    category: "monitor-arm",
    name: "ErGear モニターアーム",
    brand: "Amazonベーシック",
    tagline: "ErGear モニターアーム シングル 13～34インチ 耐荷重9kg 高いポール ガススプリング式 PCディスプレイアームモニターをより高い位置に設置可能 , 高さ・奥行き・左右・見やすい位置へ画面を自由調節",
    price: 3399,
    rating: 3.9,
    reviews: 1315,
    image: "https://m.media-amazon.com/images/I/511QVoYojOL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CQXMT3QC",
    highlights: [
      { label: "対応サイズ", value: "13〜34インチ" },
      { label: "耐荷重", value: "2.2～9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜34インチ" },
          { label: "耐荷重", value: "2.2～9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-002",
    category: "monitor-arm",
    name: "PS1S Wave",
    brand: "Pixio",
    tagline: "Pixio PS1S Wave モニターアーム シングル ブラック大型対応| 上下左右調整| 32インチ対応| 24インチ対応| 27インチ対応",
    price: 8980,
    rating: 4.3,
    reviews: 447,
    image: "https://m.media-amazon.com/images/I/518HO1ULN7L._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00CWXRI44",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "1.0～9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "1.0～9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-003",
    category: "monitor-arm",
    name: "HNSS6",
    brand: "HUANUO",
    tagline: "HUANUO (ファーノー) PCモニターアーム HNSS6 液晶ディスプレイアーム 13～32インチ対応| 耐荷重2～9kg| ガススプリング式| グロメット式＆クランプ式| VESA100*100| 多角度調節|",
    price: 3699,
    rating: 4.2,
    reviews: 1833,
    image: "https://m.media-amazon.com/images/I/6187d2GHR7L._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07W532F8J",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-004",
    category: "monitor-arm",
    name: "ERGOTRON エルゴトロン LX",
    brand: "ERGOTRON",
    tagline: "ERGOTRON エルゴトロン LX モニターアーム デスクマウント ブラック 黒 34インチまで対応 国内正規品 10年保証付シングル 耐荷重3.2-11.3kgまで メカニカルスプリング式 クランプ式 VESA規格 人間工学的デザイン",
    price: 18200,
    rating: 4.6,
    reviews: 16416,
    image: "https://m.media-amazon.com/images/I/610HqQsInRL._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07Q8TJ2KL",
    highlights: [
      { label: "対応サイズ", value: "21.5〜34インチ" },
      { label: "耐荷重", value: "3.2〜11.3kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "21.5〜34インチ" },
          { label: "耐荷重", value: "3.2〜11.3kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-005",
    category: "monitor-arm",
    name: "NB ERGONOMIC A5",
    brand: "NB",
    tagline: "17〜32インチ対応| 片手で軽く動く| ノートPCと2画面に最適| 姿勢に合わせて高さ調整| 9kgまで",
    price: 3280,
    rating: 4.4,
    reviews: 380,
    image: "https://m.media-amazon.com/images/I/61h0qKX0JZL._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GHT7N1HT",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "—" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "—" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-006",
    category: "monitor-arm",
    name: "DPA-SS02BK",
    brand: "ELECOM",
    tagline: "エレコム モニターアーム シングルアーム ブラック DPA-SS02BK 17~32インチ対応| 耐荷重9kg| ガス式| VESA規格対応",
    price: 4490,
    rating: 4.1,
    reviews: 2131,
    image: "https://m.media-amazon.com/images/I/51A-CNbw-7L._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09DSCG8DC",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-007",
    category: "monitor-arm",
    name: "NB ERGONOMIC モニターアーム",
    brand: "—",
    tagline: "NB ERGONOMIC モニターアーム シングル 場所をとらないポール型 最大32インチ / 耐荷重9kg クランプ式・グロメット式対応 H100-G ディープグレー",
    price: 2480,
    rating: 4.2,
    reviews: 1534,
    image: "https://m.media-amazon.com/images/I/51SpEJDs0cL._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08CXNR4QY",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "—" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "—" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-009",
    category: "monitor-arm",
    name: "MOUNTUP PCモニターアーム",
    brand: "ERGOMAKER",
    tagline: "MOUNTUP PCモニターアーム 32インチ対応 耐荷重2～8kg ディスプレイアーム 白 ガススプリング式 液晶モニタースタンド クランプ式 グロメット式 VESA対応 75x75mm 100×100mm (ホワイト)",
    price: 2960,
    rating: 4,
    reviews: 2094,
    image: "https://m.media-amazon.com/images/I/517NFw8CLbL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08SVW59KT",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-010",
    category: "monitor-arm",
    name: "ERGOMAKER モニターアーム",
    brand: "ERGOMAKER",
    tagline: "ERGOMAKER モニターアーム ディスプレイアーム13~27インチモニター対応| 多角度調節| ケーブル収納| VESA:75x75mm/100x100mm",
    price: 1999,
    rating: 4.2,
    reviews: 430,
    image: "https://m.media-amazon.com/images/I/511z5GX27hL._AC_SL1500_.jpg",
    connection: "クランプ式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B5Z5WQZL",
    highlights: [
      { label: "対応サイズ", value: "13〜27インチ" },
      { label: "耐荷重", value: "8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜27インチ" },
          { label: "耐荷重", value: "8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式" },
          { label: "駆動方式", value: "フルモーション" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-011",
    category: "monitor-arm",
    name: "MOUNTUP PCモニターアーム",
    brand: "THEARK",
    tagline: "MOUNTUP PCモニターアーム ディスプレイアーム 32インチ対応耐荷重2～8kg| クランプ式 グロメット式| VESA対応 75x75mm 100×100mm| 液晶モニタースタンド",
    price: 2899,
    rating: 3.9,
    reviews: 14591,
    image: "https://m.media-amazon.com/images/I/71-wm9+nUIL._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07Z7ZGHD5",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0~8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0~8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-012",
    category: "monitor-arm",
    name: "THEARK シングルモニターアーム",
    brand: "THEARK",
    tagline: "シングルモニターアーム 白 17～32インチ対応 THEARK ライトなしベーシックモデル VESA75×75/100×100 クランプ・グロメット式monitor arm 機械式スプリングでスムーズ調整 上下80°・左右180°・360°回転 デスク下を活用 クランプ・グロメット対応 天板10～85mm ケーブル収納 在宅ワーク・ゲーム・PC作業向け 最大9kg",
    price: 3280,
    rating: 4.2,
    reviews: 50,
    image: "https://m.media-amazon.com/images/I/51WVuuhEPmL._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWMJ2R4T",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-016",
    category: "monitor-arm",
    name: "HUANUO (ファーノー) モニターアーム HNCM9",
    brand: "HUANUO",
    tagline: "HUANUO (ファーノー) モニターアーム HNCM9 13-35インチ対応 シングルロングポール| 10kg高耐荷重| VESA 75x75mm 100x100mm対応| クランプ式 グロメット式| 多角度調節",
    price: 3999,
    rating: 4.1,
    reviews: 227,
    image: "https://m.media-amazon.com/images/I/41Egro1txSL._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CSJWLGQD",
    highlights: [
      { label: "対応サイズ", value: "13〜35インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜35インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-018",
    category: "monitor-arm",
    name: "BONTEC モニターアーム",
    brand: "BONTEC",
    tagline: "BONTEC モニターアーム シングル 13-32インチ ガススプリング 耐荷重9kg VESA75×75/100×100mm Cクランプ・グロメット高さ調節・チルト・スイベル・360°回転に対応",
    price: 2999,
    rating: 4.5,
    reviews: 5571,
    image: "https://m.media-amazon.com/images/I/61A2uZP2B+L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DSL5BZGY",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-019",
    category: "monitor-arm",
    name: "HNCM12",
    brand: "HUANUO",
    tagline: "HUANUO (ファーノー) モニターアーム ディスプレイアーム 1画面 シングル 10～32型 耐荷重1～8kg VESA75×75mm/100×100mm グロメット&クランプ式 多角度調節可能 在宅ワーク ゲーミング デスク周り 便利グッズ HNCM12",
    price: 2079,
    rating: 4,
    reviews: 304,
    image: "https://m.media-amazon.com/images/I/51t8kdfiaKL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTDCZT1M",
    highlights: [
      { label: "対応サイズ", value: "10〜32インチ" },
      { label: "耐荷重", value: "1.0〜8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "10〜32インチ" },
          { label: "耐荷重", value: "1.0〜8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-020",
    category: "monitor-arm",
    name: "MD6DB",
    brand: "suptek",
    tagline: "suptek 支柱取付けシングルモニターアーム MD6DB 13-27インチ対応| 耐荷重9kg| VESA規格75-100mm| ポール取り付け",
    price: 2000,
    rating: 4.1,
    reviews: 480,
    image: "https://m.media-amazon.com/images/I/51xhmzytXlL._AC_SL1500_.jpg",
    connection: "ポールマウント方式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07QXW47NW",
    highlights: [
      { label: "対応サイズ", value: "13〜27インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "ポールマウント方式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜27インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "ポールマウント方式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-021",
    category: "monitor-arm",
    name: "MD7421",
    brand: "Bracwiser",
    tagline: "Bracwiser PCモニターアーム MD7421 ディスプレイアーム 4軸 水平多関節13-32インチ対応| グロメット式＆クランプ式| VESA規格75-100mm| 耐荷重10KG",
    price: 2600,
    rating: 4.1,
    reviews: 1495,
    image: "https://m.media-amazon.com/images/I/51EUpBLnkzL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08LD23JD1",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-024",
    category: "monitor-arm",
    name: "BONTEC デュアルモニターアーム",
    brand: "—",
    tagline: "BONTEC デュアルモニターアーム 13～32インチ対応 各アーム耐荷重10kg VESA75×75・100×100mm クランプ・グロメット式高さ調整・スイベル・チルト・360°回転に対応",
    price: 2849,
    rating: 4.3,
    reviews: 2490,
    image: "https://m.media-amazon.com/images/I/61WQDbSvceL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09LV6VVHQ",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },{
    id: "arm-bs-026",
    category: "monitor-arm",
    name: "CR-LAC215BK",
    brand: "サンワサプライ",
    tagline: "サンワサプライ モニターアーム（デュアル・ショートアーム・薄型ショートクランプ・ブラック） CR-LAC215BK",
    price: 6989,
    rating: 4.2,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/41GvDaFF+OL._AC_SL1500_.jpg",
    connection: "クランプ式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJC2CLJL",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-027",
    category: "monitor-arm",
    name: "KOORUIモニターアーム",
    brand: "KOORUI",
    tagline: "デスクマウント シングル 17～32型 VESAアーム| クランプ式&グロメット式| 耐荷重9kg| 多角度調節| ケーブル管理",
    price: 3998,
    rating: 3.7,
    reviews: 789,
    image: "https://m.media-amazon.com/images/I/51QolG53TRL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C22Z91LY",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0～9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0～9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-053",
    category: "monitor-arm",
    name: "Amazonベーシック モニターアーム",
    brand: "Amazonベーシック",
    tagline: "Amazonベーシック モニターアーム シングル 調整可能 デスクマウント 最大32インチ (81.3cm) (38インチ (96.5cm) ウルトラワイド) 対応 耐荷重10.0kg テンション調整可能 VESA 75 × 75/100 × 100 ブラック",
    price: 2977,
    rating: 4.5,
    reviews: 110,
    image: "https://m.media-amazon.com/images/I/61tO+TjbiZL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FX8MQ4M7",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-056",
    category: "monitor-arm",
    name: "BMA-1MS-BK",
    brand: "Bauhutte",
    tagline: "auhutte (バウヒュッテ) ロングモニターアームMS リクライニング時に引き寄せられるロング仕様 可動距離 最大約76cm 34インチ(2～10kg)まで メカニカルスプリング式 シングル 1画面 BMA-1MS-BK",
    price: 12800,
    rating: 4.2,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/71Ce-BWWx-L._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FJRJKZ71",
    highlights: [
      { label: "対応サイズ", value: "〜34インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜34インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-057",
    category: "monitor-arm",
    name: "ZJ35-02",
    brand: "—",
    tagline: "支柱取付けモニターアーム 17～32インチ VESA75/100 耐荷重8kg1画面 角度調節可能 金属製 後付け簡単 省スペース",
    price: 1899,
    rating: 4.5,
    reviews: 120,
    image: "https://m.media-amazon.com/images/I/51pLe8J53hL._AC_SL1500_.jpg",
    connection: "ポールマウント方式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09FSG5X2S",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "ポールマウント方式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "ポールマウント方式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-058",
    category: "monitor-arm",
    name: "MDX003DB",
    brand: "—",
    tagline: "支柱取付け シングルモニターアーム ガス式ディスプレイアーム 3関節型 長いアーム 35ＭＭポール取り付け 13-34インチ対応 耐荷重11kg",
    price: 3149,
    rating: 3.6,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/517rEbo7ptL._AC_SL1500_.jpg",
    connection: "ポールマウント方式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS99Q2R4",
    highlights: [
      { label: "対応サイズ", value: "13〜34インチ" },
      { label: "耐荷重", value: "11.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "ポールマウント方式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜34インチ" },
          { label: "耐荷重", value: "11.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "ポールマウント方式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-059",
    category: "monitor-arm",
    name: "Tasavzモニターアーム（USBハブ付・ブラック）",
    brand: "—",
    tagline: "モニターアーム USBハブ付き ガススプリング式 17-32インチ対応 耐荷重2-10kg 五軸回転 多角度調整 クランプ式/グロメット式 VESA規格対応 ケープル収納 （ブラック）",
    price: 3980,
    rating: 3.8,
    reviews: 47,
    image: "https://m.media-amazon.com/images/I/51M6LlBjVqL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FN73C6VS",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },{
    id: "arm-bs-061",
    category: "monitor-arm",
    name: "DPA-DS07BK",
    brand: "ELECOM",
    tagline: "エレコム モニターアーム デュアル 2画面 DPA-DS07BK ブラック 17~32インチ対応| 耐荷重9kg| ガス式| VESA規格対応",
    price: 6980,
    rating: 3.8,
    reviews: 266,
    image: "https://m.media-amazon.com/images/I/61S8YoQc0dL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C7VPZ8ZK",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-066",
    category: "monitor-arm",
    name: "BONTEC モニターアーム",
    brand: "BONTEC",
    tagline: "BONTEC モニターアーム シングル ガススプリング式 13～34インチ 耐荷重3～9kg VESA75×75/100×100mm 対応 液晶高さ364～635mmの調整範囲と最大570mmのロングリーチ設計。上下・前後・左右へ自由に動かし、快適な視線位置と広いデスク空間を実現",
    price: 3419,
    rating: 4.5,
    reviews: 5571,
    image: "https://m.media-amazon.com/images/I/61DnGPihgmL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CKPFFQ8X",
    highlights: [
      { label: "対応サイズ", value: "13〜34インチ" },
      { label: "耐荷重", value: "3.0～9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜34インチ" },
          { label: "耐荷重", value: "3.0～9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-067",
    category: "monitor-arm",
    name: "GH-AMDN2V-BK",
    brand: "GREENHOUSE",
    tagline: "モバイルモニター スタンド アーム VESA対応 アルミ製 6関節 13‐18.5インチ対応 耐荷重1.8KG",
    price: 3799,
    rating: 4.1,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/51uwY-ZXQuL._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FLK2F2YT",
    highlights: [
      { label: "対応サイズ", value: "13〜21.4インチ" },
      { label: "耐荷重", value: "1.8kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜21.4インチ" },
          { label: "耐荷重", value: "1.8kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },{
    id: "arm-bs-069",
    category: "monitor-arm",
    name: "A1-W",
    brand: "cocopar",
    tagline: "cocopar モニターアーム 白 シングル 2WAY付け方 ホワイト ディスプレイアーム ガススプリング式 17インチ~32インチ 対応 液晶モニターアーム ケーブル収納 ゲーミングモニターアーム VESA 角度調節 薄型 コンパクト 省スペース 上下/前後/左右/360度回転 耐荷重9kg 24インチ 27インチ 32インチ対応 A1-W",
    price: 4084,
    rating: 4,
    reviews: 298,
    image: "https://m.media-amazon.com/images/I/41+PnrFauVL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FBGQDNP3",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0～9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0～9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-070",
    category: "monitor-arm",
    name: "DPAWSN01BK",
    brand: "ELECOM",
    tagline: "エレコム モニターアーム ディスプレイアーム DPAWSN01BK シングル ロング ブラック17~32インチ対応| 耐荷重9kg",
    price: 2989,
    rating: 3.8,
    reviews: 65,
    image: "https://m.media-amazon.com/images/I/61+qPq3Ij0L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FFGQSRCL",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-072",
    category: "monitor-arm",
    name: "HNHM5B",
    brand: "ErGear",
    tagline: "HUANUO (ファーノー) モニターアーム デュアル 上下 縦2画面 17-32インチ対応 耐荷重8kg ロング ポール 高い位置PC 液晶ディスプレイアーム グロメット式＆クランプ式 75*75/100*100mmVESA規格対応 ゲーミング デスク周り 便利グッズ HNHM5B",
    price: 2799,
    rating: 4.4,
    reviews: 954,
    image: "https://m.media-amazon.com/images/I/61+kFGE0aAL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FVSBNV8L",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-074",
    category: "monitor-arm",
    name: "ML7802",
    brand: "Bracwiser",
    tagline: "Bracwiser モニターアーム デュアルディスプレイ スタンド 上下2画面 PCモニターアーム 液晶ディスプレイ スタンド アーム抜き 自立式 13-32インチ対応 耐荷重10kg（1台） VESA規格75-100mm ML7802",
    price: 3850,
    rating: 4.2,
    reviews: 321,
    image: "https://m.media-amazon.com/images/I/51g3oIauw-L._AC_SL1500_.jpg",
    connection: "テーブルトップマウント/グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0967GN1Y4",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント/グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-075",
    category: "monitor-arm",
    name: "BONTEC モニターアーム",
    brand: "BONTEC",
    tagline: "BONTEC モニターアーム 1画面 13～32インチ対応 耐荷重10kg VESA75×75・100×100mm クランプ・グロメット式高さ調整・チルト・回転・スイベルに対応、",
    price: 2099,
    rating: 4.6,
    reviews: 10926,
    image: "https://m.media-amazon.com/images/I/61GnonVXS7L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C58GTXF5",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-076",
    category: "monitor-arm",
    name: "100-LAC003",
    brand: "BONTEC",
    tagline: "サンワダイレクト モニターアーム 水平垂直3関節 32インチ対応 耐荷重12㎏ ガス圧式 クランプ/グロメット 回転 ブラック 100-LAC003高さ調整,角度調整,ディスプレイアーム",
    price: 4980,
    rating: 4.1,
    reviews: 109,
    image: "https://m.media-amazon.com/images/I/51jC4DTM8gL._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CQNK2XQ6",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "1.5～12.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "1.5～12.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-078",
    category: "monitor-arm",
    name: "WORLDLIFT モニターアーム デュアル",
    brand: "WORLDLIFT",
    tagline: "WORLDLIFT モニターアーム デュアル 24～38インチ対応 調整可能 VESA スライド式 ディスプレイアーム 2画面 ポール 耐荷重9kg/1モニター グロメット式&クランプ式",
    price: 5499,
    rating: 4.2,
    reviews: 17,
    image: "https://m.media-amazon.com/images/I/61RNM1-GWjL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTLHYL4N",
    highlights: [
      { label: "対応サイズ", value: "24〜38インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "24〜38インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-079",
    category: "monitor-arm",
    name: "MU1006-07",
    brand: "—",
    tagline: "MOUNTUP モニターアーム 上下2画面 PCモニタースタンド 置き型 デュアルディスプレイ 32インチまで 縦並び 耐荷重各15kg 自立式 アーム抜き 高さ調整 VESA75mm 100mm 上下左右可動 回転可能 MU1006-07",
    price: 3699,
    rating: 4.1,
    reviews: 129,
    image: "https://m.media-amazon.com/images/I/61TDWA3mH1L._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CL9X7LX8",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "15.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "15.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-080",
    category: "monitor-arm",
    name: "DPA-SS11BK",
    brand: "ELECOM",
    tagline: "エレコム モニターアーム DPA-SS11BK ガス式 17~49インチ対応ワイドモニター対応| 耐荷重2kg～20kg| 取り付けブラケット付属| 関節5軸",
    price: 9680,
    rating: 3.9,
    reviews: 213,
    image: "https://m.media-amazon.com/images/I/613FvouUMEL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CRYWBYY8",
    highlights: [
      { label: "対応サイズ", value: "17〜49インチ" },
      { label: "耐荷重", value: "2.0〜20.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜49インチ" },
          { label: "耐荷重", value: "2.0〜20.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-bs-999",
    category: "monitor-arm",
    name: "DPA-SS10BK",
    brand: "ELECOM",
    tagline: "エレコム DPA-SS10BK モニターアーム ブラケット式 支柱式 ガス式 ブラック17インチ~35インチ対応| 耐荷重15kg| VESA規格対応| 取り付けしやすい",
    price: 8980,
    rating: 4.2,
    reviews: 124,
    image: "https://m.media-amazon.com/images/I/51gVGQzjuyL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C7VQPLS1",
    highlights: [
      { label: "対応サイズ", value: "17〜35インチ" },
      { label: "耐荷重", value: "1.0〜15.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜35インチ" },
          { label: "耐荷重", value: "1.0〜15.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1001",
    category: "monitor-arm",
    name: "PS1S Wave Black",
    brand: "Pixio",
    tagline: "【5年保証付き】Pixio PS1S Wave Black モニターアーム シングル 黒 ブラック 大型 上下 左右 32インチ 24インチ 27インチ",
    price: 10480,
    rating: 4.3,
    reviews: 447,
    image: "https://m.media-amazon.com/images/I/51eOLYug7tL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G5QFRHR1",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-003",
    category: "monitor-arm",
    name: "Amazonベーシック モニターアーム",
    brand: "Amazonベーシック",
    tagline: "Amazonベーシック モニターアーム シングル 調整可能 デスクマウント 最大32インチ (81.3cm) (38インチ (96.5cm) ウルトラワイド) 対応 耐荷重10.0kg テンション調整可能 VESA 75 × 75/100 × 100 ブラック",
    price: 2977,
    rating: 4,
    reviews: 1330,
    image: "https://m.media-amazon.com/images/I/41w7-3HjDvL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CQXL5S4T",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-007",
    category: "monitor-arm",
    name: "PS2S",
    brand: "Pixio",
    tagline: "Pixio PS2S モニターアーム ホワイト シングル 17-49インチ対応| 耐荷重2-18kg| クランプ| グロメット",
    price: 11980,
    rating: 4.1,
    reviews: 197,
    image: "https://m.media-amazon.com/images/I/41RkHlttbTL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00CWXQRHS",
    highlights: [
      { label: "対応サイズ", value: "17〜49インチ" },
      { label: "耐荷重", value: "2.0〜18.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜49インチ" },
          { label: "耐荷重", value: "2.0〜18.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-009",
    category: "monitor-arm",
    name: "ERGOTRON エルゴトロン LX モニターアーム",
    brand: "ERGOTRON",
    tagline: "ERGOTRON エルゴトロン LX モニターアーム デュアル 2画面 縦横型 長身ポール ブラック 40インチ対応 10年保証 45-509-224耐荷重3.2-10kg/1台まで メカニカルスプリング式 クランプ式 VESA規格 人間工学的デザイン 世界中で選ばれる定番モデル",
    price: 48590,
    rating: 4.6,
    reviews: 781,
    image: "https://m.media-amazon.com/images/I/61DYEZXItoL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09T78LQYQ",
    highlights: [
      { label: "対応サイズ", value: "13〜40インチ" },
      { label: "耐荷重", value: "3.2〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜40インチ" },
          { label: "耐荷重", value: "3.2〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-013",
    category: "monitor-arm",
    name: "ErGear モニターアーム シングル",
    brand: "ErGear",
    tagline: "ErGear モニターアーム シングル 13～32インチ 耐荷重2～10kg ガススプリング式 ホワイト 白 PCディスプレイアームアーム画面位置を高さ・前後・左右へ動かし、姿勢や作業内容に合わせて調節可能 , デスク上の作業領域を広げる , 仕事、学習、ゲーミングにおすすめ , VESA 75×75・100×100mm対応 , クランプ式＆クランプ式対応",
    price: 2960,
    rating: 3.9,
    reviews: 14591,
    image: "https://m.media-amazon.com/images/I/517NFw8CLbL._AC_SL1500_.jpg",
    connection: "クランプ式/グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C3M5MTRX",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0~10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式/グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0~10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式/グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-016",
    category: "monitor-arm",
    name: "MS012",
    brand: "THEARK",
    tagline: "THEARK デュアル PC モニター アーム 2画面 液晶ディスプレイ アーム スプリング式 ノートパソコン 縦 上下 配置 液タブ ロング 組み立て簡単 モニタースタンド17～32インチ対応 最大耐荷重9kg MS012 (ブラック)",
    price: 6980,
    rating: 4,
    reviews: 40,
    image: "https://m.media-amazon.com/images/I/51vz027J8nL._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G2B1KHFZ",
    highlights: [
      { label: "対応サイズ", value: "15〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "15〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-017",
    category: "monitor-arm",
    name: "ErGear モニターアーム デュアル",
    brand: "ErGear",
    tagline: "ErGear モニターアーム デュアル 上下 2画面 縦置き 13～32インチ 耐荷重各9kg ポール式 ディスプレイアーム ガススプリング式で自由に角度調節 , デュアルモニターを用途に合わせて自由配置 ,",
    price: 4999,
    rating: 4.4,
    reviews: 1812,
    image: "https://m.media-amazon.com/images/I/61SNvxu5huL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FVSRQRZ3",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-019",
    category: "monitor-arm",
    name: "HT05B-003",
    brand: "—",
    tagline: "シングルモニタースタンド 自立型 27~43インチ モニターアーム 曲面スクリーンモニターマウント 強化ガラスベース 調節可能なモーションチルト-15°から10°回転 ±45°回転 360°耐荷重 75ポンド HT05B-003",
    price: 3399,
    rating: 4.1,
    reviews: 2116,
    image: "https://m.media-amazon.com/images/I/51PyBPIeaiL._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08YNL8Y4P",
    highlights: [
      { label: "対応サイズ", value: "27〜43インチ" },
      { label: "耐荷重", value: "34.0kg" },
      { label: "VESA", value: "—" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "27〜43インチ" },
          { label: "耐荷重", value: "34.0kg" },
          { label: "VESA", value: "—" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1048",
    category: "monitor-arm",
    name: "HNDS6",
    brand: "HUANUO",
    tagline: "HUANUO PCモニターアーム デュアル HNDS6",
    price: 8599,
    rating: 4.2,
    reviews: 3422,
    image: "https://m.media-amazon.com/images/I/61ZJLx37Z3L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07W3KK949",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1049",
    category: "monitor-arm",
    name: "HUANUO (ファーノー) モニターアーム ディスプレイアーム 17～32インチ対応 耐荷重2～9kg",
    brand: "—",
    tagline: "HUANUO (ファーノー) モニターアーム ディスプレイアーム 17～32インチ対応 耐荷重2～9kg",
    price: null,
    rating: 4.3,
    reviews: 1950,
    image: "https://m.media-amazon.com/images/I/61mdBB3yy4L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B089GPNM5V",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },{
    id: "arm-sr-105",
    category: "monitor-arm",
    name: "ACCURTEK モニターアーム",
    brand: "サンワサプライ",
    tagline: "モニターアーム ポール取り付け 13～32インチ 耐荷重8kg ブラック1画面 スチール製 2関節 角度調整可能 後付け簡単",
    price: 2899,
    rating: 4.3,
    reviews: 286,
    image: "https://m.media-amazon.com/images/I/61iwoXMLzAL._AC_SL1500_.jpg",
    connection: "ポールマウント方式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0872ND3S3",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "ポールマウント方式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "ポールマウント方式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-110",
    category: "monitor-arm",
    name: "AX05TB01",
    brand: "Amazonベーシック",
    tagline: "13〜32インチ対応・耐荷重9.0kg・ガススプリング式",
    price: 2355,
    rating: 4.1,
    reviews: 57,
    image: "https://m.media-amazon.com/images/I/61CvapJpyyL._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D66Q72WJ",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "50×50 /75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "50×50 /75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-115",
    category: "monitor-arm",
    name: "LS112",
    brand: "LOCTEK",
    tagline: "13〜32インチ対応・耐荷重2.0〜9.0kg・ガススプリング式",
    price: 16335,
    rating: 4.4,
    reviews: 202,
    image: "https://m.media-amazon.com/images/I/51i7KhGXbwL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CZQ8R1SS",
    highlights: [
      { label: "対応サイズ", value: "17〜49インチ" },
      { label: "耐荷重", value: "2.0〜20.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜49インチ" },
          { label: "耐荷重", value: "2.0〜20.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-116",
    category: "monitor-arm",
    name: "ERGOTRON エルゴトロン HX モニターアーム",
    brand: "ERGOTRON",
    tagline: "ERGOTRON エルゴトロン HX モニターアーム 黒 湾曲モニター対応 49インチまで対応 国内正規品 10年保証付 45-475-224シングル ブラック ウルトラワイド 耐荷重9.1-19kg メカニカルスプリング式 クランプ式 グロメット付属 VESA規格 人間工学的デザイン 大型ディスプレイマウント",
    price: 46970,
    rating: 4.4,
    reviews: 871,
    image: "https://m.media-amazon.com/images/I/61iV6+cuzbL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08RD4FJ3Q",
    highlights: [
      { label: "対応サイズ", value: "〜49インチ" },
      { label: "耐荷重", value: "9.1〜19kg" },
      { label: "VESA", value: "75×75 / 100×100/200×100/200×200" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜49インチ" },
          { label: "耐荷重", value: "9.1〜19kg" },
          { label: "VESA", value: "75×75 / 100×100/200×100/200×200" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1051",
    category: "monitor-arm",
    name: "MD81SE",
    brand: "suptek",
    tagline: "Suptek PCモニターアーム 液晶ディスプレイアーム MD81SE 黒ガススプリング式| 17～34インチ対応| 最大耐荷重11kg| ガス圧式",
    price: 2980,
    rating: 4,
    reviews: 1179,
    image: "https://m.media-amazon.com/images/I/51dX0aBiz7L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B096FRBS6P",
    highlights: [
      { label: "対応サイズ", value: "17〜34インチ" },
      { label: "耐荷重", value: "1～11.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜34インチ" },
          { label: "耐荷重", value: "1～11.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1052",
    category: "monitor-arm",
    name: "100-LA031",
    brand: "サンワダイレクト",
    tagline: "サンワダイレクト モニターアーム デュアルモニター対応 上下2台設置 クランプ固定 2画面 デュアルディスプレイ 100-LA031",
    price: 5480,
    rating: 4.3,
    reviews: 482,
    image: "https://m.media-amazon.com/images/I/71eHeDuL-ZL._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B01DVGUDX8",
    highlights: [
      { label: "対応サイズ", value: "—" },
      { label: "耐荷重", value: "10Kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "—" },
          { label: "耐荷重", value: "10Kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1053",
    category: "monitor-arm",
    name: "EEX-LAP07",
    brand: "イーサプライ",
    tagline: "イーサプライ モニターアーム ポール取付 4関節 32インチまで 耐荷重8kg 多関節 1画面 VESA 100 EEX-LAP07",
    price: 3280,
    rating: 4.2,
    reviews: 381,
    image: "https://m.media-amazon.com/images/I/61n3wfH5LIL._AC_SL1500_.jpg",
    connection: "ポールマウント方式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B082XBG5QP",
    highlights: [
      { label: "対応サイズ", value: "〜32インチ" },
      { label: "耐荷重", value: "8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "ポールマウント方式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜32インチ" },
          { label: "耐荷重", value: "8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "ポールマウント方式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1054",
    category: "monitor-arm",
    name: "GH-AMDX1-BK",
    brand: "GREENHOUSE",
    tagline: "グリーンハウス モニターアーム 土台組立済みで設置簡単 シングル 17-32インチ対応 耐荷重2-9kg VESA規格 メカニカル式 4軸 3年保証 GH-AMDX1-BK",
    price: 4998,
    rating: 3.8,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/61TgaScegsL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G34JT9GQ",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1055",
    category: "monitor-arm",
    name: "MD01A",
    brand: "suptek",
    tagline: "suptek PCモニターアーム MD01A ガススプリング式 13-32インチ対応耐荷重2-9kg| VESA75-100mm| グロメット式・クランプ式| アルミニウム合金製| ケーブル収納",
    price: 2449,
    rating: 4.2,
    reviews: 234,
    image: "https://m.media-amazon.com/images/I/516xhP88HPL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DCVWK5RY",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1056",
    category: "monitor-arm",
    name: "HNDS8",
    brand: "HUANUO",
    tagline: "HUANUO (ファーノー) PCモニターアーム デュアル 上下 縦2画面 液晶ディスプレイアーム 13～32インチ対応 耐荷重2～9kg ガススプリング式 スムーズにモニターを動かす 多角度調節 グロメット式＆クランプ式",
    price: 7999,
    rating: 4.3,
    reviews: 1280,
    image: "https://m.media-amazon.com/images/I/61F9MZFoE7L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B085Y6W6RS",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1057",
    category: "monitor-arm",
    name: "GH-AMDP1-BK",
    brand: "GREENHOUSE",
    tagline: "グリーンハウス モニターアーム ガス圧式 17-32インチ対応 耐荷重1-9kg 3年保証 4軸 ブラック GH-AMDP1-BK",
    price: 6998,
    rating: 4,
    reviews: 123,
    image: "https://m.media-amazon.com/images/I/61ynernQnVL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CPLJT9FX",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "1.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "1.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1058",
    category: "monitor-arm",
    name: "ErGear モニターアーム デュアル",
    brand: "BONTEC",
    tagline: "ErGear モニターアーム デュアル 2画面 13-32インチ デュアル 耐荷重8kg ポール式 2画面 PC ディスプレイアームデスクを広く使える省スペース設計 ±45°チルト 180°スイベル 360°回転 多角度調節 Cクランプ式 グロメット式",
    price: 5414,
    rating: 4.3,
    reviews: 21353,
    image: "https://m.media-amazon.com/images/I/61KgkZnwScL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B082MLVXRR",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1059",
    category: "monitor-arm",
    name: "Vexify モニターアーム",
    brand: "ErGear",
    tagline: "【Amazon.co.jp限定】モニターアーム 17～32インチ対応 耐荷重2～11kg VESA規格対応 5軸可動式 多角度調節 ガススプリング式 アルミニウム合金製 グロメット式&クランプ式 ケープル収納 日本語説明書付き 3年保証 (ブラック)",
    price: 3399,
    rating: 4.4,
    reviews: 954,
    image: "https://m.media-amazon.com/images/I/619hqhPelvL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FVSGD9GZ",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜11.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜11.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
  {
    id: "arm-sr-1060",
    category: "monitor-arm",
    name: "8関節ロングモニターアーム",
    brand: "EastForce",
    tagline: "EastForce 自由自在 8関節ロングモニターアーム ブラック シングルアーム17～32インチ, 耐荷重2～7kg, VESA規格,",
    price: 8999,
    rating: 4.4,
    reviews: 95,
    image: "https://m.media-amazon.com/images/I/31oExy8+90L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DQ4PS5GD",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
        ]},
    ],
  },
]
