import type { Gadget } from "./gadgets"

/** Amazon.co.jp Lenovo ディスプレイ検索 pg2（26インチ以上 / Lenovo）。 */
export const monitorLenovoSearch26PlusPage2: Gadget[] = [
  {
    id: "mon-lenovo-26p2-001",
    category: "monitor",
    name: "27\" QHD 2560X1440 3SIDE Near Edgeless Display",
    brand: "Lenovo",
    tagline: "Lenovo 27\" QHD 2560X1440 3SIDE Near Edgeless Display",
    price: 82809,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/516bDfLrUGL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BGQDTM53",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #49" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "9.98 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-002",
    category: "monitor",
    name: "Legion Y27q-30",
    brand: "Lenovo",
    tagline: "Lenovo Legion Y27q-30 Monitor - 2025 - Gaming Monitor - 27\" QHD IPS Display - Ov",
    price: 87869,
    rating: 3.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71DXx8djiEL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BMFPCWTG",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #50" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 53.6 × 25.9 cm" },
          { label: "重量", value: "6.62 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-003",
    category: "monitor",
    name: "ThinkVision T27i-30 27 Full HD WLED LCD - 16:9 -",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T27i-30 27 Full HD WLED LCD Monitor - 16:9 - Black",
    price: 75410,
    rating: 4.5,
    reviews: 17,
    image: "https://m.media-amazon.com/images/I/61VqhbqbjQL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BMLW5LBS",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "3\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "3\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #51" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 54.4 × 20.4 cm" },
          { label: "重量", value: "1.81 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-004",
    category: "monitor",
    name: "Legion Y27f-30 27\" FHD , 1920x1080, 0.5ms Respon",
    brand: "Lenovo",
    tagline: "Lenovo Legion Y27f-30 27\" FHD Gaming Monitor, 1920x1080, 0.5ms Response, 240Hz/2",
    price: 107707,
    rating: 4.4,
    reviews: 83,
    image: "https://m.media-amazon.com/images/I/718ea0jdzlL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C2W25LJZ",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "280Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "280Hz" },
          { label: "Amazon検索", value: "PCモニター #52" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 53.6 × 25.9 cm" },
          { label: "重量", value: "6.4 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-005",
    category: "monitor",
    name: "ThinkVision E29w-20 29\" UW-UXGA WLED LCD - 21:9",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision E29w-20 29\" UW-UXGA WLED LCD Monitor - 21:9 - Raven Black",
    price: 85086,
    rating: 4.8,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/61jyBgjeAZL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09HZ1ZDR3",
    monitorFilterTags: ["size-27","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "29\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "29\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #53" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "68.8 × 32 × 4.8 cm" },
          { label: "重量", value: "4.40 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-006",
    category: "monitor",
    name: "27インチThinkVision E27q-20、2560x1440解像度、1000:1コントラ",
    brand: "Lenovo",
    tagline: "Lenovo 27インチThinkVision E27q-20、2560x1440解像度、1000:1コントラスト比、アセットタグ付き。",
    price: 115288,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/81v9SEdiitL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G2BDW1YY",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #54" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "36.8 × 4.6 × 61.4 cm" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
    {
    id: "mon-lenovo-26p2-008",
    category: "monitor",
    name: "ThinkVision P27QD-40 27\" Class WQHD LED - 16:9 -",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P27QD-40 27\" Class WQHD LED Monitor - 16:9 - Raven Black",
    price: 97931,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61ou-zb5wOL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FM4441RH",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #56" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 35.8 × 4.6 cm" },
          { label: "重量", value: "4.60 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-009",
    category: "monitor",
    name: "Legion R27qc-30 27\" Class WQHD Curved Screen Gam",
    brand: "Lenovo",
    tagline: "Lenovo Legion R27qc-30 27\" Class WQHD Curved Screen Gaming LED Monitor - 16:9 -",
    price: 90271,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61IttMCjq0L._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DY5223M7",
    monitorFilterTags: ["size-27","res-wqhd","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "—" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "—" },
          { label: "Amazon検索", value: "PCモニター #57" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61 × 37.1 × 8.9 cm" },
          { label: "重量", value: "7.94 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-010",
    category: "monitor",
    name: "63A4ZAR1US Thinkvision T27i-30 Mntr",
    brand: "Lenovo",
    tagline: "Lenovo 63A4ZAR1US Thinkvision T27i-30 Mntr",
    price: 90938,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71sylHe3VIL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CPTD2XJD",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "10\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "10\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #58" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-011",
    category: "monitor",
    name: "C19270QT1",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T27h-20 C19270QT1 27 inch Monitor",
    price: 86189,
    rating: 5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61AoS6u6EBL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B087V5F1TV",
    monitorFilterTags: ["size-27","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #60" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 36.8 × 4.6 cm" },
          { label: "重量", value: "9.48 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-012",
    category: "monitor",
    name: "27 IPS QHD (2560X1440) ThinkVision",
    brand: "Lenovo",
    tagline: "Lenovo 27 IPS QHD (2560X1440) ThinkVision Monitor",
    price: 88393,
    rating: 4.4,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/71ZeMSKaVdL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08245GVGF",
    monitorFilterTags: ["size-238","res-wqhd","refresh-60","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "12\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "12\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #61" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 59.9 × 28.4 cm" },
          { label: "重量", value: "6.77 kg" },
        ]},

    ],
  },{
    id: "mon-lenovo-26p2-014",
    category: "monitor",
    name: "ThinkVision T27QD-40 27\" Class WQHD LED - 16:9 -",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T27QD-40 27\" Class WQHD LED Monitor - 16:9 - Eclipse Black",
    price: 114370,
    rating: 3.8,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61oJ7jaPM4L._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FLDYKLJK",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #63" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 35.8 × 4.6 cm" },
          { label: "重量", value: "4.60 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-015",
    category: "monitor",
    name: "ThinkVision T27h-30",
    brand: "Lenovo",
    tagline: "Lenovo TS/ThinkVision T27h-30 27 USB-C Monitor",
    price: 111686,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51NMp7S3pFL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B8X32QWH",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #64" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "52 × 19 × 69 cm" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-016",
    category: "monitor",
    name: "Legion R34w-30",
    brand: "Lenovo",
    tagline: "Lenovo Legion R34w-30 34\" Class UW-QHD Curved Screen Gaming LED Monitor - 21:9 -",
    price: 123012,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61cgfkXXlzL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G72L47DS",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #65" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "80.8 × 36.8 × 11.2 cm" },
          { label: "重量", value: "10.73 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-018",
    category: "monitor",
    name: "ThinkVision T27hv-30",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T27hv-30 27\" Class Webcam WQHD LED Monitor - 16:9 - Raven Bla",
    price: 123435,
    rating: 5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61pvMrDVU6L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CS6Z1QLK",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #67" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 40.4 × 5.3 cm" },
          { label: "重量", value: "5.70 kg" },
        ]},

    ],
  },
    {
    id: "mon-lenovo-26p2-020",
    category: "monitor",
    name: "ThinkVision P27H-20",
    brand: "Lenovo",
    tagline: "27\" WQHD IPS",
    price: 155960,
    rating: 4,
    reviews: 35,
    image: "https://m.media-amazon.com/images/I/51UKvWqMz1L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08JHB4XFM",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #69" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "9.62 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-021",
    category: "monitor",
    name: "Legion Pro 34WD-10",
    brand: "Lenovo",
    tagline: "Lenovo Legion Pro 34WD-10 Curved Gaming Monitor - 34\" WQHD OLED - 240Hz - AMD Fr",
    price: 173380,
    rating: 4.1,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/717sL9e4NRL._AC_SL1500_.jpg",
    connection: "HDMI 2.1 / DisplayPort 1.4 / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DZFJ27LQ",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "OLED" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "OLED" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #70" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
          { label: "USB Type-C", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "79 × 57.8 × 26.3 cm" },
          { label: "重量", value: "8.71 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-022",
    category: "monitor",
    name: "ThinkVision P32p-20 62A2GAR2US 31.5\" 4K UHD 2160",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P32p-20 62A2GAR2US 31.5\" 4K UHD 2160p LED Monitor Black",
    price: 132935,
    rating: 3.9,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/61cwjAlw0ML._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08JV2W5PD",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #71" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 42.7 × 5.1 cm" },
          { label: "重量", value: "6.96 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-023",
    category: "monitor",
    name: "ThinkVision T32p-30",
    brand: "Lenovo",
    tagline: "31.5\" 4K IPS",
    price: 135525,
    rating: 3,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/614J48spZtL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CN34NMJB",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #72" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "59.9 × 23.5 × 71.4 cm" },
          { label: "重量", value: "9.48 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-024",
    category: "monitor",
    name: "ThinkVision P34WD-40 34\" Class UWQHD Curved Scre",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P34WD-40 34\" Class UWQHD Curved Screen LED Monitor - 21:9 - E",
    price: 176950,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71ICyTDM3qL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCM4B3WZ",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #73" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "81.8 × 35.8 × 8.1 cm" },
          { label: "重量", value: "7.20 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-025",
    category: "monitor",
    name: "Y27g 27-Inch FHD LED-Lit 16:9 Curved Widescreen",
    brand: "Lenovo",
    tagline: "Lenovo Y27g 27-Inch FHD LED-Lit 16:9 Curved Widescreen Gaming Monitor with G-Syn",
    price: 211348,
    rating: 3.5,
    reviews: 18,
    image: "https://m.media-amazon.com/images/I/61+3xGDSweL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B01FXDVZF2",
    monitorFilterTags: ["size-27","res-fhd","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "—" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "—" },
          { label: "Amazon検索", value: "PCモニター #74" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "その他", rows: [
          { label: "重量", value: "6.74 kg" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "6.74 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-026",
    category: "monitor",
    name: "ThinkVision P27u-20 with Asset Tag, 27\" UHD (384",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P27u-20 with Asset Tag, 27\" UHD (3840x2160) IPS Display, Anti",
    price: 182318,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/514o0VDpkeL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FF9P328S",
    monitorFilterTags: ["size-27","res-4k","refresh-60","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #75" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },{
    id: "mon-lenovo-26p2-028",
    category: "monitor",
    name: "ThinkVision T34WD-40 (34インチ) WQHD HDMI/DP/USB-C/",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T34WD-40 (34インチ) WQHD HDMI/DP/USB-C/DOC。",
    price: 257715,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71b24jd8zkL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FGZWMW43",
    monitorFilterTags: ["size-315-plus","res-wqhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #77" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49 × 19 × 97 cm" },
          { label: "重量", value: "13.02 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-030",
    category: "monitor",
    name: "ThinkVision P32p-30 アセットタグ付き、31.5インチ UHD (3840x2",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P32p-30 アセットタグ付き、31.5インチ UHD (3840x2160) IPS ディスプレイ、アンチグレア16:",
    price: 350792,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51G3Wm26bFL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FF9PQGZK",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #79" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-031",
    category: "monitor",
    name: "ThinkVision P40w-20 40\" 5K2K WUHD Curved Screen",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P40w-20 40\" 5K2K WUHD Curved Screen WLED LCD Monitor - 21:9 -",
    price: 327078,
    rating: 4.2,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/61eI6U4llvL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B468HQFD",
    monitorFilterTags: ["size-315-plus","res-5k2k","refresh-60","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "40\"" },
      { label: "解像度", value: "5K2K (5120×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "40\"" },
          { label: "解像度", value: "5K2K (5120×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #80" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "94.7 × 64.1 × 27.9 cm" },
          { label: "重量", value: "20.41 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-032",
    category: "monitor",
    name: "ThinkVision P32pz-30",
    brand: "—",
    tagline: "ThinkVision P32pz-30",
    price: 355310,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61EABOj9ncL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D73ZWVJ7",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "32\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "32\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #81" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "14.6 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-033",
    category: "monitor",
    name: "ThinkVision T34w 30 34\" 4K UHD 2160p",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T34w 30 34\" 4K UHD 2160p Monitor",
    price: 331000,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/51GBTYL2xRL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C3B1RSM6",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #82" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "15 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-034",
    category: "monitor",
    name: "ThinkVision P34WD-40",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P34WD-40",
    price: 404316,
    rating: 4.1,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71Ax+bIw00L._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FJSBBMZ7",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #83" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "81.7 × 35.9 × 8.2 cm" },
          { label: "重量", value: "10 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-035",
    category: "monitor",
    name: "ThinkVision P32p-30 アセットタグ付き、31.5インチ UHD (3840x2",
    brand: "Lenovo",
    tagline: "LENOVO ThinkVision P32p-30",
    price: 266330,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/51g6vIxLelL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C3B19F3D",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "35\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "35\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #84" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "53 × 15 × 94 cm" },
          { label: "重量", value: "10 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-036",
    category: "monitor",
    name: "ThinkVision E27q-20 27\" WQHD WLED LCD - 16:9 - R",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision E27q-20 27\" WQHD WLED LCD Monitor - 16:9 - Raven Black, 14.5\"",
    price: 97535,
    rating: 4.3,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/71SIPH6EjvL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09M2L8T5H",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #85" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 36.8 × 4.6 cm" },
          { label: "重量", value: "4.49 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-037",
    category: "monitor",
    name: "ThinkVision T32UD-40 32\" Class 4K UHD LED - 16:9",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T32UD-40 32\" Class 4K UHD LED Monitor - 16:9 - Eclipse Black",
    price: 14980,
    rating: 3.8,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/71hhtzGuh5L._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCNC4W9M",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "32\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "32\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #86" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 41.4 × 4.6 cm" },
          { label: "重量", value: "6.30 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-038",
    category: "monitor",
    name: "63D1RAR1US 31.5\" Thinkvision P32p-30 4k Mntr 95",
    brand: "Lenovo",
    tagline: "Lenovo 63D1RAR1US 31.5\" Thinkvision P32p-30 4k Mntr 95 Dci-p399 RGB W/Accurate C",
    price: 80166,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/517ZnJOvtOL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C7CZYLWQ",
    monitorFilterTags: ["size-315-plus","res-4k","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "—" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "—" },
          { label: "Amazon検索", value: "PCモニター #87" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 42.2 × 5.8 cm" },
          { label: "重量", value: "9.48 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26p2-041",
    category: "monitor",
    name: "ThinkVision P27h-30 27\" Class WQHD LED - 16:9 -",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P27h-30 27\" Class WQHD LED Monitor - 16:9 - Raven Black",
    price: 22016,
    rating: 4.3,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/51TqQcrJZLL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGNRK1TX",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #90" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 35.3 × 4.8 cm" },
          { label: "重量", value: "10.16 kg" },
        ]},

    ],
  },
]
