import type { Gadget } from "./gadgets"

/** Amazon.co.jp コンピュータモニターアーム 新着2ページ目（10351517051 pg=2）。本体のみ。 */
export const monitorArmNewReleasesPage2: Gadget[] = [
  {
    id: "arm-nr2-51",
    category: "monitor-arm",
    name: "ACCURTEK 高耐荷重2画面モニターアーム",
    brand: "ACCURTEK",
    tagline: "ACCURTEK 高耐荷重2画面モニターアーム 17-35インチ対応 耐荷重各16kg デュアル ディスプレイ アーム ガススプリング式 多角度調節 クランプ式・グロメット式 省スペース VESA",
    price: 6399,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/616JMHQoeqL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWHT3DBL",
    highlights: [
      { label: "対応サイズ", value: "17〜35インチ" },
      { label: "耐荷重", value: "2.0〜16.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜35インチ" },
          { label: "耐荷重", value: "2.0〜16.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #51" },
        ]},
    ],
  },
  {
    id: "arm-nr2-52",
    category: "monitor-arm",
    name: "monTEK モニターアーム",
    brand: "monTEK",
    tagline: "monTEK モニターアーム 13～32インチ対応 耐荷重2～9kg PCモニターアーム ロングポール 上下 左右 多角度調節",
    price: 3599,
    rating: 4,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/61FkMl1zdHL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GL7QG2WK",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #52" },
        ]},
    ],
  },
  {
    id: "arm-nr2-53",
    category: "monitor-arm",
    name: "ETHU PCモニターアーム",
    brand: "ETHU",
    tagline: "ETHU PCモニターアーム ディスプレイスタンド 人間工学デスクマウント フルモーション可動 Cクランプ/グロメット両対応 ブラック17-32インチ対応 耐荷重2-10kg VESA規格 ガススプリング式 ケーブル管理 組み立て簡単",
    price: 2990,
    rating: 4.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/61xJ62eaGQL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2YSWK5W",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #53" },
        ]},
    ],
  },
  {
    id: "arm-nr2-56",
    category: "monitor-arm",
    name: "AS-MABE01",
    brand: "Archiss",
    tagline: "アーキス(Archiss) モニターアーム 液晶ディスプレイアーム ガススプリング式 32インチ対応 耐荷重2-8kg クランプ/グロメット固定 AS-MABE01",
    price: 3580,
    rating: 3.6,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/514J23s34aL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWZYZB5G",
    highlights: [
      { label: "対応サイズ", value: "〜32インチ" },
      { label: "耐荷重", value: "2.0〜8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜32インチ" },
          { label: "耐荷重", value: "2.0〜8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #56" },
        ]},
    ],
  },
  {
    id: "arm-nr2-57",
    category: "monitor-arm",
    name: "AS-MABE01",
    brand: "Archiss",
    tagline: "アーキス(Archiss) モニターアーム 液晶ディスプレイアーム ガススプリング式 32インチ対応 耐荷重2-8kg クランプ/グロメット固定 AS-MABE01",
    price: 3580,
    rating: 4.7,
    reviews: 25,
    image: "https://m.media-amazon.com/images/I/61OUUlFL13L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZVMHSHM",
    highlights: [
      { label: "対応サイズ", value: "〜32インチ" },
      { label: "耐荷重", value: "2.0〜8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜32インチ" },
          { label: "耐荷重", value: "2.0〜8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #57" },
        ]},
    ],
  },
  {
    id: "arm-nr2-58",
    category: "monitor-arm",
    name: "EEX-LAFS01BK",
    brand: "ACCURTEK",
    tagline: "イーサプライ モニターアーム 32インチ 耐荷重9kg 1画面 クランプ グロメット 高さ角度調整 壁寄せ EEX-LAFS01BK",
    price: 3180,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71LhcZkGMlL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2RZ2TWV",
    highlights: [
      { label: "対応サイズ", value: "〜32インチ" },
      { label: "耐荷重", value: "9Kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜32インチ" },
          { label: "耐荷重", value: "9Kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #58" },
        ]},
    ],
  },{
    id: "arm-nr2-60",
    category: "monitor-arm",
    name: "Hemudu PCモニターアーム 壁掛け",
    brand: "Hemudu",
    tagline: "Hemudu PCモニターアーム 壁掛け 耐荷重約2～10kg対応 ディスプレイアーム VESA75x75mm/100x100mm 17～32 インチモニターに適応 壁掛けモニターアーム",
    price: 3799,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/619uaC5cJdL._AC_SL1500_.jpg",
    connection: "テーブルトップマウント",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2D1G1KX",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "テーブルトップマウント" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "テーブルトップマウント" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #60" },
        ]},
    ],
  },
  {
    id: "arm-nr2-65",
    category: "monitor-arm",
    name: "Bｏｏｋwａrmデュアルモニターアーム",
    brand: "WORLDLIFT",
    tagline: "デュアルモニターアーム 2画面 13～27インチ 各2～9kg 合計18kg VESA75/100 クランプ・グロメット式 高さ角度調整 ブラック",
    price: 4180,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51UZHpksYxL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HBJBV6Q6",
    highlights: [
      { label: "対応サイズ", value: "13〜27インチ" },
      { label: "耐荷重", value: "8.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜27インチ" },
          { label: "耐荷重", value: "8.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #65" },
        ]},
    ],
  },
  {
    id: "arm-nr2-66",
    category: "monitor-arm",
    name: "WORLDLIFT PCモニターアーム デュアル",
    brand: "WORLDLIFT",
    tagline: "WORLDLIFT PCモニターアーム デュアル 17~49インチ対応各耐荷重16kg ポール式 ガススプリアーム 液晶ディスプレイアーム 2画面 クランプ式＆グロメット式 高さ調節 VESA75/100mm",
    price: 9980,
    rating: 4,
    reviews: 65,
    image: "https://m.media-amazon.com/images/I/6116V7gxwKL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYP6FS7N",
    highlights: [
      { label: "対応サイズ", value: "17〜49インチ" },
      { label: "耐荷重", value: "16.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜49インチ" },
          { label: "耐荷重", value: "16.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #66" },
        ]},
    ],
  },
  {
    id: "arm-nr2-70",
    category: "monitor-arm",
    name: "デュアルモニターアーム",
    brand: "Rfiver",
    tagline: "13〜34インチ対応・耐荷重2.0〜10.0kg・ガススプリング式",
    price: 8999,
    rating: 3.9,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/61ceDrbwotL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWMM8F4H",
    highlights: [
      { label: "対応サイズ", value: "13〜34インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜34インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #70" },
        ]},
    ],
  },
  {
    id: "arm-nr2-71",
    category: "monitor-arm",
    name: "デュアルモニターアーム",
    brand: "Rfiver",
    tagline: "13〜34インチ対応・耐荷重2.0〜10.0kg・ガススプリング式",
    price: 8999,
    rating: 4.5,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/61zuGABC0BL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H151CBG2",
    highlights: [
      { label: "対応サイズ", value: "13〜34インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜34インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #71" },
        ]},
    ],
  },
  {
    id: "arm-nr2-72",
    category: "monitor-arm",
    name: "ポール式シングルモニターアーム",
    brand: "PEGZONE",
    tagline: "PEGZONE モニターアーム ポール式 シングル 17-49インチ 耐荷重2-20kg クイック着脱VESA ガススプリング クランプ式 ホワイトディスプレイアーム モニタースタンド pc ディスプレイスタンド 縦並び グロメット 高さ調整 多角度調節 ケーブル収納",
    price: 9990,
    rating: 4.3,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/61jYJ0JRUAL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXVDDFN3",
    highlights: [
      { label: "対応サイズ", value: "17〜49インチ" },
      { label: "耐荷重", value: "2.0〜20.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜49インチ" },
          { label: "耐荷重", value: "2.0〜20.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #72" },
        ]},
    ],
  },
  {
    id: "arm-nr2-77",
    category: "monitor-arm",
    name: "Mkastry　PCモニターアーム シングル",
    brand: "—",
    tagline: "PCモニターアーム17～32インチ対応 耐荷重：2～9kg対応アルミニウム合金製 ガススプリング式 VESA 75x75mm 100x100mm対応 グロメット式&クランプ式 多角度調節 ケープル収納",
    price: 6999,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/51h-Wb5f4hL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H74Z2P2F",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #77" },
        ]},
    ],
  },
  {
    id: "arm-nr2-78",
    category: "monitor-arm",
    name: "MDX003DB",
    brand: "Bracwiser",
    tagline: "13〜32インチ対応・耐荷重10.0kg",
    price: null,
    rating: 4,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/217-tnwY+YL._AC_SL1500_.jpg",
    connection: "ポールマウント方式",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZD3DX6M",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "ポールマウント方式" },
    ],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100 mm" },
          { label: "アーム数", value: "シングル (1画面)" },
        ]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "ポールマウント方式" },
          { label: "駆動方式", value: "—" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム pg2 #78" },
        ]},
    ],
  }]
