import type { Gadget } from "./gadgets"

/** Amazon.co.jp PHILIPS モニター検索（2151982051 / PHILIPS）。 */
export const monitorPhilipsSearch: Gadget[] = [{
    id: "mon-philips-003",
    category: "monitor",
    name: "PHILIPS EVNIA　27M2N3500NL/11",
    brand: "PHILIPS",
    tagline: "HILIPS EVNIA ゲーミングモニター (27インチ/180Hz/WQHD/VA/超高速0.5ms/HDR10/AMD FreeSync対応/5年保証/2560x1440/チルト/HDMI2.0×2、DisplayPort1.4×1/フレームレス/フリッカーフリー/ブルーライト軽減/電源内蔵)",
    price: 20707,
    rating: 4.4,
    reviews: 280,
    image: "https://m.media-amazon.com/images/I/616DrmKM9xL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DCNN7G7V",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #3" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.34 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 46.3 × 19.6 cm" },
          { label: "重量", value: "4.34 kg" }]}],
  },
  {
    id: "mon-philips-004",
    category: "monitor",
    name: "PHILIPS 27E1N5500B/11",
    brand: "PHILIPS",
    tagline: "27インチ/5年保証/WQHD/IPS/HDMI,Display Port/高さ調整/チルト/ピボット/フレームレス/Adaptive Sync/ちらつき防止/ブルーライト軽減/sRGB121.46%",
    price: 24400,
    rating: 4.4,
    reviews: 54,
    image: "https://m.media-amazon.com/images/I/81sCQZxfyEL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F1QY415D",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #4" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "5.59 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 51 × 21.2 cm" },
          { label: "重量", value: "5.59 kg" }]}],
  },
    {
    id: "mon-philips-006",
    category: "monitor",
    name: "PHILIPS 27インチモニター 27E1N1800A/11",
    brand: "PHILIPS",
    tagline: "27インチ/3840x2160 4K/IPS/スピーカー2W x2/チルト/HDMI2.0 x2,DisplayPort1.4 x1/フレームレス/HDR 10/Adaptive Sync/Delta E:<2/ちらつき防止/ブルーライト軽減",
    price: 26980,
    rating: 3.8,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/61F0Ar51u+L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D93LGMHR",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #6" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.35 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 46.5 × 21.1 cm" },
          { label: "重量", value: "4.35 kg" }]}],
  },
  {
    id: "mon-philips-007",
    category: "monitor",
    name: "PHILIPS 34B2U3600C/11",
    brand: "PHILIPS",
    tagline: "湾曲TypeCディスプレイ ウルトラワイルド PCモニター (34インチ/VA/曲面1500R/UWQHD/120Hz/1ms/5年保証/HDMI, DP, Type-C(PD90W)/チルト/高さ調節/ＲJ45/電源内蔵/ケーブル付/エナジースター/TCO10)",
    price: 54930,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/717IyOgxReL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G91LKMV9",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-va"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #7" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "10.4 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "80.7 × 60.2 × 28.7 cm" },
          { label: "重量", value: "10.4 kg" }]}],
  },
  {
    id: "mon-philips-008",
    category: "monitor",
    name: "PHILIPS モニターディスプレイ 271V8L/11",
    brand: "PHILIPS",
    tagline: "(27インチ/FHD/5年保証/HDMI 1.4x1, D-Sub(VGA)x1/チルト/フレームレス/ブルーライトカット)",
    price: 13675,
    rating: 3.9,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/51sYG26NTOL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTT3M22X",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-75","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #8" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 45.6 × 23.1 cm" },
          { label: "重量", value: "3.26Kg" }]}],
  },
  {
    id: "mon-philips-009",
    category: "monitor",
    name: "PHILIPS 221S9A/11",
    brand: "PHILIPS",
    tagline: "1920×1080 フルHD ブラック 221S9A/11 5年間フル保証ディスプレイ",
    price: 9900,
    rating: 4.3,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/41L9OSgfB3L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CPC17DZ9",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #9" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "2.0Kg" }]}],
  },
  {
    id: "mon-philips-010",
    category: "monitor",
    name: "Philips　243B9/11",
    brand: "PHILIPS",
    tagline: "Philips(フィリップス) 23.8型ワイド 液晶ディスプレイ",
    price: 16980,
    rating: 4.5,
    reviews: 43,
    image: "https://m.media-amazon.com/images/I/71wK2Dw9+rS._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B094FMX5YB",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #10" }]},
      { title: "接続端子", rows: [
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 52.2 × 21.6 cm" },
          { label: "重量", value: "3.42Kg" }]}],
  },
  {
    id: "mon-philips-011",
    category: "monitor",
    name: "PHILIPS ウルトラワイドディスプレイ(44.5インチ　45B1U6900CH/11",
    brand: "PHILIPS",
    tagline: "(32:9)曲面, VA, 5120×1440@75Hz, 4ms, HDMI2.0 x2, DP1.4x1, USBハブ(DP Alt mode, PD100W), USBポートx4, Webcamカメラ/マイク, 昇降/縦横回転, KVM スイッチ, DisplayHDR 400, リモコン付き)",
    price: 126645,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/51qcHccxHIL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CNQ2743P",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-dqhd","refresh-75","port-hdmi","port-dp","port-usb-c","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "44.5\"" },
      { label: "解像度", value: "5K DQHD (5120×1440)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "44.5\"" },
          { label: "解像度", value: "5K DQHD (5120×1440)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #11" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "9.7Kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "108.5 × 51.5 × 23.8 cm" },
          { label: "重量", value: "9.7Kg" }]}],
  },
  {
    id: "mon-philips-012",
    category: "monitor",
    name: "Philips(フィリップス) 27インチ ゲーミングモニター27E2G5600W/11",
    brand: "PHILIPS",
    tagline: "QHD(2560x1440) 144Hz 0.5ms IPSパネル USB Type-C(65W給電) 高さ調整 エルゴノミクス 5年保証",
    price: 26557,
    rating: 4,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/610pDu0OZaL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVY6JKYJ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #12" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "5.42Kg" }]}],
  },
  {
    id: "mon-philips-013",
    category: "monitor",
    name: "PHILIPS 241S9A/11",
    brand: "PHILIPS",
    tagline: "5年間フル保証ディスプレイ 241S9A/11 [液晶ディスプレイ 23.8型/1920×1080/ブラック]",
    price: 11960,
    rating: 4.5,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/41m7OZLN+rL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CPBZMBKT",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #13" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "2.00Kg" }]}],
  },
  {
    id: "mon-philips-017",
    category: "monitor",
    name: "PHILIPS 346B1C/11",
    brand: "PHILIPS",
    tagline: "5年間フル保証ディスプレイ 346B1C/11 [液晶ディスプレイ 34型/3440×1440/ブラック]",
    price: 49800,
    rating: 3.2,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/717n9f7U5lL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BTT3D43V",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #17" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "8.21Kg" }]}],
  },
  {
    id: "mon-philips-018",
    category: "monitor",
    name: "PHILIPS 272S1AE/11",
    brand: "PHILIPS",
    tagline: "5年間フル保証ディスプレイ 272S1AE/11 [液晶ディスプレイ 27型/1920×1080/ブラック]",
    price: 16980,
    rating: 2.9,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71izkhFxpBL._AC_SL1500_.jpg",
    connection: "VGA / DisplayPort / HDMI / DVI-D",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B7N2ML9L",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-75","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #18" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "4.8Kg" }]}],
  },
  {
    id: "mon-philips-019",
    category: "monitor",
    name: "PHILIPS 32E1N1800LA/11",
    brand: "PHILIPS",
    tagline: "31.5インチ/VA/4K UHD/60Hz/4ms/5年保証/HDMI, DP端子/チルト/HDR10/ブルーライト軽減/在宅ワーク向け/SDGs対応/ケーブル付/電源内蔵",
    price: 35475,
    rating: 4.4,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61W0lMfphCL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FH22XCQL",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #19" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "7.39 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 51.2 × 26.1 cm" },
          { label: "重量", value: "7.39 kg" }]}],
  },
  {
    id: "mon-philips-020",
    category: "monitor",
    name: "PHILIPS 32B1U3900/11",
    brand: "PHILIPS",
    tagline: "PHILIPS 4K液晶Type-Cディスプレイ PCモニター (31.5インチ/IPS/4K UHD/5年保証/HDMI, DP, Type-C(PD90W)/チルト/ＲJ45/AdaptiveSync/電源内蔵/ケーブル付/チルト/高さ調整/スイーベル/ピボット/PIP/PBP/sRGB122.44%",
    price: 53334,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/81PkqMs2wUL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTY2H5TK",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #20" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "11.47 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "63.1 × 71.4 × 28 cm" },
          { label: "重量", value: "11.47 kg" }]}],
  },
  {
    id: "mon-philips-021",
    category: "monitor",
    name: "PHILIPSポータブルディスプレイ 16B1P3320/11",
    brand: "PHILIPS",
    tagline: "15.6インチ/IPS/FHD/5年保証/microHDMI, USB Type-Cx2 /チルト(角度調整)/マルチアングルスタンド/保護カバー付き/HDR10/PS5/PCなど対応/リモートワーク)",
    price: 16980,
    rating: 4.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71-R1VTUFFL._AC_SL1500_.jpg",
    connection: "USB Type-C / Micro HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FC2JWSMN",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS　非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #21" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "Micro HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "1.03 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "35.9 × 23.2 × 12 cm" },
          { label: "重量", value: "1.03 kg" }]}],
  },
  {
    id: "mon-philips-024",
    category: "monitor",
    name: "PHILIPS４K液晶 27B1U3900/11",
    brand: "PHILIPS",
    tagline: "27インチ/IPS/4K UHD/5年保証/HDMI, DP, Type-C(PD90W)/チルト/ＲJ45/AdaptiveSync/電源内蔵/ケーブル付/チルト/高さ調整130mm/ピボット/PIP/PBP/sRGB116.29%",
    price: 42222,
    rating: 1,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/81ktOEV6TSL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTXXZF6W",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #24" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "6.65 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "52.4 × 61.3 × 20.5 cm" },
          { label: "重量", value: "6.65 kg" }]}],
  }]
