import type { Gadget } from "./gadgets"

/** Amazon.co.jp PCモニター売れ筋ランキング（2151982051）2ページ目 #51–#100。 */
export const monitorBestsellersPage2: Gadget[] = [
  {    id: "mon-bs2-046",
    category: "monitor",
    name: "EX2710S",
    brand: "BenQ",
    tagline: "ベンキュージャパン BenQ MOBIUZ EX2710S ゲーミングモニター (27インチ/165Hz/IPS/フルHD/1ms/HDRi treVoloスピーカー/FreeSync Premium",
    price: 29800,
    rating: 4.5,
    reviews: 2215,
    image: "https://m.media-amazon.com/images/I/610W3pMpT6L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B099545PH8",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #96" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 54 × 21.7 cm" },
          { label: "重量", value: "8.4Kg" },
        ]},

    ],
  },
  {
    id: "mon-bs2-047",
    category: "monitor",
    name: "EV2795-BK",
    brand: "EIZO",
    tagline: "EIZO オフィス移転改装・デイジーチェーン対応モニター | FlexScan EV2795-BK | 27型・USB Type-C・ブラック",
    price: 88000,
    rating: 4.4,
    reviews: 147,
    image: "https://m.media-amazon.com/images/I/71moQCMSS6L._AC_SL1500_.jpg",
    connection: "USB Type-C 対応 / LAN / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08CMRR74S",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #97" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C (70W PD)", value: "映像/給電対応" },
          { label: "LAN", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "61.1 × 54.5 × 23 cm" },
          { label: "重量", value: "5 kg" },
        ]},

    ],
  },
  {
    id: "mon-bs2-048",
    category: "monitor",
    name: "M24f",
    brand: "HP",
    tagline: "New_HP 24インチ FHD 1080p IPS LED アンチグレアモニター、AMD FreeSync、70Hz、300 nits、HDMI & VGAポート、チルト(m24f)",
    price: 15800,
    rating: 4.5,
    reviews: 228,
    image: "https://m.media-amazon.com/images/I/71nJms0JbkL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B097SLKH5G",
    vesaStandard: "非対応",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-none","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "70Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "70Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #98" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "53.6 × 17.7 × 39.7 cm" },
          { label: "重量", value: "3.20 kg" },
        ]},

    ],
  },
  {
    id: "mon-bs2-049",
    category: "monitor",
    name: "Amazon Basics 27 Inch Monito",
    brand: "Amazon Basics",
    tagline: "Amazon Basics 27 Inch Monitor, FHD 1080P, Max 100Hz, VESA Compatible, Built-in",
    price: 13980,
    rating: 4.2,
    reviews: 132,
    image: "https://m.media-amazon.com/images/I/710q+sSccwL._AC_SL1500_.jpg",
    connection: "HDMI / VGA / Display port対応 / USB-A対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CP928BL3",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #99" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "4.1 kg" },
        ]},

    ],
  },
  {
    id: "mon-bs2-050",
    category: "monitor",
    name: "MFG25X1",
    brand: "Minifire",
    tagline: "Minifire ゲーミングモニター24.5インチ/300Hz/240Hz/フルHD/非光沢 Fast IPSパネル/OD 1ms/Adaptive Sync/5年保証/チルト/HDMI2.0×2、DP1.4×2/DC1-P390%/120%sRGB広色域/1920x1080/フリッカーフリー/ブルーライト軽減/スピーカー内蔵/射撃補助/角度調整) DPケーブル付き",
    price: 17999,
    rating: 4.1,
    reviews: 57,
    image: "https://m.media-amazon.com/images/I/71FHUOYLtmL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DY15G5W8",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-75","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "300Hz" },
      { label: "パネル", value: "Fast IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "300Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #100" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 41.9 × 19.1 cm" },
          { label: "重量", value: "2.8 kg" },
        ]},

    ],
  },
]
