import type { Gadget } from "./gadgets"

/** Amazon.co.jp ディスプレイ人気ギフト（2151982051 pg=1）#1–#30。 */
export const monitorMostGifted: Gadget[] = [{
    id: "mon-gift-002",
    category: "monitor",
    name: "FeuVision モニター 24インチ",
    brand: "FeuVision",
    tagline: "FeuVision モニター 24インチ 120Hz フルHD 1080p IPS ディスプレイ Adaptive Sync 対応 VESA 3辺超狭額&超薄型, pc モニター, 非光沢 ブルーライト軽減, 角度調節, sRGB 99%, HDMI&VGAポート",
    price: 10980,
    rating: 3.9,
    reviews: 134,
    image: "https://m.media-amazon.com/images/I/71XaJxUDaJL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DRC23SSG",
    monitorFilterTags: ["size-24","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazonギフト", value: "PCモニター #2" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "42.3 × 17.4 × 54.2 cm" },
          { label: "重量", value: "3.56Kg" }]}],
  },
  {
    id: "mon-gift-003",
    category: "monitor",
    name: "PX248Wave",
    brand: "Pixio",
    tagline: "Pixio ゲーミングモニター PX248Wave ホワイト 24インチ 200hz FHD Fast IPS ゲーミング モニター 白 ピクシオ ディスプレイ サブモニター pcモニター ゲームモニター monitor gaming 23.8インチ スピーカー内蔵",
    price: 26980,
    rating: 4.3,
    reviews: 1214,
    image: "https://m.media-amazon.com/images/I/71f4BinbCqL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B00CWXR15K",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-75","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "75×75 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazonギフト", value: "PCモニター #3" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 42.5 × 18 cm" },
          { label: "重量", value: "3.0Kg" }]}],
  },
  {
    id: "mon-gift-004",
    category: "monitor",
    name: "アイリスオーヤマ モニター 21インチDT-IF215S-B",
    brand: "—",
    tagline: "Full HD(1920×1080) 国内サポート VAパネル スピーカー内蔵 100Hz フリッカー軽減 非光沢タイプ ディスプレイ HDMI ブラック",
    price: 11980,
    rating: 4,
    reviews: 444,
    image: "https://m.media-amazon.com/images/I/61LPoQ97aML._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DX1BJ2R8",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-75","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "75×75 mm",
    highlights: [
      { label: "画面サイズ", value: "21\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazonギフト", value: "PCモニター #4" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.2 × 38 × 17 cm" },
          { label: "重量", value: "2.2 kg" }]}],
  },
    {
    id: "mon-gift-007",
    category: "monitor",
    name: "DKS-4K43DG6",
    brand: "DMM.make",
    tagline: "(DMM.make) DMM.make 大型ディスプレイ モニター 43インチ 4K/HDR/HDMI・USB",
    price: 40000,
    rating: 3.3,
    reviews: 61,
    image: "https://m.media-amazon.com/images/I/61o8uImv-hL._AC_SL1500_.jpg",
    connection: "HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CH2DHDJH",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","vesa-200-plus","panel-va"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "200×200mm",
    highlights: [
      { label: "画面サイズ", value: "43\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "43\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazonギフト", value: "PCモニター #7" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "USB", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "96.2 × 60.6 × 19.7 cm" },
          { label: "重量", value: "6.3 kg" }]}],
  },
  {
    id: "mon-gift-008",
    category: "monitor",
    name: "15.6型 デュアルモバイルモニター",
    brand: "UPERFECT",
    tagline: "15.6インチ 2画面 FHD・折り畳み・ドライバー不要",
    price: 27528,
    rating: 4.2,
    reviews: 3614,
    image: "https://m.media-amazon.com/images/I/71VF90actIL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DK1F8RGD",
    monitorFilterTags: ["port-hdmi","port-usb-c","size-238","refresh-60","res-fhd","vesa-75","panel-ips"],
    vesaStandard: "75×75 mm",
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6 インチ" },
          { label: "解像度", value: "1920 x 1080 (FHD)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazonギフト", value: "PCモニター #8" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.1 × 28.5 × 0.9 cm" },
          { label: "重量", value: "1.5 kg" }]}],
  },
  {
    id: "mon-gift-009",
    category: "monitor",
    name: "EX-D242SA-F",
    brand: "IODATA",
    tagline: "23.8インチ FHD 100Hz IPS・縦横回転・スピーカー付",
    price: 17980,
    rating: 4.1,
    reviews: 58,
    image: "https://m.media-amazon.com/images/I/71g4i9e77CL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F32NVN1T",
    monitorFilterTags: ["size-238","port-hdmi","port-dp","refresh-100","res-fhd","vesa-100","panel-ips"],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8 インチ" },
          { label: "解像度", value: "1920 x 1080 (FHD)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazonギフト", value: "PCモニター #9" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 44.3 × 22.7 cm" },
          { label: "重量", value: "—" }]}],
  },
    {
    id: "mon-gift-011",
    category: "monitor",
    name: "EX-U431DX",
    brand: "IODATA",
    tagline: "IODATA モニター 43インチ 4K サイネージ フレームレス 18時間連続稼働 HDMI EX-U431DX ADSパネル,スピーカー付,リモコン付",
    price: 48800,
    rating: 3.9,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/81PrJfS+NBL._AC_SL1500_.jpg",
    connection: "HDMI / RS-232C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DGXLLLQJ",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","vesa-200-plus","panel-ads"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "200×100",
    highlights: [
      { label: "画面サイズ", value: "43\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "ADS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "43\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "ADS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazonギフト", value: "PCモニター #11" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "96 × 59 × 26 cm" },
          { label: "重量", value: "7.3Kg" }]}],
  },
    {
    id: "mon-gift-013",
    category: "monitor",
    name: "Pixio ゲーミングモニター PX24QPro",
    brand: "KTC",
    tagline: "Pixio ゲーミングモニター PX24QPro ブラック 24インチ 180hz WQHD 多機能スタンドFast IPS モニター 黒 ピクシオゲーミング ディスプレイ サブモニター pcモニター ゲームモニター monitor gaming 23.8インチ スピーカー内蔵",
    price: 16980,
    rating: 4.4,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/71NWPC1Do3L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F99BZ76P",
    monitorFilterTags: ["size-238","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazonギフト", value: "PCモニター #13" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 48.9 × 27.1 cm" },
          { label: "重量", value: "4.4 kg" }]}],
  },
    {
    id: "mon-cocopar-s-238hw",
    category: "monitor",
    name: "cocopar S-238HW",
    brand: "cocopar",
    tagline: "cocopar モニター 23.8インチ 240Hz ホワイト 3年保証 HDMI*2つ ゲーミングモニター 100%sRGB広色域 400nit高輝度 1ms応答 VESA対応 狭額縁 薄型 FHD 非光沢IPSパネル 角度調整 FreeSync/HDR/OD/MPRT/チルト/スピーカー 240Hz/200Hz/180Hz/120Hz/100Hz/60Hz対応",
    price: 19999,
    rating: 4.4,
    reviews: 2681,
    image: "https://m.media-amazon.com/images/I/71SJ+kK3U3L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GC67N6Z5",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "75×75 mm",
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazonギフト", value: "PCモニター #16" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "40 × 30 × 5 cm" },
          { label: "重量", value: "4.08Kg" }]}],
  },
    {
    id: "mon-gift-020",
    category: "monitor",
    name: "EX-YC162H",
    brand: "IODATA",
    tagline: "IODATA モバイルモニター 15.6インチ FHD 持ち運び（HDMI/USB-C",
    price: 19980,
    rating: 4,
    reviews: 68,
    image: "https://m.media-amazon.com/images/I/81f5e+dDg0L._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D5Y19RLY",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "FFS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "FFS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazonギフト", value: "PCモニター #20" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "35.9 × 22.6 × 1.6 cm" },
          { label: "重量", value: "0.80Kg" }]}],
  },
  {
    id: "mon-gift-021",
    category: "monitor",
    name: "G27i",
    brand: "Xiaomi",
    tagline: "Xiaomi G27i 27インチ ゲーミングモニター FHD 1920×1080 165Hz Fast IPS 1ms GTG sRGB99% ΔE<2 | TÜV認証 ブルーライト低減 | AMD FreeSync | DP1.4 VESA 75×75対応",
    price: 17980,
    rating: 4.3,
    reviews: 428,
    image: "https://m.media-amazon.com/images/I/61E7ZEGg-BL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CNC7NDC4",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-75","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "75×75 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazonギフト", value: "PCモニター #21" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "43 × 68 × 11 cm" },
          { label: "重量", value: "3.8 kg" }]}],
  },
    {
    id: "mon-gift-027",
    category: "monitor",
    name: "27型 USB-C モニター",
    brand: "Minifire",
    tagline: "Minifire モニター27インチ 120Hz フルHD 1920x1080 ディスプレイ USB-Type C/HDMI Adaptive Sync OD 5ms HDR10 sRGB 110% ブルーライト軽減 フリッカーフリー VESA対応 フレームレス 5年保証",
    price: 15999,
    rating: 4.2,
    reviews: 533,
    image: "https://m.media-amazon.com/images/I/71NCimKpwpL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CG5VDGKY",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","port-usb-c","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazonギフト", value: "PCモニター #27" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "44.3 × 61.4 × 21.3 cm" },
          { label: "重量", value: "3.5 kg" }]}],
  },
  {
    id: "mon-gift-028",
    category: "monitor",
    name: "EX251",
    brand: "BenQ",
    tagline: "BenQ MOBIUZ EX251 24.5インチ IPS フルHD 220Hz 1ms ゲーミングモニター ノングレア DisplayHDR 400 sRGB 99% FreeSync 輝度自動調整(B.I.+ Gen2) スピーカー内蔵 3年保証",
    price: 23305,
    rating: 4.2,
    reviews: 293,
    image: "https://m.media-amazon.com/images/I/71q5w8TChKL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DT3NLNCC",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "220Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "220Hz" },
          { label: "Amazonギフト", value: "PCモニター #28" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 42.9 × 21.2 cm" },
          { label: "重量", value: "4.17Kg" }]}],
  },{
    id: "mon-gift-030",
    category: "monitor",
    name: "Minifire 24インチ USB-C 120Hz モニター",
    brand: "Minifire",
    tagline: "Minifire 24インチ USB-C 120Hz モニター FHD HDR10 Adaptive Sync VESA対応 フレームレス Type-C/HDMI チルト調節可 ビジネス用 五年保証(USB Type-Cケーブル付-",
    price: 12999,
    rating: 4,
    reviews: 455,
    image: "https://m.media-amazon.com/images/I/71VR8zB2CYL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CNK91XLQ",
    monitorFilterTags: ["size-24","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920 x 1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920 x 1080)" },
          { label: "パネル", value: "IPS非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazonギフト", value: "PCモニター #30" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 39.8 × 16.8 cm" },
          { label: "重量", value: "2.5 kg" }]}],
  }]
