import type { Gadget } from "./gadgets"

/** Amazon.co.jp ディスプレイ新着 2ページ目（2151982051 pg=2）#51–#80。 */
export const monitorNewReleasesPage2: Gadget[] = [
  {
    id: "mon-nr2-001",
    category: "monitor",
    name: "EVC-160U",
    brand: "EVICIV",
    tagline: "EVICIV モバイルモニター 16インチ 卓上スタンド付き FHD 1200P 自立型 125%sRGB 1200:1 ゲーミング用 ポータブルディスプレイ IPS 非光沢 液晶パネル 薄型 軽量 モバイルディスプレイ USB Type-C Mini HDMI 搭載",
    price: 11980,
    rating: 4.3,
    reviews: 3223,
    image: "https://m.media-amazon.com/images/I/71PnR7oNrvL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HCN85ML5",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "16\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "16\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #51" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "0.73 kg" }]}],
  },
  {
    id: "mon-nr2-002",
    category: "monitor",
    name: "Mini LED 27型 ゲーミングモニター",
    brand: "KOORUI",
    tagline: "LED ゲーミングモニター 27インチ 200Hz WQHD 2560×1440 Fast IPS 1ms HDR1000 Adaptive Sync対応/Adobe RGB 99%/ 高さ調整/縦横回転/PIP PBP機能/HDMI2.0 DP1.4",
    price: 35800,
    rating: 4.4,
    reviews: 1544,
    image: "https://m.media-amazon.com/images/I/71MMM+UJSML._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F6T1GW8G",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "Fast IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon新着", value: "PCモニター #52" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 54.3 × 21.4 cm" },
          { label: "重量", value: "8.99Kg" }]}],
  },
  {
    id: "mon-nr2-003",
    category: "monitor",
    name: "JN-IPS34G165UQ2",
    brand: "JAPANNEXT",
    tagline: "JAPANNEXT 34インチ ゲーミングモニター JN-IPS34G165UQ2【2年保証】 IPSパネル,165Hz/1msMPRT対応,UWQHD3440×1440解像度,HDMI,DisplayPort,HDR,PS5,WQHD,120Hz接続,PIP/PBP,アスペクト比21:9,2年保証",
    price: 43618,
    rating: 4,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/717-uN+smVL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GRZT7K5T",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon新着", value: "PCモニター #53" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "81.6 × 44.5 × 23.4 cm" },
          { label: "重量", value: "5.2 kg" }]}],
  },
  {
    id: "mon-nr2-004",
    category: "monitor",
    name: "ZenScreen MB16FC-J",
    brand: "ASUS",
    tagline: "【amazon.co.jp限定】ASUS ZenScreen MB16FC-J ポータブルモニター – 16インチ/16:10画面比率/WUXGA(1920x1200)解像度/IPSパネル/パススルー給電/自動回転/USB Type-C・mini-HDMI/フリッカーフリー/ブルーライト低減/FSC Mix認証/国内正規品",
    price: 23616,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/81xjP36DeIL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZ21C95F",
    vesaStandard: "非対応",
    monitorFilterTags: ["size-238","refresh-75","port-hdmi","port-usb-c","vesa-none","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "16\"" },
      { label: "解像度", value: "WUXGA（1920×1200）" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "16\"" },
          { label: "解像度", value: "WUXGA（1920×1200）" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon新着", value: "PCモニター #54" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "35.8 × 24.6 × 1.1 cm" },
          { label: "重量", value: "0.9 kg" }]}],
  },
  {
    id: "mon-nr2-005",
    category: "monitor",
    name: "VisionOwl　Y-14QH",
    brand: "—",
    tagline: "【Amazon限定ブランド】VisionOwl モバイル・ゲーミングモニター 14インチ 120Hz 2.5K解像度 高輝度450nit 100％sRGB広色域 Switch2直結 超軽量540g 自立型 画像比率調整可能 収納ケース付 モバイルディスプレイ 光沢IPSパネル 2520x1680",
    price: 17980,
    rating: 4.5,
    reviews: 3087,
    image: "https://m.media-amazon.com/images/I/710F3c2GoaL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H28F8CWD",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "14\"" },
      { label: "解像度", value: "2.5K(2560 x 1600)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "14\"" },
          { label: "解像度", value: "2.5K(2560 x 1600)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #55" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "0.5 kg" }]},      { title: "本体", rows: [
          { label: "寸法", value: "30.8 × 22 × 0.8 cm" },
          { label: "重量", value: "0.5 kg" }]}],
  },{
    id: "mon-nr2-007",
    category: "monitor",
    name: "EX-GD252UHW",
    brand: "KOORUI",
    tagline: "IODATA GCFX ゲーミングモニター 24.5型 フルHD 260Hz ホワイト HDMI/DP/VESA/チルト調整 EX-GD252UHW 応答速度0.8ms［GTG］,内部遅延時間「約0.03フレーム」,IPS方式（HFS）パネル,ナイトビジョンモード,色彩強調,超解像度,3辺フレームレス,ゲームモード,ブルーライト低減機能,無輝点保証",
    price: 17980,
    rating: 4.5,
    reviews: 484,
    image: "https://m.media-amazon.com/images/I/71yEIZEPUFL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HCNDB4GQ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "260Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "260Hz" },
          { label: "Amazon新着", value: "PCモニター #57" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 41.6 × 17.3 cm" },
          { label: "重量", value: "3.2 kg" }]}],
  },
  {
    id: "mon-nr2-008",
    category: "monitor",
    name: "G2412V",
    brand: "KOORUI",
    tagline: "KOORUI ゲーミングモニター 24インチ 180Hz フルHD モニター G2412V 180Hz/FHD/AdaptiveSync/HDMI×2/VESA対応/ブルーライト軽減/VAパネル/傾き調整",
    price: 12980,
    rating: 4.3,
    reviews: 1290,
    image: "https://m.media-amazon.com/images/I/71NTTChf5cL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / VGA対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GRVJL7VK",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon新着", value: "PCモニター #58" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "38 × 49 × 21 cm" },
          { label: "重量", value: "3.55Kg" }]}],
  },
  {
    id: "mon-nr2-009",
    category: "monitor",
    name: "G2421V",
    brand: "KOORUI",
    tagline: "KOORUI ゲーミングモニター 24インチ WQHD (2560x1440) 180Hz 1ms (GTG) Fast IPSパネル HDR400 FreeSync/G-Sync対応/HDMI/DP ブルーライト低減 VESAマウント対応",
    price: 22800,
    rating: 4.3,
    reviews: 529,
    image: "https://m.media-amazon.com/images/I/718lI2rFXLL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GSZMHT6D",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "Fast IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS 非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon新着", value: "PCモニター #59" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "54 × 43 × 23 cm" },
          { label: "重量", value: "3.07 kg" }]}],
  },
  {
    id: "mon-nr2-010",
    category: "monitor",
    name: "YELPLION 10.5型 モバイルモニター",
    brand: "YELPLION",
    tagline: "モバイルモニター 10.5\" 1280P IPSパネル 100%sRGB HDR 超軽量260g ノートPC/スマホ/ゲーム機対応 ポータブルモニター、420nits高輝度、保護カバー付き、VESA対応、モバイルディスプレイ、USB Type-C1本で給電・映像出力、Mini HDMI搭載、",
    price: 7450,
    rating: 4.3,
    reviews: 25,
    image: "https://m.media-amazon.com/images/I/71wDo58-dEL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8SQ13B8",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "10.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "10.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #60" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "0.3 kg" }]},      { title: "本体", rows: [
          { label: "寸法", value: "23 × 16 × 1 cm" },
          { label: "重量", value: "0.3 kg" }]}],
  },
  {
    id: "mon-nr2-011",
    category: "monitor",
    name: "LivElect 18.5型 モバイルモニター",
    brand: "LivElect",
    tagline: "LivElect モバイルモニター 18.5インチ 120HZ 1920*1080 モバイルディスプレイ VESA対応 在宅勤務 リモートワーク | 18.5イ",
    price: 18999,
    rating: 4.6,
    reviews: 18,
    image: "https://m.media-amazon.com/images/I/81SzpBxPo6L._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8SQ79QJ",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["port-hdmi","port-usb-c","refresh-100","res-fhd","vesa-75","panel-ips"],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5 インチ" },
          { label: "解像度", value: "1920 x 1080 (FHD)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #61" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "900 g" }]}],
  },{
    id: "mon-nr2-013",
    category: "monitor",
    name: "XUNDEFINED 21.5型 モニター",
    brand: "XUNDEFINED",
    tagline: "XUNDEFINED 21.5インチ モニター フルHD(1920x1080) 120Hz 超薄型 液晶ディスプレイ スピーカー内蔵 VAパネル 非光沢 100%sRGB 4000:1コントラスト比 AdaptiveSync対応 ブルーライト軽減 フリッカーフリー HDMI+DP+音声出力端子搭載 チルト調整 75mm*75mm VESA対応",
    price: 11980,
    rating: 4.2,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/71nTwqm72QL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3NNB52H",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-75","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "VA 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #63" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "49.3 × 38 × 16 cm" },
          { label: "重量", value: "2.5Kg" }]}],
  },
  {
    id: "mon-nr2-014",
    category: "monitor",
    name: "LivElect 15.6インチ デュアルモバイルモニター P7pro",
    brand: "—",
    tagline: "15.6インチ ディアルモバイルモニター【ケーブル一本接続可能】 2画面 ノートパソコン用 1080P ポータブルディスプレイ USB-C接続 全パソコン対応 アルミ製拡張スクリーン Windows、Mac、Chrome対応",
    price: 35998,
    rating: 4.5,
    reviews: 55,
    image: "https://m.media-amazon.com/images/I/71lpncoj5+L._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTD6N932",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-usb-c","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #64" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "33.4 × 7.1 × 44.4 cm" },
          { label: "重量", value: "2.97Kg" }]}],
  },
  {
    id: "mon-nr2-017",
    category: "monitor",
    name: "JN-i27G180Q-ARM-MK",
    brand: "JAPANNEXT",
    tagline: "【モニ研監修モニターアーム同梱モデル】 JAPANNEXT 27インチ ゲーミングモニタIPSパネル搭載 180Hz/1ms(MPRT)対応 WQHD(2560×1440)解像度 HDMI DP sRGB:100% HDR400相当 PS5 WQHD:120Hz接続 【2年保証】",
    price: 29979,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/81MvkHguW7L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8S9V2J1",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon新着", value: "PCモニター #67" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 58 × 56 cm" },
          { label: "重量", value: "5.6 kg" }]}],
  },
  {
    id: "mon-nr2-018",
    category: "monitor",
    name: "P2426HE",
    brand: "Dell",
    tagline: "Dell P2426HE 23.8インチ USB-C ハブ モニタ /1920×1080 /HDMI、DisplayPort、USB-C 給電/ブラック/スピーカー:なし(メーカー3年保証、良品先出しサービス保証付き)",
    price: 34100,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61amK7p5veL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GWHRXL3B",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","port-usb-c","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #68" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C (PD)", value: "映像/給電対応" },
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "53.8 × 49.7 × 18.2 cm" },
          { label: "重量", value: "3.45Kg" }]}],
  },
  {
    id: "mon-nr2-019",
    category: "monitor",
    name: "ASTEX 40型 スマートモニター",
    brand: "ASTEX",
    tagline: "ASTEX 40型 モニター ビジネスモニター兼用 Google TV スマートディスプレイ フルHD VA広視野角パネル VOD Bluetooth対応 PCモニター 店頭表示用 待合室用",
    price: 29980,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/81+J1fd5ykL._AC_SL1500_.jpg",
    connection: "HDMI / USB / AV入力",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GG9BXTV1",
    vesaStandard: "200×100",
    monitorFilterTags: ["size-315-plus","res-fhd","refresh-60","port-hdmi","vesa-200-plus","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "40\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "40\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #69" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "USB", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "90.4 × 56.8 × 20.7 cm" },
          { label: "重量", value: "4.65 kg" }]}],
  },
  {
    id: "mon-nr2-020",
    category: "monitor",
    name: "U3226QER",
    brand: "Dell",
    tagline: "Dell U3226QER 31.5インチ Thunderbolt ハブ モニター 無輝点3年保証/4K/IPS Black,非光沢/DP1.4x1,HDMIx1,TB4x1/有線Ethernet/PbP,PiP,KVM/環境光センサー,DisplayHDR 600/DCI-P3 99％/縦横回転,高さ調整",
    price: 122800,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71FsnJayLzL._AC_SL1500_.jpg",
    connection: "Thunderbolt 4 / USB Type-C / HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H4V7RJ9Y",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS Black 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS Black 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #70" }]},
      { title: "接続端子", rows: [
          { label: "Thunderbolt 4", value: "対応" },
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "71.3 × 61.9 × 21.5 cm" },
          { label: "重量", value: "6.52Kg" }]}],
  },
  {
    id: "mon-nr2-021",
    category: "monitor",
    name: "iiyama ProLite 27型 モニター (XB2797QSN-B1J)",
    brand: "iiyama",
    tagline: "iiyama 【5年メーカー保証】モニター ディスプレイ ProLite XB2491HS-B1J 23.8インチ フルHD IPS方式 高さ調整 角度調整 縦回転 HDMI DisplayPort ケーブル付",
    price: 28930,
    rating: 4.6,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/7156019AR6L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GNR572Y6",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon新着", value: "PCモニター #71" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 40.4 × 21 cm" },
          { label: "重量", value: "4.8Kg" }]}],
  },
  {
    id: "mon-nr2-022",
    category: "monitor",
    name: "Newsoul 15.6型 タッチモバイルモニター",
    brand: "Newsoul",
    tagline: "モバイルモニター 15.6インチ 8000mAh大容量バッテリー内蔵 タッチパネルター ッチペン付き Newsoul 1080P モバイルディスプレイ IPS液晶パネル 非光沢画面 薄型軽量 180°自立スタンド 充電式 スイッチ用 ポータブルモニター HDR VESA対応壁掛け可能 USB Type-C ミニHDMI",
    price: 24999,
    rating: 4.8,
    reviews: 84,
    image: "https://m.media-amazon.com/images/I/71O5qwL7TCL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GRFY9CY4",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "75×75 mm" },
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #72" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "0.6 kg" }]}],
  },
    {
    id: "mon-nr2-024",
    category: "monitor",
    name: "Laptomo トリプルモバイルモニター",
    brand: "Laptomo",
    tagline: "トリプルモニター 15.6インチ デュアルモバイルモニター FHD 1080P IPS ノートパソコンモニター 2画面/3画面 拡張ディスプレイ 折りたたみ式 180°回転 HDMI/Type-C プラグアンドプレイ",
    price: 43998,
    rating: 5,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/81+YQ-y82UL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3FD8HV8",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #74" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "28 × 10 × 40 cm" },
          { label: "重量", value: "4.01Kg" }]}],
  },
  {
    id: "mon-nr2-025",
    category: "monitor",
    name: "JN-IPS32FW-M",
    brand: "JAPANNEXT",
    tagline: "JAPANNEXT 32インチ 液晶モニター JN-IPS32FW-M【2年保証】 IPSパネル,FWXGA(1366×768)解像度,HDMI,VGA,ビデオ/音声入力,コアキシャル音声出力,USBメモリ再生対応,簡易サイネージ,リモコン同梱,2年保証",
    price: 22255,
    rating: 3.8,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61Tw2FaGhYL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS1CVBFB",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","refresh-60","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "32\"" },
      { label: "解像度", value: "FWXGA(1366×768)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "32\"" },
          { label: "解像度", value: "FWXGA(1366×768)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #75" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "71.8 × 46.6 × 20 cm" },
          { label: "重量", value: "3.4 kg" }]}],
  },
  {
    id: "mon-nr2-026",
    category: "monitor",
    name: "JN-MD-IPST101WHD",
    brand: "JAPANNEXT",
    tagline: "JAPANNEXT 10.1インチ IPSパネル搭載 10点マルチタッチ対応 ワイドHD(1540×720)解像度 モバイルモニター JN-MD-IPST101WHD miniHDMI USB-C 自立式キックスタンド搭載 フェルトケース同梱 【2年保証】",
    price: 19982,
    rating: 4.6,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61MBFrl1HXL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GX5KHPQV",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","refresh-60","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "10.1\"" },
      { label: "解像度", value: "ワイドHD(1540×720)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "10.1\"" },
          { label: "解像度", value: "ワイドHD(1540×720)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #76" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "24.8 × 12.9 × 1.6 cm" },
          { label: "重量", value: "0.46 kg" }]}],
  },
  {
    id: "mon-nr2-027",
    category: "monitor",
    name: "JN-MD-iE133F-T",
    brand: "JAPANNEXT",
    tagline: "JAPANNEXT 13.3インチ IPSパネル搭載 10点マルチタッチ対応 フルHD(1920×1080)解像度 モバイルモニターminiHDMI USB-C sRGB:99% HDR 自立式キックスタンド搭載 フェルトケース同梱 【2年保証】",
    price: 20979,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71eQlAiPgwL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GX5K8ZKZ",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "13.3\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "13.3\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #77" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "30.6 × 19.5 × 1.8 cm" },
          { label: "重量", value: "0.52 kg" }]}],
  },
  {
    id: "mon-nr2-028",
    category: "monitor",
    name: "JN-IPS215FNS",
    brand: "JAPANNEXT",
    tagline: "JAPANNEXT 21.5インチ IPSパネル搭載 フルHD(1920×1080)解像度 液晶モニター JN-IPS215FNS HDMI,DP,sRGB:100%,HDR,2年保証",
    price: 13480,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71PWZ6YQBnL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HBQ28VPH",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon新着", value: "PCモニター #78" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "36.3 × 49.3 × 18 cm" },
          { label: "重量", value: "2.1 kg" }]}],
  },
  {
    id: "mon-nr2-029",
    category: "monitor",
    name: "JN-IPS238Q-HSPC6-W",
    brand: "JAPANNEXT",
    tagline: "JAPANNEXT 23.8インチ IPSパネル搭載 WQHD(2560×1440)解像度 液晶モニター(ホワイト) JN-IPS238Q-HSPC6-W HDMI DP USB-C(最大65W給電) sRGB:99% HDR 高さ調整 ピボット(縦回転)対応 ケーブル(ホワイト)同梱【2年保証】",
    price: 26345,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/81+mLqbgymL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H5HGJ6YS",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-wqhd","refresh-75","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "WQHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "WQHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon新着", value: "PCモニター #79" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "54 × 48 × 19 cm" },
          { label: "重量", value: "4 kg" }]}],
  },
  {
    id: "mon-nr2-030",
    category: "monitor",
    name: "Thinlerain 19型 モニター",
    brand: "Thinlerain",
    tagline: "19インチモニター 10点タッチ対応 ディスプレイモニター/HDMI VGA AV BNC USB ポート/1440×900 /16:10/VESAマウント/スピーカー内蔵",
    price: 9999,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71oeRoVNnwL._AC_SL1500_.jpg",
    connection: "HDMI / VGA / AV",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZZR8XQC",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","refresh-60","port-hdmi","vesa-75","panel-tn"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "19\"" },
      { label: "解像度", value: "HD+ (1440×900)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "TN" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "19\"" },
          { label: "解像度", value: "HD+ (1440×900)" },
          { label: "パネル", value: "TN" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon新着", value: "PCモニター #80" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
          { label: "USB", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "44.5 × 35 × 18 cm" },
          { label: "重量", value: "2.8Kg" }]}],
  }]
