import type { Gadget } from "./gadgets"

/** Amazon.co.jp ディスプレイ売れ筋 1ページ目（2151982051）#1–#50。 */
export const monitorBestsellers: Gadget[] = [
  {
    id: "mon-bs-001",
    category: "monitor",
    name: "EVC-1506S モバイルモニター",
    brand: "EVICIV",
    tagline: "EVICIV モバイルモニター 15.6インチ FHD 1920×1080 モバイルディスプレイ 自立型 ポータブルモニター 軽量 薄型 持ち運び IPS液晶 非光沢 ブルーライトカット USB Type-C/Mini HDMI 在宅勤務・外出作業 Switch2・PS5・PC・Mac対応 EVC-1506S",
    price: 7976,
    rating: 4.3,
    reviews: 7371,
    image: "https://m.media-amazon.com/images/I/61nyLT8F3YL._AC_SL1500_.jpg",
    connection: "Mini HDMI×1",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07ZNTHZHZ",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #1" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "×2" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "22.2 × 35.7 × 1.2 cm" },
          { label: "重量", value: "0.68 kg" }]}],
  },
  {
    id: "mon-bs-002",
    category: "monitor",
    name: "KEEPTIMEモバイルモニター 15.6インチ",
    brand: "KEEPTIME",
    tagline: "モバイルモニター 15.6\" 1080P IPS非光沢 薄型 軽量 USB-C ミニHDMI対応 ノートPC/スマホ/ゲーム機対応モバイルディスプレイ1920*1080、 ポータブルモニター IPSパネル、ノングレア、5mm薄型、570g軽量、マグネットカバー、モニターUSB C/mini HDMI付き",
    price: 8990,
    rating: 4.2,
    reviews: 3600,
    image: "https://m.media-amazon.com/images/I/81acSfz-TCL._AC_SL1500_.jpg",
    connection: "Mini HDMI×1 / USBポート×2",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D1K8H4F5",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #2" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "×1" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "34.8 × 24.6 × 0.5 cm" },
          { label: "重量", value: "0.6 kg" }]}],
  },
  {
    id: "mon-bs-003",
    category: "monitor",
    name: "H24V27",
    brand: "KTC",
    tagline: "KTC 24インチ モニター FHD 100Hz VA HDR10 3年保証 H24V27 24インチ・FHD 1920×1080・100Hz・VA・HDR10・300cd/㎡・4000:1・Adaptive Sync・HDMI1.4・VGA・VESA対応・チルト調整・低ブルーライト・フリッカーフリー",
    price: 10980,
    rating: 4.1,
    reviews: 267,
    image: "https://m.media-amazon.com/images/I/71guzQ7ahpL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9K624F9",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-100","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #3" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "50 × 40 × 60 cm" },
          { label: "重量", value: "3.8Kg" }]}],
  },
  {
    id: "mon-bs-004",
    category: "monitor",
    name: "S2725DC",
    brand: "Dell",
    tagline: "Dell S2725DC 27インチ モニター無輝点3年保証/QHD/IPS,非光沢/USB-Cx1,HDMIx1,DP1.4x1/sRGB 99%/縦横回転,高さ調整/1ms,144Hz/AMD FreeSync/内蔵スピーカー",
    price: 32800,
    rating: 4.5,
    reviews: 238,
    image: "https://m.media-amazon.com/images/I/71iLuNyaz5L._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / DisplayPort / USB-A　対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FPF1HGT8",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #4" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.1 × 50 × 20.2 cm" },
          { label: "重量", value: "6.48 kg" }]}],
  },
    {
    id: "mon-bs-006",
    category: "monitor",
    name: "PRO MP2412",
    brand: "MSI",
    tagline: "【Amazon.co.jp限定】MSI ビジネスモニター PRO MP2412 薄型 VAパネル フルHD/23.8インチ/HDMI/DisplayPort/リフレッシュレート100Hz/応答速度1ms(MPRT)/ブルーライトカット/アンチフリッカー/VESA75対応/メーカー3年保証",
    price: 17328,
    rating: 4.2,
    reviews: 506,
    image: "https://m.media-amazon.com/images/I/61Q7Y7qpWXL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CDBS93QZ",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-75","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #6" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 42.9 × 18.2 cm" },
          { label: "重量", value: "2.9 kg" }]}],
  },
  {
    id: "mon-bs-007",
    category: "monitor",
    name: "EX-A241DB",
    brand: "IO DATA",
    tagline: "【Amazon.co.jp 限定】IODATA モニター 23.8型 省電力 (HDMI/アナログRGB/スピーカ付/VESA) EX-A241DBADSパネル,ブラック",
    price: 14800,
    rating: 4.3,
    reviews: 805,
    image: "https://m.media-amazon.com/images/I/71MBuR5fWaL._AC_SL1500_.jpg",
    connection: "HDMI / RGB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CPXQQLL2",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-ads"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "ADS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "ADS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #7" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "54 × 38.2 × 21.5 cm" },
          { label: "重量", value: "4.72Kg" }]}],
  },
  {
    id: "mon-bs-008",
    category: "monitor",
    name: "SE2425H",
    brand: "Dell",
    tagline: "Dell SE2425H 23.8インチ モニター 1920×1080/HDMI、VGA/ブラック/スピーカー：なし(メーカー3年保証、良品先出しサービス保証付き)",
    price: 11800,
    rating: 4.4,
    reviews: 95,
    image: "https://m.media-amazon.com/images/I/6129+jA4geL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DD6GJVV5",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #8" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "55.3 × 42 × 49.3 cm" },
          { label: "重量", value: "2.8 kg" }]}],
  },
  {
    id: "mon-bs-009",
    category: "monitor",
    name: "27SQ750S-W",
    brand: "LG",
    tagline: "LG モニター 27U731SA-W 27インチ/4K/IPS/約10.7億色表示(8bit+FRC)/HDR/USB-C PD65W",
    price: 39800,
    rating: 4.1,
    reviews: 335,
    image: "https://m.media-amazon.com/images/I/71cgX7UiKAL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / USB-A　対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F6CVWFYB",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-60","port-hdmi","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #9" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 45.2 × 21 cm" },
          { label: "重量", value: "5.85 kg" }]}],
  },
  {
    id: "mon-bs-011",
    category: "monitor",
    name: "AMZG34C8 Pro",
    brand: "Amzfast",
    tagline: "Amzfast 34インチ ゲーミングモニター 240Hz 曲面ウルトラワイド UWQHD 3440x1440 1ms MPRT 130%sRGB 3000:1コントラスト 450nits/Adaptive Sync/フリッカー防止/PIP PBP機能/ブルーライト低減/HDMI 2.1FRL*2+DP1.4 *2/100x100 VESA/5年保証 AMZG34C8 Pro（VRR対応）",
    price: 36980,
    rating: 4.2,
    reviews: 2437,
    image: "https://m.media-amazon.com/images/I/71LeNIsYjFL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DZ6LG8PZ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-va"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "VA 曲面" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA 曲面" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #11" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "44 × 19 × 80.7 cm" },
          { label: "重量", value: "5.3 kg" }]}],
  },
  {
    id: "mon-bs-012",
    category: "monitor",
    name: "EX-GDU271JLAQD",
    brand: "IODATA",
    tagline: "IODATA GigaCrysta S ゲーミングモニター 27型 FHD/360Hz 4K/180Hz MiniLED EX-GDU271JLAQD 量子ドット, DisplayHDR1400, 無輝点保証",
    price: 74800,
    rating: 4.6,
    reviews: 123,
    image: "https://m.media-amazon.com/images/I/71kWUzN1eKL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-A　対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GNRS88NQ",
    vesaStandard: "—",
    monitorFilterTags: ["size-27","res-4k","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "360Hz" },
      { label: "パネル", value: "Fast IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "360Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #12" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 39.8 × 23.9 cm" },
          { label: "重量", value: "10.4Kg" }]}],
  },
  {
    id: "mon-bs-013",
    category: "monitor",
    name: "H25T7",
    brand: "KTC",
    tagline: "KTC 24.5インチ ゲーミングモニター FHD 240Hz Fast IPS H25T7-A 24.5インチ・FHD 1920×1080・240Hz・Fast IPS・HDR10・sRGB128%・350cd/㎡・1000:1・Adaptive Sync・HDMI2.0×2・DP1.4×1・低ブルーライト・チルト調整",
    price: 15980,
    rating: 4.4,
    reviews: 298,
    image: "https://m.media-amazon.com/images/I/71cl6vRfPXL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9K8WK2Q",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #13" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 32.7 × 4.9 cm" },
          { label: "重量", value: "5.04Kg" }]}],
  },
    {
    id: "mon-bs-018",
    category: "monitor",
    name: "VG259Q5A",
    brand: "ASUS",
    tagline: "【Amazon.co.jp限定】ASUSゲーミングモニター/TUF Gaming VG259Q5A – 24.5インチ / フルHD（1920x1080） / 200Hz / Fast IPS/ELMB / 0.3ms GTG（最小） / ステレオスピーカー/DisplayWidget Center/国内正規品",
    price: 16980,
    rating: 4.2,
    reviews: 214,
    image: "https://m.media-amazon.com/images/I/71hhyOqLuZL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F9WJLW45",
    vesaStandard: "—",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "Fast IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #18" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "55.9 × 40.1 × 17.4 cm" },
          { label: "重量", value: "3.4 kg" }]}],
  },
  {
    id: "mon-bs-019",
    category: "monitor",
    name: "MAG 244F",
    brand: "MSI",
    tagline: "【Amazon.co.jp限定】MSI ゲーミングモニター MAG 244F 23.8インチ/フルHD/RAPID IPSパネル/200Hz/0.5ms(GTG)/Adaptive-Sync/HDR/HDMI 2.0b/DP1.2a/VESA100/メーカー3年保証",
    price: 22800,
    rating: 4,
    reviews: 139,
    image: "https://m.media-amazon.com/images/I/61BVpY0X4+L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F18KF4HH",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "200Hz" },
      { label: "パネル", value: "Rapid IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Rapid IPS" },
          { label: "リフレッシュレート", value: "200Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #19" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "39.9 × 54.2 × 22.1 cm" },
          { label: "重量", value: "2.88 kg" }]}],
  },
  {
    id: "mon-bs-020",
    category: "monitor",
    name: "GW2790",
    brand: "BenQ",
    tagline: "BenQ GW2790 27インチ フルHD IPS 100Hz アイケアモニター\"ノングレア,黒筐体,sRGB,99%,3辺ウルトラスリムベゼル,輝度自動調整機能(B.I.,Gen2),ブルーライト軽減プラス,フリッカーフリー,スピーカー内蔵,3年保証(パネル・バックライト1年),ベンキュージャパン \"",
    price: 19800,
    rating: 4.2,
    reviews: 277,
    image: "https://m.media-amazon.com/images/I/61qXVEY7lXL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CTM6T5C2",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #20" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 44.9 × 18.2 cm" },
          { label: "重量", value: "5 kg" }]}],
  },
  {
    id: "mon-bs-021",
    category: "monitor",
    name: "BenQ GW2790",
    brand: "UPERFECT",
    tagline: "BenQ GW2790 27インチ フルHD IPS 100Hz アイケアモニター\"ノングレア,黒筐体,sRGB,99%,3辺ウルトラスリムベゼル,輝度自動調整機能(B.I.,Gen2),ブルーライト軽減プラス,フリッカーフリー,スピーカー内蔵,3年保証(パネル・バックライト1年),ベンキュージャパン \"",
    price: 15880,
    rating: 4.2,
    reviews: 6423,
    image: "https://m.media-amazon.com/images/I/711AO9gu58L._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FH58W9NF",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #21" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "35.9 × 22.5 × 0.9 cm" },
          { label: "重量", value: "1.2 kg" }]}],
  },
  {
    id: "mon-bs-024",
    category: "monitor",
    name: "EX-LD2381DB",
    brand: "IO DATA",
    tagline: "I-O DATA モニター 23.8インチ ADS非光沢 スピーカー付 3年保証 土日サポート EX-LD2381DB",
    price: 13980,
    rating: 4.2,
    reviews: 1933,
    image: "https://m.media-amazon.com/images/I/61Aq5zCdTVL._AC_SL1500_.jpg",
    connection: "HDMI / DVI-D / RGB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B011OBZ5Y4",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-ads"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "ADS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "ADS" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #24" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 41 × 21 cm" },
          { label: "重量", value: "4.2kg" }]}],
  },
  {
    id: "mon-bs-026",
    category: "monitor",
    name: "G2724D",
    brand: "Dell",
    tagline: "メーカー終売",
    price: 32800,
    rating: 4.4,
    reviews: 160,
    image: "https://m.media-amazon.com/images/I/51N81sKPvoL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / USB-C　対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C9PVL4FM",
    vesaStandard: "—",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "Fast IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #26" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 52.3 × 20.2 cm" },
          { label: "重量", value: "8.4Kg" }]}],
  },
  {
    id: "mon-bs-027",
    category: "monitor",
    name: "27N1A",
    brand: "KOORUI",
    tagline: "KOORUI モニター 27インチ、ディスプレイ FHD 1080P IPS 非光沢 デスクトップディスプレイ(75hz/5ms/sRGB 99%色域/HDMI VGA/75mm*75mm VESA対応/アイケア/広い視野角178°)",
    price: 13980,
    rating: 4.3,
    reviews: 1290,
    image: "https://m.media-amazon.com/images/I/81Vc8Bbh06L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B3DS23NB",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-75","port-hdmi","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #27" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "4.76 kg" }]}],
  },
  {
    id: "mon-bs-029",
    category: "monitor",
    name: "JN-IPS238FHDR-C65W",
    brand: "JAPANNEXT",
    tagline: "JAPANNEXT 23.8インチ 液晶モニター JN-IPS238FHDR-C65W【2年保証】 IPSパネル,フルHD1920×1080解像度,KVM,HDMI,USB-C,給電65W,スピーカー内蔵,VESA対応,ブルーライトカット,ブラック",
    price: 17980,
    rating: 4.2,
    reviews: 168,
    image: "https://m.media-amazon.com/images/I/71Y50t5c5CL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / USB-A　対応 / USB-B / 対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BNTNRBHK",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #29" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C (65W PD)", value: "映像/給電対応" },
          { label: "HDMI", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "53.8 × 39.5 × 17.3 cm" },
          { label: "重量", value: "2.8 kg" }]}],
  },
  {
    id: "mon-bs-031",
    category: "monitor",
    name: "G272QPF E2",
    brand: "MSI",
    tagline: "MSI G272QPF E2 27インチ 2560 x 1440 (QHD) コンピューターモニター 180Hz 適応同期 HDMI DisplayPort VESAマウント可能 傾き 高さ調整可能 スピーカー 1ms ブラック",
    price: 29800,
    rating: 4.1,
    reviews: 50,
    image: "https://m.media-amazon.com/images/I/71uFq6IrdQL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CZWZLJVQ",
    vesaStandard: "—",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "Fast IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #31" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "USB Type-C", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 40.5 × 23.4 cm" },
          { label: "重量", value: "8.51Kg" }]}],
  },
  {
    id: "mon-bs-033",
    category: "monitor",
    name: "VP229HE",
    brand: "ASUS",
    tagline: "21.5型FHD 75Hz・IPS・Eye Care",
    price: 9980,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71Oz1gibNGL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07Y5VJ8XG",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #33" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]}],
  },
  {
    id: "mon-bs-037",
    category: "monitor",
    name: "RLD-27FHD-B",
    brand: "IRIS OHYAMA",
    tagline: "27型FHD・VA・HDMI/VGA",
    price: 13800,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61w5ryKbouL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C7B8YQ8K",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-60","port-hdmi","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #37" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]}],
  },
  {
    id: "mon-bs-039",
    category: "monitor",
    name: "MFG24F1",
    brand: "Minifire",
    tagline: "Minifire ゲーミングモニター 24インチ 180Hz 4000：1コントラスト比 NTSC72% HDR 300cd/m² Adaptive Sync FHD 16.7M(8 bits) VESA 75*75mm DP1.4 HDMI ポート (HDMIケーブル付属、MFG24F4L)",
    price: 11999,
    rating: 4.1,
    reviews: 113,
    image: "https://m.media-amazon.com/images/I/71Mjp6jvKAL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F6N5GXNX",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-75","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #39" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.3 × 20.2 cm" },
          { label: "重量", value: "2.7 kg" }]}],
  },
  {
    id: "mon-bs-040",
    category: "monitor",
    name: "241E1D/11",
    brand: "PHILIPS",
    tagline: "23.8型FHD・IPS・HDMI/DVI/VGA",
    price: 13800,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/710v0dPuJQL._AC_SL1500_.jpg",
    connection: "HDMI / DVI-D / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVYKG7CW",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #40" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DVI-D", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "25 × 10 × 20 cm" },
          { label: "重量", value: "—" }]}],
  },
  {
    id: "mon-bs-041",
    category: "monitor",
    name: "A27i",
    brand: "Xiaomi",
    tagline: "Xiaomi A27i 27インチモニター、100Hzの高リフレッシュレート、IPSハードスクリーン、7.5mmウルトラスリムボディ、1080p FHD解像度、各スクリーンに2つの工場カラーキャリブレーション、DP 1.4対応で簡単な取り付け。",
    price: 13980,
    rating: 4.4,
    reviews: 53,
    image: "https://m.media-amazon.com/images/I/51JoW0aDVML._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DFXYMGVR",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","port-dp","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #41" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 52.7 × 16.9 cm" },
          { label: "重量", value: "3.6Kg" }]}],
  },
    {
    id: "mon-bs-044",
    category: "monitor",
    name: "L24i-40",
    brand: "Lenovo",
    tagline: "23.8型FHD 100Hz・IPS・HDMI/VGA",
    price: 12800,
    rating: 4.5,
    reviews: 176,
    image: "https://m.media-amazon.com/images/I/6164fgzVq2L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DF83VJV6",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","port-hdmi","refresh-100","res-fhd","vesa-100","panel-ips"],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8 インチ" },
          { label: "解像度", value: "1920 x 1080 (FHD)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #44" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "43.4 × 18.3 × 53.9 cm" },
          { label: "重量", value: "3.84 kg" }]}],
  },
    {
    id: "mon-bs-047",
    category: "monitor",
    name: "AW2725Q",
    brand: "Dell",
    tagline: "Dell AW2725Q 26.7インチ 有機EL Alienware ゲーミングモニター無輝点3年保証/4K/QD-OLED抗反射/DPx1,HDMIx2/DCI-P3 95%/縦横回転,高さ調整/0.03ms,240Hz/Free-Sync Premium Pro,VESA DisplayHDR True Black 400",
    price: 74580,
    rating: 4.3,
    reviews: 108,
    image: "https://m.media-amazon.com/images/I/71jeWSQcpRL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI / USB-A　対応 / USB-B / 対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F23DY221",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-144-plus","refresh-240-plus","port-hdmi","port-usb-c","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "26.7\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "QD-OLED" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "26.7\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "QD-OLED" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #47" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "61 × 51.6 × 21 cm" },
          { label: "重量", value: "6.79 kg" }]}],
  },
  {
    id: "mon-bs-048",
    category: "monitor",
    name: "Pixio モバイルモニター PX160Wave",
    brand: "cocopar",
    tagline: "ブラック 15.6インチ Type-C ミニHDMI 60Hz モバイル ディスプレイ 黒 ピクシオモバイルディスプレイ ポータブルモニター サブモニター pcモニター ゲームモニター monitor gaming 15.6inch black display ぴくしお ps5 switch2 ゲーミングpc モニター台 IPS HDR 軽量",
    price: 12595,
    rating: 4.1,
    reviews: 67,
    image: "https://m.media-amazon.com/images/I/61nxsxhxGGL._AC_SL1500_.jpg",
    connection: "Mini HDMI / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DPKL9R3Q",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #48" }]},
      { title: "接続端子", rows: [
          { label: "Mini HDMI", value: "対応" },
          { label: "USB Type-C", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "35.7 × 22.5 × 1 cm" },
          { label: "重量", value: "0.7 5kg" }]}],
  },
  {
    id: "mon-bs-049",
    category: "monitor",
    name: "IODATA GigaCrysta EX-GD242UDB",
    brand: "IODATA",
    tagline: "IODATA ゲーミングモニター 23.8インチ GigaCrysta 240Hz ADSパネル 1ms シャドウブラック 無輝点保証対応(HDMI×2/DisplayPort/VESA対応/土日サポート/日本メーカー)",
    price: 21800,
    rating: 4.3,
    reviews: 291,
    image: "https://m.media-amazon.com/images/I/710tB8ZGudL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-A　対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DQKY19KV",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","panel-ads"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "ADS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "ADS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #49" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" }]},      { title: "本体", rows: [
          { label: "寸法", value: "54 × 41.8 × 21.5 cm" },
          { label: "重量", value: "4.5kg" }]}],
  },
  {
    id: "mon-bs-050",
    category: "monitor",
    name: "Amazonベーシック 23.8インチ モニター",
    brand: "Amazonベーシック",
    tagline: "120 Hz FHD 1080p HDMI DP VGA VESA対応 オフィス 家庭用 60.5cm ブラック ディスプレイ",
    price: 11615,
    rating: 4.4,
    reviews: 57,
    image: "https://m.media-amazon.com/images/I/71pSRyYnDIL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DZ5BRBZ7",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon売れ筋", value: "PCモニター #50" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "5.04Kg" }]}],
  },
]
