import type { Gadget } from "./gadgets"

/** Amazon.co.jp Lenovo ディスプレイ検索（26インチ以上 / Lenovo）。 */
export const monitorLenovoSearch26Plus: Gadget[] = [{
    id: "mon-lenovo-26-002",
    category: "monitor",
    name: "Lenovo Legion 27Q-15",
    brand: "Lenovo",
    tagline: "27インチ/QHD/Fast IPS/240Hz/1ms(GtG)/HDMI2.1x2, DP1.4x1/HDR10/AMD FreeSync™ Premium/縦横回転,高さ調整/日本国内5年保証",
    price: 25800,
    rating: 4.6,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/71FiXbzdoQL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G64CW3LL",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #2" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1 ×2", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 53.7 × 21.4 cm" },
          { label: "重量", value: "3.8kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-003",
    category: "monitor",
    name: "Lenovo L27-41",
    brand: "Lenovo",
    tagline: "Lenovo L27-41 Monitor, 27-Inch, Full HD/IPS Panel/HDMI 1.4 x 1, VGA/Tilt Adjustm",
    price: 12980,
    rating: 4.5,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/61IFEULXkjL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G42Z3577",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #3" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 44.4 × 21 cm" },
          { label: "重量", value: "3.7Kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-004",
    category: "monitor",
    name: "Lenovo Legion Pro 27Q-15",
    brand: "Lenovo",
    tagline: "26.5インチ/QHD/QD-OLEDパネル/280hz/0.03ms(GtG)/DisplayHDR™ True Black 400/DCI-P3 99%/AMD FreeSync™ Premium Pro/縦横回転,高さ調整/日本国内5年保証",
    price: 56800,
    rating: 4.3,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/71YcGs7B6vL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G64DFTWR",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "26.5\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "280Hz" },
      { label: "パネル", value: "OLED" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "26.5\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "OLED" },
          { label: "リフレッシュレート", value: "280Hz" },
          { label: "Amazon検索", value: "PCモニター #4" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61 × 52.3 × 20.3 cm" },
          { label: "重量", value: "4.1Kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-005",
    category: "monitor",
    name: "Legion R27s",
    brand: "Lenovo",
    tagline: "27インチ/フルHD/IPSパネル/144Hz/1ms (MPRT)/HDMI2.1x1, DP1.2x1/VESA Media Sync/チルト対応/日本国内3年保証",
    price: 15800,
    rating: 3.6,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/714K9-UYlcL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G41B5K4R",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #5" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 44.6 × 20.5 cm" },
          { label: "重量", value: "3.7 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-006",
    category: "monitor",
    name: "Lenovo ThinkVision T32p-30",
    brand: "Lenovo",
    tagline: "31.5インチ UHD(4K)【100%sRGB / 95%DCI-P3 / Type-C 90W給電対応】 IPS液晶 非光沢 VESA対応 USB 3.2 HDMI DP Type-Ax4",
    price: 55931,
    rating: 4.7,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/61S5eRhhtfL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLML3M6",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "32\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "32\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #6" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 60 × 23.5 cm" },
          { label: "重量", value: "5.1kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-007",
    category: "monitor",
    name: "Lenovo Y27f-30 モニター",
    brand: "Lenovo",
    tagline: "27.0インチ IPS WLED液晶 FHD 240Hz 0.5ms 非光沢 チルト対応 VESA",
    price: 22190,
    rating: 3.9,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/71mYrP2UsXL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CVMRMJVY",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #7" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 53.7 × 25.9 cm" },
          { label: "重量", value: "4.4 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-008",
    category: "monitor",
    name: "Lenovo L32p-30",
    brand: "Lenovo",
    tagline: "31.5インチ Lenovo L32p-30 (66C9UAC1JP)【31.5型ワイド UHD IPS WLED液晶モニター】【3年保証】",
    price: 44980,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71qQ3dtho7L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CVNCWGQ8",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #8" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 52.3 × 20.7 cm" },
          { label: "重量", value: "4.95Kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-010",
    category: "monitor",
    name: "Lenovo ゲーミングモニター R27i-30",
    brand: "Lenovo",
    tagline: "27.0インチ IPS WLED液晶 FHD 165Hz 0.5ms 非光沢 チルト対応 VESA",
    price: 23998,
    rating: 3.6,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/71Neue-e2kL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DBVB6G53",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #10" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 52.7 × 25.9 cm" },
          { label: "重量", value: "4.3 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-011",
    category: "monitor",
    name: "Lenovo ゲーミングモニター Legion 27U-15",
    brand: "Lenovo",
    tagline: "27インチ/デュアル解像度(フルHD/4K)/Fast IPSパネル/320Hz(フルHD),160Hz(4K)/1ms(GtG)/HDMI2.1x2, DP1.4x1/HDR10/DCI-P3 95%/NVIDIA® G-SYNC® Compatible/縦横回転,高さ調整/日本国内5年保証",
    price: 42800,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/71879HIIt0L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G633NVHW",
    monitorFilterTags: ["size-27","res-4k","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "160Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "160Hz" },
          { label: "Amazon検索", value: "PCモニター #11" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 52.9 × 21.4 cm" },
          { label: "重量", value: "4.3 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-012",
    category: "monitor",
    name: "Lenovo ゲーミングモニター R27q-30",
    brand: "Lenovo",
    tagline: "27.0インチ IPS WLED液晶 QHD 165Hz 0.5ms 非光沢 チルト対応 VESA",
    price: 35354,
    rating: 3.5,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/71oBTGV3GtL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DBV5MZ62",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #12" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 52.7 × 25.9 cm" },
          { label: "重量", value: "3.9 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-013",
    category: "monitor",
    name: "Lenovo ThinkVision E27q-40",
    brand: "Lenovo",
    tagline: "27型 QHD 非光沢 IPS HDMI DisplayPort チルト スイベル ピボット 高さ調節 Vesa 内蔵スピーカー 3 ブラック",
    price: 31790,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51jCojHxlqL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZ333LB5",
    monitorFilterTags: ["size-27","res-wqhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #13" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 53.9 × 22 cm" },
          { label: "重量", value: "4.0Kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-014",
    category: "monitor",
    name: "Lenovo L27-4e モニター",
    brand: "Lenovo",
    tagline: "27インチ フラット IPS FullHD ディスプレイ - 100Hz リフレッシュレート - 4ms 応答時間 - HDMI 1.4 - VGA - チルトスタンド",
    price: 30391,
    rating: 4.9,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/71F00DzOAlL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FTVB3V15",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #14" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 44.3 × 21 cm" },
          { label: "重量", value: "4.08 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-016",
    category: "monitor",
    name: "27インチ フラット IPS FullHD ディスプレイ - 100Hz リフレッシュレート - 4ms 応答時間 - HDMI 1.4 - VGA - チルトスタンド",
    brand: "Lenovo",
    tagline: "Lenovo Japan ThinkVision E27q-20 62D0GAR1JP",
    price: 28427,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51l3jXwOhvL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLJB8BG",
    monitorFilterTags: ["size-27","refresh-100","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #16" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },{
    id: "mon-lenovo-26-019",
    category: "monitor",
    name: "Lenovo L27q-4a",
    brand: "Lenovo",
    tagline: "27インチ QHD IPS ディスプレイ - 100Hz リフレッシュレート - MaxxAudio チューニングスピーカー - VESA MediaSync - 1ms MPRT",
    price: 47985,
    rating: 4.3,
    reviews: 65,
    image: "https://m.media-amazon.com/images/I/61YXDZPmMDL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DJTXKX7P",
    monitorFilterTags: ["size-27","res-wqhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #19" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 57.2 × 19.6 cm" },
          { label: "重量", value: "5.64 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-020",
    category: "monitor",
    name: "Lenovo Legion LOQ 32Q-10",
    brand: "Lenovo",
    tagline: "ゲーミングモニター 80cm QHD フラット VA 180Hz 0.5ms MPRT AMD FreeSync HDR10 チルトスタンド HDMI 2.1 DP 1.4 2倍",
    price: 44968,
    rating: 4.3,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/71AXD-utWaL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZQND3TT",
    monitorFilterTags: ["size-315-plus","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "32\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "75×75 mm" },
          { label: "画面サイズ", value: "32\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #20" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 50.8 × 21.6 cm" },
          { label: "重量", value: "7.39 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-021",
    category: "monitor",
    name: "Lenovo ThinkVision P27q-30",
    brand: "Lenovo",
    tagline: "27インチ クラス WQHD LED モニター - 16:9",
    price: 97349,
    rating: 5,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/51GjLUYuIfL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BD65ZXG3",
    monitorFilterTags: ["size-27","res-wqhd","refresh-75","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #21" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 35.3 × 4.8 cm" },
          { label: "重量", value: "6.80 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-022",
    category: "monitor",
    name: "Japan ThinkVision P27u-20 62CBRAR6JP",
    brand: "Lenovo",
    tagline: "Lenovo Japan ThinkVision P27u-20 62CBRAR6JP",
    price: 102550,
    rating: 4,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/41wZImBbkWL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLG9CPD",
    monitorFilterTags: ["size-27","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #22" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-023",
    category: "monitor",
    name: "Lenovo Legion Y27h-30",
    brand: "Lenovo",
    tagline: "ゲームモニター - 27インチ QHDディスプレイ - オーバークロック180z リフレッシュレート 動脈ソフトウェア - AMD FreeSync プレミアム - 0.5ms MPRT",
    price: 52968,
    rating: 4,
    reviews: 34,
    image: "https://m.media-amazon.com/images/I/71Y+bF+HhWL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BN1YNVQR",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #23" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 53.6 × 25.9 cm" },
          { label: "重量", value: "4.54 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-024",
    category: "monitor",
    name: "Lenovo L27h-4A",
    brand: "Lenovo",
    tagline: "27インチ QHD IPSパネルディスプレイ、100Hz、HDR10、USB-C- Waves MaxxAudio、1ms MPRT",
    price: 91192,
    rating: 5,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/71npQBWJ5cL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DP1G8R18",
    monitorFilterTags: ["size-27","res-wqhd","refresh-100","port-usb-c","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #24" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 57.2 × 19.6 cm" },
          { label: "重量", value: "5.96 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-025",
    category: "monitor",
    name: "Lenovo ThinkVision T34WD-40",
    brand: "Lenovo",
    tagline: "34インチクラス UW-QHD カーブスクリーンLEDモニター - 21:9",
    price: 85623,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71WE2XODUXL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJ6SV9M6",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "VA　非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #25" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "80.5 × 35.6 × 11.4 cm" },
          { label: "重量", value: "6.40 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-026",
    category: "monitor",
    name: "Lenovo ThinkVision T27-40",
    brand: "Lenovo",
    tagline: "27インチクラスフルHD LEDモニター - 16:9",
    price: 48925,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61k-PVqS25L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJFNK7QC",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #26" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 35.6 × 4.6 cm" },
          { label: "重量", value: "4.40 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-027",
    category: "monitor",
    name: "Lenovo ThinkVision P27Q-40",
    brand: "—",
    tagline: "27 QHD 2560x1440 IPS ディスプレイ、アンチグレア、16:9 エクストリームモード 4ms 応答時間 最大120Hz リフレッシュレート 99 sRGB、99 BT.709、98 DCIP3、10bit 5~+23.5チルト、左右45回転、90~ +90P",
    price: 88133,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51-ZD93K0iL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FB9B5F3Y",
    monitorFilterTags: ["size-27","res-wqhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #27" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 35.8 × 4.6 cm" },
          { label: "重量", value: "4.30 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-028",
    category: "monitor",
    name: "Lenovo Legion 27QD-10",
    brand: "Lenovo",
    tagline: "ゲーミングモニター - 27インチ QHD IPSディスプレイ - 240Hz リフレッシュレート - 0.5ms MPRT - 99% sRGB - AMD FreeSync プレミアム",
    price: 57285,
    rating: 4.3,
    reviews: 29,
    image: "https://m.media-amazon.com/images/I/81IgFr9zKjL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FTVC78FT",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","port-usb-c","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #28" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 52.9 × 21.4 cm" },
          { label: "重量", value: "5.58 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-029",
    category: "monitor",
    name: "Lenovo Legion R27q-30",
    brand: "Lenovo",
    tagline: "ゲーミングモニター 27インチ QHDディスプレイ 180Hz 0.5msレスポンス、AMD FreeSync Premium、リフト/チルト/ピボット/スイベルスタンド、HDMI 2.1およびDisplayPort 1.4、350nits",
    price: 73099,
    rating: 4,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/71RKTHvdd5L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGTK2RVK",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #29" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.1", value: "対応" },
          { label: "DisplayPort 1.4", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 39.2 × 25.9 cm" },
          { label: "重量", value: "5.81 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-031",
    category: "monitor",
    name: "Lenovo ThinkVision S27i-30",
    brand: "Lenovo",
    tagline: "27 フルHD LEDモニター - 16:9",
    price: 69095,
    rating: 4.4,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/61S59oFRPqL._AC_SL1500_.jpg",
    connection: "HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CH11GLR1",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #31" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 47.5 × 18.5 cm" },
          { label: "重量", value: "7.03 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-032",
    category: "monitor",
    name: "Lenovo L27q-4A モニター",
    brand: "Lenovo",
    tagline: "27.0インチ IPS WLED液晶 QHD 100Hz 1ms 非光沢 チルト対応 VESA",
    price: 87593,
    rating: 4.4,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/61EOOSqqJ6L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DCZBBD6M",
    monitorFilterTags: ["size-27","res-wqhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #32" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.3 × 57.2 × 19.6 cm" },
          { label: "重量", value: "3.91Kg" },
        ]},

    ],
  },{
    id: "mon-lenovo-26-034",
    category: "monitor",
    name: "Lenovo THINKVISION T22V",
    brand: "Lenovo",
    tagline: "21.5インチ 19X10 6MS CAM",
    price: 70167,
    rating: 4.1,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/51p-AsjlWYL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07988L39H",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #34" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "VGA (D-Sub)", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "5.49 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-035",
    category: "monitor",
    name: "Lenovo ThinkVision P27q-30",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P27q-30 27インチ WQHD LED モニター - スタンドなし - 3年保証",
    price: 76673,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/513TTEfRSFL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GR1RGFFZ",
    monitorFilterTags: ["size-27","res-wqhd","refresh-75","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #35" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 53.5 × 20.4 cm" },
          { label: "重量", value: "10.2Kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-036",
    category: "monitor",
    name: "Lenovo ThinkVision S27i-30",
    brand: "Lenovo",
    tagline: "1920x1080解像度、1300:1コントラスト比、アセットタグ付き",
    price: 63777,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/81h7gPzFnJL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G2BCLT3H",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #36" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "47.5 × 18.5 × 61.2 cm" },
          { label: "重量", value: "3.81 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-037",
    category: "monitor",
    name: "Lenovo G27-20 ゲーミングモニター",
    brand: "Lenovo",
    tagline: "27インチ ゲーミングモニター FHD (1920 x 1080) IPS 144Hz 1ms FreeSync Premium & NVIDIA G-SYNC 対応 ニアエッジレス VESAマウント 高さと傾き調整 HDMI DP",
    price: 78255,
    rating: 4,
    reviews: 46,
    image: "https://m.media-amazon.com/images/I/61sCKLtlnqL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08Z5JNL1C",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","port-hdmi","port-dp","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #37" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-038",
    category: "monitor",
    name: "Lenovo ThinkVision T27i-30",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T27i-30 27インチクラスフルHD LEDモニター - 16:9",
    price: 61109,
    rating: 3.8,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/51y66gZP+EL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CYHTK9JD",
    monitorFilterTags: ["size-27","res-fhd","refresh-75","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #38" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 36.3 × 5.1 cm" },
          { label: "重量", value: "4.90 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-039",
    category: "monitor",
    name: "Lenovo Legion Y32p-30",
    brand: "Lenovo",
    tagline: "ゲームモニター - 31.5インチ UHD IPS ディスプレイ - 144Hz - DisplayHDR 400 - AMD FreeSync Premium - 0.2ms MPRT",
    price: 130397,
    rating: 4,
    reviews: 34,
    image: "https://m.media-amazon.com/images/I/71tXjjyZGcL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CK5MBVBY",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #39" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.5 × 59.9 × 29.8 cm" },
          { label: "重量", value: "9.62 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-040",
    category: "monitor",
    name: "ThinkVision S27q-10 27\" QHD LED Backlight",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision S27q-10 27\" QHD LED Backlight",
    price: 79354,
    rating: 1,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/51m1NLKFq9L._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09C885VBG",
    monitorFilterTags: ["size-27","res-wqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #40" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "6.35 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-041",
    category: "monitor",
    name: "Lenovo Legion Y27h-30",
    brand: "Lenovo",
    tagline: "QHD IPS WLEDゲーミング液晶 ノングレア HDMI スピーカー搭載 3年保証",
    price: 32800,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61U8rh+l-dL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CVN36JXY",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #41" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 53.7 × 25.9 cm" },
          { label: "重量", value: "6.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-042",
    category: "monitor",
    name: "ThinkVision T32p-20",
    brand: "Lenovo",
    tagline: "T32P-20",
    price: 106394,
    rating: 3.5,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/61ojKRBdWzL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B085S89955",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #42" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "9.85 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-043",
    category: "monitor",
    name: "Lenovo Q27h-10",
    brand: "Lenovo",
    tagline: "QHD (2560 x 1440)、IPS、LEDバックライト、16:9、AMD FreeSync、USB-C、4サイドボーダーレス、75Hz、4ms応答時間、99%sRGB、チルト、HDMI、DP 1.2、ローブルーライト",
    price: 90412,
    rating: 4.4,
    reviews: 257,
    image: "https://m.media-amazon.com/images/I/61uy89WgofL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B08BDWNC8Q",
    monitorFilterTags: ["size-27","res-wqhd","refresh-75","port-hdmi","port-dp","port-usb-c","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #43" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "5.1 × 30.5 × 30.5 cm" },
          { label: "重量", value: "5.89 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-044",
    category: "monitor",
    name: "27IN QHD THINKVISION P27H-28",
    brand: "Lenovo",
    tagline: "Lenovo 27IN QHD THINKVISION P27H-28",
    price: 85627,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/51c6Ek6XfrL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09RVF4CGQ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["res-wqhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "—" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "—" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #45" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "9.25 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-045",
    category: "monitor",
    name: "Lenovo Legion R27fc-30",
    brand: "Lenovo",
    tagline: "LEDディスプレイ、フルHD、ブラック、1920 x 1080",
    price: 25800,
    rating: 4.6,
    reviews: 57,
    image: "https://m.media-amazon.com/images/I/71zi+MU8PaL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CLSSG57W",
    monitorFilterTags: ["size-27","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #46" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "30 × 30 × 30 cm" },
          { label: "重量", value: "6.2 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-26-046",
    category: "monitor",
    name: "ThinkVision P27u-20 - LED - 27\" (27\" Visible) - ",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision P27u-20 - LED Monitor - 27\" (27\" Visible) - 3840 x 2160 4K @ ",
    price: 124519,
    rating: 4,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61mnlPAALuL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09S6KWHFQ",
    monitorFilterTags: ["size-27","port-hdmi","port-dp","port-usb-c","refresh-60","res-4k","vesa-100","panel-ips"],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27 インチ" },
          { label: "解像度", value: "3840 x 2160 (4K UHD)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #47" },
        ]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 55.6 × 22 cm" },
          { label: "重量", value: "10.6 kg" },
        ]},

    ],
  }]
