import type { Gadget } from "./gadgets"

/** Amazon.co.jp Lenovo ディスプレイ検索（18.0～22.0インチ / Lenovo）。 */
export const monitorLenovoSearch1822: Gadget[] = [
  {
    id: "mon-lenovo-1822-002",
    category: "monitor",
    name: "ThinkVision E22-30",
    brand: "Lenovo",
    tagline: "21.5\" FHD IPS ビジネス",
    price: 16307,
    rating: 4.7,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/71EHJC7E5ML._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCFFLRHK",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #2" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "VGA (D-Sub)", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "48.9 × 47 × 17.9 cm" },
          { label: "重量", value: "5.8 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-005",
    category: "monitor",
    name: "ThinkVision E20-30",
    brand: "Lenovo",
    tagline: "19.5\" HD+ IPS",
    price: 20535,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/41PdBCBAJ+L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLJGD4V",
    monitorFilterTags: ["size-238","refresh-60","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "19.5\"" },
      { label: "解像度", value: "HD+" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "19.5\"" },
          { label: "解像度", value: "HD+" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #5" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA (D-Sub)", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-006",
    category: "monitor",
    name: "Lenovo L22-4e",
    brand: "Lenovo",
    tagline: "オフィスモニター - 21.5インチ FHD IPS ディスプレイ - 100Hz リフレッシュレート - 4 ms MPRT - 99% sRGB",
    price: 19169,
    rating: 4.3,
    reviews: 46,
    image: "https://m.media-amazon.com/images/I/71ayWwdCU-L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FPRGSK6J",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "—",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #6" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA (D-Sub)", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "48.9 × 37.9 × 17.4 cm" },
          { label: "重量", value: "2.81 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-009",
    category: "monitor",
    name: "ThinkVision E22-30 22\" Class Full HD LED - 16:9",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision E22-30 22\" Class Full HD LED Monitor - 16:9 - Raven Black",
    price: 27195,
    rating: 4.8,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/615VAUd82lL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D4F6H377",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "22\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "22\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #9" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "48.8 × 29.5 × 4.6 cm" },
          { label: "重量", value: "2.70 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-010",
    category: "monitor",
    name: "L22e-40 - Everyday - 21.4\" FHD Display - 75Hz -",
    brand: "Lenovo",
    tagline: "Lenovo L22e-40 - Everyday Monitor - 21.4\" FHD Display - 75Hz - 4ms-16ms Response",
    price: 38609,
    rating: 4.7,
    reviews: 45,
    image: "https://m.media-amazon.com/images/I/71o6chf4O5L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGT1SGKG",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-75"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "75×75 mm",
    highlights: [
      { label: "画面サイズ", value: "21.4\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.4\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #10" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "43.5 × 61.6 × 18.3 cm" },
          { label: "重量", value: "4.40 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-011",
    category: "monitor",
    name: "ThinkVision T22i-30",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T22i-30 22\" Class Full HD LED Monitor - 16:9 - Raven Black",
    price: 36982,
    rating: 3.8,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/71s63XijwmL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / VGA / USB",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FYPJVF6S",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #11" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "VGA (D-Sub)", value: "対応" },
          { label: "USB", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49 × 29.5 × 4.6 cm" },
          { label: "重量", value: "6.89 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-012",
    category: "monitor",
    name: "54.6cm/21.5inch (1920x1080) Lenovo ThinkVision T",
    brand: "—",
    tagline: "54.6cm/21.5inch (1920x1080) Lenovo ThinkVision T22i-30 16:9 FHD IPS 60Hz 4ms HDM",
    price: 44506,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51Qz0y7YY-L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0B7PFTXZV",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #12" },
        ]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.12 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-013",
    category: "monitor",
    name: "ThinkVision T22i-30 21.5 Full HD WLED LCD - 16:9",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T22i-30 21.5 Full HD WLED LCD Monitor - 16:9 - Raven Black",
    price: 43916,
    rating: 3.9,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/61r24cBG3wL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C1T7LJBB",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #13" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "38.1 × 50.8 × 55.9 cm" },
          { label: "重量", value: "6.80 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-016",
    category: "monitor",
    name: "Japan ThinkVision T22i-30 63B0MAR6JP",
    brand: "Lenovo",
    tagline: "Lenovo Japan ThinkVision T22i-30 63B0MAR6JP",
    price: 28767,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/318PIoIiUNL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGLJH51T",
    monitorFilterTags: ["size-238","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #16" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-017",
    category: "monitor",
    name: "ThinkVision TIO22 Gen5",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision TIO22Gen5 22インチクラス ウェブカメラ フルHD LEDモニター - 16:9 - ブラック",
    price: 25219,
    rating: 3,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/41uyU+4D9RL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FXX8SMD2",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #17" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49 × 34 × 7.4 cm" },
          { label: "重量", value: "8.07 kg" },
        ]},

    ],
  },
      {
    id: "mon-lenovo-1822-020",
    category: "monitor",
    name: "ThinkVision T22i-30 22インチクラスフルHD LED - 16:9 - レイ",
    brand: "Lenovo",
    tagline: "Lenovo ThinkVision T22i-30 22インチクラスフルHD LEDモニター - 16:9 - レイヴンブラック",
    price: 39839,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/41WjOwK3muL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GH2PMX77",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "22\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "22\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #20" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "49 × 29.5 × 4.6 cm" },
          { label: "重量", value: "3 kg" },
        ]},

    ],
  },
    {
    id: "mon-lenovo-1822-022",
    category: "monitor",
    name: "ThinkVision S22-4e 21.5\"",
    brand: "—",
    tagline: "ThinkVision S22-4e 21.5\" Monitor",
    price: 44453,
    rating: 3.4,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/61FjzjFb3aL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FY3H12G6",
    monitorFilterTags: ["size-238","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #22" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "35.3 × 11.7 × 56.1 cm" },
          { label: "重量", value: "2.50 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-024",
    category: "monitor",
    name: "ThinkCentre Tiny-in-One 22 Gen 5 21.5\" 16:9 Full",
    brand: "Lenovo",
    tagline: "Lenovo ThinkCentre Tiny-in-One 22 Gen 5 21.5\" 16:9 Full HD Touchscreen IPS WLED",
    price: 83465,
    rating: 3,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/51nnPbVSAEL._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CLD4KTNJ",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #24" },
        ]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "12.7 × 38.1 × 55.9 cm" },
          { label: "重量", value: "5.99 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-025",
    category: "monitor",
    name: "20.1IN LCD 700:1 1600X1200 60HZ Thinkvision L201",
    brand: "—",
    tagline: "20.1IN LCD 700:1 1600X1200 60HZ Thinkvision L201P Black VGA Dvi",
    price: 96687,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/21SqmWvxeaL._AC_SL1500_.jpg",
    connection: "VGA / DVI-D",
    purchaseUrl: "https://www.amazon.co.jp/dp/B000E43DLK",
    monitorFilterTags: ["size-238","refresh-60","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "20.1\"" },
      { label: "解像度", value: "—" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "VESA", value: "100×100 mm" },
          { label: "画面サイズ", value: "20.1\"" },
          { label: "解像度", value: "—" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #25" },
        ]},
      { title: "接続端子", rows: [
          { label: "VGA", value: "対応" },
          { label: "DVI-D", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "11.34 kg" },
        ]},

    ],
  },
  {
    id: "mon-lenovo-1822-027",
    category: "monitor",
    name: "L22e-40 , 21.5\" Full HD Resolution, 250nits Brig",
    brand: "Lenovo",
    tagline: "Lenovo L22e-40 Monitor, 21.5\" Full HD Resolution, 250nits Brightness, 75Hz Refre",
    price: 19169,
    rating: 4.5,
    reviews: 107,
    image: "https://m.media-amazon.com/images/I/71ZPu8-MrPL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGSSNBGH",
    monitorFilterTags: ["size-238","res-fhd","refresh-75","port-hdmi","vesa-100"],
    monitorSpreadsheetLTags: [],
    vesaStandard: "100×100 mm",
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #27" },
        ]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" },
        ]},
      { title: "本体", rows: [
          { label: "寸法", value: "40.2 × 49.1 × 18.3 cm" },
          { label: "重量", value: "3.80 kg" },
        ]},

    ],
  },
]
