import type { Gadget } from "./gadgets"

/** Amazon.co.jp Dell モニター検索（2151982051 / Dell）。 */
export const monitorDellSearch: Gadget[] = [
  {
    id: "mon-dell-001",
    category: "monitor",
    name: "P2219H",
    brand: "Dell",
    tagline: "P series P2219H [プロフェッショナルシリーズ 21.5インチワイドモニタ",
    price: 29800,
    rating: 4.5,
    reviews: 1097,
    image: "https://m.media-amazon.com/images/I/71gRa1I86ZL._AC_SL1500_.jpg",
    connection: "VGA / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07F8Z2WFL",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #1" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "48.7 × 47.2 × 16.6 cm" },
          { label: "重量", value: "2.77 kg" }]}],
  },
    {
    id: "mon-dell-010",
    category: "monitor",
    name: "Dell 液晶ディスプレイ E2425HSM",
    brand: "Dell",
    tagline: "23.8型/1920×1080/HDMI、DisplayPort、VGA/ブラック/スピーカー：あり",
    price: 15598,
    rating: 4.3,
    reviews: 66,
    image: "https://m.media-amazon.com/images/I/51ha0slRNfL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F4PDMS9G",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #10" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 48.6 × 2.1 cm" },
          { label: "重量", value: "2.81Kg" }]}],
  },
  {
    id: "mon-dell-011",
    category: "monitor",
    name: "Dell Alienware AW3426DWM　曲面",
    brand: "Dell",
    tagline: "34インチ曲面 ゲーミングモニター無輝点3年保証/WQHD/VA,非光沢,1500R曲面/HDMIx2,DP1.4x1/DCI-P3 95%/高さ調整,傾き/1ms,240Hz/FreeSync Premium,DisplayHDR 400",
    price: 54980,
    rating: 4.6,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/61E-8LGCjeL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6J2QR7N",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #11" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "6.78 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "80.5 × 55.5 × 23.3 cm" },
          { label: "重量", value: "6.78 kg" }]}],
  },
  {
    id: "mon-dell-012",
    category: "monitor",
    name: "Dell AW3225DM-A 31.5インチ 曲面",
    brand: "Dell",
    tagline: "Alienware ゲーミングモニター無輝点5年保証/QHD/VA非光沢,1500R曲面/DP1.4x1,HDMI2.1x2/DCI-P3 95%/高さ調整,傾き/1ms,180Hz(DP),144Hz(HDMI)",
    price: 34980,
    rating: 3.7,
    reviews: 11,
    image: "https://m.media-amazon.com/images/I/71ed01WGG9L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F23FHHRK",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: ["曲面"],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #12" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "9.75Kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "70.7 × 58.3 × 23.2 cm" },
          { label: "重量", value: "9.75Kg" }]}],
  },
  {
    id: "mon-dell-014",
    category: "monitor",
    name: "Dell 液晶ディスプレイ E2425HM",
    brand: "Dell",
    tagline: "23.8型/1920×1080/HDMI、DisplayPort、VGA/ブラック/スピーカー：なし",
    price: 13370,
    rating: 4.3,
    reviews: 91,
    image: "https://m.media-amazon.com/images/I/51HVJeQhQ-L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F4PFD9LX",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #14" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.2 × 1.7 cm" },
          { label: "重量", value: "2.81Kg" }]}],
  },
  {
    id: "mon-dell-015",
    category: "monitor",
    name: "Dell 液晶ディスプレイ U3225QE",
    brand: "Dell",
    tagline: "31.5型/3840×2160/HDMI、DisplayPort、USB-C/シルバー/スピーカー：なし",
    price: 128960,
    rating: 4.3,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/51kNEo5nIGL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI / Thunderbolt",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F4P9F74G",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-4k","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #15" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "71.4 × 55.1 × 2.4 cm" },
          { label: "重量", value: "5.43 kg" }]}],
  },
  {
    id: "mon-dell-017",
    category: "monitor",
    name: "Dell AW2726DM 26.5インチ",
    brand: "Dell",
    tagline: "有機EL Alienware ゲーミングモニター 無輝点3年保証/QHD/QD-OLED,抗反射/DP 1.4×1,HDMI×2/DCI-P3 99%/縦横回転,高さ調整/0.03ms,240Hz(DP),120Hz(HDMI)/AMD FreeSync Premium",
    price: 64980,
    rating: 4.3,
    reviews: 129,
    image: "https://m.media-amazon.com/images/I/71P1cQhGHCL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / USB-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GR9F5TNY",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "26.5\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "OLED" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "26.5\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "OLED" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #17" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.3 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "60.9 × 52.3 × 23.3 cm" },
          { label: "重量", value: "4.3 kg" }]}],
  },
  {
    id: "mon-dell-018",
    category: "monitor",
    name: "Dell 液晶ディスプレイ E2225HSM",
    brand: "Dell",
    tagline: "21.5型/1920×1080/HDMI、DisplayPort、VGA/ブラック/スピーカー：あり",
    price: 13267,
    rating: 4.4,
    reviews: 47,
    image: "https://m.media-amazon.com/images/I/61NTTmk2OJL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F4PDQYKB",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-va"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #18" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.2 × 46.9 × 2.1 cm" },
          { label: "重量", value: "2.58Kg" }]}],
  },
  {
    id: "mon-dell-019",
    category: "monitor",
    name: "Dell 液晶ディスプレイ U2725QE",
    brand: "Dell",
    tagline: "27型/3840×2160/HDMI、DisplayPort、USB-C/シルバー/スピーカー：なし",
    price: 92980,
    rating: 3.6,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/41OvvuhpKzL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI / Thunderbolt",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F4P9D1L1",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #19" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 53.4 × 2 cm" },
          { label: "重量", value: "4.49Kg" }]}],
  },
  {
    id: "mon-dell-021",
    category: "monitor",
    name: "Dell 23.8インチタッチモニター P2424HT",
    brand: "Dell",
    tagline: "23.8型/1920×1080/HDMI、DisplayPort、USB-C/ブラック/スピーカー：あり タッチパネル",
    price: 46999,
    rating: 3.8,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61NG-KccR5L._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DH4G2TWF",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #21" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 32.1 × 2.5 cm" },
          { label: "重量", value: "3.86Kg" }]}],
  },
  {
    id: "mon-dell-022",
    category: "monitor",
    name: "Dell 液晶ディスプレイ E2225HM",
    brand: "Dell",
    tagline: "21.5型/1920×1080/HDMI、DisplayPort、VGA/ブラック/スピーカー：なし",
    price: 11366,
    rating: 3.9,
    reviews: 33,
    image: "https://m.media-amazon.com/images/I/61UNmChzS5L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F4PDLB7J",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #22" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.2 × 37.7 × 1.7 cm" },
          { label: "重量", value: "2.58Kg" }]}],
  },
  {
    id: "mon-dell-023",
    category: "monitor",
    name: "DELL-P2425HE",
    brand: "Dell",
    tagline: "Dell P2425HE 23.8-inch USB-C Hub Monitor / 1920×1080 / HDMI, DisplayPort, USB-C",
    price: 37598,
    rating: 4.3,
    reviews: 214,
    image: "https://m.media-amazon.com/images/I/71H2AvEWTYL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D1CT7ZW4",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-100","port-hdmi","port-dp","port-usb-c","vesa-100"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "100Hz" },
      { label: "パネル", value: "—" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "100Hz" },
          { label: "Amazon検索", value: "PCモニター #23" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.2 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 36.4 × 18.2 cm" },
          { label: "重量", value: "4.2 kg" }]}],
  }]
