import type { Gadget } from "./gadgets"

/** Amazon.co.jp ASUS モニター検索・人気ランキング（2151982051 / ASUS）。 */
export const monitorAsusSearch: Gadget[] = [{
    id: "mon-asus-003",
    category: "monitor",
    name: "XG259CMS",
    brand: "ASUS",
    tagline: "ASUS ゲーミングモニター ROG Strix XG259CMS 24.5インチ / HDR / 310Hz / 1ms (GTG) / Fast IPS/Extreme Low Motion Blur Sync/USB Type-C/G-Sync対応",
    price: 36800,
    rating: 4.2,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/71WgxfjK38L._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09TDSC9WS",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "310Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "310Hz" },
          { label: "Amazon検索", value: "PCモニター #3" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "3.42Kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.8 × 49.2 × 21.8 cm" },
          { label: "重量", value: "3.42Kg" }]}],
  },
  {
    id: "mon-asus-004",
    category: "monitor",
    name: "ASUS 4K モニター ProArt PA279CRV-J",
    brand: "ASUS",
    tagline: "IPS/HDMI/DisplayPort/USB Type-C(96W給電) / 99% DCI-P3 / 99% Adobe RGB/色精度ΔE < 2 / VESA DisplayHDR 400 / エルゴノミクススタンド/国内正規品",
    price: 65800,
    rating: 3.5,
    reviews: 61,
    image: "https://m.media-amazon.com/images/I/813B6KjWmlL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort / USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B086ZSRRDB",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #4" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "USB Type-C", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.07Kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.2 × 53.8 × 21.5 cm" },
          { label: "重量", value: "4.07Kg" }]}],
  },
  {
    id: "mon-asus-005",
    category: "monitor",
    name: "ASUS Eye Care VA329HE-J",
    brand: "ASUS",
    tagline: "ASUS モニター Eye Care VA329HE-J 31.5インチ / フルHD (1920 x 1080) / IPS / HDMIx2 / 75Hz / ブルーライト軽減/フリッカフリー/VESA対応 / 4年保証",
    price: 24280,
    rating: 4.1,
    reviews: 83,
    image: "https://m.media-amazon.com/images/I/71LeL2ZyntL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B07MDV2L3S",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-fhd","refresh-75","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #5" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "7.1 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "72.7 × 48 × 20.2 cm" },
          { label: "重量", value: "7.1 kg" }]}],
  },
  {
    id: "mon-asus-006",
    category: "monitor",
    name: "ASUS TUF Gaming VG34VQL3A",
    brand: "ASUS",
    tagline: "ASUS ゲーミングモニター TUF Gaming VG34VQL3A 34インチ/180Hz/WQHD/1ms/Freesync Premium Pro",
    price: 46000,
    rating: 4.3,
    reviews: 77,
    image: "https://m.media-amazon.com/images/I/71QTohvgVhL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort 対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D2948FZD",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-uwqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "34\"" },
      { label: "解像度", value: "UWQHD (3440×1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "VA 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "34\"" },
          { label: "解像度", value: "UWQHD (3440×1440)" },
          { label: "パネル", value: "VA 非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #6" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "8.1 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "80.8 × 54.1 × 25 cm" },
          { label: "重量", value: "8.1 kg" }]}],
  },
  {
    id: "mon-asus-007",
    category: "monitor",
    name: "ASUS ROG Strix OLED XG27AQDMES-J",
    brand: "ASUS",
    tagline: "27インチ ゲーミングモニター 240hz WQHD（2560x1440） OLED 0.03ms 有機EL 3年保証",
    price: 73535,
    rating: 3.6,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/91fgUa-f+rL._AC_SL1500_.jpg",
    connection: "HDMI / DisplayPort 対応",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09BLF98K2",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "OLED" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "OLED" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #7" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.9 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.1 × 50.3 × 18.8 cm" },
          { label: "重量", value: "4.9 kg" }]}],
  },
    {
    id: "mon-asus-009",
    category: "monitor",
    name: "ASUS 有機EL ゲーミングモニター ROG Strix OLED XG27AQDMG (26.5イン",
    brand: "ASUS",
    tagline: "/2560x1440/WOLED 有機EL/240Hz/0.03ms(GTG)/99% DCI-P3/DisplayPort 1.4/HDMI/国内正規品)",
    price: 68000,
    rating: 4.4,
    reviews: 47,
    image: "https://m.media-amazon.com/images/I/91JZfPPJquL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B09TKJQHLQ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "26.5\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "OLED" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "26.5\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "OLED" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #9" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "3.8Kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "60.5 × 50.8 × 21.9 cm" },
          { label: "重量", value: "3.8Kg" }]}],
  },
  {
    id: "mon-asus-011",
    category: "monitor",
    name: "PA278CV",
    brand: "ASUS",
    tagline: "ASUS モニター ProArt PA278CV 27インチ/3年間無輝点交換保証/WQHD/IPS/USB Type-C DisplayPortデイジーチェーン HDMI/100% sRGB/100% Rec. 709/ΔE<2",
    price: 49209,
    rating: 4.2,
    reviews: 35,
    image: "https://m.media-amazon.com/images/I/81LL6ybSGOL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0921CPSNX",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-75","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "75Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "75Hz" },
          { label: "Amazon検索", value: "PCモニター #11" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "5.5 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.5 × 52.4 × 22.8 cm" },
          { label: "重量", value: "5.5 kg" }]}],
  },
  {
    id: "mon-asus-013",
    category: "monitor",
    name: "PG27AQWP-G",
    brand: "ASUS",
    tagline: "ASUS ROG Swift 27インチ エディション 20 OLED ゲーミングモニター (PG27AQWP-G) 26.5インチ QHD WOLED デュアルモード (QHD@540Hz、HD@720Hz)、0.02ms 99.5% DCI-P3色域 TrueBlack 光沢",
    price: 220469,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71-AxNYa3eL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3Z2PZNF",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-wqhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "540Hz" },
      { label: "パネル", value: "OLED" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "OLED" },
          { label: "リフレッシュレート", value: "540Hz" },
          { label: "Amazon検索", value: "PCモニター #13" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "60.5 × 54.6 × 27.2 cm" },
          { label: "重量", value: "3.8Kg" }]}],
  },
  {
    id: "mon-asus-014",
    category: "monitor",
    name: "ASUS ゲーミングモニター/TUF Gaming シリーズ 5 -VG249QML5A",
    brand: "ASUS",
    tagline: "23.8インチ/フルHD/Fast-IPSパネル/240Hz/0.3ms/G-SYNC対応/AMD FreeSync Premium/ELMB SYNC/99% sRGB/高さ調整可能/DisplayWidget Center/Gaming AI/国内正規品",
    price: 24364,
    rating: 4.8,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71K3gAcUA-L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G4D34W46",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #14" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "その他", rows: [
          { label: "重量", value: "4.9 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 52.5 × 20.5 cm" },
          { label: "重量", value: "4.9 kg" }]}],
  },
  {
    id: "mon-asus-015",
    category: "monitor",
    name: "ASUS ROG Swift OLED PG27UCDM",
    brand: "ASUS",
    tagline: "27インチ / 4K 第4世代量子ドット有機ELパネル / 240Hz / 0.03ms / OLED Anti-Flicker/G-SYNC対応/VESA DisplayHDR 400 True Black/DisplayPort 2.1a UHBR20 / USB-C/HDMI 2.1",
    price: 178000,
    rating: 4.2,
    reviews: 46,
    image: "https://m.media-amazon.com/images/I/91ZHpCIh8vL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DVBFRTJG",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","port-usb-c","vesa-100","panel-oled"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "26.5\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "OLED　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "26.5\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "OLED　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #15" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "7.62 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61 × 55 × 21.9 cm" },
          { label: "重量", value: "7.62 kg" }]}],
  },
  {
    id: "mon-asus-016",
    category: "monitor",
    name: "ASUS 6K モニター ProArt PA32QCV",
    brand: "ASUS",
    tagline: "31.5インチ / 【DGPイメージングアワード2025 金賞】 / IPS/HDMI/DisplayPort/Thunderbolt 4(96W給電) / Auto KVM / 98% DCI-P3 / 色精度 ΔE < 2 / VESA DisplayHDR 600",
    price: 163455,
    rating: 4.2,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/811Vyb2oSQL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI / Thunderbolt",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FQC2YS28",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-315-plus","res-6k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "31.5\"" },
      { label: "解像度", value: "6K（6016 x 3384）" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "31.5\"" },
          { label: "解像度", value: "6K（6016 x 3384）" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #16" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "9.3 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.8 × 71.4 × 24 cm" },
          { label: "重量", value: "9.3 kg" }]}],
  },
  {
    id: "mon-asus-017",
    category: "monitor",
    name: "MB16AHV",
    brand: "ASUS",
    tagline: "ASUS Portable Monitor ZenScreen MB16AHV 16-Inch (15.6-Inch Display) / Full HD (1",
    price: 25800,
    rating: 4.8,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/81NHkNCnf2L._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BRY53CZM",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-hdmi","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #17" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "0.9 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "35.8 × 1 × 22.5 cm" },
          { label: "重量", value: "0.9 kg" }]}],
  },
  {
    id: "mon-asus-019",
    category: "monitor",
    name: "MB166CR-J",
    brand: "ASUS",
    tagline: "ASUS ポータブルモニター ZenScreen MB166CR-J 16インチ(15.6インチ表示)/フルHD/IPS/USB Type-C/フリッカーフリー/ブルーライトフィルター/ノングレアパネル/360°キックスタンド/4年保証 / 国内正規品",
    price: 19800,
    rating: 4.4,
    reviews: 25,
    image: "https://m.media-amazon.com/images/I/51oBwol1koL._AC_SL1500_.jpg",
    connection: "USB Type-C",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D3GZXQ4Q",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-60","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "15.6\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "15.6\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #19" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "0.78 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "36 × 22.6 × 1.2 cm" },
          { label: "重量", value: "0.78 kg" }]}],
  },
    {
    id: "mon-asus-021",
    category: "monitor",
    name: "ASUSモニター / VA27UCPS",
    brand: "ASUS",
    tagline: "27インチ / 4K UHD (3840 x 2160) / IPSパネル / 99% sRGB/HDR-10 / USB-C 65W給電 / 高さ調整 縦横回転機能付き/ステレオスピーカー/フリッカーフリー/ブルーライトフィルター/エルゴノミクスデザイン/壁掛け対応/環境サスティナビリティ/国内正規品/5年保証",
    price: 45800,
    rating: 3.9,
    reviews: 77,
    image: "https://m.media-amazon.com/images/I/81HQF+IHPSL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F6XTTMNN",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-4k","refresh-60","port-hdmi","port-dp","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "4K (3840×2160)" },
      { label: "リフレッシュ", value: "60Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "4K (3840×2160)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "60Hz" },
          { label: "Amazon検索", value: "PCモニター #21" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" }]},
      { title: "その他", rows: [
          { label: "重量", value: "6.9 kg" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "61.4 × 52.3 × 22.4 cm" },
          { label: "重量", value: "6.9 kg" }]}],
  },
  {
    id: "mon-asus-022",
    category: "monitor",
    name: "VA279QGZ [27-inch]",
    brand: "ASUS",
    tagline: "ASUS VA279QGZ [27-inch]",
    price: 16470,
    rating: 4.4,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/41zxC8HRn2L._AC_SL1500_.jpg",
    connection: "—",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FJ19QDXL",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-27","res-fhd","refresh-100","vesa-100"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "27\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "—" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "27\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "—" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #22" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "—" }]}],
  }]
