import type { Gadget } from "./gadgets"

/** Amazon.co.jp コンピュータモニターアーム 新着（10351517051）。本体のみ。 */
export const monitorArmNewReleases: Gadget[] = [{
    id: "arm-nr-04",
    category: "monitor-arm",
    name: "Tasavzモニターアーム（USBハブ付・ブラック）",
    brand: "—",
    tagline: "モニターアーム USBハブ付き ガススプリング式 17-32インチ対応 耐荷重2-10kg 五軸回転 多角度調整 クランプ式/グロメット式 VESA規格対応 ケープル収納 （ブラック）",
    price: 3980,
    rating: 3.5,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/51MHdplBPmL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXFNLFQT",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #4" }]}],
  },
  {
    id: "arm-nr-05",
    category: "monitor-arm",
    name: "Pivotix シングル",
    brand: "—",
    tagline: "モニターアーム シングル Pivotix 17〜32インチ対応 2〜9kg耐荷重 VESA 75×75/100×100 機械式スプリング",
    price: 4980,
    rating: 4,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/61GPYp-wl2L._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6V4QTFQ",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #5" }]}],
  },
  {
    id: "arm-nr-06",
    category: "monitor-arm",
    name: "GH-AMDU1-BK",
    brand: "—",
    tagline: "グリーンハウス ウルトラワイドモニター対応モニターアーム 17-49インチ対応 耐荷重2-20kg ガス圧 4軸 ブラック GH-AMDU1-BK",
    price: 9998,
    rating: 4,
    reviews: 146,
    image: "https://m.media-amazon.com/images/I/61+ooSw6BrL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D1VCW8VW",
    highlights: [
      { label: "対応サイズ", value: "17〜49インチ" },
      { label: "耐荷重", value: "2.0〜20.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜49インチ" },
          { label: "耐荷重", value: "2.0〜20.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #6" }]}],
  },
  {
    id: "arm-nr-07",
    category: "monitor-arm",
    name: "DPAWSSA01BK",
    brand: "ELECOM",
    tagline: "エレコム モニターアーム シングル 1画面 13-32インチ対応 ガススプリング式 耐荷重2-10kg VESA規格対応 ブラック DPAWSSA01BK",
    price: 3480,
    rating: 4.4,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/511nSRHtYTL._AC_SL1500_.jpg",
    connection: "クランプ式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HBV2YL66",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #7" }]}],
  },
  {
    id: "arm-nr-08",
    category: "monitor-arm",
    name: "AS-MABG06D",
    brand: "—",
    tagline: "アーキス ガススプリング式 デュアル液晶モニターアーム 35インチ対応 耐荷重2-12kg ブラック AS-MABG06Dデュアルモニターでもデスクスペースが広々。ガススプリング式で前後・左右・上下あらゆる方向に対応",
    price: 9980,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61v5OxCUNVL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8Y1J4R7",
    highlights: [
      { label: "対応サイズ", value: "〜35インチ" },
      { label: "耐荷重", value: "2.0〜12.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜35インチ" },
          { label: "耐荷重", value: "2.0〜12.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #8" }]}],
  },{
    id: "arm-nr-10",
    category: "monitor-arm",
    name: "KR20Y",
    brand: "KOORUI",
    tagline: "KOORUI モニター アームシングル 17-32インチ VESA 耐荷重9kg ガススプリング式 ブラック KR20Yディスプレイ アーム クランプ式&グロメット式 多角度調節 ケーブル管理 monitor arm",
    price: 4280,
    rating: 4.4,
    reviews: 227,
    image: "https://m.media-amazon.com/images/I/614ElqPlQWL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H93JTYM5",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #10" }]}],
  },
  {
    id: "arm-nr-11",
    category: "monitor-arm",
    name: "WORLDLIFT モニターアーム 3画面",
    brand: "WORLDLIFT",
    tagline: "20～32インチ対応 水平調整 VESAスライド式 各耐荷重10kg PC液晶ディスプレイアーム トリプル グロメット式&クランプ式",
    price: 8499,
    rating: 4.6,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/619TJItkkTL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "トリプルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2TS23L7",
    highlights: [
      { label: "対応サイズ", value: "20〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "20〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "トリプル (3画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #11" }]}],
  },
  {
    id: "arm-nr-12",
    category: "monitor-arm",
    name: "monTEK モニターアームデュアル",
    brand: "monTEK",
    tagline: "13〜32インチ対応 耐荷重2〜9kg PCモニターアーム 2画面 ロングポール 上下 左右 多角度調節",
    price: 5999,
    rating: 4,
    reviews: 11,
    image: "https://m.media-amazon.com/images/I/719EzkgdiSL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GL6Y7F34",
    highlights: [
      { label: "対応サイズ", value: "13〜32インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜32インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "—" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #12" }]}],
  },
  {
    id: "arm-nr-14",
    category: "monitor-arm",
    name: "PS3S Wave",
    brand: "Pixio",
    tagline: "17〜32インチ対応・耐荷重9.0kg・ガススプリング式",
    price: 14980,
    rating: 4.8,
    reviews: 21,
    image: "https://m.media-amazon.com/images/I/41iGf2Lq87L._AC_SL1500_.jpg",
    connection: "クランプ式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HB9PNDMQ",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #14" }]}],
  },
  {
    id: "arm-nr-15",
    category: "monitor-arm",
    name: "HUANUO モニタースタンド",
    brand: "—",
    tagline: "HUANUO(ファーノー) モニターアーム 置き型 モニタースタンド 自立型 13~34インチ対応 耐荷重20kg 5段階高さ調整可能 卓上PCディスプレイスタンド 360度回転 テレビスタンド シングル 1画面",
    price: 2699,
    rating: 4.6,
    reviews: 20,
    image: "https://m.media-amazon.com/images/I/51N+wRiXiuL._AC_SL1500_.jpg",
    connection: "自立型",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXW6S3QG",
    highlights: [
      { label: "対応サイズ", value: "13〜34インチ" },
      { label: "耐荷重", value: "20.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "自立型" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "13〜34インチ" },
          { label: "耐荷重", value: "20.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "自立型" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #15" }]}],
  },
  {
    id: "arm-nr-19",
    category: "monitor-arm",
    name: "MA6S",
    brand: "FlexiSpot",
    tagline: "FLEXISPOT モニターアーム MA6S 17-35インチ 湾曲 耐荷重2-9kg ケーブル工具収納 黒 テンションインジケーター 5年保証付",
    price: 6280,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51B2S7vM5WL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H487TL29",
    highlights: [
      { label: "対応サイズ", value: "17〜35インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜35インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #19" }]}],
  },
  {
    id: "arm-nr-20",
    category: "monitor-arm",
    name: "MA6S",
    brand: "FlexiSpot",
    tagline: "FLEXISPOT モニターアーム MA6S 17-35インチ 湾曲 耐荷重2-9kg ケーブル工具収納 黒 テンションインジケーター 5年保証付",
    price: 6280,
    rating: 4.4,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/51WMh-7HYoL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXZS7YZC",
    highlights: [
      { label: "対応サイズ", value: "17〜35インチ" },
      { label: "耐荷重", value: "2.0〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜35インチ" },
          { label: "耐荷重", value: "2.0〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #20" }]}],
  },
  {
    id: "arm-nr-21",
    category: "monitor-arm",
    name: "MA6",
    brand: "FlexiSpot",
    tagline: "FLEXISPOT モニターアーム MA6 17-35インチ 湾曲最大39 耐荷重3-12kg 上部固定クランプ式 5年保証付 シングル 黒",
    price: 11080,
    rating: 4.3,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/51z0otVsXCL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GX3BX543",
    highlights: [
      { label: "対応サイズ", value: "17〜35インチ" },
      { label: "耐荷重", value: "3.0〜12.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜35インチ" },
          { label: "耐荷重", value: "3.0〜12.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #21" }]}],
  },{
    id: "arm-nr-23",
    category: "monitor-arm",
    name: "PEGZONE モニターアーム シングル",
    brand: "PEGZONE",
    tagline: "PEGZONE モニターアーム シングル 17-49インチ 耐荷重2-20kg クイック着脱VESA ガススプリング クランプ式 ホワイト",
    price: 8990,
    rating: 4.1,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/61YtokEhvKL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXVFB37R",
    highlights: [
      { label: "対応サイズ", value: "17〜49インチ" },
      { label: "耐荷重", value: "2.0〜20.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜49インチ" },
          { label: "耐荷重", value: "2.0〜20.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #23" }]}],
  },
  {
    id: "arm-nr-24",
    category: "monitor-arm",
    name: "Pro 無重力 シングル",
    brand: "monTEK",
    tagline: "17〜57インチ対応・耐荷重2.0〜27.0kg・ガススプリング式",
    price: 2999,
    rating: 4.6,
    reviews: 361,
    image: "https://m.media-amazon.com/images/I/41F84qiIXgL._AC_SL1500_.jpg",
    connection: "自立型",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZZS5Y2M",
    highlights: [
      { label: "対応サイズ", value: "～32インチ" },
      { label: "耐荷重", value: "〜9.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "自立型" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "～32インチ" },
          { label: "耐荷重", value: "〜9.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "自立型" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #24" }]}],
  },{
    id: "arm-nr-26",
    category: "monitor-arm",
    name: "無重力 Pro デュアル",
    brand: "COFO",
    tagline: "COFO 無重力モニターアーム Pro デュアル 17〜40インチ、2.5〜14kg対応 角度/高さ調整可能 ダブルメカニカルスプリング式 デスク設置用 スチール アルミ合金製 2画面（上下配置版） (ブラック)",
    price: 32980,
    rating: 4.8,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/51ex6GaOTCL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "デュアルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXT1M66H",
    highlights: [
      { label: "対応サイズ", value: "17〜40インチ" },
      { label: "耐荷重", value: "2.5〜14.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜40インチ" },
          { label: "耐荷重", value: "2.5〜14.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "デュアル (2画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #26" }]}],
  },
  {
    id: "arm-nr-28",
    category: "monitor-arm",
    name: "monTEK モニターアーム デュアル",
    brand: "monTEK",
    tagline: "monTEK モニターアーム デュアル 17〜32インチ対応 耐荷重各10kg 縦2画面 PCモニターアーム 2画面 上下 左右 多角度調節",
    price: 4999,
    rating: 4.8,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/61dJEUIGOQL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GQYYBN2Q",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "10.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "10.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "機械式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #28" }]}],
  },
  {
    id: "arm-nr-29",
    category: "monitor-arm",
    name: "CR-LAW119BK",
    brand: "サンワサプライ",
    tagline: "CR-LAW119BKサンワサプライ 壁掛け式モニターアーム（3関節アーム",
    price: 6570,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/710do7ev85L._AC_SL1500_.jpg",
    connection: "壁面取付",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6MDQ37Q",
    highlights: [
      { label: "対応サイズ", value: "17〜32インチ" },
      { label: "耐荷重", value: "9Kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "壁面取付" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "17〜32インチ" },
          { label: "耐荷重", value: "9Kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "壁面取付" },
          { label: "駆動方式", value: "メカニカルスプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #29" }]}],
  },
  {
    id: "arm-nr-30",
    category: "monitor-arm",
    name: "AS-MABG05",
    brand: "Archiss",
    tagline: "アーキス モニターアーム 49インチ(2〜20kgまで)対応 ブラック AS-MABG0549インチまでのモニターに対応する高荷重設計のガススプリング式モニターアーム",
    price: 8980,
    rating: 4.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/61-GRRlqwlL._AC_SL1500_.jpg",
    connection: "クランプ式 & グロメット式",
    monitorArmSpreadsheetArmType: "シングルアーム",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8N6GMXK",
    highlights: [
      { label: "対応サイズ", value: "〜49インチ" },
      { label: "耐荷重", value: "2.0〜20.0kg" },
      { label: "VESA", value: "75×75 / 100×100" },
      { label: "取付方式", value: "クランプ式 & グロメット式" }],
    compat: [],
    specGroups: [
      { title: "対応モニター", rows: [
          { label: "画面サイズ", value: "〜49インチ" },
          { label: "耐荷重", value: "2.0〜20.0kg" },
          { label: "VESA", value: "75×75 / 100×100" },
          { label: "アーム数", value: "シングル (1画面)" }]},
      { title: "設置 / 可動", rows: [
          { label: "取付方式", value: "クランプ式 & グロメット式" },
          { label: "駆動方式", value: "ガススプリング式" },
          { label: "重量", value: "—" },
          { label: "Amazon新着", value: "モニターアーム #30" }]}],
  }]
