import type { Gadget } from "./gadgets"

/** Amazon.co.jp ディスプレイ検索（18.0～25.9インチ / 144–240Hz）。 */
export const monitorRefresh144Search: Gadget[] = [{
    id: "mon-hfr144-005",
    category: "monitor",
    name: "ASUS VY249HGR",
    brand: "ASUS",
    tagline: "Eye Care モニター / 23.8インチ FHD（1920 x 1080）/ IPS / 120Hz(OC) / SmoothMotion / 1ms（MPRT）/ Adaptive Sync/ブルーライト軽減機能/フリッカーフリー",
    price: 12580,
    rating: 4.2,
    reviews: 315,
    image: "https://m.media-amazon.com/images/I/71T7FXVO9ZL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DNDXMLR7",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
      { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #5" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.1 × 39.5 × 18.5 cm" },
          { label: "重量", value: "3.4 kg" }]}],
  },{
    id: "mon-hfr144-007",
    category: "monitor",
    name: "Dell SE2426H 23.8インチ モニター",
    brand: "Dell",
    tagline: "3年保証/FHD/IPS,非光沢/HDMIx2/傾き調整/1ms,144Hz/AMD",
    price: 14980,
    rating: 4.4,
    reviews: 186,
    image: "https://m.media-amazon.com/images/I/712+djqVlIL._AC_SL1500_.jpg",
    connection: "HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G6JMQK17",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #7" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.2 × 17.9 cm" },
          { label: "重量", value: "3.37 kg" }]}],
  },
  {
    id: "mon-hfr144-008",
    category: "monitor",
    name: "Xiaomi A24i 24インチ モニター",
    brand: "Xiaomi",
    tagline: "Xiaomi モニター A24i モニター 24インチ FHD 144Hz IPS sRGB99% 300nits TÜV低ブルーライト VESA対応 | フル",
    price: 12580,
    rating: 4.3,
    reviews: 156,
    image: "https://m.media-amazon.com/images/I/61+uB+T4YFL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCC92XD8",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #8" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 43.4 × 17 cm" },
          { label: "重量", value: "3.82Kg" }]}],
  },
  {
    id: "mon-hfr144-009",
    category: "monitor",
    name: "TERRA 2441W",
    brand: "TERRA",
    tagline: "23.8インチ フルHD IPS モニター 144Hz HDMI/VGA 最長 5年保証 非光沢 ハードウェアブルーライトカット スピーカー内蔵 ヘッドホン端子 傾き調整 24インチ ゲーミングモニター",
    price: 9999,
    rating: 4.2,
    reviews: 220,
    image: "https://m.media-amazon.com/images/I/61yL99x5MnL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G1X4CL2X",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #9" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 41.8 × 20.3 cm" },
          { label: "重量", value: "3.4 kg" }]}],
  },
  {
    id: "mon-hfr144-010",
    category: "monitor",
    name: "Dell SE2426HG 23.8インチ",
    brand: "Dell",
    tagline: "ゲーミングモニター3年保証/FHD/IPS,非光沢/HDMIx2,DPx1/sRGB99%/傾き調整/0.5ms,240Hz/AMD FreeSync™ Premium",
    price: 17980,
    rating: 4.3,
    reviews: 129,
    image: "https://m.media-amazon.com/images/I/81Z4kNI2m-L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G6JV85HG",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #10" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.2 × 18.8 cm" },
          { label: "重量", value: "3.36 kg" }]}],
  },
  {
    id: "mon-hfr144-013",
    category: "monitor",
    name: "KTC 24.5インチ  H25T7-3",
    brand: "KTC",
    tagline: "24.5インチ FHD(1920*1080) 240Hz ゲーミングモニター FAST IPS 1ms HDR400対応 ΔE<2 sRGB 114% コントラスト比1000:1 400cd/m² Adaptive Sync 前後チル・高さ調整・ピボット回転 工具不要 アイケア HDMI2.0*2 DP1.4*1 USB2.0 VESA対応 三年保証",
    price: 22265,
    rating: 4.2,
    reviews: 78,
    image: "https://m.media-amazon.com/images/I/71+n39Zx+lL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G4VT13LQ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #13" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "45 × 30 × 78 cm" },
          { label: "重量", value: "1 kg" }]}],
  },
  {
    id: "mon-hfr144-014",
    category: "monitor",
    name: "HKC PCモニター 23.8インチ MB24V29FO2",
    brand: "—",
    tagline: "23.8インチ FHD 144Hz IPS Adaptive-Sync sRGB99% PS5対応 3年保証1920×1080・コントラスト1500:1",
    price: 13280,
    rating: 4.4,
    reviews: 33,
    image: "https://m.media-amazon.com/images/I/71-pncXSCEL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G7JPFHXK",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
      { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #14" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 42.5 × 18.6 cm" },
          { label: "重量", value: "3 kg" }]}],
  },{
    id: "mon-hfr144-016",
    category: "monitor",
    name: "PHILIPS 液晶TypeCモニター",
    brand: "PHILIPS",
    tagline: "23.8インチ/IPS/FHD/120Hz/1ms/5年保証/HDMI, USB Type-C(65W急速給電)/チルト/昇降・高さ調節/ちらつき防止/ブルーライト軽減/スピーカー付",
    price: 19506,
    rating: 4.3,
    reviews: 91,
    image: "https://m.media-amazon.com/images/I/618NtTAWhhL._AC_SL1500_.jpg",
    connection: "USB Type-C / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCQPC9FQ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #16" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 44.2 × 18.7 cm" },
          { label: "重量", value: "4.68 kg" }]}],
  },
  {
    id: "mon-hfr144-028",
    category: "monitor",
    name: "LG UltraGear 24G411A-B",
    brand: "LG",
    tagline: "23.8インチ/1920×1080/120Hz（オーバークロック時 144Hz）/IPS/sRGB 99%/HDR/アンチグレア/HDMI/DisplayPort/VRR(FreeSync/G-SYNC Compatible)/フリッカーセーフ/ブルーライト低減モード/色覚調整",
    price: 14799,
    rating: 3.7,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/71YqsVkflXL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FQ972ZVT",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #28" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.2 × 22 cm" },
          { label: "重量", value: "3.3 kg" }]}],
  },
  {
    id: "mon-hfr144-029",
    category: "monitor",
    name: "Newsoul モバイルモニター18.5インチ",
    brand: "Newsoul",
    tagline: "120Hz ポータブルディスプレイ Newsoul ゲーミングモニター 1080P 125%sRGB 自立型スタンド Amazon 8月限定新登場 大画面フルHD 350 Nits IPS非光沢 HDR 持ち運び サブモニター VESA壁掛け スピーカー内蔵 TYPE-C/Mini HDMI接続",
    price: 15198,
    rating: 4.4,
    reviews: 412,
    image: "https://m.media-amazon.com/images/I/8140rrS787L._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F5WRVTN7",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #29" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "42.5 × 25 × 7 cm" },
          { label: "重量", value: "1.15 kg" }]}],
  },{
    id: "mon-hfr144-032",
    category: "monitor",
    name: "Dell S2425HSM-A",
    brand: "—",
    tagline: "23.8インチ モニター無輝点5年保証/FHD/IPS,非光沢/HDMIx2/sRGB 99%/縦横回転,高さ調整/1ms,144Hz/AMD FreeSync/内蔵スピーカー",
    price: 20670,
    rating: 4.4,
    reviews: 395,
    image: "https://m.media-amazon.com/images/I/71J8sfxGrWL._AC_SL1500_.jpg",
    connection: "HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FPDZWJ7K",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #32" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.8 × 45.7 × 19.2 cm" },
          { label: "重量", value: "3.03Kg" }]}],
  },{
    id: "mon-hfr144-035",
    category: "monitor",
    name: "レグザ PCモニター RM-24N3SE",
    brand: "REGZA",
    tagline: "3.8インチ FHD 5年保証 144Hz 広視野角IPS HDMI/VGA対応 アイケア 在宅勤務 ゲーム用途 簡単組み立て VESA対応 ブラック",
    price: 15980,
    rating: 4.8,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/71xKXKQQNyL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H5BSQHSC",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #35" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 40.3 × 21.5 cm" },
          { label: "重量", value: "3 kg" }]}],
  },
  {
    id: "mon-hfr144-036",
    category: "monitor",
    name: "MAXZEN モニター 23.8インチ 144Hz FHD",
    brand: "MAXZEN",
    tagline: "144Hz FHD pcモニター フリッカーレス FullHD ブルーライトカット ノングレア ディスプレイ HDMI 144hz Adaptive-Sync ブラック MJM24IC01 マクスゼン",
    price: 11480,
    rating: 4.4,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/61HOUVSyxCL._AC_SL1500_.jpg",
    connection: "HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F53K3Z9H",
    vesaStandard: "—",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #36" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "52.4 × 41.5 × 21.9 cm" },
          { label: "重量", value: "3 kg" }]}],
  },
  {
    id: "mon-hfr144-037",
    category: "monitor",
    name: "Lenovo Legion 24-15 ゲーミングモニター",
    brand: "Lenovo",
    tagline: "23.8インチ/フルHD/Fast IPSパネル/240Hz/1ms(GtG)/HDMI2.1x2, DP1.4x1/HDR10/AMD FreeSync™ Premium/縦横回転,高さ調整/日本国内5年保証",
    price: 15180,
    rating: 4.3,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/71enTa9RXGL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G42NGPTD",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #37" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 54.3 × 21.4 cm" },
          { label: "重量", value: "3.9Kg" }]}],
  },{
    id: "mon-hfr144-040",
    category: "monitor",
    name: "EVICIV モバイルモニター 18.5インチ 120Hz",
    brand: "EVICIV",
    tagline: "ゲーミング ポータブル スプレイ 自立型スタンド付き 壁掛け VESA対応 125%sRGB 1500:1 FHD 1080P 非光沢 モバイルディスプレイ スピーカー内蔵 350Nit Type-C/Mini HDMI搭載",
    price: 15199,
    rating: 4.3,
    reviews: 7371,
    image: "https://m.media-amazon.com/images/I/71x5jZRImQL._AC_SL1500_.jpg",
    connection: "USB Type-C / Mini HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H9LFWFGC",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-usb-c","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "18.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "18.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #40" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "HDMI", value: "対応" },
          { label: "Mini HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "42.3 × 25 × 1.8 cm" },
          { label: "重量", value: "1.11 kg" }]}],
  },{
    id: "mon-hfr144-042",
    category: "monitor",
    name: "JAPANNEXT 21.5インチ 液晶モニター JN-215IPS120F-HSP",
    brand: "JAPANNEXT",
    tagline: "IPSパネル,フルHD(1920×1080)解像度,HDMI,DP,HDR,120Hz,高さ調整,ピボット(縦回転)対応,2年保証",
    price: 14526,
    rating: 4.6,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/71wIZ3WSf8L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJSCDTC6",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #42" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.6 × 45 × 19 cm" },
          { label: "重量", value: "3.2 kg" }]}],
  },
  {
    id: "mon-hfr144-043",
    category: "monitor",
    name: "KOORUI モニター 21.5インチ FHD",
    brand: "KOORUI",
    tagline: "FHD 120Hz VA 非光沢 Adaptive Sync HDMI/VGA VESA ブルーライト軽減 アンチフリッカー/傾き調整 (HDMIケーブル付）/三年保証/スピーカー非搭載",
    price: 13980,
    rating: 4.5,
    reviews: 572,
    image: "https://m.media-amazon.com/images/I/81eUWO8GSGL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G8J8J3NQ",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-va-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "VA　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "VA　非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #43" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "—" },
          { label: "重量", value: "3.01Kg" }]}],
  },
  {
    id: "mon-hfr144-045",
    category: "monitor",
    name: "MSI ゲーミングモニター MAG 245F X24",
    brand: "MSI",
    tagline: "23.8インチ/フルHD/RAPID IPS/240Hz/0.5ms（GTG、最小値）/HDR/FreeSync Premium/HDMI 2.0/DP 1.2a/VESA100/メーカー3年保証",
    price: 23800,
    rating: 4.4,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/71ei9jRpjyL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B096Y284KC",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #45" }]},
      { title: "接続端子", rows: [
          { label: "HDMI 2.0", value: "対応" },
          { label: "DisplayPort 1.2a", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.2 × 22.1 cm" },
          { label: "重量", value: "3.3 kg" }]}],
  },
  {
    id: "mon-hfr144-046",
    category: "monitor",
    name: "IODATA ゲーミングモニター 24.5インチ GigaCrysta",
    brand: "IO DATA",
    tagline: "240Hz 0.4ms TNパネル (HDMI×2/ DisplayPort/高さ調整/縦横回転/VESA対応/メーカー3年保証",
    price: 22980,
    rating: 4.3,
    reviews: 291,
    image: "https://m.media-amazon.com/images/I/71FoSEKVOrL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C77BLCWX",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","vesa-100","panel-tn"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "TN 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "TN 非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #46" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "55.7 × 45.5 × 22.7 cm" },
          { label: "重量", value: "6.1 kg" }]}],
  },{
    id: "mon-hfr144-049",
    category: "monitor",
    name: "KTC 24インチ FHDモニター H24V27S",
    brand: "KTC",
    tagline: "165Hz IPS HDR10 H24V27S 24インチ・FHD・144Hz OC 165Hz・IPS・HDR10・300cd/㎡・Adaptive Sync・HDMI・VGA・VESA対応・チルト調整・低ブルーライト",
    price: 14980,
    rating: 4.4,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/71kOgUgg43L._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2FJVZLP",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "165Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "165Hz" },
          { label: "Amazon検索", value: "PCモニター #49" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54 × 40.5 × 18.3 cm" },
          { label: "重量", value: "4Kg" }]}],
  },
  {
    id: "mon-hfr144-050",
    category: "monitor",
    name: "Amzfast 24インチ ゲーミングモニター WQHD 180Hz",
    brand: "Amzfast",
    tagline: "ast IPS 1ms(MPRT) 130%sRGB 回転・昇降可能 HDR低ブルーライト フリッカーフリー Adaptive Sync PS5対応 HDMI2.0×2 DP1.4×2 VESA 100*100 無輝点保証 5年保証",
    price: 19999,
    rating: 4.2,
    reviews: 2437,
    image: "https://m.media-amazon.com/images/I/71nDQ9DE+GL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FXLTM2WG",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-24","res-wqhd","refresh-144-plus","port-hdmi","port-dp","vesa-100","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "QHD (2560 x 1440)" },
      { label: "リフレッシュ", value: "180Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "QHD (2560 x 1440)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "180Hz" },
          { label: "Amazon検索", value: "PCモニター #50" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "50 × 22 × 53.9 cm" },
          { label: "重量", value: "4.3 kg" }]}],
  },
  {
    id: "mon-hfr144-051",
    category: "monitor",
    name: "JAPANNEXT 21.5インチJN-IPS215G120F-W",
    brand: "JAPANNEXT",
    tagline: "IPSパネル,フルHD(1920×1080)解像度,HDMI,DisplayPort,120Hz,ケーブル(ホワイト)同梱,2年保証,",
    price: 14980,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/71U5JgrSfNL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GS12H8S7",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","port-dp","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.5\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.5\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #51" }]},
      { title: "接続端子", rows: [
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49.6 × 38.5 × 17.5 cm" },
          { label: "重量", value: "2.2 kg" }]}],
  },{
    id: "mon-hfr144-053",
    category: "monitor",
    name: "TERRA 2441W PV",
    brand: "TERRA",
    tagline: "23.8インチ 高さ調整 縦横回転 ピボット モニター フルHD IPS 144Hz HDMI/VGA 最長 5年保証 非光沢 ハードウェアブルーライトカット スピーカー内蔵",
    price: 13990,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/61MIWDFnBiL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2LX5Y89",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","vesa-100","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #53" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 51.4 × 22.9 cm" },
          { label: "重量", value: "4.4 kg" }]}],
  },
  {
    id: "mon-hfr144-054",
    category: "monitor",
    name: "MSI PRO MAX 241PHW E14",
    brand: "MSI",
    tagline: "23.8インチ/フルHD/IPS/144Hz/1ms/HDR/USB PD65W/スピーカー/KVM/MSI Power Link/Eye-Q Check/HDMI 2.0b/DP 1.2a/USB Type-C DP alt mode/VESA75/メーカー3年保証",
    price: 27826,
    rating: 5,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/71rtZJm3TBL._AC_SL1500_.jpg",
    connection: "USB Type-C / DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GMS4QWVR",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","port-usb-c","vesa-75","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #54" }]},
      { title: "接続端子", rows: [
          { label: "USB Type-C", value: "対応" },
          { label: "DisplayPort", value: "対応" },
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 38.2 × 20.1 cm" },
          { label: "重量", value: "5.35 kg" }]}],
  },
  {
    id: "mon-hfr144-055",
    category: "monitor",
    name: "Pixio PX249Wave",
    brand: "Pixio",
    tagline: "24インチ 240hz FHD Fast IPS ゲーミング モニター 白 ピクシオ ディスプレイ サブモニター pcモニター ゲームモニター monitor gaming 23.8インチ スピーカー内蔵",
    price: 29980,
    rating: 4.7,
    reviews: 45,
    image: "https://m.media-amazon.com/images/I/716Cs1SmK3L._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GLN7725V",
    vesaStandard: "—",
    monitorFilterTags: ["size-24","res-fhd","refresh-144-plus","refresh-240-plus","port-hdmi","port-dp","panel-fast-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "24\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "240Hz" },
      { label: "パネル", value: "Fast IPS　非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "24\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "Fast IPS　非光沢" },
          { label: "リフレッシュレート", value: "240Hz" },
          { label: "Amazon検索", value: "PCモニター #55" }]},
      { title: "接続端子", rows: [
          { label: "接続端子", value: "—" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "54.2 × 42.5 × 18 cm" },
          { label: "重量", value: "3 kg" }]}],
  },
  {
    id: "mon-hfr144-056",
    category: "monitor",
    name: "XUNDEFINED 23.8インチ モニター",
    brand: "XUNDEFINED",
    tagline: "フルHD(1920x1080) 144Hz 超薄型 ディスプレイ スピーカー内蔵 非光沢 IPSパネル 114%sRGB HDR FreeSync対応 ブルーライト軽減 フリッカーフリー HDMI2.0 DP1.4 音声出力端子搭載 チルト調整",
    price: 11780,
    rating: 4.5,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/714+sNosvGL._AC_SL1500_.jpg",
    connection: "DisplayPort / HDMI",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G3PG56V2",
    vesaStandard: "75×75 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-144-plus","port-hdmi","port-dp","vesa-75","panel-ips-matte"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "23.8\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "144Hz" },
      { label: "パネル", value: "IPS 非光沢" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
      { label: "画面サイズ", value: "23.8\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
      { label: "パネル", value: "IPS 非光沢" },
          { label: "リフレッシュレート", value: "144Hz" },
          { label: "Amazon検索", value: "PCモニター #56" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "53.9 × 41.5 × 17 cm" },
          { label: "重量", value: "2.74Kg" }]}],
  },
  {
    id: "mon-hfr144-069",
    category: "monitor",
    name: "PRO MP225",
    brand: "MSI",
    tagline: "MSI Business Monitor PRO MP225 E12L 21.45 Inch Full HD/IPS/120Hz/1ms/Adaptive-Sy",
    price: 12800,
    rating: 4.5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71Gs6231DeL._AC_SL1500_.jpg",
    connection: "HDMI / VGA",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H7147ZCB",
    vesaStandard: "100×100 mm",
    monitorFilterTags: ["size-238","res-fhd","refresh-100","port-hdmi","vesa-100","panel-ips"],
    monitorSpreadsheetLTags: [],
    highlights: [
      { label: "画面サイズ", value: "21.45\"" },
      { label: "解像度", value: "FHD (1920×1080)" },
      { label: "リフレッシュ", value: "120Hz" },
      { label: "パネル", value: "IPS" }],
    compat: [],
    specGroups: [
      { title: "ディスプレイ", rows: [
          { label: "画面サイズ", value: "21.45\"" },
          { label: "解像度", value: "FHD (1920×1080)" },
          { label: "パネル", value: "IPS" },
          { label: "リフレッシュレート", value: "120Hz" },
          { label: "Amazon検索", value: "PCモニター #69" }]},
      { title: "接続端子", rows: [
          { label: "HDMI", value: "対応" },
          { label: "VGA", value: "対応" }]},
      { title: "本体", rows: [
          { label: "寸法", value: "49 × 38.5 × 18.3 cm" },
          { label: "重量", value: "2.42 kg" }]}],
  }]
