import type { Gadget } from "./gadgets"

/** Amazon.co.jp gpro 検索 page=3。マウス本体のみ。 */
export const mouseGproPage3: Gadget[] = [
  {
    id: "m-gp3-001",
    category: "mouse",
    name: "G PRO 2 LIGHTSPEED G-PPD-002XWL-BKd",
    brand: "Logicool G",
    tagline: "【セット買い】【Amazon.co.jp限定】 Logicool G PRO 2 LIGHTSPEED ワイヤレス ゲーミングマウス G-PPD-002XWL-BKd 80g 国内正規品※Amazon限定の壁紙ダウンロード付き + ゲーミングマウスパッド G240 クロス表面 標準サイズ 340×280×1mm G240f",
    price: 14300,
    rating: 4.8,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/518phJVP92L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F5PV5B9D",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "80 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "80 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-002",
    category: "mouse",
    name: "G PRO X SUPERLIGHT 2 G-PPD-004WL-BKd",
    brand: "Logicool G",
    tagline: "【Set Purchase】【Amazon.co.jp Exclusive】Logicool G 8000Hz Symmetric Left and Right PRO X SUPERLIGHT 2 Wireless Gaming Mouse G-PPD-004WL-BKd…",
    price: 23500,
    rating: 5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/51N6VfkcKTL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "2ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F5PYPCCK",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "2ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },{
    id: "m-gp3-004",
    category: "mouse",
    name: "レイザー DeathAdder V4 Pro",
    brand: "Razer",
    tagline: "Razer レイザー DeathAdder V4 Pro ゲーミングマウス ワイヤレス 無線 56gの超軽量 8,000Hzドングル同梱 高精度の第2世代 Focus Pro 45K オプティカルセンサー 超低遅延を実現する第2世代 HyperSpeed Wireless オプティカルスクロールホイール 第4世代 オプティカルマウススイッチ 150時間のバッテリー駆動",
    price: 28980,
    rating: 4.8,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/71j6PDIwegL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FGX8N9KP",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "56 g" },
      { label: "最大DPI", value: "45,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "56 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-005",
    category: "mouse",
    name: "G903h",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングマウス G903h LIGHTSPEED ワイヤレス ゲーミング マウス HERO 25Kセンサー 多ボタン 180時間連続使用可能 LIGHTSYNC RGB POWERPLAY",
    price: 13582,
    rating: 4.4,
    reviews: 557,
    image: "https://m.media-amazon.com/images/I/5121I8ZNcZL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "11ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07T36TLS5",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "110 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "110 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "11ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-006",
    category: "mouse",
    name: "AIM1 時雨 ゲーミングマウス",
    brand: "AIM1",
    tagline: "AIM1 時雨 ゲーミングマウス ポーリングレート 8,000Hz 45g 超軽量 ワイヤレス 無線 有線 80時間駆動 SHIGURE ホワイト",
    price: 14980,
    rating: 4.5,
    reviews: 208,
    image: "https://m.media-amazon.com/images/I/518wZsyNnlL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "2ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DRNT3FP1",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "45 g" },
      { label: "最大DPI", value: "26,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "45 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "2ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "単4形乾電池×1本" },
        ]},
    ],
  },
  {
    id: "m-gp3-007",
    category: "mouse",
    name: "MAYA REJECT",
    brand: "LAMZU",
    tagline: "LAMZU MAYA REJECTモデル【8Kドングル入り】 ゲーミングマウス リジェクトSPECIAL EDITIONリジェクト×ラムズ 無線 軽量 45g type-C 充電",
    price: 19800,
    rating: 4.5,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/71bcVRD3XCL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FCYF4VNS",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "45 g" },
      { label: "最大DPI", value: "30,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "45 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-008",
    category: "mouse",
    name: "MAYA X REJECT",
    brand: "LAMZU",
    tagline: "LAMZU MAYA X REJECTモデル【8Kドングル入り】 ゲーミングマウス リジェクトSPECIAL EDITION無線 軽量 47g type-C 充電 ワイヤレス リジェクト×ラムズ",
    price: 19800,
    rating: 4.5,
    reviews: 69,
    image: "https://m.media-amazon.com/images/I/61H2IVx2CPL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F31Z6RN8",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "47 g" },
      { label: "最大DPI", value: "30,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "47 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-009",
    category: "mouse",
    name: "X2 v3",
    brand: "Pulsar",
    tagline: "Pulsar Gaming Gears X2 v3 ワイヤレス ゲーミングマウス 超軽量 52グラム 左右対称 2.4Ghz 1ms 32000 DPI Optical swhich XS-1 Flagship Sensor 国内正規品",
    price: 14960,
    rating: 3.8,
    reviews: 60,
    image: "https://m.media-amazon.com/images/I/51gt+c1FXOL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DHRYVQM7",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "52 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "52 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-010",
    category: "mouse",
    name: "G502XWL-CRBK",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングマウス G502 X LIGHTSPEED ワイヤレス マウス G502XWL-CRBK LIGHTFORCE ハイブリッドスイッチ HERO 25K センサー 13個プログラムボタン USB Type-C 充電 POWERPLAY 対応",
    price: 17600,
    rating: 4.3,
    reviews: 579,
    image: "https://m.media-amazon.com/images/I/61NTCA2g+6L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "13ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BHL3B2VF",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "102 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "102 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "サイドボタン", value: "あり" },
          { label: "ボタン数", value: "13ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-011",
    category: "mouse",
    name: "SPK9618",
    brand: "Philips",
    tagline: "フィリップス EVNIA ワイヤレス ゲーミングマウス SPK9618 黒 53g 超軽量 最大16K DPI 1Kポーリングレート 左右対称 充電式 | 無線/有線両対応 Bluetooth/2.4g/USB-C接続 ６段階DPI調節 1ms低遅延 6個プログラムボタン …",
    price: 4686,
    rating: 4.7,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/61p2BvrH9mL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H69JYZ9K",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "53 g" },
      { label: "最大DPI", value: "16,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "53 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "サイドボタン", value: "あり" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-012",
    category: "mouse",
    name: "STORIA Kikyo",
    brand: "STORIA",
    tagline: "STORIA Kikyo マウスゲーミング 無線 軽量 静音 PAW3950 8000Hz ハーフエルゴ 左右非対称 FPS向け ワイヤレス 白",
    price: 14960,
    rating: 4.6,
    reviews: 11,
    image: "https://m.media-amazon.com/images/I/51+XtnGP+4L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GMGF2YNX",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "50 g" },
      { label: "最大DPI", value: "42,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "50 g" },
          { label: "形状", value: "左右非対称（ハーフエルゴノミクス）" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "マウス最大感度", value: "42,000 DPI" },
          { label: "ポーリングレート", value: "最大8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-013",
    category: "mouse",
    name: "STORIA Shion",
    brand: "STORIA",
    tagline: "STORIA Gaming Mouse Shion ワイヤレス ゲーミングマウス カーボンファイバー PAW3950 8000Hz ポーリングレート 低遅延 Type-C ハニカム構造 左右対称 FPS向け 国内正規品",
    price: 16830,
    rating: 4.1,
    reviews: 7,
    image: "https://m.media-amazon.com/images/I/61oedn16FWL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GKFPNTR4",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "50 g" },
      { label: "最大DPI", value: "42,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "50 g" },
          { label: "形状", value: "左右対称（ハイバンプ）" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "マウス最大感度", value: "30,000 DPI（最大42,000 DPI）" },
          { label: "ポーリングレート", value: "最大8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },{
    id: "m-gp3-015",
    category: "mouse",
    name: "MX MASTER 4　MX2400GRd",
    brand: "Logicool",
    tagline: "【Amazon.co.jp限定】 ロジクール MX MASTER 4 アドバンスド ワイヤレス マウス 触覚フィードバック 静音 MX2400GRd",
    price: 19900,
    rating: 4,
    reviews: 526,
    image: "https://m.media-amazon.com/images/I/61BPuOamilL._AC_SL1500_.jpg",
    connection: "Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0FR8LPP2K",
    mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "150 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "150 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-016",
    category: "mouse",
    name: "ZA13-DW",
    brand: "BenQ ZOWIE ZA13-DW",
    tagline: "BenQ ZOWIE ZA13-DW ワイヤレスゲーミングマウス 高プロファイル/左右対称/65g/3950センサー/4000Hz/右利き用",
    price: 19800,
    rating: 4.2,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/51XI1QI5+9L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0DWMQ6NLY",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["gaming"],
    highlights: [
      { label: "重量", value: "65 g" },
      { label: "最大DPI", value: "3,950 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "4,000 Hz" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "65 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "4,000 Hz" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-gp3-017",
    category: "mouse",
    name: "M550MBKs",
    brand: "Logicool",
    tagline: "【Amazon.co.jp限定】 ロジクールワイヤレスマウス 静音 無線 Signature M550MBKs レギュラー ブラック 国内正規品",
    price: 4000,
    rating: 4.3,
    reviews: 1909,
    image: "https://m.media-amazon.com/images/I/618q9UO6GIL._AC_SL1500_.jpg",
    connection: "Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0BKP2XWY5",
    mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "97 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "97 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "単3形乾電池×1本" },
        ]},
    ],
  },
  {
    id: "m-gp3-018",
    category: "mouse",
    name: "Naga V2 Pro",
    brand: "Razer",
    tagline: "Razer(レイザー) ゲーミングマウス Naga V2 Pro ブラック 134g RZ01-04400100-R3A1",
    price: 28800,
    rating: 3.6,
    reviews: 115,
    image: "https://m.media-amazon.com/images/I/71D9cxs+rXL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "20ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BW414LJL",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "134 g" },
      { label: "最大DPI", value: "30,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "134 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "20ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },{
    id: "m-gp3-020",
    category: "mouse",
    name: "Viper V3 Pro",
    brand: "Razer",
    tagline: "Razer Viper V3 Pro ゲーミングマウス ワイヤレス 無線 Focus Pro 35Kセンサー 35000DPI 高速応答 オプティカルスイッチ 6ボタン",
    price: 26480,
    rating: 4.4,
    reviews: 108,
    image: "https://m.media-amazon.com/images/I/61BJ2MpgTTL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CVRGCGWJ",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "54 g" },
      { label: "最大DPI", value: "35,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "54 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "サイドボタン", value: "あり" },
          { label: "ボタン数", value: "8ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
]
