import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングマウス新着ランキング（2151973051）。マウス本体のみ。 */
export const mouseGamingNewReleases: Gadget[] = [
  {
    id: "m-gnr-001",
    category: "mouse",
    name: "Viper V4 Pro",
    brand: "Razer",
    tagline: "Razer レイザー Viper V4 Pro ゲーミングマウス 49g 超軽量 8,000Hzドングル同梱 ワイヤレス HyperSpeed Wireless 第3世代 Razer Focus Pro オプティカルセンサー 50,000DPI 第4世代 オプティカルマウス…",
    price: 26980,
    rating: 4.3,
    reviews: 126,
    image: "https://m.media-amazon.com/images/I/71UvLd6bHAL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GLM7WKVH",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "49 g" },
      { label: "最大DPI", value: "40,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "49 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "40,000" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "180 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "USB, Wi-Fi" }]}],
  },
  {
    id: "m-gnr-002",
    category: "mouse",
    name: "Naga V2 HyperSpeed",
    brand: "Razer",
    tagline: "Razer(レイザー) Naga V2 HyperSpeed MMOに最適な多ボタンのワイヤレスゲーミングマウス プログラム可能な19ボタン フリースピンまたはタクタイルスクロールホイール HyperSpeed Wireless Bluetooth Focus Pro 30…",
    price: 13800,
    rating: 4,
    reviews: 70,
    image: "https://m.media-amazon.com/images/I/51XETDioM+L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "19ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BW3ZS795",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "130 g" },
      { label: "最大DPI", value: "30,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "30,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "19ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "400 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth" }]}],
  },
  {
    id: "m-gnr-003",
    category: "mouse",
    name: "EVNIA SPK9418",
    brand: "Philips",
    tagline: "フィリップス EVNIA ワイヤレス ゲーミングマウス SPK9418 黒 52g 超軽量 最大12K DPI 1Kポーリングレート 右手専用 充電式無線/有線両対応 Bluetooth/2.4g/USB-C接続 ６段階DPI調節 1ms応答速度 6個プログラムボタン サイドボタン付き エルゴノミクス 低遅延 高耐久",
    price: 4485,
    rating: 4.3,
    reviews: 96,
    image: "https://m.media-amazon.com/images/I/415CW3niQTL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GT7BV9D6",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "52 g" },
      { label: "最大DPI", value: "12,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "52 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "12,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "60 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
    {
    id: "m-gnr-005",
    category: "mouse",
    name: "(レイザー) Cobra",
    brand: "Razer",
    tagline: "Cobra ゲーミングマウス 58g 軽量 コンパクト つかみ持ち/つまみ持ちにフィット 有線 第3世代 オプティカルマウススイッチ 没入感を高めるアンダーグロー Chroma ライティング 8500 DPI オプティカルセンサー Speedflex ケーブル コブラ 【日本正規代理店保証品】",
    price: 6040,
    rating: 4.5,
    reviews: 2190,
    image: "https://m.media-amazon.com/images/I/51O6HhLrSZL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0C5XNRVWM",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "83 g" },
      { label: "最大DPI", value: "8,500 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "83 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "8,500" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gnr-006",
    category: "mouse",
    name: "Orochi V2",
    brand: "Razer",
    tagline: "【Amazon.co.jp限定】 Razer Orochi V2 ゲーミングマウス ワイヤレス HyperSpeed Bluetooth 2つの無線モード 5G 高性能 18000 DPI オプティカルセンサー",
    price: 5980,
    rating: 4.9,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/61SEqMSA-YL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GXZHRJR3",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "18,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "18,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "1100 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth" }]}],
  },
    {
    id: "m-gnr-010",
    category: "mouse",
    name: "PAW3955",
    brand: "ATK",
    tagline: "【国内正規品】ATK ワイヤレス ゲーミングマウス A9 MINI+ PAW3955 Master センサー 50,000 DPI 軽量 39g 200時間連続使用可能 最新ナノコーティング採用 5個プログラムボタン Windows Mac 対応 ブルー",
    price: 11699,
    rating: 4.6,
    reviews: 51,
    image: "https://m.media-amazon.com/images/I/51W7tbcnZ6L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H1M8DSXT",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "39 g" },
      { label: "最大DPI", value: "50,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "39 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "50,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "800 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },{
    id: "m-gnr-014",
    category: "mouse",
    name: "M814",
    brand: "Redragon",
    tagline: "Redragon M814 ワイヤレスゲーミングマウス トリモード 無線・有線 ラピッドファイアキー搭載 8000DPI | 7プログラム可能マクロショートカット 充電式 軽量設計 PC Windows Mac ゲーマー向け ブラック",
    price: 12980,
    rating: 4.6,
    reviews: 2067,
    image: "https://m.media-amazon.com/images/I/61RHIMV5UQL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "7ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H38KKFF3",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "100 g" },
      { label: "最大DPI", value: "8,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ボタン数", value: "5個" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "100 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "マウス最大感度", value: "26,000 DPI" },
          { label: "ボタン数", value: "7ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr-015",
    category: "mouse",
    name: "M814",
    brand: "Redragon",
    tagline: "Redragon M814 ワイヤレスゲーミングマウス トリモード 無線・有線 ラピッドファイアキー搭載 8000DPI | 7プログラム可能マクロショートカット 充電式 軽量設計 PC Windows Mac ゲーマー向け ブラック",
    price: 3999,
    rating: 4.4,
    reviews: 417,
    image: "https://m.media-amazon.com/images/I/51WUh44kG5L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "7ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DBQC2YP6",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "100 g" },
      { label: "最大DPI", value: "8,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "100 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "8,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "7ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gnr-020",
    category: "mouse",
    name: "IRONCLAW WIRELESS SE",
    brand: "CORSAIR",
    tagline: "CORSAIR IRONCLAW ワイヤレス SE ゲーミングマウス – 黒 CH-9317110-WW | 26,000 DPI、人間工学に基づいた非対称形状、10 個のプログラム可能のボタン、MOBA、FPS、MMO",
    price: 21571,
    rating: 5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/61Ayc1B1v7L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H4X9J6JS",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "54 g" },
      { label: "最大DPI", value: "35,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "54 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "35,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gnr-023",
    category: "mouse",
    name: "AJ139 V2 MC",
    brand: "Ajazz",
    tagline: "AJAZZ AJ139 V2 MC ワイヤレスゲーミングマウス 軽量 66g 3モード接続 2.4GHz/Bluetooth/有線 国内正規品 PAW3311センサー 最大24000DPI 1000Hzポーリングレート マグネット式充電ドック付き RGBライト 500mAh…",
    price: 4399,
    rating: 4.3,
    reviews: 6,
    image: "https://m.media-amazon.com/images/I/51KHjbbOP9L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GPDC376L",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "54 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "54 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "32,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr-024",
    category: "mouse",
    name: "M6",
    brand: "Keychron",
    tagline: "Keychron M6 サイレント ワイヤレス ゲーミング マウス、1000Hz、Bluetooth 5.3/2.4GHz/有線、PixArt 3395 センサー（26K DPI）、86g、オンボード メモリ プロファイルでプラグ＆プレイ",
    price: 15440,
    rating: 4,
    reviews: 154,
    image: "https://m.media-amazon.com/images/I/613DrNAGI0L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "4ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "silent"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FP2D8DW6",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "86 g" },
      { label: "最大DPI", value: "26,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "86 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "26,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "4ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gnr-027",
    category: "mouse",
    name: "M2",
    brand: "TMKB",
    tagline: "TMKB M2 ワイヤレスゲーミングマウス・軽量・3 モード対応 (2.4G/Bluetooth/有線)・24000 DPI・9 個プログラム可能ボタン・600mAh 充電式・RGB バックライト・PC/ノート PC/Mac 対応",
    price: 3980,
    rating: 4.4,
    reviews: 99,
    image: "https://m.media-amazon.com/images/I/61SPSBFKldL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "9ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GY52YRYL",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "96 g" },
      { label: "最大DPI", value: "24,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "96 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "24,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "9ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr-028",
    category: "mouse",
    name: "Aerox 3 WL Gen 2 Shadow",
    brand: "SteelSeries",
    tagline: "SteelSeries ゲーミングマウス Aerox 3 WL Gen 2 Shadow 無線 ワイヤレス マウス 2.4Ghz/Bluetooth USB 超軽量 薄型 IP54規格 防水 防塵 耐久性 62717 シャドー",
    price: 13936,
    rating: 4.4,
    reviews: 47,
    image: "https://m.media-amazon.com/images/I/61I472Gq94L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GNM9S22Q",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "68 g" },
      { label: "最大DPI", value: "26,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "68 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "26,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  }]
