import type { Gadget } from "./gadgets"

/** Amazon.co.jp マウス新着ランキング pg2（2151978051）。マウス本体のみ。 */
export const mouseNewReleasesPage2: Gadget[] = [
  {
    id: "m-nr2-001",
    category: "mouse",
    name: "Padholds ゲーミングマウス",
    brand: "Padholds",
    tagline: "Padholds ゲーミングマウス、ノートPC用マウス、有線マウス。7色を自動で切り替えるバックライト（呼吸効果）を搭載し、解像度は1200 DPI、ボタンは3つ、人間工学に基づいた設計の光学式マウスです。",
    price: 499,
    rating: 2.4,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/71DaRajdHBL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "3ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GY45PG1F",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "95 g" },
      { label: "最大DPI", value: "1,200 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "95 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,200" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
        ]},
    ],
  },
  {
    id: "m-nr2-002",
    category: "mouse",
    name: "Ring Mouse RMWTB200",
    brand: "Futuristec",
    tagline: "Futuristec リングマウス Ring Mouse / スマートフォン・タブレット用ワイヤレスページ送り / SNS動画、小説、ウェブトゥーン閲覧用 / 最大10m長距離操作、会議およびプレゼンテーション活用可能 / セルカ用リモートシャッター / 指の動きでマウスカ…",
    price: 7999,
    rating: 3.4,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/51dYWcLAQmL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GMWL5KWX",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "9 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "ジャイロスコープ" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "9 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "—" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "ジャイロスコープ" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-005",
    category: "mouse",
    name: "【驚きのスリム＆Type-C 充電式 】マウス 無線 Bluetooth 5.4 静音 小型 ワイヤレスマウス 2.4GHz 3段階DPI…",
    brand: "—",
    tagline: "【驚きのスリム＆Type-C 充電式 】マウス 無線 Bluetooth 5.4 静音 小型 ワイヤレスマウス 2.4GHz 3段階DPI切替 省エネ 瞬時接続 7色ライト付き 小型 光学式 高耐久性 Mac/Windows/Surface/パソコン/Mac 対応",
    price: 999,
    rating: 4.9,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/51sg4w7nrEL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYQW8PZ7",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "—" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-006",
    category: "mouse",
    name: "Viper V3 HyperSpeed",
    brand: "Razer",
    tagline: "つかみ持ちにもつまみ持ちにも最適な軽量ワイヤレスゲーミングマウス HyperSpeed Wireless 電池式 Focus Pro 30K オプティカルセンサー 最大280時間のバッテリー持続時間【日本正規代理店保証品】",
    price: 11800,
    rating: 4.4,
    reviews: 1863,
    image: "https://m.media-amazon.com/images/I/517nfncP9BL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CBCPB2T1",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "83 g" },
      { label: "最大DPI", value: "30,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "83 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "30,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "単3形 乾電池（付属）" },
          { label: "電池持続", value: "280 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "高周波" },
        ]},
    ],
  },
  {
    id: "m-nr2-007",
    category: "mouse",
    name: "A39R",
    brand: "Redbean",
    tagline: "Redbean A39R ブラック クォンタムスクロール エルゴノミクス ワイヤレスマウス Bluetooth 2.4GHz無線 両対応 静音マウス 急速充電式 高精度DPI 5ボタン 人間工学 手首の疲労軽減 マルチペアリング 縦型 バーティカルマ",
    price: 5390,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/51j-rTcCzaL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "7ボタン",
    mouseSpreadsheetUsageSpecs: ["ergonomic", "silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6LDM4T4",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "93 g" },
      { label: "最大DPI", value: "4,800 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "93 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "4,800" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "7ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-008",
    category: "mouse",
    name: "Bisoom ワイヤレスマウス",
    brand: "—",
    tagline: "ワイヤレスマウス 無線マウス 静音クリック 超薄型 軽量モデル 2.4GHz安定接続 高精度センサー 800/1200/1600DPI 3段階調整 7色LEDライト USBレシーバー付",
    price: 1399,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/41pFM5d4nIL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "3ボタン",
    mouseSpreadsheetUsageSpecs: ["silent"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0HC2V1SHC",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "100 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "100 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-009",
    category: "mouse",
    name: "MAKOTOYAワイヤレス静音超薄型マウス",
    brand: "—",
    tagline: "マウス 無線 超薄型 高精度 高感度 ワイヤレスマウス 静音 3段階DPI切替 Type-C 充電式 省エネ 2.4GHz Bluetooth 5.0 節電モデル 瞬時接続 7色ライト付き 小型 光学式 高精度 左右対称 SEIYES",
    price: 780,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/4130vrgWklL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "3ボタン",
    mouseSpreadsheetUsageSpecs: ["silent"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H73YH8BF",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "70 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "70 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-010",
    category: "mouse",
    name: "PHILIPS SPK7858",
    brand: "Philips",
    tagline: "【PHILIPS ワイヤレスマウス】Bluetooth 5.0 USB-C USB-A対応 静音 充電式 最大100時間使用 サイドホイール搭載 横スクロール 7ボタン 3Dホイール 5段階DPI切替 右手用 エルゴノミクスマウス 自動スリープ Windows Mac対応 フィリップスマウスSPK7858",
    price: 1500,
    rating: 3.6,
    reviews: 25,
    image: "https://m.media-amazon.com/images/I/71ShiAqcrzL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "7ボタン",
    mouseSpreadsheetUsageSpecs: ["ergonomic", "silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTM4P3XS",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "97 g" },
      { label: "最大DPI", value: "4,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "97 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "4,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "7ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-011",
    category: "mouse",
    name: "FADZECO ワイヤレスマウス",
    brand: "—",
    tagline: "ワイヤレスマウス 縦型 エルゴノミック 6ボタン DPI切替 サイドボタン搭載 手首負担軽減 ブラック",
    price: 1500,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/31qYZ52ToML._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTXF3L34",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "87 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "87 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "単4形 乾電池" },
        ]},
    ],
  },
  {
    id: "m-nr2-012",
    category: "mouse",
    name: "Pebble Mouse 2 M350S",
    brand: "Logicool",
    tagline: "Logitech (Logicool) Pebble Mouse 2 M350S ワイヤレスマウス Bluetooth 静音 マルチデバイス スリム コンパクト 軽量 Tonal White オフホワイト 白 [海外パッケージ品]",
    price: 3190,
    rating: 4.3,
    reviews: 422,
    image: "https://m.media-amazon.com/images/I/51IXak2vOAL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGCXNF6F",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "—" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "—" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "—" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "単3形乾電池×1本" },
        ]},
    ],
  },
  {
    id: "m-nr2-013",
    category: "mouse",
    name: "Lenovo 350",
    brand: "Lenovo",
    tagline: "レノボ Lenovo 350 ワイヤレスマウス Bluetooth 5.3 静音 2台接続 左右対称 3段階DPI調整 最大2400DPI 36ヶ月電池寿命 マルチデバイス対応 ルナグレー 国内正規品",
    price: 1980,
    rating: 5,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/31I2smnVVLL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "3ボタン",
    mouseSpreadsheetUsageSpecs: ["silent"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2975Z5T",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "70 g" },
      { label: "最大DPI", value: "2,400 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "70 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "2,400" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "単3形乾電池×1本" },
        ]},
    ],
  },
  {
    id: "m-nr2-014",
    category: "mouse",
    name: "AJL ワイヤレスマウス",
    brand: "—",
    tagline: "マウス 無線 bluetooth 5.2 + 2.4GHz ワイヤレスマウス Type-C充電式 戻る/進むボタン搭載 3段階DPI切替 ゲーミングマウス 瞬時接続 光学式 高感度 高耐久性 握りの極み デュアルモード オフィス ゲーミング",
    price: 1910,
    rating: 4,
    reviews: 35,
    image: "https://m.media-amazon.com/images/I/61k0LVRPzxL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTYD1H7N",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "120 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "120 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "単4形 乾電池（付属）" },
        ]},
    ],
  },
  {
    id: "m-nr2-015",
    category: "mouse",
    name: "Vootic ワイヤレスマウス",
    brand: "—",
    tagline: "マウス 無線 【極薄型・静音・Type-C充電式】 ワイヤレスマウス Bluetooth5.3 2.4GHz Windows/Mace/PC対応",
    price: 1399,
    rating: 5,
    reviews: 5,
    image: "https://m.media-amazon.com/images/I/41HudOz6u5L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0H8YXFGQQ",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "100 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "100 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "—" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-016",
    category: "mouse",
    name: "BTM010L",
    brand: "TPPT",
    tagline: "TPPT ミニ エルゴノミクス ワイヤレス マウス 静音 5ボタン デュアルモード充電、4段階のDPI調整、RGBライティング効果、左右対称デザイン (BTM010L – 左利き用 – ピンク – Bluetoothデュアルモード)",
    price: 5999,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51UmCxOtyrL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["ergonomic", "silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H98WLQZ9",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "500 g" },
      { label: "最大DPI", value: "2,400 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "500 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "2,400" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },{
    id: "m-nr2-018",
    category: "mouse",
    name: "ワイヤレスマウス",
    brand: "—",
    tagline: "ワイヤレスマウス Bluetooth 2.4GHz両対応 高精度センサー 静音クリック 3段階DPI 軽量 コンパクト RGB呼吸ライト USBレシーバー収納 長時間使用 Type-C充電 日本語取扱説明書",
    price: 1389,
    rating: 5,
    reviews: 2,
    image: "https://m.media-amazon.com/images/I/619iROqEv0L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "3ボタン",
    mouseSpreadsheetUsageSpecs: ["silent"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6X1JLTB",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "94 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "94 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr2-019",
    category: "mouse",
    name: "EZ4-MAWS223BK",
    brand: "ELECOM",
    tagline: "イーサプライ 小型ワイヤレスマウス 2.4GHzレシーバー USB-C充電式 戻る/進む 5ボタン 静音 無線 ラバーコーティング ブラック EZ4-MAWS223BK",
    price: 2580,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61rh+3gWO8L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6WTGMPR",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "39 g" },
      { label: "最大DPI", value: "4,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "39 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "4,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
]
