import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングマウス新着ランキング pg2（2151973051）。マウス本体のみ。 */
export const mouseGamingNewReleasesPage2: Gadget[] = [
  {
    id: "m-gnr2-001",
    category: "mouse",
    name: "AJ159PMCPRO",
    brand: "Ajazz",
    tagline: "A.JAZZ AJ159PMCPRO ゲーミングマウス57±3g超軽量 ワイヤレス2.4G/USB コスパマウス PAW3311センサー | 24000DPI DIY LCDディスプレイ左右対称人間工学 PC/Mac対応 マグネット式充電ドックRGB ゲーミング用 Wind…",
    price: 5399,
    rating: 4.3,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/61tAT18e5XL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZNSNRKK",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "57 g" },
      { label: "最大DPI", value: "24,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "57 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "24,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-002",
    category: "mouse",
    name: "RS3 ULTRA",
    brand: "ATTACK SHARK",
    tagline: "ATTACK SHARK RS3ULTRA ゲーミングマウス ワイヤレス 8000Hz PAW3955MAX 52000DPI 1DPI刻み 約66g | デュアル8K 0.168ms 20000FPS 軽量カーボン複合素材 アイスコーティング 3モード 有線/2.4G/B…",
    price: 14399,
    rating: 4.7,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/81CRkSJHS0L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6SC44MQ",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "66 g" },
      { label: "最大DPI", value: "52,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "66 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "52,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-003",
    category: "mouse",
    name: "Basilisk V3 Pro White",
    brand: "Razer",
    tagline: "Razer(レイザー) Basilisk V3 Pro White ゲーミングマウス ワイヤレス Bluetooth 無線 接続 Focus Pro 30K オプティカルセンサー 30,000DPI 第 3 世代オプティカルマウススイッチ 高速スクロール可能なチルトホイール…",
    price: 11699,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61-KlhO7fJL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3ZXTK76",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "48 g" },
      { label: "最大DPI", value: "20,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "48 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "20,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },{
    id: "m-gnr2-005",
    category: "mouse",
    name: "VM-V1",
    brand: "VARO",
    tagline: "VARO 光学式ゲーミングマウス VM-V1 有線 無線 Bluetooth 対応 超軽量45g 大容量バッテリー",
    price: 19800,
    rating: 3,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/51d6QMsrmtL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZ81FN4M",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["gaming"],
    highlights: [
      { label: "重量", value: "45 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "45 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "—" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-006",
    category: "mouse",
    name: "Cobra Cinnamonroll Edition",
    brand: "Razer",
    tagline: "Razer Cobra 有線ゲーミングマウス 58g 軽量 シナモロール エディション | Gen-3オプティカルスイッチ、Chroma RGBライティングアンダーグロー、8500 DPI光学センサー、100%PTFEマウスフィート、Speedfle",
    price: 12068,
    rating: 4.8,
    reviews: 43,
    image: "https://m.media-amazon.com/images/I/61KooCHXYtL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "4ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTX55LJY",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "58 g" },
      { label: "最大DPI", value: "8,500 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "58 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "8,500" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "4ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gnr2-008",
    category: "mouse",
    name: "R1",
    brand: "MAGIC-REFINER",
    tagline: "MAGIC-REFINER R1 ゲーミングマウス、25000DPI、充電ドック付き、 LCD数値ディスプレイ搭載、超軽量65g 、マクロ対応 | Bluetooth/2.4GHz/有線対応、PAW3311センサー、RGBライティング、低遅延、Broadcom BK3633…",
    price: 3999,
    rating: 4.4,
    reviews: 22,
    image: "https://m.media-amazon.com/images/I/71BX0cRTBTL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYNR4NHP",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "65 g" },
      { label: "最大DPI", value: "25,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "65 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "25,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-009",
    category: "mouse",
    name: "RS3 ULTRA",
    brand: "ATTACK SHARK",
    tagline: "ATTACK SHARK RS3 ULTRA ゲーミングマウス、8KHz、52KDPI、カーボン、1DPI刻み、LOD5段階、Nordic54L15 | 0.168ms低遅延 、20000FPSトラッキング、軽量63g±3g、PAW3955MAXセンサー、3モード(ワイヤレ…",
    price: 6867,
    rating: 4.5,
    reviews: 8,
    image: "https://m.media-amazon.com/images/I/71P3e74FiIL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H6Q55DZQ",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "63 g" },
      { label: "最大DPI", value: "52,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "63 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "52,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gnr2-014",
    category: "mouse",
    name: "KO-ONE WHITE",
    brand: "CRDRAKO",
    tagline: "CRDRAKO KO-ONE WHITE ゲーミングマウス 超軽量35g 液晶ドングル付き ポーリングレート 8,000Hz ワイヤレス 無線 有線(ホワイト) 【国内正規品】",
    price: 19800,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51nDavI0tPL._AC_SL1500_.jpg",
    connection: "有線 USB",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0H1BGXGYQ",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["gaming"],
    highlights: [
      { label: "重量", value: "35 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "35 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "—" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gnr2-015",
    category: "mouse",
    name: "UltralightX Frostlord",
    brand: "Finalmouse",
    tagline: "Finalmouse UltralightX Frostlord ワイヤレスゲーミングマウス, ハニカムデザイン, 軽量, ホワイト(Medium)",
    price: 49800,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51Dbd3Sl4EL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GW1BKC59",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "36 g" },
      { label: "最大DPI", value: "16,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "36 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "16,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-016",
    category: "mouse",
    name: "DeathAdder V4 Pro NiKo Edition",
    brand: "Razer",
    tagline: "Razer レイザー DeathAdder V4 Pro NiKo Edition ゲーミングマウス ワイヤレス 57g 超軽量 8,000Hzドングル同梱 第2世代 Focus Pro 45Kオプティカルセンサー 超低遅延を実現する HyperSp",
    price: 34000,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/718I6BSBSVL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GV244HTD",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "57 g" },
      { label: "最大DPI", value: "45,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "57 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "45,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-017",
    category: "mouse",
    name: "KO-ONE BLACK",
    brand: "CRDRAKO",
    tagline: "CRDRAKO KO-ONE BLACK ゲーミングマウス 超軽量35g 液晶ドングル付き ポーリングレート 8,000Hz ワイヤレス 無線 有線(ブラック) 【国内正規品】",
    price: 31930,
    rating: 4.3,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/71+BbD6RAyL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G3PM7JBD",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "55 g" },
      { label: "最大DPI", value: "33,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "55 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "33,000" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "120 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth, USB, Wi-Fi" }]}],
  },{
    id: "m-gnr2-019",
    category: "mouse",
    name: "CRC-GMRGB03_FP",
    brand: "Century",
    tagline: "センチュリー 「RACEN」 12ボタン搭載 RGBゲーミングマウス CRC-GMRGB03_FP 12ボタン搭載 本体重量100ｇ～118g(ウェイト付属)",
    price: 3981,
    rating: 2,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61l0Lbz4zHL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "12ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3STF4DH",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "100 g" },
      { label: "最大DPI", value: "10,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "100 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "10,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "12ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gnr2-021",
    category: "mouse",
    name: "AJ200NLAIMC",
    brand: "Ajazz",
    tagline: "AJAZZ AJ200NLAIMC ワイヤレス ゲーミングマウス 超軽量61g PAW3311高精度センサー搭載 24000DPI 低遅延 ブラック | NearLink星閃対応 PAW3311高精度センサー 低遅延＆高い通信安定性 500mAh大容量バッテリー AI分析＆…",
    price: 4999,
    rating: 4.6,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/71KJ19ScnBL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB / NearLink",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H7RCMG3X",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "61 g" },
      { label: "最大DPI", value: "24,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "61 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "24,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB / NearLink" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-023",
    category: "mouse",
    name: "AE7 PRO",
    brand: "DAREU",
    tagline: "DAREU AE7PRO 無線8K ゲーミングマウス 準分子コーティング 62g軽量 右手用 人間工学 エルゴノミックス 30000DPI 進化したPAW3950センサー搭載 ワイヤレス 充電スタンド付き 黒/ブラック 技適認証取得【1年間メーカー保証】",
    price: 12880,
    rating: 4.8,
    reviews: 20,
    image: "https://m.media-amazon.com/images/I/619IGKlCGEL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FH6X16SF",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "62 g" },
      { label: "最大DPI", value: "30,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "62 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gnr2-024",
    category: "mouse",
    name: "Stormbreaker V3",
    brand: "PWNAGE",
    tagline: "PWNAGE ストームブレーカー マグネシウム ゲーミングマウス V3 – Nyomi Purple限定版 超軽量人間工学ワイヤレスマウス 8Kポーリング 36K DPI ゼロセンサー センサー位置調整可能 Pro FPSマウス",
    price: 26980,
    rating: 3.8,
    reviews: 1,
    image: "https://m.media-amazon.com/images/I/61p51YUkAHL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GYNMMNX5",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "39 g" },
      { label: "最大DPI", value: "36,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "39 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "36,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  }]
