import type { Gadget } from "./gadgets"

/** Amazon.co.jp ゲーミングマウス売れ筋（2151973051）。マウスソール等アクセサリ除外。 */
export const mouseGamingBestsellers: Gadget[] = [{
    id: "m-gbs-003",
    category: "mouse",
    name: "G PRO 2 LIGHTSPEED G-PPD-002XWL-BK",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G PRO 2 LIGHTSPEED ゲーミングマウスワイヤレス 44K DPI 軽量 80g LIGHTFORCE ハイブリッドスイッチ HERO2 センサー USB Type-C 95時間 POWERPLAY 充電 FPS ゲーミング マウス",
    price: 14200,
    rating: 4.4,
    reviews: 467,
    image: "https://m.media-amazon.com/images/I/51tqDjEoETL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9VVJ967",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "80 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "80 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "8ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "95 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "LIGHTSPEED ワイヤレス" }]}],
  },
    {
    id: "m-gbs-005",
    category: "mouse",
    name: "G203",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングマウス G203 有線 ゲーミング マウス USB 接続 G203-BK 軽量 85g LIGHTSYNC RGB 6個プログラムボタン ブラック PC windows mac 国内正規品",
    price: 3727,
    rating: 4.4,
    reviews: 3286,
    image: "https://m.media-amazon.com/images/I/61eElLlfVDL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B087BTXHX4",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "85 g" },
      { label: "最大DPI", value: "8,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "85 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "8,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
    {
    id: "m-gbs-007",
    category: "mouse",
    name: "Viper V3 Pro White Edition",
    brand: "Razer",
    tagline: "【8000Hzドングル同梱・超軽量55g】Razer Viper V3 Pro White Edition ゲーミングマウス ワイヤレス 無線 Focus Pro 35Kセンサー 35000DPI 高速応答 オプティカルスイッチ 6ボタン",
    price: 18164,
    rating: 4.5,
    reviews: 582,
    image: "https://m.media-amazon.com/images/I/619xpFKAXPL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D1X5B9PC",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "55 g" },
      { label: "最大DPI", value: "35,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "55 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "35,000" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "95 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "USB, Razer HyperSpeed Wireless" }]}],
  },
  {
    id: "m-gbs-008",
    category: "mouse",
    name: "PRO X SUPERLIGHT 2 G-PPD-004WL-BK",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G PRO X SUPERLIGHT 2 ゲーミングマウス G-PPD-004WL-BKd | 8000Hz ポーリングレート ワイヤレス 軽量 60g LIGHTFORCE ハイブリッドスイッチ HERO2 センサー U…",
    price: 24500,
    rating: 4.5,
    reviews: 730,
    image: "https://m.media-amazon.com/images/I/51aHtlvwrGL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D21Q6QG4",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "32,000" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "95 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "LIGHTSPEEDワイヤレスレシーバー" }]}],
  },
  {
    id: "m-gbs-009",
    category: "mouse",
    name: "G502 G502RGBhr",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングマウス G502 有線 USB 接続 マウス HERO 25Kセンサー G502RGBhr LIGHTSYNC RGB 11個プログラムボタン FPS / MMO / RPG ブラック PC windows mac 国内正規品 【 ファイナル…",
    price: 7627,
    rating: 4.5,
    reviews: 2502,
    image: "https://m.media-amazon.com/images/I/51d10VscHOL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "11ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08CKZ9TSY",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "121 g" },
      { label: "最大DPI", value: "25,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "25,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "11ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gbs-010",
    category: "mouse",
    name: "CrazyLight Series",
    brand: "Pulsar",
    tagline: "Pulsar Gaming Gears CrazyLight Series ワイヤレス ゲーミングマウス 超軽量 44グラム 1ms 32000 DPI Optical swhich XS-1 Flagship Sensor 国内正規品",
    price: 15500,
    rating: 4.3,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/51lEUb7dKvL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "7ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G5Y7BYF1",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "44 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "44 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "32,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "7ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gbs-013",
    category: "mouse",
    name: "G502 LIGHTSPEED G502WL",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングマウス G502WL LIGHTSPEED ワイヤレス ゲーミング マウス HERO 25K センサー LIGHTSYNC RGB 11個プログラムボタン POWERPLAY 無線 充電 対応 ブラック PC windows mac G502…",
    price: 13109,
    rating: 4.5,
    reviews: 2806,
    image: "https://m.media-amazon.com/images/I/51wEAqspqTL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "11ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07RR94VQT",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "114 g" },
      { label: "最大DPI", value: "25,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "114 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "25,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "11ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "60 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "LIGHTSPEEDワイヤレス" }]}],
  },
    {
    id: "m-gbs-017",
    category: "mouse",
    name: "Logicool G ゲーミングマウス G403h HERO",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G ゲーミングマウス G403h HERO 有線 軽量 87g ゲーミング マウス 有線マウス 25Kセンサー エルゴノミクス LIGHTSYNC RGB PC windows mac G403 ブラック 国内正規品 ※A…",
    price: 8700,
    rating: 4.4,
    reviews: 3730,
    image: "https://m.media-amazon.com/images/I/418VFOE9V6L._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07T4BHZ7J",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "87 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "87 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "25,600" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
  {
    id: "m-gbs-018",
    category: "mouse",
    name: "PAW3395",
    brand: "ATK",
    tagline: "ATK ワイヤレス ゲーミングマウス VXE Dragonfly R1 SE+ Black 軽量55グラム Pixart PAW3395 SE搭載 最大70時間 無線有線両対応 国内正規品",
    price: 4073,
    rating: 4.1,
    reviews: 94,
    image: "https://m.media-amazon.com/images/I/414GwfH8eKL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DBVQF5Y8",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "55 g" },
      { label: "最大DPI", value: "18,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "55 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "18,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "70 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
  {
    id: "m-gbs-019",
    category: "mouse",
    name: "M908 Impact RGB LED MMO ゲーミングマウス、12サイドボタン、光学式有線エルゴノミクスゲーマーマウス、最大12,40…",
    brand: "Redragon",
    tagline: "Redragon M908 Impact RGB LED MMO ゲーミングマウス、12サイドボタン、光学式有線エルゴノミクスゲーマーマウス、最大12,400DPI、高精度、20プログラム可能マクロショートカット、コンフォートグリップ付き",
    price: 4999,
    rating: 4.2,
    reviews: 8546,
    image: "https://m.media-amazon.com/images/I/61kI0PIuXVL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "18ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07FK9PKSM",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "280 g" },
      { label: "最大DPI", value: "12,400 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "280 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "12,400" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "18ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "レーザー" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
  {
    id: "m-gbs-020",
    category: "mouse",
    name: "SCIMITAR ELITE WIRELESS CH-9314011-AP",
    brand: "CORSAIR",
    tagline: "CORSAIR SCIMITAR ELITE WIRELESS SE MMO向け ワイヤレスゲーミングマウス 16ボタン プログラム可能 ホワイト",
    price: 15091,
    rating: 4,
    reviews: 67,
    image: "https://m.media-amazon.com/images/I/61owvr27BLL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0F7M6WN7K",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    highlights: [
      { label: "重量", value: "114 g" },
      { label: "最大DPI", value: "33,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "114 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "33,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "16ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "150 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth, USB, Wi-Fi" }]}],
  },
  {
    id: "m-gbs-021",
    category: "mouse",
    name: "Razer レイザー DeathAdde",
    brand: "Razer",
    tagline: "Razer レイザー DeathAdder V4 Pro ゲーミングマウス ワイヤレス 無線 56gの超軽量 8,000Hzドングル同梱 高精度の第2世代 Focus Pro 45K オプティカルセンサー 超低遅延を実現する第2世代 HyperSpeed Wireless オプティカルスクロールホイール 第4世代 オプティカルマウススイッチ 150時間のバッテリー駆動 【日本正規代理店保証品】",
    price: 22200,
    rating: 4.5,
    reviews: 87,
    image: "https://m.media-amazon.com/images/I/71j6PDIwegL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FGPY2NQH",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "56 g" },
      { label: "最大DPI", value: "45,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "56 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "45,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gbs-024",
    category: "mouse",
    name: "G402",
    brand: "Logicool G",
    tagline: "Logicool G ゲーミングマウス G402 有線 ゲーミング マウス USB 接続 FPS ゲーム向け 4段階DPI切り替え 8個プログラムボタン ブラック PC windows mac 国内正規品",
    price: 4564,
    rating: 4.3,
    reviews: 2982,
    image: "https://m.media-amazon.com/images/I/51BG1TU57LL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B00MCIIX1G",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "108 g" },
      { label: "最大DPI", value: "4,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "108 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "4,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "8ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
    {
    id: "m-gbs-027",
    category: "mouse",
    name: "X11 ゲーミングマウス ワイヤレス 無線 2.4g/Bluetooth/USB-C 超軽量63g 22000DPI（ホワイト）",
    brand: "ATTACK SHARK",
    tagline: "ATTACK SHARK X11 ゲーミングマウス ワイヤレス 無線 2.4g/Bluetooth/USB-C 超軽量63g 22000DPI（ホワイト）",
    price: 4599,
    rating: 4.2,
    reviews: 52,
    image: "https://m.media-amazon.com/images/I/51fyy80NI1L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D3G6PFM7",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "62 g" },
      { label: "最大DPI", value: "22,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "62 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "22,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "65 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth, USB" }]}],
  },
  {
    id: "m-gbs-028",
    category: "mouse",
    name: "Glorious グロリアス モデルo ゲーミングマウス 白 有線 マウス 軽量 ゲーム用 RGB 6個プログラムボタン USB 白 マウ…",
    brand: "—",
    tagline: "Glorious グロリアス モデルo ゲーミングマウス 白 有線 マウス 軽量 ゲーム用 RGB 6個プログラムボタン USB 白 マウス 国内正規品",
    price: 4990,
    rating: 4,
    reviews: 7784,
    image: "https://m.media-amazon.com/images/I/61psCUSZnpL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07VRQWBMR",
        mouseUsage: "gaming",
    highlights: [
      { label: "重量", value: "58 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "58 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gbs-029",
    category: "mouse",
    name: "V3PRO PAW3311",
    brand: "ATTACK SHARK",
    tagline: "ATTACK SHARK V3PRO ゲーミングマウス 3モードワイヤレス/ 有線/2.4G接続 65g軽量マウス PAW3311センサー | アタックシャークマウス BK52820 MCU 右利き用カーブド RGBマグネット充電スタンド エルゴノミクス設計DPI25000…",
    price: 3220,
    rating: 4,
    reviews: 59,
    image: "https://m.media-amazon.com/images/I/61zTdmKziDL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G24THVLJ",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "66 g" },
      { label: "最大DPI", value: "25,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "1,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "66 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "25,000" },
          { label: "ポーリングレート", value: "1,000 Hz" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
  {
    id: "m-gbs-030",
    category: "mouse",
    name: "V3　PAW3311",
    brand: "ATTACK SHARK",
    tagline: "ATTACK SHARK V3 マウス 軽量 無線 中大手 ワイヤレスゲーミングマウス ゲーム・オフィス兼用 仕事 500mAh大容量バッテリー | 62g PAW3311光学センサー 25,000dpi 右手エルゴノミクスデザイン 3モード接続(2.4G/BT/USB-C…",
    price: 2969,
    rating: 4.7,
    reviews: 30,
    image: "https://m.media-amazon.com/images/I/51haPNGhitL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "7ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0G1H1QZTP",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "62 g" },
      { label: "最大DPI", value: "25,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "62 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "25,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "7ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gbs-031",
    category: "mouse",
    name: "レイザー Basilisk V3 Pro ゲーミングマウス ワイヤレス Bluetooth 無線 接続 Focus Pro 30K オプテ…",
    brand: "Razer",
    tagline: "Razer レイザー Basilisk V3 Pro ゲーミングマウス ワイヤレス Bluetooth 無線 接続 Focus Pro 30K オプティカルセンサー 30,000DPI 第 3 世代オプティカルマウススイッチ 高速スクロール可能なチル",
    price: 17859,
    rating: 4.3,
    reviews: 129,
    image: "https://m.media-amazon.com/images/I/71mrcB4eVJL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "11ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BGS1KQ68",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "111 g" },
      { label: "最大DPI", value: "30,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "30,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "11ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "サイドホイール", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth" }]}],
  },
  {
    id: "m-gbs-032",
    category: "mouse",
    name: "DeathAdder V2 X HyperSpeed ゲーミングマウス 9ボタン 受賞歴を誇るエルゴノミクスデザイン HyperSpeed…",
    brand: "Razer",
    tagline: "Razer DeathAdder V2 X HyperSpeed ゲーミングマウス 9ボタン 受賞歴を誇るエルゴノミクスデザイン HyperSpeed Wireless 最大 235 時間バッテリー持続 第 2 世代メカニカルマウススイッチ 14,0",
    price: 3480,
    rating: 4.1,
    reviews: 380,
    image: "https://m.media-amazon.com/images/I/71TLjnQYxzL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "9ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B09KNM6V9Q",
        mouseUsage: "gaming",
    mouseFilterTags: ["side-buttons"],
    highlights: [
      { label: "重量", value: "102 g" },
      { label: "最大DPI", value: "14,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "102 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "14,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "9ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "単3形 乾電池（付属）" }]}],
  },{
    id: "m-gbs-034",
    category: "mouse",
    name: "Rival 3 Gen 2",
    brand: "SteelSeries",
    tagline: "SteelSeries ゲーミングマウス 有線 軽量 低遅延 1.35ms 高耐久 8,500DPI メカニカルスイッチ 絡まり防止 PTFE(テフロン)ソール 3ゾーンRGBイルミネーション Rival 3 Gen 2 62515 ブラック",
    price: 5073,
    rating: 4.5,
    reviews: 359,
    image: "https://m.media-amazon.com/images/I/51+n4w7IRqL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "2ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0F5QBSRDR",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "106 g" },
      { label: "最大DPI", value: "8,500 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "106 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "8,500" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "2ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gbs-035",
    category: "mouse",
    name: "M913インパクトエリートワイヤレスゲーミングマウス、16000 DPI有線/無線RGBゲーマーマウス、16プログラマブルボタン、45時間…",
    brand: "Redragon",
    tagline: "Redragon M913インパクトエリートワイヤレスゲーミングマウス、16000 DPI有線/無線RGBゲーマーマウス、16プログラマブルボタン、45時間バッテリーとプロ光学式センサー、12サイドボタンMMOマウス | FPSゲーマー専用のケーブル不要の0遅延、キーバイン…",
    price: 7999,
    rating: 4.2,
    reviews: 6496,
    image: "https://m.media-amazon.com/images/I/61C7blR0ZAL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "16ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B088B3ZM76",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "132 g" },
      { label: "最大DPI", value: "16,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "132 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "16,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "16ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "45 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
  {
    id: "m-gbs-036",
    category: "mouse",
    name: "e元素 X-53",
    brand: "—",
    tagline: "ワイヤレスゲーミングマウス Bluetooth/2.4G無線/有線 6 プログラマブルボタン 充電式 RGBバックライト ホワイト軽量67グラム,トリプルモード, ソフトウェアで最大10000DPIまで調整可能,6ボタンカスタマイズ可能",
    price: 3988,
    rating: 4,
    reviews: 27,
    image: "https://m.media-amazon.com/images/I/51z2jcYnF-L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / USB-C",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GBTSQXRZ",
        mouseUsage: "gaming",
    mouseFilterTags: ["side-buttons"],
    highlights: [
      { label: "重量", value: "76 g" },
      { label: "最大DPI", value: "10,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "76 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "10,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / USB-C" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gbs-037",
    category: "mouse",
    name: "V8 Black ゲーミングマウス 8000hz 重量36±3g 左右対称 - Kailh Optical スイッチ【国内正規品】",
    brand: "SCYROX",
    tagline: "SCYROX V8 Black ゲーミングマウス 8000hz 重量36±3g 左右対称 - Kailh Optical スイッチ【国内正規品】",
    price: 3480,
    rating: 4.1,
    reviews: 259,
    image: "https://m.media-amazon.com/images/I/71P7NtVKSsS._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0876B7592",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "180 g" },
      { label: "最大DPI", value: "6,400 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "180 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "6,400" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
    {
    id: "m-gbs-040",
    category: "mouse",
    name: "M910-WS",
    brand: "Redragon",
    tagline: "Redragon M910-WS ワイヤレスゲーミングマウス 8000DPI RGB 70時間駆動 | エルゴノミクス設計 ゲーム・オフィス・トラベルに最適 1,680万色RGB 充電式 ホワイトマウス PC・Mac対応",
    price: 3909,
    rating: 4.4,
    reviews: 5598,
    image: "https://m.media-amazon.com/images/I/61aTUUe-bML._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "9ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BW8DB72Z",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "135 g" },
      { label: "最大DPI", value: "8,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "8,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "9ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gbs-041",
    category: "mouse",
    name: "X11SE",
    brand: "ATTACK SHARK",
    tagline: "ATTACK SHARK X11SE ゲーミングマウス スーパーライト 3モード接続 ワイヤレス 無線2.4g/Bluetooth/USB-C | 超軽量 59gPAW3311センサー 22000DPI 6レベルDPI切替 1000Hz ポーリングレート、300mAh、（ベ…",
    price: 2231,
    rating: 4.4,
    reviews: 43,
    image: "https://m.media-amazon.com/images/I/51Vl26fmcPL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FBGFM6B1",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "59 g" },
      { label: "最大DPI", value: "22,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "59 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "22,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gbs-043",
    category: "mouse",
    name: "Viper V3 Pro SE",
    brand: "Razer",
    tagline: "Razer レイザー Viper V3 Pro SE ゲーミングマウス 1000Hzドングル同梱 ワイヤレス 無線 超軽量54g 第 2 世代 Focus Pro 35Kセンサー 35000DPI 最大95時間駆動 高速無線 オプティカルスイッチ 6ボタン USB Type C",
    price: 17480,
    rating: 4.6,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/61fPqQWtXfL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / 有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GCC7TQ3D",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "54 g" },
      { label: "最大DPI", value: "35,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "1,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "54 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "35,000" },
          { label: "ポーリングレート", value: "1,000 Hz" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / 有線 USB" },
          { label: "電源", value: "充電式" },
          { label: "電池持続", value: "95 Hours" },
          { label: "通信インターフェース（Amazon記載）", value: "有線(USB A) / 無線(USB A)" }]}],
  },
  {
    id: "m-gbs-044",
    category: "mouse",
    name: "(レッドドラゴン) M612 RGBゲーミングマウス、8000 DPI 有線光学マウス プログラム可能なボタン9個＆バックライトモード5つ…",
    brand: "Redragon",
    tagline: "Redragon(レッドドラゴン) M612 RGBゲーミングマウス、8000 DPI 有線光学マウス プログラム可能なボタン9個＆バックライトモード5つ、ソフトウェアはDIYキーバインド、ラピッドファイアボタン対応、グレー＆ホワイト",
    price: 3599,
    rating: 4.5,
    reviews: 11198,
    image: "https://m.media-amazon.com/images/I/516+KFMihPL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "9ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D2W7NV97",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "170 g" },
      { label: "最大DPI", value: "8,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "170 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "8,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gbs-045",
    category: "mouse",
    name: "ATTACK SHARK X3　PAW3395",
    brand: "ATTACK SHARK",
    tagline: "ATTACK SHARK X3 超軽量化マウス49g ゲーミングマウス ワイヤレス2.4G/Bluetooth/有線 PAW3395 26000DPI",
    price: 5299,
    rating: 4.2,
    reviews: 192,
    image: "https://m.media-amazon.com/images/I/51caYlmLetL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0CCDV5JHX",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["gaming"],
    highlights: [
      { label: "重量", value: "49 g" },
      { label: "最大DPI", value: "26,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "49 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "26,000" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gbs-046",
    category: "mouse",
    name: "PAW3950",
    brand: "—",
    tagline: "GravaStar MERCURY X PRO ワイヤレス ゲーミングマウス マグネシウム合金 無線 49g超軽量 8Kポーリングレート | 8000Hzドングル同梱 PAW3950搭載 32,000DPI 高速無線 Webブラウザ設定 プログラム対応 2.4GHz/Blu…",
    price: 20980,
    rating: 4.4,
    reviews: 585,
    image: "https://m.media-amazon.com/images/I/61bL5gKKFUL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DRJ8FC3B",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "49 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "49 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "32,000" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth / 有線 USB" },
          { label: "電源", value: "バッテリー式" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  },
  {
    id: "m-gbs-047",
    category: "mouse",
    name: "ゲーミングマウス Kone XP Air",
    brand: "—",
    tagline: "タートルビーチ(Turtle Beach) ワイヤレス 2.4GHz/Bluetooth ブラック/黒 光学式 19K オプティカル 多ボタン 99g 充電ドック Reflex RGB 国内正規品",
    price: 17834,
    rating: 3.9,
    reviews: 371,
    image: "https://m.media-amazon.com/images/I/611m1kXvz8L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "10ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D1CTCP8D",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "99 g" },
      { label: "最大DPI", value: "19,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "99 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  },
    {
    id: "m-gbs-049",
    category: "mouse",
    name: "FORGE GM100",
    brand: "MSI",
    tagline: "MSI FORGE GM100 オプティカル ゲーミングマウス 有線 MS0716",
    price: 1950,
    rating: 4,
    reviews: 129,
    image: "https://m.media-amazon.com/images/I/613GpV6ybdL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "7ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D25MNB15",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "108 g" },
      { label: "最大DPI", value: "6,400 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "108 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "7ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "センサー", value: "光学" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" },
          { label: "通信インターフェース（Amazon記載）", value: "USB" }]}],
  }]
