import type { Gadget } from "./gadgets"

/** Amazon.co.jp マウス新着ランキング pg1（2151978051）。マウス本体のみ。 */
export const mouseNewReleases: Gadget[] = [
  {
    id: "m-nr-001",
    category: "mouse",
    name: "Slint M-TM25MBMSABK",
    brand: "ELECOM",
    tagline: "エレコム ワイヤレスマウス 静音 Slint Bluetooth 無線2.4GHz 3台マルチペアリング 薄型 軽量 充電式 Mサイズ ブラック M-TM25MBMSABK",
    price: 2499,
    rating: 4.2,
    reviews: 79,
    image: "https://m.media-amazon.com/images/I/618NWiOGOnL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "4ボタン",
    mouseSpreadsheetUsageSpecs: ["silent"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H1JVHGD3",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "64 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "BlueLED" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "64 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "読み取り方式", value: "BlueLED" },
          { label: "ボタン数", value: "4ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth, USB" },
        ]},
    ],
  },
  {
    id: "m-nr-002",
    category: "mouse",
    name: "Mucuru ワイヤレス静音マウス",
    brand: "—",
    tagline: "マウス 無線 静音 ワイヤレスマウス Bluetooth 5.4 2.4GHz Type-C 充電式 無線マウス 薄型 3段階DPI切替",
    price: 1468,
    rating: 4,
    reviews: 55,
    image: "https://m.media-amazon.com/images/I/61hPNLS4DlL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0H74SGFVW",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "70 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
          { label: "サイドボタン", value: "あり" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },{
    id: "m-nr-004",
    category: "mouse",
    name: "縦型ワイヤレスマウス 充電式 【2026 強化版 】Bluetoothマウス エルゴノミクスマウス 6 ボタン搭載 高精度 800/120…",
    brand: "—",
    tagline: "縦型ワイヤレスマウス 充電式 【2026 強化版 】Bluetoothマウス エルゴノミクスマウス 6 ボタン搭載 高精度 800/1200/1600DPI 切替 2.4G 無線光学式 手首・肩の疲れ緩和 省電力スリープ機能付き USB 充電ケーブル付属 Windows、M…",
    price: 2498,
    rating: 2.6,
    reviews: 28,
    image: "https://m.media-amazon.com/images/I/618nFglsCBL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["ergonomic", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H7LM2MV5",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","reading-trackball","side-buttons"],
    highlights: [
      { label: "重量", value: "140 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "140 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" },
          { label: "サイドボタン", value: "あり" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-005",
    category: "mouse",
    name: "OSMOD8 M-MY50MBSBK-G",
    brand: "ELECOM",
    tagline: "エレコム ワイヤレスマウス OSMOD8 静音 Bluetooth 無線2.4GHz 3台マルチペアリング 高速スクロール＋チルトホイール搭載 Mサイズ ブラック M-MY50MBSBK-G",
    price: 3990,
    rating: 3.9,
    reviews: 80,
    image: "https://m.media-amazon.com/images/I/617yiJgT26L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVDZCKTN",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "89 g" },
      { label: "最大DPI", value: "1,000 DPI" },
      { label: "読み取り方式", value: "BlueLED" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "89 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,000" },
          { label: "読み取り方式", value: "BlueLED" },
          { label: "ボタン数", value: "8ボタン" },
          { label: "サイドボタン", value: "あり" },
          { label: "サイドホイール", value: "あり" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "単3形乾電池×1本" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth, USB" },
        ]},
    ],
  },
  {
    id: "m-nr-006",
    category: "mouse",
    name: "M840LGRd",
    brand: "Logicool",
    tagline: "ロジクール ワイヤレスマウス 静音 高速スクロール 無線 Signature Comfort Plus M840LGRd グラファイト 国内正規品",
    price: 6100,
    rating: 4.1,
    reviews: 14,
    image: "https://m.media-amazon.com/images/I/61vnVVbl1oL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJ8FWK42",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "103 g" },
      { label: "最大DPI", value: "4,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "103 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "4,000" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
          { label: "サイドボタン", value: "あり" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "単3形乾電池×1本" },
          { label: "電池持続", value: "24 月" },
          { label: "通信インターフェース（Amazon記載）", value: "Bluetooth, Logi Bolt" },
        ]},
    ],
  },
  {
    id: "m-nr-007",
    category: "mouse",
    name: "Mobi Fold MF900",
    brand: "Logicool",
    tagline: "マウス Bluetooth 無線 【人間工学設計・静音】 Bluetooth＆2.4GHz接続 ワイヤレスマウス 軽量 戻る進むボタン搭載 5ボタン Type-C充電式 3段階DPI切替 800/1200/1600 USBレシーバー付",
    price: 1709,
    rating: 4.1,
    reviews: 72,
    image: "https://m.media-amazon.com/images/I/619LHWTrpLL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GL22BBQ7",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "—" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "—" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "—" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-009",
    category: "mouse",
    name: "TECKNET マウス",
    brand: "Technet",
    tagline: "TECKNET マウス 無線 Bluetooth 2.4GHz 静音 4800DPI 6段階調整 エルゴノミクス ワイヤレスマウス Type-C充電 6ボタン 同時接続可能 Windows/macOS/Chrome/Linux対応 戻る/進むボタン搭載 持ち運び プログラマ…",
    price: 2799,
    rating: 4.5,
    reviews: 10280,
    image: "https://m.media-amazon.com/images/I/61ohmYmNccL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["ergonomic", "silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GVYRXBTJ",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "150 g" },
      { label: "最大DPI", value: "4,800 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "4,800" },
          { label: "サイドボタン", value: "あり" },
          { label: "ボタン数", value: "6ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電池持続", value: "3 月" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-010",
    category: "mouse",
    name: "MAWB231BK",
    brand: "Sanwa Direct",
    tagline: "サンワダイレクト ペン型マウス Bluetooth 5ボタン 【戻る・進む】 DPI切り替え 充電式 無線 ブラック 400-MAWB231BK | ワイヤレス USB A/Type-Cレシーバー 持ち運び プレゼンテーション 出張",
    price: 5680,
    rating: 3.6,
    reviews: 32,
    image: "https://m.media-amazon.com/images/I/51lxEvICobL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["side-button", "pen-mouse"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3RDXM7N",
    mouseUsage: "productivity",
    mouseFilterTags: ["side-buttons"],
    highlights: [
      { label: "重量", value: "25 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "25 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-011",
    category: "mouse",
    name: "SPK7538B",
    brand: "—",
    tagline: "フィリップス ワイヤレスマウス SPK7538B 静音 Bluetooth/USB接続 2台同時接続 DPI切替可 レギュラー 軽量 電池式 ブラック | 無線 800/1200/1600DPI切替 Windows/mac/Chromebook/iPad OS/iOSなど対…",
    price: 2286,
    rating: 4.7,
    reviews: 44,
    image: "https://m.media-amazon.com/images/I/51CRYVc22bL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0H3STBK7T",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "62 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "62 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "単3形 乾電池" },
        ]},
    ],
  },
  {
    id: "m-nr-014",
    category: "mouse",
    name: "QEIKI ワイヤレスマウス",
    brand: "—",
    tagline: "マウス 無線 ワイャレスマウス【超薄型&Type-C充電式] 静音3DPIモ-ド 2.4GHz 7色ライト 光学式節電モデル 持ち運び便利 簡単接続 小型 高耐久性 八ソコン",
    price: 599,
    rating: 4,
    reviews: 21,
    image: "https://m.media-amazon.com/images/I/61s-GbClqVL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0H28N4Z2Z",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "75 g" },
      { label: "最大DPI", value: "—" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-016",
    category: "mouse",
    name: "PDFASTW ワイヤレスマウス",
    brand: "—",
    tagline: "静音 Mouse Bluetooth 5.2 2.4GHz Type-C 充電式 無線マウス 高感度 3段階DPI切替 シルバー",
    price: 998,
    rating: 4.8,
    reviews: 9,
    image: "https://m.media-amazon.com/images/I/51wxGOEVDCL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0H2MRJK6B",
    mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "—" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "—" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-017",
    category: "mouse",
    name: "BSMBB115RD",
    brand: "Buffalo",
    tagline: "バッファロー マウス Bluetooth 5.1 ワイヤレス 静音 3ボタン BlueLED 左右対称 カーソル速度切り替え BSMBB115RD",
    price: 1680,
    rating: 4.4,
    reviews: 19,
    image: "https://m.media-amazon.com/images/I/71zm8i3koXL._AC_SL1500_.jpg",
    connection: "Bluetooth",
    mouseSpreadsheetButtonCount: "3ボタン",
    mouseSpreadsheetUsageSpecs: ["silent"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZYS8KX7",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "BlueLED" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "BlueLED" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "Bluetooth" },
          { label: "電源", value: "単3形乾電池×1本" },
        ]},
    ],
  },
  {
    id: "m-nr-018",
    category: "mouse",
    name: "MAWB220",
    brand: "Sanwa Direct",
    tagline: "サンワダイレクト マウス 無線 Bluetooth 高速スクロール サイドホイール 5ボタン 静音 マルチペアリング 充電式 400-MAWB220 | DPI切換え",
    price: 1216,
    rating: 4.3,
    reviews: 3,
    image: "https://m.media-amazon.com/images/I/41QVqTzFF8L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZ9XGF12",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "121 g" },
      { label: "最大DPI", value: "6,400 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ボタン数", value: "2ボタン" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "121 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "マウス最大感度", value: "1,600 DPI" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-019",
    category: "mouse",
    name: "MAWB220",
    brand: "Sanwa Direct",
    tagline: "サンワダイレクト マウス 無線 Bluetooth 高速スクロール サイドホイール 5ボタン 静音 マルチペアリング 充電式 400-MAWB220 | DPI切換え",
    price: 7980,
    rating: 3.7,
    reviews: 26,
    image: "https://m.media-amazon.com/images/I/71W1nqiaUdL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["silent", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GZ21VMVB",
    mouseUsage: "productivity",
    mouseFilterTags: ["side-buttons"],
    highlights: [
      { label: "重量", value: "121 g" },
      { label: "最大DPI", value: "6,400 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "121 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "6,400" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-020",
    category: "mouse",
    name: "ワイヤレスマウス超薄型＆Type-C充電式",
    brand: "—",
    tagline: "マウス 無線 ワイヤレスマウス超薄型＆Type-C充電式bluetooth 高精度 高感度 静音 3段階DPI切替 2.4GHz 小型 光学式 左右対称 ブルートゥース コンパクト 軽量 握りやすい 簡単接続 持ち運び便利",
    price: 1460,
    rating: 4.2,
    reviews: 13,
    image: "https://m.media-amazon.com/images/I/51eSRuqduDL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0H23M9892",
    mouseUsage: "productivity",
    mouseFilterTags: ["reading-optical"],
    mouseSpreadsheetUsageSpecs: ["silent"],
    highlights: [
      { label: "重量", value: "63 g" },
      { label: "最大DPI", value: "1,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "63 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "1,600" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
  {
    id: "m-nr-021",
    category: "mouse",
    name: "ECHTPower エルゴノミクスマウス",
    brand: "—",
    tagline: "ECHTPower エルゴノミクスマウス ワイヤレス 縦型 無線2.4GHz 静音 腱鞘炎防止",
    price: 2469,
    rating: 0,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/61oXQ3hcLNL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",

    purchaseUrl: "https://www.amazon.co.jp/dp/B0H9QSGQ2N",
    mouseUsage: "productivity",
    mouseSpreadsheetUsageSpecs: ["ergonomic", "silent"],
    highlights: [
      { label: "重量", value: "100 g" },
      { label: "最大DPI", value: "3,200 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "100 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "最大 DPI", value: "3,200" },
          { label: "ポーリングレート", value: "—" },
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "3ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },{
    id: "m-nr-025",
    category: "mouse",
    name: "Pulsar Gaming Gears [Pro Series] Susanto-X Medium ワイヤレス ゲーミングマウス 50グラ…",
    brand: "—",
    tagline: "Pulsar Gaming Gears [Pro Series] Susanto-X Medium ワイヤレス ゲーミングマウス 50グラム 1ms 32000 DPI Optical swhich XS-1 Flagship Sensor 国内正規品(Susanto-X,…",
    price: 19800,
    rating: 5,
    reviews: 4,
    image: "https://m.media-amazon.com/images/I/51jyiBBQMkL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "7ボタン",
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FQD181ZV",
    mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "50 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" },
    ],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "50 g" },
        ]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "7ボタン" },
        ]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" },
        ]},
    ],
  },
]
