import type { Gadget } from "./gadgets"

/** Amazon.co.jp gpro 検索（/gpro/s?k=gpro）。Logicool G PRO マウス本体のみ。 */
export const mouseGProSearch: Gadget[] = [{
    id: "m-gpro-005",
    category: "mouse",
    name: "PRO X2 SUPERSTRIKE G-PPD-004WL-STRKD",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G PRO X2 SUPERSTRIKE ゲーミングマウス G-PPD-004WL-STRKdラピッドトリガー 8000Hz ポーリングレート 軽量 61g ハプティック誘導トリガーシステム HITS 90時間 HERO2 USB Type-C 充電 POWERPLA",
    price: 26500,
    rating: 4.5,
    reviews: 326,
    image: "https://m.media-amazon.com/images/I/61bPoEYL6RL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GGX35X72",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "61 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "61 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-006",
    category: "mouse",
    name: "G PRO X SUPERLIGHT 2 SE G-PPD-004WLSE-BK",
    brand: "Logicool G",
    tagline: "Logicool G PRO X SUPERLIGHT 2 SE 44K DPI ワイヤレス ゲーミングマウス G-PPD-004WLSE-BK 軽量 60g LIGHTFORCE ハイブリッドスイッチ LIGHTSPEED HERO2 センサー USB Type-C 88時間連続使用可能",
    price: 16445,
    rating: 4.5,
    reviews: 84,
    image: "https://m.media-amazon.com/images/I/51nEL5eX9UL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FPRQPGT7",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },{
    id: "m-gpro-008",
    category: "mouse",
    name: "G PRO X SUPERLIGHT 2 SE G-PPD-004WLSE-WH",
    brand: "Logicool G",
    tagline: "Logicool G PRO X SUPERLIGHT 2 SE 44K DPI ワイヤレス ゲーミングマウス G-PPD-004WLSE-WH 軽量 60g LIGHTFORCE ハイブリッドスイッチ LIGHTSPEED HERO2 センサー USB Type-C 88時間連続使用可能 POWERPLAY",
    price: 16445,
    rating: 4.5,
    reviews: 84,
    image: "https://m.media-amazon.com/images/I/51yijJiwCqL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FPRZTG3G",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-009",
    category: "mouse",
    name: "G PRO 2 LIGHTSPEED G-PPD-002XWL-MG",
    brand: "Logicool G",
    tagline: "Logicool G PRO 2 LIGHTSPEED 44K DPI ワイヤレス ゲーミングマウス G-PPD-002XWL-MG 軽量 80g LIGHTFORCE ハイブリッドスイッチ HERO2 センサー USB Type-C 95時間連続使用可能 POWERPLAY 無線 充電 対応 FPS ゲーミング マウス",
    price: 13327,
    rating: 4.4,
    reviews: 467,
    image: "https://m.media-amazon.com/images/I/51UonxhjjDL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DF2B7TTJ",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "80 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "80 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "8ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-010",
    category: "mouse",
    name: "G PRO 2 LIGHTSPEED G-PPD-002XWL-WH",
    brand: "Logicool G",
    tagline: "Logicool G PRO 2 LIGHTSPEED 44K DPI ワイヤレス ゲーミングマウス G-PPD-002XWL-WH 軽量 80g LIGHTFORCE ハイブリッドスイッチ HERO2 センサー USB Type-C 95時間連続使用可能 POWERPLAY 無線 充電 対応 FPS ゲーミング マウス",
    price: 13327,
    rating: 4.4,
    reviews: 467,
    image: "https://m.media-amazon.com/images/I/51YpsPns6tL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0DF2J64VN",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "80 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "80 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "8ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },{
    id: "m-gpro-012",
    category: "mouse",
    name: "PRO X2 SUPERSTRIKE G-PPD-004WL-STRK",
    brand: "Logicool G",
    tagline: "Logicool G Rapid Trigger PRO X2 SUPERSTRIKE LIGHTSPEED Gaming Mouse, G-PPD-004WL-STRK 8000, Polling Rate, Lightweight, 2.2 oz (61 g), Hap…",
    price: 25800,
    rating: 4.5,
    reviews: 326,
    image: "https://m.media-amazon.com/images/I/61bPoEYL6RL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GGWQ7HZ2",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "61 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "61 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-013",
    category: "mouse",
    name: "G PRO X SUPERLIGHT 2 G-PPD-004WL-CY",
    brand: "Logicool G",
    tagline: "Logicool G 8000Hz ポーリングレート PRO X SUPERLIGHT 2 ワイヤレス ゲーミングマウス G-PPD-004WL-CY軽量 60g LIGHTFORCE ハイブリッドスイッチ LIGHTSPEED HERO2 センサー USB Type-C 充電 POWERPLAY 対応 ゲーミング マウス",
    price: 24500,
    rating: 4.4,
    reviews: 10,
    image: "https://m.media-amazon.com/images/I/510-BuaT96L._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GTWJM48D",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-014",
    category: "mouse",
    name: "G PRO X SUPERLIGHT 2 DEX GPROXSL-WLDEXBKd",
    brand: "Logicool G",
    tagline: "Logicool G Pro X Superlight 2 DEX Gaming Mouse GPROXSL-WLDEXBKd (Amazon.co.jp Exclusive) | 8000Hz ポーリングレート 右手 44K DPI ワイヤレス ゲーミング マウス エルゴ…",
    price: 24500,
    rating: 4.5,
    reviews: 360,
    image: "https://m.media-amazon.com/images/I/61CFuum7uvL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0D9VWPG1T",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-015",
    category: "mouse",
    name: "G PRO X SUPERLIGHT 2 G-PPD-004WL-MG",
    brand: "Logicool G",
    tagline: "Logicool G 8000Hz ポーリングレート PRO X SUPERLIGHT 2 ワイヤレス ゲーミングマウス G-PPD-004WL-MG軽量 60g LIGHTFORCE ハイブリッドスイッチ LIGHTSPEED HERO2 センサー USB Type-C 充電 POWERPLAY 対応 ゲーミング マウス",
    price: 21091,
    rating: 4.5,
    reviews: 730,
    image: "https://m.media-amazon.com/images/I/51Z7dYH0POL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0CGR24WQH",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "32,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "4,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "4,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-016",
    category: "mouse",
    name: "G PRO X SUPERLIGHT 2 SE G-PPD-004WLSE-BKD",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】Logicool G PRO SUPERLIGHT ワイヤレス ゲーミングマウス G-PPD-004WLSE-BKd軽量 Type-C 充電 POWERPLAY 対応 ゲーミング マウス",
    price: 18600,
    rating: 4.5,
    reviews: 84,
    image: "https://m.media-amazon.com/images/I/51nEL5eX9UL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FG6M4DFP",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "60 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "60 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-017",
    category: "mouse",
    name: "G PRO LIGHTSPEED G-PPD-002WLR",
    brand: "Logicool G",
    tagline: "Logicool G PRO LIGHTSPEED ワイヤレス ゲーミング マウス G-PPD-002WLr ゲーミングマウス 軽量 80g HERO 25Kセンサー 充電 POWERPLAY 対応 ゲーム 充電 無線 左右対称 FPS PC",
    price: 12474,
    rating: 4.6,
    reviews: 3890,
    image: "https://m.media-amazon.com/images/I/3142nM2rNYL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Micro-USB",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08CKZNCPP",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "80 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "80 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "8ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Micro-USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-018",
    category: "mouse",
    name: "logitch Logitech G Pro Wireless Mouse",
    brand: "Logicool G",
    tagline: "logitch Logitech G Pro Wireless Mouse LIGHTSPEED ロジテック ワイヤレス ゲーミング マウス",
    price: 13500,
    rating: 4.5,
    reviews: 798,
    image: "https://m.media-amazon.com/images/I/51ySu55JzAL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B07M5DK18R",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "80 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "80 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "8ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-019",
    category: "mouse",
    name: "PRO X SUPERLIGHT 2c G-PPD-004WLCO-BKD",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】Logicool G 8000Hz ポーリングレート PRO X SUPERLIGHT 2c コンパクト ワイヤレス ゲーミングマウス G-PPD-004WLCO-BKd 軽量 51g LIGHTSPEED HERO2 センサー USB Type-C 充電 POWERPLAY",
    price: 24500,
    rating: 4.4,
    reviews: 146,
    image: "https://m.media-amazon.com/images/I/51Gn4GWV7mL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FG74B2PC",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "51 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "51 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },{
    id: "m-gpro-021",
    category: "mouse",
    name: "G PRO X SUPERLIGHT G-PPD-003WL-WH",
    brand: "Logicool G",
    tagline: "Logicool G PRO X SUPERLIGHT ワイヤレス ゲーミングマウス G-PPD-003WL-WH 軽量 63g未満 LIGHTSPEED HERO 25Kセンサー POWERPLAY 無線 充電 対応 ゲーミング マウス ホワイト PC windows 国内正規品",
    price: 12500,
    rating: 4.6,
    reviews: 9047,
    image: "https://m.media-amazon.com/images/I/61ykKLbddNL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Micro-USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08MVQ6G49",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "63 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "63 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Micro-USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-022",
    category: "mouse",
    name: "G PRO X SUPERLIGHT G-PPD-003WL-RD",
    brand: "Logicool G",
    tagline: "Logicool G PRO X SUPERLIGHT ワイヤレス ゲーミングマウス G-PPD-003WL-RD 軽量 63g未満 LIGHTSPEED HERO 25Kセンサー POWERPLAY 無線 充電 対応 ゲーミング マウス レッド 赤 PC windows 国内正規品",
    price: 12474,
    rating: 4.6,
    reviews: 9047,
    image: "https://m.media-amazon.com/images/I/41mNB8ie0eL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Micro-USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BHDHQTD8",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "63 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "63 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Micro-USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-023",
    category: "mouse",
    name: "PRO X SUPERLIGHT 2c G-PPD-004WLCO-WH",
    brand: "Logicool G",
    tagline: "Logicool G 8000Hz ポーリングレート PRO X SUPERLIGHT 2c コンパクト ワイヤレス ゲーミングマウス G-PPD-004WLCO-WH 軽量 51g LIGHTFORCE ハイブリッドスイッチ LIGHTSPEED HERO2 センサー USB Type-C 充電 POWERPLAY 対応",
    price: 22200,
    rating: 4.4,
    reviews: 146,
    image: "https://m.media-amazon.com/images/I/51yLYGE4STL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FNMVZCP9",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "51 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "51 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-024",
    category: "mouse",
    name: "PRO X SUPERLIGHT 2c G-PPD-004WLCO-BK",
    brand: "Logicool G",
    tagline: "Logicool G 8000Hz ポーリングレート PRO X SUPERLIGHT 2c コンパクト ワイヤレス ゲーミングマウス G-PPD-004WLCO-BK 軽量 51g LIGHTFORCE ハイブリッドスイッチ LIGHTSPEED HERO2 センサー USB Type-C 充電 POWERPLAY 対応",
    price: 22200,
    rating: 4.4,
    reviews: 146,
    image: "https://m.media-amazon.com/images/I/51Gn4GWV7mL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー)",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0FNMYDBSX",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "51 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "8,000 Hz" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "51 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ポーリングレート", value: "8,000 Hz" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー)" },
          { label: "電源", value: "充電式" }]}],
  },{
    id: "m-gpro-026",
    category: "mouse",
    name: "G PRO LIGHTSPEED G-PPD-002WLRD",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G PRO LIGHTSPEED ワイヤレス ゲーミング マウス G-PPD-002WLrd ゲーミングマウス 軽量 80g HERO 25Kセンサー 充電 POWERPLAY 対応 ゲーム 充電 無線 左右対称 FPS",
    price: 15729,
    rating: 4.5,
    reviews: 1535,
    image: "https://m.media-amazon.com/images/I/3142nM2rNYL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Micro-USB",
    mouseSpreadsheetButtonCount: "8ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0BC13CZ13",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "80 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "80 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "8ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Micro-USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-027",
    category: "mouse",
    name: "G PRO X SUPERLIGHT G-PPD-003WL-BK",
    brand: "Logicool G",
    tagline: "Logicool G PRO X SUPERLIGHT ワイヤレス ゲーミングマウス G-PPD-003WL-BK 軽量 63g未満 LIGHTSPEED HERO 25Kセンサー POWERPLAY 無線 充電 対応 ゲーミング マウス ブラック PC windows 国内正規品",
    price: 8880,
    rating: 4.6,
    reviews: 9047,
    image: "https://m.media-amazon.com/images/I/41l9QIbAVSL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Micro-USB",
    mouseSpreadsheetButtonCount: "5ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08LVCQLSH",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "63 g" },
      { label: "最大DPI", value: "25,600 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "63 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "5ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Micro-USB" },
          { label: "電源", value: "充電式" }]}],
  },
  {
    id: "m-gpro-028",
    category: "mouse",
    name: "G-PPD-001T",
    brand: "Logicool G",
    tagline: "Logicool G ロジクール G USB PRO ゲーミングマウス 有線 HERO 25Kセンサー FPS向け 83g 軽量 LIGHTSYNC RGB 6個プログラムボタン G-PPD-001t 国内正規品",
    price: 8455,
    rating: 4.4,
    reviews: 794,
    image: "https://m.media-amazon.com/images/I/41SoR5dfZbL._AC_SL1500_.jpg",
    connection: "有線 USB",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B08CL19PSH",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical","side-buttons"],
    highlights: [
      { label: "重量", value: "83 g" },
      { label: "最大DPI", value: "25,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "83 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "有線 USB" },
          { label: "電源", value: "有線給電" }]}],
  },
  {
    id: "m-gpro-029",
    category: "mouse",
    name: "G304X Superlight",
    brand: "Logicool G",
    tagline: "【Amazon.co.jp限定】 Logicool G ワイヤレス ゲーミングマウス G304 X SUPERLIGHT G304X-SL-WHd軽量 59g HERO 44Kセンサー LIGHTSYNC RGB 130時間連続利用可能 LIGHTSPEED USB Type-C 充電 Bluetooth 対応",
    price: 11800,
    rating: 4.3,
    reviews: 0,
    image: "https://m.media-amazon.com/images/I/51d+ya-1cuL._AC_SL1500_.jpg",
    connection: "2.4GHz (USBレシーバー) / Bluetooth",
    mouseSpreadsheetButtonCount: "6ボタン",
    mouseSpreadsheetUsageSpecs: ["gaming", "side-button"],
    purchaseUrl: "https://www.amazon.co.jp/dp/B0GJ92D4LY",
        mouseUsage: "gaming",
    mouseFilterTags: ["reading-optical"],
    highlights: [
      { label: "重量", value: "59 g" },
      { label: "最大DPI", value: "44,000 DPI" },
      { label: "読み取り方式", value: "光学式" },
      { label: "ポーリングレート", value: "—" }],
    compat: [],
    specGroups: [
      { title: "サイズ / 重量", rows: [
          { label: "重量", value: "59 g" }]},
      { title: "センサー / 入力", rows: [
          { label: "読み取り方式", value: "光学式" },
          { label: "ボタン数", value: "6ボタン" }]},
      { title: "接続 / 電源", rows: [
          { label: "接続方式", value: "2.4GHz (USBレシーバー) / Bluetooth" },
          { label: "電源", value: "充電式" }]}],
  }]
